### ISSUE TITLE
decode format

### ISSUE THREAD

**Issue by lucheng07082221** [NVIDIA/VideoProcessingFramework#1]
Hi, this is a good project!
I want to know the VPF support rtsp stream format?

**Comment by rarzumanyan** [comment]
Hi,
VPF relies on FFMpeg demuxer under the hood, so it does support rtsp. 
Just make sure that ffmpeg build your're using when building VPF, was configured with rtsp support on.

**Comment by lucheng07082221** [comment]
thank you! good job

**Comment by rarzumanyan** [comment]
You're welcome.
I'm closing the issue.
