### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by pycoco** [NVIDIA/VideoProcessingFramework#10]
python3 SampleDecode.py 
Decoding on GPU 0
[-----] Media format: QuickTime / MOV (mov,mp4,m4a,3gp,3g2,mj2)
Traceback (most recent call last):
  File "SampleDecode.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: CUDA error:

**Comment by rarzumanyan** [comment]
Hi pycoco,

I've added verbose CUDA error messages to NvDecoder class. 
Can you please update the sources on your machine & re-upload the error message?

**Comment by pycoco** [comment]
perhaps it's my ffmpeg problem.now i can't reproduce this error.because i recompile my ffmpeg. can u show me some  guide for compile ffmpeg for source. such as which ffmpeg version?  i follow the https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source. but i  cmake error happend.

**Comment by rarzumanyan** [comment]
Hi,

Take a look a the [FFmpeg build instructions for Ubuntu](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu). \
However it makes little sense to build it from source unless you want the latest version. \
I've tried ffmpeg 4.0.1 and it worked fine. VPF uses only basic ffmpeg features for demuxing.

**Comment by pycoco** [comment]
thx,now i install ffmpeg 4.1.3. but when i make VPF. it show me 
`n file included from /home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:14:0:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/inc/FFmpegDemuxer.h:37:3: error: ‘AVBSFContext’ does not name a type
   AVBSFContext *bsfc = nullptr;
   ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp: In member function ‘bool FFmpegDemuxer::Demux(uint8_t*&, size_t&)’:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:61:48: error: ‘AVBSFContext’ has not been declared
                         AVPacket &avPacketBsf, AVBSFContext *pAvbsfContext,
                                                ^
In file included from /home/luban/VideoProcessingFramework/PyNvCodec/TC/inc/FFmpegDemuxer.h:29:0,
                 from /home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:14:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp: In lambda function:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:72:53: error: ‘av_bsf_send_packet’ was not declared in this scope
       ck(av_bsf_send_packet(pAvbsfContext, &avPacket));
                                                     ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/inc/NvCodecUtils.h:121:24: note: in definition of macro ‘ck’
 #define ck(call) check(call, __LINE__, __FILE__)
                        ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:73:59: error: ‘av_bsf_receive_packet’ was not declared in this scope
       ck(av_bsf_receive_packet(pAvbsfContext, &avPacketBsf));
                                                           ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/inc/NvCodecUtils.h:121:24: note: in definition of macro ‘ck’
 #define ck(call) check(call, __LINE__, __FILE__)
                        ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp: In member function ‘bool FFmpegDemuxer::Demux(uint8_t*&, size_t&)’:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:103:45:error: ‘bsfc’ was not declared in this scope
   appendBytes(videoBytes, pkt, pktFiltered, bsfc, videoStream,
                                             ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp: In destructor ‘FFmpegDemuxer::~FFmpegDemuxer()’:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:136:7: error: ‘bsfc’ was not declared in this scope
   if (bsfc) {
       ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:137:22:error: ‘av_bsf_free’ was not declared in this scope
     av_bsf_free(&bsfc);
                      ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp: In constructor ‘FFmpegDemuxer::FFmpegDemuxer(AVFormatContext*)’:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:231:45:error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
   eVideoCodec = fmtc->streams[videoStream]->codecpar->codec_id;
                                             ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:232:39:error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
   width = fmtc->streams[videoStream]->codecpar->width;
                                       ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:233:40:error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
   height = fmtc->streams[videoStream]->codecpar->height;
                                        ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:235:62:error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
   eChromaFormat = (AVPixelFormat)fmtc->streams[videoStream]->codecpar->format;
                                                              ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:255:69:error: ‘av_bsf_get_by_name’ was not declared in this scope
   const AVBitStreamFilter *bsf = av_bsf_get_by_name(bfs_name.c_str());
                                                                     ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:259:28:error: ‘bsfc’ was not declared in this scope
   ret = av_bsf_alloc(bsf, &bsfc);
                            ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:259:32:error: ‘av_bsf_alloc’ was not declared in this scope
   ret = av_bsf_alloc(bsf, &bsfc);
                                ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:266:61:error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
                                 fmtc->streams[videoStream]->codecpar);
                                                             ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:266:69:error: ‘avcodec_parameters_copy’ was not declared in this scope
                                 fmtc->streams[videoStream]->codecpar);
                                                                     ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:272:25:error: ‘av_bsf_init’ was not declared in this scope
   ret = av_bsf_init(bsfc);
                         ^
PyNvCodec/TC/CMakeFiles/TC.dir/build.make:101: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/src/FFmpegDemuxer.cpp.o' failed
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/src/FFmpegDemuxer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/luban/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:30:0:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/inc/FFmpegDemuxer.h:37:3: error: ‘AVBSFContext’ does not name a type
   AVBSFContext *bsfc = nullptr;
   ^
In file included from /usr/include/x86_64-linux-gnu/libavutil/avutil.h:295:0,
                 from /usr/include/x86_64-linux-gnu/libavutil/samplefmt.h:24,
                 from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:31,
                 from /home/luban/VideoProcessingFramework/PyNvCodec/TC/inc/FFmpegDemuxer.h:23,
                 from /home/luban/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:30:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp: In member function ‘virtual VPF::TaskExecStatus VPF::NvencEncodeFrame::Execute()’:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:119:33: error: class VPF::Surface’ has no member named ‘AVPixelFormat’
     if (input && NV12 == input->PixelFormat()) {
                                 ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp: In member function ‘void VPF::MuxFrame_Impl::SetupVideoStream(MuxingParams&)’:
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:569:5: error: ‘AVCodecParameters’ was not declared in this scope
     AVCodecParameters *videoCodecParams = videoStream->codecpar;
     ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:569:24: error: videoCodecParams’ was not declared in this scope
     AVCodecParameters *videoCodecParams = videoStream->codecpar;
                        ^
/home/luban/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:569:56: error: AVStream {aka struct AVStream}’ has no member named ‘codecpar’
     AVCodecParameters *videoCodecParams = videoStream->codecpar;
                                                        ^
PyNvCodec/TC/CMakeFiles/TC.dir/build.make:75: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o' failed
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o] Error 1
CMakeFiles/Makefile2:165: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/all' failed
make[1]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by rarzumanyan** [comment]
It means that VPF can’t find ffmpeg headers.
If you’ve installed ffmpeg with your packet manager, make please make sure you have also installed packet for development (something named like ffmpeg-devel depending on your distro).

**Comment by pycoco** [comment]
thank u, and i reproduce the problem.error is :
`python SampleDecode.py 
Decoding on GPU 0
[-----] Media format: QuickTime / MOV (mov,mp4,m4a,3gp,3g2,mj2)
Traceback (most recent call last):
  File "SampleDecode.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: /home/luban/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:580
CUDA error with code70470496No error string available`

**Comment by rarzumanyan** [comment]
70470496 is not a valid CUDA error code.
At VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:580 cuvid lock context is being created:
`ThrowOnCudaError(cuvidCtxLockCreate(&p_impl->m_ctxLock, cuContext), __LINE__,
                   __FILE__);`
This is basically the first call to Video Codec SDK in VPF.
What video driver & Video Codec SDK versions are you using?

**Comment by pycoco** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.30       Driver Version: 430.30       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID P40-12C        On   | 00000000:00:0B.0 Off |                  N/A |
| N/A   N/A    P0    N/A /  N/A |   1705MiB / 12224MiB |     37%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------

Video Codec SDK: Video_Codec_SDK_9.1.23

**Comment by rarzumanyan** [comment]
Please update the video driver, you need 435.21 for Video Codec SDK 9.1.23.
Or you can choose Video Codec SDK 9.0 if you don't want to upgrade the video driver.

**Comment by pycoco** [comment]
hi,i change to SDK9.0.show me this error:
python SampleDecode.py 
Decoding on GPU 0
[-----] Media format: QuickTime / MOV (mov,mp4,m4a,3gp,3g2,mj2)
Traceback (most recent call last):
  File "SampleDecode.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: /home/luban/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:580
CUDA error with code-223806624No error string available

**Comment by rarzumanyan** [comment]
Hi @pycoco 

Please check that proper CUDA & VideoCodecSDK dynamic libraries are loaded.
libcuda.so and libnvcuvid.so should be loaded from default system paths (e. g. /usr/lib64/libcuda.so) where they were put by GPU driver installer.

**Comment by woodenwatcher** [comment]
I got the same problem:

`Traceback (most recent call last):
  File "SampleDecode.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: /home/admin/codec/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:568
CUDA error with code 1883268768
No error string available`

driver version is 440.64.00, cuda version is 10.2.89

**Comment by rarzumanyan** [comment]
Hi @woodenwatcher 
Same advice here: run ldd on your Python module as per wiki [page](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source#build-procedure-details-for-linux-users) and check if CUDA & Video Codec SDK libraries are loaded from system locations.

**Comment by woodenwatcher** [comment]
I copy Video Codec SDK library from download dir to /lib64
ldd result as follow:
`linux-vdso.so.1 =>  (0x00007fffa07b1000)
	libTC.so => /home/admin/codec/VideoProcessingFramework/build/PyNvCodec/TC/libTC.so (0x00007fdc3bb38000)
	libpython3.6m.so.1.0 => /root/miniconda/lib/libpython3.6m.so.1.0 (0x00007fdc3b7f1000)
	libnvcuvid.so.1 => /lib64/libnvcuvid.so.1 (0x00007fdc3b5e0000)
	libnvidia-encode.so.1 => /lib64/libnvidia-encode.so.1 (0x00007fdc3b3de000)
	libTC_CORE.so => /home/admin/codec/VideoProcessingFramework/build/PyNvCodec/TC/TC_CORE/libTC_CORE.so (0x00007fdc3b1d9000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdc3afbd000)
	libavutil.so.56 => /root/miniconda/lib/libavutil.so.56 (0x00007fdc3aeb2000)
	libavcodec.so.58 => /root/miniconda/lib/libavcodec.so.58 (0x00007fdc399e0000)
	libavformat.so.58 => /root/miniconda/lib/libavformat.so.58 (0x00007fdc39772000)
	libswresample.so.3 => /root/miniconda/lib/libswresample.so.3 (0x00007fdc39752000)
	libcudart.so.10.2 => /usr/local/cuda/lib64/libcudart.so.10.2 (0x00007fdc394d4000)
	libcuda.so.1 => /lib64/libcuda.so.1 (0x00007fdc382ce000)
	libnpps.so.10 => /usr/local/cuda/lib64/libnpps.so.10 (0x00007fdc377c5000)
	libnppig.so.10 => /usr/local/cuda/lib64/libnppig.so.10 (0x00007fdc35bdd000)
	libnppicc.so.10 => /usr/local/cuda/lib64/libnppicc.so.10 (0x00007fdc35552000)
	libnppidei.so.10 => /usr/local/cuda/lib64/libnppidei.so.10 (0x00007fdc34ae1000)
	libstdc++.so.6 => /root/miniconda/lib/libstdc++.so.6 (0x00007fdc3496d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fdc3466b000)
	libgcc_s.so.1 => /root/miniconda/lib/libgcc_s.so.1 (0x00007fdc34656000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fdc34289000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fdc34081000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fdc33e7c000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fdc33c79000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdc3c045000)
	libvpx.so.5 => /root/miniconda/lib/./libvpx.so.5 (0x00007fdc337f7000)
	libz.so.1 => /root/miniconda/lib/./libz.so.1 (0x00007fdc337d7000)
	libmp3lame.so.0 => /root/miniconda/lib/./libmp3lame.so.0 (0x00007fdc33759000)
	libopus.so.0 => /root/miniconda/lib/./libopus.so.0 (0x00007fdc336f3000)
	libx264.so.152 => /root/miniconda/lib/./libx264.so.152 (0x00007fdc33577000)
	libopenh264.so.4 => /root/miniconda/lib/./libopenh264.so.4 (0x00007fdc3346c000)
	libbz2.so.1.0 => /root/miniconda/lib/./libbz2.so.1.0 (0x00007fdc33457000)
	libssl.so.1.1 => /root/miniconda/lib/./libssl.so.1.1 (0x00007fdc333c7000)
	libcrypto.so.1.1 => /root/miniconda/lib/./libcrypto.so.1.1 (0x00007fdc330fb000)
	libnppc.so.10 => /usr/local/cuda/lib64/libnppc.so.10 (0x00007fdc32e7e000)`

but still have the same error:
`Traceback (most recent call last):
  File "SampleDecode.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: /home/admin/codec/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:568
CUDA error with code 2068334080
No error string available`

**Comment by rarzumanyan** [comment]
>Video Codec SDK library from download dir to /lib64

Please don't do this.

CUDA & Video Codec SDK libraries (`libcuda.so`, `libnvcuvid.so` etc.) are installed with GPU driver. 
Your application shall load `libcuda.so` and `libnvcuvid.so` from those locations where they were put by driver installer.

**Comment by woodenwatcher** [comment]
I got the error as follow when use "libnvcuvid.so" from gpu driver installer:
`Traceback (most recent call last):
  File "SampleDecode.py", line 17, in <module>
    import PyNvCodec as nvc
ImportError: /lib64/libnvcuvid.so.1: invalid ELF header`

check the type of libnvcuvid.so file,result as follow:
`/usr/lib64/libnvcuvid.so.440.64.00: gzip compressed data, from Unix, last modified: Mon Apr 13 17:39:41 2020`

**Comment by rarzumanyan** [comment]
Please run
```bash
readelf /usr/lib64/libnvcuvid.so.440.64.00
sudo ln -s /usr/lib64/libnvcuvid.so.440.64.00 /lib64/libnvcuvid.so.1
```
Chances are low that shared library shipped with driver has broken ELF header.

**Comment by woodenwatcher** [comment]
`#readelf -h /usr/lib64/libnvcuvid.so.440.64.00
readelf: Error: Unable to read in 0x78a4 bytes of section headers
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start`

**Comment by rarzumanyan** [comment]
I'm not sure this is the original libnvcuvid library.
Can you re-install the driver?

**Comment by woodenwatcher** [comment]
I have re-installed driver，the error was fixed. THANKS!

**Comment by rarzumanyan** [comment]
Glad that it worked out for you. 
Closing the issue.

**Comment by mchl0203** [comment]
@rarzumanyan Hi, I meet the same problem when I execute `python3 SampleRTSP.py rtmp://...`. But I cann't upgrade driver because of some permissions. 

My envs:
- python3.6
- gcc 5.4.0 or gcc 4.8.3
- GPU: GeForce RTX 2080 Ti
- Driver Version: 418.39
- CUDA Version: 10.1 
- Video_Codec_SDK_9.0.20 or Video_Codec_SDK_9.1.23

I have tried several versions of the above combinations, but alway get error:
```
This sample takes rtsp stream URL as input and transcodes it to local H.264 file
Decoding on GPU 0
[rtsp @ 0x55edf44f8c80] max delay reached. need to consume packet
[rtsp @ 0x55edf44f8c80] RTP: missed 1 packets
/usr/local/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:568
CUDA error with code -231682512
No error string available
```
Sometimes there are 2 `[rtsp @ 0x55edf44f8c80]`  sometimes  4/6/8/10..., and CUDA error with code is not a definite number, like 1702964784 or -1419772368 or -1989087696 and so on.

Do you know where I went wrong, looking forward to your reply, thank you~

**Comment by rarzumanyan** [comment]
Hi @mchl0203 

This often happens when application loads wrong versions of CUDA and Video Codec SDK libs.
Please make sure your app loads them from system locations (like `/usr/local/lib64/cuda` etc.) where they were put by driver installer.

People often export `LD_LIBRARY_PATH` so that application loads `libnvcuvid.so` and `libnvidia-encode.so` from Video Codec SDK distro, but that's wrong as `Video_Codec_SDK_9.1.23\Lib\linux\stubs\x86_64` contains stub versions of libraries which shall be used only during installation. 

During the runtime app must load those libraries which are installed with the GPU driver.

**Comment by mchl0203** [comment]
@rarzumanyan Thank you for your detailed answer! When I use `/usr/lib64/libnvcuvid.so` and `/usr/lib64/libnvidia-encode.so`, it can work, Thank you~
