### ISSUE TITLE
LoadNvEncApi : Current Driver Version does not support this NvEncodeAPI version

### ISSUE THREAD

**Issue by krydm** [NVIDIA/VideoProcessingFramework#101]
**Describe the bug**
I'm trying to run the snippet from https://developer.nvidia.com/blog/vpf-hardware-accelerated-video-processing-framework-in-python/
It't looks slightly obsolete, so I've reworked it a bit looking at the provided samples(fixed check for zero Surface and usage of EncodeSingleSurface):

```bash
import PyNvCodec as nvc
import numpy as np

gpuID = 0
#encFile = "big_buck_bunny_1080p_h264.mov"
encFile = "/home/ericsson/sync/archive/boatattack_2160p60.mov"
xcodeFile = open("new_boatattack_2160p60.h264", "wb")

nvDec = nvc.PyNvDecoder(encFile, gpuID)
nvEnc = nvc.PyNvEncoder({'preset': 'hq', 'codec': 'h264', 's': '1920x1080'}, gpuID)

while True:
    rawSurface = nvDec.DecodeSingleSurface()
    # Decoder will return zero surface if input file is over;

    # if not (rawSurface.GetCudaDevicePtr()):
    if not (rawSurface.PlanePtr()):
        break

    encFrame = np.ndarray(shape=(0), dtype=np.uint8) 
 
    # encFrame = nvEnc.EncodeSingleSurface(rawSurface)
    # if (encFrame.size):
    success = nvEnc.EncodeSingleSurface(rawSurface, encFrame)
    if (success):
        frameByteArray = bytearray(encFrame)
        xcodeFile.write(frameByteArray)

# Encoder is asynchronous, so we need to flush it
encFrames = nvEnc.Flush()
for encFrame in encFrames:
    encByteArray = bytearray(encFrame)
    xcodeFile.write(encByteArray)
```
On run I'm getting a following error:
```bash
Traceback (most recent call last):
  File "TryTranscode.py", line 31, in <module>
    success = nvEnc.EncodeSingleSurface(rawSurface, encFrame)
RuntimeError: LoadNvEncApi : Current Driver Version does not support this NvEncodeAPI version, please upgrade driver at /home/ericsson/VideoProcessingFramework/PyNvCodec/TC/src/NvEncoder.cpp:125
```
No idea how to upgrade the driver

**To Reproduce**
Just try to run the code above

**Expected behavior**
To prepare the transcoded file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04.1
 - Nvidia driver version 440.100
 - CUDA Version: 10.2
- Video Codec SDK Version 10.0.26
 - Python Version 3.8

**Additional context**

**Comment by rarzumanyan** [comment]
Hello @krydm 

You need to upgrade video driver to latest available version or use Video Codec SDK 9.1.

**Comment by krydm** [comment]
Hello @rarzumanyan ,
Thanks, but how do I do it?
TIA

**Comment by rarzumanyan** [comment]
@krydm 

>Thanks, but how do I do it?

You download the driver from nvidia site and run it, or use packet manager to update.
Or you download the Video Codec SDK 9.1 and re-build VPF providing the path to SDK 9.1 instead of path to SDK 10.

**Comment by krydm** [comment]
@rarzumanyan Well, I'd prefer not to go with manual update to 450.66, and it looks like automatic update still keeps the 440.100 version. However, I did get Video Codec SDK 9.1 and rebuilt VPF with it and now everything is OK, many thanks!

But now I have another question, may I ask it here without opening a new issue?

My task is a bit more complex than just decode/encode/transcode: I need, for example, to collect/manage the frame info –– type of a frame(i/p/b), frame sizes etc(most important, though, are frame types and sizes). However I couldn't find any kind of "GetSize" interface in the samples/documentation/pydoc output for VPF. I do see frame extraction to byte array, but it looks like just a plain fixed size buffer and there's no way to get the actual frame size.

Am I right that for tasks of this kind I should go to Video Codec SDK C++ API and there's just now Python wrapper for this functionality?

Assuming so, I'm trying to make the SDK Samples. AppDecode/AppDec passed the make, but on AppDecode/AppDecGL I've got a complaint about missing GL/glew.h, included from FramePresenterGL.h. I do see GL/glew.h in External subfolder, so I've edited  AppDecGL Makefile adding -I../../External to INCLUDES and then the compilation passed OK. However, I'm not sure this was the correct way to fix the issue rather than just a quick and dirty patch. What should be the right way to include External without hacking the AppDecGL Makefile?

Further, I've got a complaint about not found /usr/local/cuda/bin/nvcc. Well, this was easy, my nvcc is indeed located at /usr/bin/nvcc, so I've just exported NVCC=/usr/bin/nvcc and then this step went OK too.

Now I'm getting linker complaints:
/usr/bin/ld: cannot find -lglut
/usr/bin/ld: cannot find -lGLEW

locate libglut.so returns me nothing. 
locate libGLEW.so finds 
/usr/lib/x86_64-linux-gnu/libGLEW.so.2.1
/usr/lib/x86_64-linux-gnu/libGLEW.so.2.1.0

I've exported /usr/lib/x86_64-linux-gnu/ to LIBRARY_PATH to get rid at least of non-found lGLEW, but still get the two above ld errors.

Could you advise please?
TIA

**Comment by rarzumanyan** [comment]
Hi @krydm 

>My task is a bit more complex than just decode/encode/transcode: I need, for example, to collect/manage the frame info –– type of a frame(i/p/b), frame sizes etc(most important, though, are frame types and sizes).

This is feasible and relatively easy to do.
Frame resolution, type and other parameters may be passed as second output of `NvdecDecodeFrame` task.
As you can see, frame resolution is already there, obtaining the frame type isn't much more difficult:
https://github.com/NVIDIA/VideoProcessingFramework/blob/ff68d9aea2cd82db54bcf1ee68c1685bb0f23c4b/PyNvCodec/TC/src/Tasks.cpp#L282-L294

>Everything is built OK except AppDecGL and AppEncGL. For now I've just removed them from the main Makefile.

Don't get me wrong with this, but Video Codec SDK Samples issues are outside this project scope.

**Comment by krydm** [comment]
Hi @rarzumanyan 

Gotcha regarding the project scope, sorry.

Regarding the frame parameters -- not sure I get it. I need the encoded frame type/size in bytes, in the same way I can get it with, say "ffprobe -show_frames", while you're talking about resolution. Can you explain a bit more please?
TIA

**Comment by rarzumanyan** [comment]
Hi @krydm 

Can you take a look at [this issue](https://github.com/NVIDIA/VideoProcessingFramework/issues/99)?
There's a branch which implements `PyNvDecoder` accepting demuxed packets from PyAV project.
IMO this is by far cleaner and superior solution which allows to see encoded frame size, type, etc. straight from demuxer.
Patch development is somewhat WIP, the VPF interface was extended and now needs some testing.

**Comment by rarzumanyan** [comment]
No response for almost 2 years, closing this issue.
