### ISSUE TITLE
Get FPS and millisecond information

### ISSUE THREAD

**Issue by Jack-Lee1994** [NVIDIA/VideoProcessingFramework#103]
Hi @rarzumanyan, do you intend to add FPS and millisecond methods in PyNvDecoder class? The project I am working need get all frames in a video, so I want to know the "time position" for each frame, just like OpenCV:

imflag, imframe = video.read()
while (imflag):
        miniseconds = int(video.get(cv2.CAP_PROP_POS_MSEC))

By the way, this framework is much faster than OpenCV. I really want to apply it to the project, hope to get your reply.

**Comment by rarzumanyan** [comment]
Hi @Jack-Lee1994 

>do you intend to add FPS and millisecond methods in PyNvDecoder class? 

You can get video FPS by calling `PyNvDecoder.Framerate()` method.

>so I want to know the "time position" for each frame

I'm not very familiar with OpenCV Python bindings. Do you mean frame PTS and DTS values?

**Comment by Jack-Lee1994** [comment]
@rarzumanyan Thank you very much, I think it‘s fine if can get the fps for whole video.

For the "time position" I mentioned, it's really like PTS and DTS in ffmpeg. OpenCV can get millisecond in whole time duration for each frame, e.g. I can get one frame's millisecond like int: 23451( = 23.451 seconds) by opencv, so I know the position of this frame in time duration is 23.451s. I don't need to save all frames in my disk, I can just capture this frame by its "time position". Actually it can be calculated by fps and all number of frames. So if I get fps of video, that's enough.
