### ISSUE TITLE
Does VPF surpport float FPS (like 24.35) in encode process?

### ISSUE THREAD

**Issue by TracelessLe** [NVIDIA/VideoProcessingFramework#106]
**Describe the bug**
Hi @rarzumanyan, I meet a trouble while I do encode. I try to set PyNvEncoder with params like {'preset': 'hq', 'codec': 'h264', 's': '1280x720', 'fps':'24.65'}, but I find the result has an int FPS like 24. I find the param 'FPS' is converted to uint32_t from string in the VPF source code as follows. 

```
  // FPS;
  auto fps = FindAttribute(options, "fps");
  if (!fps.empty()) {
    params.frameRateNum = FromString<uint32_t>(fps);
    params.frameRateDen = 1;
  }
```

How can I achieve my goal with some modify?
Thanks.

**Expected behavior**
Set FPS as float type, not just int.

**Desktop (please complete the following information):**
- OS: ubuntu 18.04
- Nvidia driver version: 440.82
- CUDA Version: 10.1
- Video Codec SDK Version: 9.1.23
- Python Version: 3.6.10

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

Regarding this piece of code:
https://github.com/NVIDIA/VideoProcessingFramework/blob/ff68d9aea2cd82db54bcf1ee68c1685bb0f23c4b/PyNvCodec/TC/src/NvCodecCliOptions.cpp#L425-L429

Video Codec SDK API supports `uint32_t` numerator and denominator for FPS value.
It's not a big deal to pass a float FPS value like 24.65 but it's not trivial to represent arbitral real number as rational fraction.
You can come up with something like this:
```cpp
 static void FpsToNumDen (const float& fps, uint32_t& num, uint32_t &den) {
   // Conversion algorithm;
 }

 auto fps = FindAttribute(options, "fps"); 
 if (!fps.empty()) {
   FpsToNumDen(FromString<float>(fps), params.frameRateNum, params.frameRateDen);
 }
```

Another solution would be to extend the encoder cli options with `fps_num` and `fps_den` flags and pass them straight to Video Codec SDK API.

**Comment by TracelessLe** [comment]
@rarzumanyan Thanks a lot. I have solve the problem according to your guidance. And I submit a PR for this excellent work, hope that helps.
