### ISSUE TITLE
windows10 build INSTALL problem

### ISSUE THREAD

**Issue by wuwenhao8866** [NVIDIA/VideoProcessingFramework#108]
**Describe the bug**
In the Windows operating system, cmake has no problem, and then there is a problem when compiling INSTALL with VS2019.
Both the driver and cuda are latest. I don't know where it is incompatible.  Thx.
**Desktop (please complete the following information):**
 - OS: Windows10
 - Nvidia driver version：452.06
 - CUDA Version ：11.0.2
 - Video Codec SDK Version ：9.1.23
 - Python Version：3.7.7
![error](https://user-images.githubusercontent.com/61042901/92677521-a3427500-f356-11ea-9a27-0b8412371bbb.png)

**Comment by rarzumanyan** [comment]
Hi @wuwenhao8866 

Can you check it with other Visual Studio version?
I've just checked VS 2017 and VS 2019, it works fine.

Regarding the first compilation error you see:
https://github.com/NVIDIA/VideoProcessingFramework/blob/314e6d26a7a5f089be97861e8fc95cab6e49b291/PyNvCodec/TC/TC_CORE/src/Task.cpp#L17-L26

`string` header is included and `std` namespace is used so compiler shall not complain about `name` variable type, it's clearly `std::string`

**Comment by rarzumanyan** [comment]
No response for 1.5 years, closing the issue.
