### ISSUE TITLE
PyNvCodec/TC/src/NvDecoder.cpp:468 CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by xinyi61** [NVIDIA/VideoProcessingFramework#112]
cpp_samples branch mult-thread (64) rtsp stream decoding raise a error:

PyNvCodec/TC/src/NvDecoder.cpp:468
CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS
an illegal memory access was encountered

when calling the following function：
```
int NvDecoder::HandlePictureDecode(CUVIDPICPARAMS *pPicParams) noexcept
{
    try
    {
        if (!p_impl->m_hDecoder)
        {
            throw runtime_error("Decoder not initialized.");
        }

        p_impl->m_nPicNumInDecodeOrder[pPicParams->CurrPicIdx] = p_impl->m_nDecodePicCnt++;
       ThrowOnCudaError(cuvidDecodePicture(p_impl->m_hDecoder, pPicParams), __LINE__);// Error

        return 1;
    }
    catch (exception &e)
    {
        cerr << e.what();
        return 0;
    }
}
```
**Desktop (please complete the following information):**
OS: ubuntu 18.04
Nvidia driver version: 440.33.01
CUDA Version: 10.2
Video Codec SDK Version:Video_Codec_SDK_10.0.26
C++
CPU(s): 40

**Comment by xinyi61** [comment]
Have any idea? Thanks in advance.

**Comment by xinyi61** [comment]
@rarzumanyan 
I get the new cpp version from master, replace py::array with std::vector and some other modify such as remove pybind11,   change frame.mutable_data() to frame.data() and
```c++
void DemuxFrame::GetParams(MuxingParams &params) const {
  params.videoContext.width = pImpl->demuxer.GetWidth();
  params.videoContext.height = pImpl->demuxer.GetHeight();
  params.videoContext.frameRate = pImpl->demuxer.GetFramerate();
  params.videoContext.timeBase = pImpl->demuxer.GetTimebase();
  params.videoContext.streamIndex = pImpl->demuxer.GetVideoStreamIndex();
  params.videoContext.codec = FFmpeg2NvCodecId(pImpl->demuxer.GetVideoCodec());
  params.videoContext.format = NV12;
  // switch (pImpl->demuxer.GetPixelFormat()) {
  // case AV_PIX_FMT_YUV420P:
  // case AV_PIX_FMT_NV12:
  //   params.videoContext.format = NV12;
  //   break;
  // case AV_PIX_FMT_YUV444P:
  //   params.videoContext.format = YUV444;
  //   break;
  // }
}
```
Unfortunately, when to decode 64 rtsp stream it also raise the error CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS
an illegal memory access was encountered，Could you have a try??

**Comment by rarzumanyan** [comment]
Hi @xinyi61 

Unfortunately I'm under water with other tasks now and can't give it a try. One thing I'm working on now is separate demuxer support so that on can use any external demuxer (say PyAV) to get Annex.B packets and feed them to PyNvDecoder class.

That should be also helpful as 90% of VPF issues are really can't-get-video-over-rtsp which are mostly on ffmpeg side.

**Comment by xinyi61** [comment]
@rarzumanyan 
Thank you all the same.

**Comment by niaoyu** [comment]
> @rarzumanyan
> I get the new cpp version from master, replace py::array with std::vector and some other modify such as remove pybind11, change frame.mutable_data() to frame.data() and
> 
> ```c++
> void DemuxFrame::GetParams(MuxingParams &params) const {
>   params.videoContext.width = pImpl->demuxer.GetWidth();
>   params.videoContext.height = pImpl->demuxer.GetHeight();
>   params.videoContext.frameRate = pImpl->demuxer.GetFramerate();
>   params.videoContext.timeBase = pImpl->demuxer.GetTimebase();
>   params.videoContext.streamIndex = pImpl->demuxer.GetVideoStreamIndex();
>   params.videoContext.codec = FFmpeg2NvCodecId(pImpl->demuxer.GetVideoCodec());
>   params.videoContext.format = NV12;
>   // switch (pImpl->demuxer.GetPixelFormat()) {
>   // case AV_PIX_FMT_YUV420P:
>   // case AV_PIX_FMT_NV12:
>   //   params.videoContext.format = NV12;
>   //   break;
>   // case AV_PIX_FMT_YUV444P:
>   //   params.videoContext.format = YUV444;
>   //   break;
>   // }
> }
> ```
> 
> Unfortunately, when to decode 64 rtsp stream it also raise the error CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS
> an illegal memory access was encountered，Could you have a try??

Hi, did you try to decode 64 rtsp streams using vpf python version?
