### ISSUE TITLE
Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.8.3

### ISSUE THREAD

**Issue by sbbug** [NVIDIA/VideoProcessingFramework#113]
@rarzumanyan hi ,when i use python3.8,i encounterred the problem:

 `Traceback (most recent call last):
  File "/home/ndww/20200924/VideoProcessingFramework/install/bin/test11.py", line 1, in <module>
    import PyNvCodec as nvc
ImportError: Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0].`

some steps:

cmake .. -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" -DGENERATE_PYTHON_BINDINGS:BOOL="1" -DGENERATE_PYTORCH_EXTENSION:BOOL="1" -DPYTHON_LIBRARY=/home/ndww/anaconda3/envs/vpf/lib/libpython3.8.so -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" -DPYTHON_EXECUTABLE=/home/ndww/anaconda3/envs/vpf/bin/python

results:
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 10.1.168
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Searching for FFmpeg libs in /home/ndww/ffmpeg/build_x64_release_shared/lib
-- Searching for FFmpeg headers in /home/ndww/ffmpeg/build_x64_release_shared/include
-- Found PythonLibs: /home/ndww/anaconda3/envs/vpf/lib/libpython3.8.so (found suitable version "3.6.9", minimum required is "3.5") 
-- Found PythonInterp: /home/ndww/anaconda3/envs/vpf/bin/python (found version "3.8.3") 
-- Found PythonLibs: /home/ndww/anaconda3/envs/vpf/lib/libpython3.8.so
-- pybind11 v2.3.dev0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ndww/20200924/VideoProcessingFramework/build

ok,i use libpython3.8.so and python3.8,but why:
`ImportError: Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.8.3`

**Comment by rarzumanyan** [comment]
Hi @sbbug 

>ok,i use libpython3.8.so and python3.8,but why:

CMake finds Python 3.8 libs but for some reason picks up 3.6 for build:
`-- Found PythonLibs: /home/ndww/anaconda3/envs/vpf/lib/libpython3.8.so (found suitable version "3.6.9", minimum required is "3.5")`

Issue is here: https://github.com/NVIDIA/VideoProcessingFramework/blob/da57ab2125414b87b918b0da3cabb5b2706e4d18/PyNvCodec/CMakeLists.txt#L46-L48

As I understand the problem, overriding the PythonLibs by hand
```
-DPYTHON_LIBRARY=/home/ndww/anaconda3/envs/vpf/lib/libpython3.8.so
```
doesn't help.

**Comment by sbbug** [comment]
@rarzumanyan 
hi , i modify the VideoProcessingFramework/PyNvCodec/CMakeLists.txt as :
`find_package(PythonLibs 3.8 REQUIRED)`
but cmake... 
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 10.1.168
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Searching for FFmpeg libs in /home/ndww/ffmpeg/build_x64_release_shared/lib
-- Searching for FFmpeg headers in /home/ndww/ffmpeg/build_x64_release_shared/include
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS) (Required is at
  least version "3.8")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  PyNvCodec/CMakeLists.txt:48 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ndww/20200924/VideoProcessingFramework/build/CMakeFiles/CMakeOutput.log".

```
this is strange that ```
Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS) (Required is at
  least version "3.8")
```

**Comment by sbbug** [comment]
@rarzumanyan 
hi, i sloved above problem,,
modify cmake and add below line:
` -DPYTHON_INCLUDE_DIR=/home/ndww/anaconda3/envs/vpf/include/python3.8
`
and then cmake as below:
`cmake .. -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" -DGENERATE_PYTHON_BINDINGS:BOOL="1" -DGENERATE_PYTORCH_EXTENSION:BOOL="1" -DPYTHON_LIBRARY=/home/ndww/anaconda3/envs/vpf/lib/libpython3.8.so -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" -DPYTHON_EXECUTABLE=/home/ndww/anaconda3/envs/vpf/bin/python -DPYTHON_INCLUDE_DIR=/home/ndww/anaconda3/envs/vpf/include/python3.8
`
