### ISSUE TITLE
Could not get any frames when decode more than 20 rtsp urls

### ISSUE THREAD

**Issue by niaoyu** [NVIDIA/VideoProcessingFramework#114]
Hi, I just using the SampleDecodeMultiThread.py, which simply 
A) changing it to multi rtsp streams with just 1 GPU
B) exporting decoded video frames to PyTorch tensors. 
C) Decode one frame and ignore the following frames(using "if self._skip_frame_count % self.skip_frame_num == 0")

1. Preprocessing consume too much time
For decoding 20 rtsp urls(1080p 25fps),  the printing in first 10 minutes, always be 
 ```bash
HW decoder reset time: 38 milliseconds
Decode Error occurred for picture 33
Exception thrown during decoding process: HW decoder faced error. Re-create instance.
HW decoder will be reset.
 ```

After 10 minutes,(I almost lost my patience) the decoding process printing is good and smoothly, shown as
2020-09-29 08:52:35,836 - vpf_gpu_decode.py - 128 - INFO - [id-13 fps-5.537999788559167
2020-09-29 08:52:35,843 - vpf_gpu_decode.py - 128 - INFO - [id-5 fps-4.926044068882844

could you just tell me how to reduce the time consuming when multi rtsp urls？

2. Decoding processing never start if adding more
When adding more than 20 rtsp urls,  for example copy the 20th urls to next line as 21st url. The decode process will never start even after 30 minutes. The printing will always:

 ```bash
HW decoder reset time: 38 milliseconds
Decode Error occurred for picture 33
Exception thrown during decoding process: HW decoder faced error. Re-create instance.
HW decoder will be reset.
 ```

3. The code is shown as :
 ```python

import PyNvCodec as nvc
import torch
import PytorchNvCodec as pnvc
import numpy as np
import sys
import time

from threading import Thread
import datetime
import logging
import traceback


LOG_FORMAT = "%(asctime)s - %(filename)s - %(lineno)s - %(levelname)s - %(message)s"
logging.basicConfig(
    format=LOG_FORMAT,
    level=logging.INFO,
)

class FPS(object):
    def __init__(self):
        self._start = None
        self._end = None
        self._numFrames = 0

    def start(self):
        self._start = datetime.datetime.now()
        self._numFrames = 0

    def stop(self):
        self._end = datetime.datetime.now()

    def update(self):
        self._numFrames += 1

    def _elapsed(self):
        return (self._end - self._start).total_seconds()

    def fps(self):
        return self._numFrames / self._elapsed()


class Worker(Thread):
    def __init__(self, stream_id, gpuID, encFile):
        Thread.__init__(self)
        self.stream_id = stream_id
        self.gpuID = gpuID
        self.encFile = encFile

        self.nvDec = self._reset()

        self.width, self.height, self.framerate = self.nvDec.Width(), self.nvDec.Height(), self.nvDec.Framerate()
        logging.info(f"id-{self.stream_id} framerate:{self.framerate} width{self.width} height{self.height}")


        width, height = self.nvDec.Width(), self.nvDec.Height()

        self.nv_cvt = nvc.PySurfaceConverter(self.width, self.height, self.nvDec.Format(), nvc.PixelFormat.RGB, self.gpuID)
        self.nv_cvt_2 = nvc.PySurfaceConverter(self.width, self.height, self.nv_cvt.Format(), nvc.PixelFormat.RGB_PLANAR, self.gpuID)

        self.fps_freq = 100
        self.fps = FPS()

        self.skip_frame_num = 5,  # 5 means, "decode 1 frame and  ignore following 4frame"
        self._skip_frame_count = 0

    def _reset(self):
        nvDec = nvc.PyNvDecoder(self.encFile, self.gpuID,
                                     {
                                         'rtsp_transport': 'tcp',
                                         'max_delay': '10000000',
                                         'bufsize': '60000k'
                                     }
                                     )
        return nvDec

    def run(self):
        try:
            self.fps.start()

            while True:
                try:
                    rawSurface = self.nvDec.DecodeSingleSurface()
                    assert not rawSurface.Empty()

                    if self._skip_frame_count % self.skip_frame_num == 0:
                        cvt_surface = self.nv_cvt.Execute(rawSurface)
                        assert not cvt_surface.Empty()

                        rgb_planar_surface = self.nv_cvt_2.Execute(cvt_surface)
                        assert not rgb_planar_surface.Empty()

                        surfPlane = rgb_planar_surface.PlanePtr()
                        surface_tensor = pnvc.makefromDevicePtrUint8(surfPlane.GpuMem(), surfPlane.Width(),
                                                                     surfPlane.Height(),
                                                                     surfPlane.Pitch(), surfPlane.ElemSize())
                        surface_tensor.resize_(3, self.height, self.width)

                        self.fps.update()
                        if self.fps._numFrames % self.fps_freq == 0:
                            self.fps.stop()
                            logging.info(f'[id-{self.stream_id} fps-{self.fps.fps()}')
                            self.fps.start()

                except nvc.HwResetException:
                    # logging.error('Continue after HW decoder was reset')
                    continue

                except:
                    self.nvDec = self._reset()
                    self._skip_frame_count = 0
                    self.fps.start()
                    error_msg = traceback.format_exc()
                    # logging.error(f'Decode restart traceback {error_msg}')
                    continue
                self._skip_frame_count += 1



        except Exception as e:
            print(getattr(e, 'message', str(e)))


def create_threads(gpu_id, input_files):
    thread_list = list()
    for i in range(len(input_files)):
        thread_list.append(Worker(i, gpu_id, input_files[i]))
        time.sleep(5)
    [thead.start() for thead in thread_list]
    [thead.join() for thead in thread_list]


if __name__ == "__main__":
    rtsp_urls = list()
    with open('urls.txt', 'r') as fp:
        rtsp_urls = fp.readlines()

    rtsp_urls = [rtsp_url.strip() for rtsp_url in rtsp_urls]
    gpu_id = 1


    create_threads(gpu_id, rtsp_urls)
    ```

**Comment by rarzumanyan** [comment]
Hi @niaoyu 

>could you just tell me how to reduce the time consuming when multi rtsp urls？

RTSP and demuxing is done by FFMpeg, VPF only with local Annex.B video packets.
If you want to check whether issue lies on VPF or FFMpeg side I recommend you to run your app against 20 local video files (preferably Annex.B elementary streams to avoid FFmpeg processing completely).

>When adding more than 20 rtsp urls, for example copy the 20th urls to next line as 21st url

What's the output of `nvidia-smi dmon` utility?

**Comment by niaoyu** [comment]
> Hi @niaoyu
> 
> > could you just tell me how to reduce the time consuming when multi rtsp urls？
> 
> RTSP and demuxing is done by FFMpeg, VPF only deals with local Annex.B video packets.
> If you want to check whether issue lies on VPF or FFMpeg side I recommend you to run your app against 20 local video files (preferably Annex.B elementary streams to avoid FFmpeg processing completely).
> 
> > When adding more than 20 rtsp urls, for example copy the 20th urls to next line as 21st url
> 
> What's the output of `nvidia-smi dmon` utility?

Hi, the output of nvidia-smi dmon is just normal. 

I just keep confusing about my situation. 

1. For 10 rtsp urls , the printing shown in log which has a short "warming stage"(30s) and then run very smoothly in "normal stage" withour any reset or warning or error. 
[10_urls.log](https://github.com/NVIDIA/VideoProcessingFramework/files/5303535/10_urls.log)


2. For 20 rtsp urls, it needs almost 8minutes from "warming stage" to "normal stage"(usually more than 10 mins),
[20_urls.log](https://github.com/NVIDIA/VideoProcessingFramework/files/5303808/20_urls.log)

3. For 30 rtsp urls, it will never go through "warming stage".

I am so confusing about these.

**Comment by niaoyu** [comment]
I will try use 2containers, which one will decode 20urls.
Thanks for your patience

**Comment by stepstep123** [comment]
> RTSP and demuxing is done by FFMpeg, VPF only deals with local Annex.B video packets.

@rarzumanyan @niaoyu 
it means if i got a rtmp url, i can only use FFMpeg to decode?

**Comment by rarzumanyan** [comment]
RTMP, RTSP or local video file are just sources.

FFMpeg is used to extract video stream from this sources as abstraction layer.

Nvdec can only decode elementary video stream which is not put into container like avi or accessed via network protocol like RTMP.

Hence we use FFMpeg to access the data and feed it to Nvdec which does actual decoding.
