### ISSUE TITLE
Unplayable videos when encoding numpy RGB data.

### ISSUE THREAD

**Issue by Timen** [NVIDIA/VideoProcessingFramework#115]
Hello I'm trying to encode some RGB video from a numpy array to an YUV420 h.265 mp4 file. For what I want to use the GPU for speeding up the preprocessing of a video dataset which in turn will be loaded using [DALI](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/) for training in pytorch.

However from what I have read it seem the only supported path would be:
RGB->YUV420->NV12->MP4. which adds an extra step + it increases the file size quite a bit. Quality is less of an issue than large file sizes. 

But I have tried this path, and while it does generate videos neither `ffprobe` can determine duration and I can't play them using VLC either. Am I doing someting wrong?:
```
nvUpl = nvc.PyFrameUploader(int(width), int(height), nvc.PixelFormat.RGB, gpuID)
nvCvt = nvc.PySurfaceConverter(int(width), int(height), nvc.PixelFormat.RGB, nvc.PixelFormat.YUV420, gpuID)
nvCvt2 = nvc.PySurfaceConverter(int(width), int(height), nvc.PixelFormat.YUV420, nvc.PixelFormat.NV12, gpuID)
nvEnc = nvc.PyNvEncoder({'preset': 'hq', 'codec': 'h264', 's': res, 'bitrate' : '10M'}, gpuID,True)

for image in images:
            rawSurface = nvUpl.UploadSingleFrame(image.flatten().astype(np.uint8))
            cvtSurface = nvCvt.Execute(rawSurface)
            if (cvtSurface.Empty()):
                print('Failed to do color conversion')
                break
            cvtSurface2 = nvCvt2.Execute(cvtSurface)
            if (cvtSurface2.Empty()):
                print('Failed to do color conversion')
                break
            success = nvEnc.EncodeSingleSurface(cvtSurface, encFrame,sync = True)
            if(success):
                bits = bytearray(encFrame)
                encFile.write(bits)
success = nvEnc.Flush(encFrame)
if(success):
     bits = bytearray(encFrame)
     encFile.write(bits)
encFile.close()
```
Ideally I would do something like this:
RGB->YUV420-->MP4

Let me know if this would be possible and what the reason could be for my videofiles not playing in VLC.

OS: Ubuntu 20
Python: 3.7
GPU: RTX2080Ti

**Comment by rarzumanyan** [comment]
Hi @Timen 

>RGB->YUV420->NV12->MP4

VPF doesn't have video muxer, so it outputs Annex.B elementary video stream, not the MP4 container.
Generally you can save encoded video packets to "\*.h264" or "\*.h265" file and open it with VLC.

>I'm trying to encode some RGB video from a numpy array to an YUV420 h.265 mp4 file. For what I want to use the GPU for speeding up the preprocessing of a video dataset which in turn will be loaded using DALI for training in pytorch

VPF does support interoperability with Pytorch so you can convert your rgb frames to planar rgb and upload to Pytorch tensors without encoding + decoding.

**Comment by Timen** [comment]
> VPF doesn't have video muxer, so it outputs Annex.B elementary video stream, not the MP4 container.
> Generally you can save encoded video packets to "*.h264" or "*.h265" file and open it with VLC.
Ah okay, that is good to know thanks!

> VPF does support interoperability with Pytorch so you can convert your rgb frames to planar rgb and upload to Pytorch tensors without encoding + decoding.

Directly processing with pytorch during training is not an option (I would have done it if I could), as I would run into a CPU bottleneck. Therefore I want to preprocess data, to store on disk so I don't run into a CPU bottleneck during training. So the goal is to preprocess data to some size efficient format that can be decoded quickly on GPU using the Nvidia DALI framework.(It offers very good integration with pytorch for distributed training etc.)

So ideally I was thinking I use h265 with YUV420 pixel format to get the best size and decoding performance when decoding on the GPU. I verified this pipeline works when using FFMPEG for encoding, but now that you pointed out that VPF doesn't support muxing I'm not sure the generated files would be compatible with the DALI VideoReader.

**Comment by Timen** [comment]
I think I may have figured out but just to be sure: Is YUV420 the same  as NV12?

**Comment by rarzumanyan** [comment]
@Timen 

No, it has different chroma pixels sampling.
NV12 of size `WxH` is `Wx(H+H/2)` 2D chunk of memory. First `WxH` is Y plane, then `WxH/2` UV plane with U and V values interleaved.
YUV420 is `WxH` Y plane, then `(W/2)x(H/2)` U plane, then `(W/2)x(H/2)` V plane.

**Comment by rarzumanyan** [comment]
@Timen 

I'm closing this issue as resolved.
In case you still have problems with Annex.B videos playback please reopen.
