### ISSUE TITLE
How to encode videos of different resolution

### ISSUE THREAD

**Issue by Timen** [NVIDIA/VideoProcessingFramework#116]
I'm trying to encode videos from numpy arrays which have multiple resolution. Everything works fine using when I resize the videos to a consistent resolution before encoding. But If I want to support dynamic resolution I run into several errors. Some example code:
```
nvUpl =None
nvCvt = None
nvCvt2 = None
nvEnc = nvc.PyNvEncoder({'preset': 'hq', 'codec': 'hevc',"s":"{}x{}".format(1280,1280)}, gpuID)
for video in videos:
     width = video.shape[2]
     height = video.shape[1]
    nvUpl = nvc.PyFrameUploader(int(width), int(height), nvc.PixelFormat.RGB, gpuID)
    nvCvt = nvc.PySurfaceConverter(int(width), int(height), nvc.PixelFormat.RGB, nvc.PixelFormat.YUV420, gpuID)
    nvCvt2 = nvc.PySurfaceConverter(int(width), int(height), nvc.PixelFormat.YUV420, nvc.PixelFormat.NV12, gpuID)
    success = nvEnc.Flush()
    if(success):
                bits = bytearray(encFrame)
                encFile.write(bits)
    nvEnc.Reconfigure({"s":"{}x{}".format(width,height)},reset_encoder=True)
    for idx, image in enumerate(video):
            image =  image[...,::-1]
            rawSurface = nvUpl.UploadSingleFrame(image.flatten().astype(np.uint8))
            cvtSurface = nvCvt.Execute(rawSurface)
            if (cvtSurface.Empty()):
                print('Failed to do color conversion')
                break
            cvtSurface2 = nvCvt2.Execute(cvtSurface)
            if (cvtSurface2.Empty()):
                print('Failed to do color conversion')
                break
            success = nvEnc.EncodeSingleSurface(cvtSurface2, encFrame,sync=False)
            if(success):
                bits = bytearray(encFrame)
                encFile.write(bits)
```

Running this results in the following error:
```
success = nvEnc.EncodeSingleSurface(cvtSurface2, encFrame,sync=False)
RuntimeError: Error while encoding frame
```

Note that the new width and height are always smaller than the original 1280x1280 used to initialize the encoder. The reason for the 1280x1280 initialization is that otherwise reconfiguring the size would result in an error telling that the new size is larger than the maximum encode width or height.

**Comment by rarzumanyan** [comment]
@Timen 

Every time you change resolution you need to reconfigure encoder. Look at the SampleEncode.py to see how it's done.
Please note that resolution change affects encoding efficiency.

**Comment by Timen** [comment]
I reconfigure the encoder before I loop over the video frames using this line:
`nvEnc.Reconfigure({"s":"{}x{}".format(width,height)},reset_encoder=True)`

**Comment by Timen** [comment]
Okay, I'm able to make it work but it requires me running one dummy frame at the max resolution through the encoder before reconfiguring and resetting the encoder to a different resolution.

**Comment by rarzumanyan** [comment]
@Timen 

>So I think this simply means dynamic resolutions aren't possible when reusing one encoder, as the set of resolutions are limited for me, I'll probably create a separate encoder for each resolution.

Dynamic resolution change isn't the most popular feature so I did some basic testing and nothing above that.
Can you elaborate a bit more on what resolutions do you use during the encoding process?
Maybe I've just missed something during the feature development process.

**Comment by Timen** [comment]
Okay I have multiple videos anywhere from 320x180 to 240x320 (and anything in between), that I want to encode. So in theory a max resolution of 320x320. If I could set this max resolution during the encoder init that would help already, the issue is that each time i pass the "s" argument this also adjusts the maximum resolution, decoupling the s argument and max encode resolution could help there. 

However this wouldn't fix the aspect ratio error I mentioned above, where it seems one can only have aspect ratios smaller than the aspect ratio of the maximum resolution.

**Comment by rarzumanyan** [comment]
@Timen 

>the issue is that each time i pass the "s" argument this also adjusts the maximum resolution, decoupling the s argument and max encode resolution could help there

Ok, allow me some time to investigate and fix. I'll update you as I get something.
Meanwhile I guess the multiple encoders will work the issue around.

**Comment by Timen** [comment]
No problem, thank you for helping out! I can work around it for now.

**Comment by rarzumanyan** [comment]
@Timen 

I've added `max_res` encoder option which decouples maximum resolution from input frame resolution.
It has the same syntax as `s` option: 
```python
nvEnc = nvc.PyNvEncoder({
  'preset':'hq', 
  'codec':'h264', 
  's':'1280x720', 
  'max_res':'1920x1080', 
  'bitrate':'10M'}, 
gpuID)
```

**Comment by Timen** [comment]
@rarzumanyan Great, I'll give this a try! Would this also allow dynamic scaling with different aspect ratios?

**Comment by rarzumanyan** [comment]
Closing this issue.
