### ISSUE TITLE
Is there any API for converting a pytorch tensor to surface?

### ISSUE THREAD

**Issue by hive-cas** [NVIDIA/VideoProcessingFramework#118]
Dear colleague,
I see there is 'pnvc.makefromDevicePtrUint8' function to transform a decoded surface to pytorch tensor.
Is there any reverse procedure: transforming a pytorch tensor to surface for encoding?
Thanks

**Comment by rarzumanyan** [comment]
Hello @hive-cas 

>Is there any reverse procedure: transforming a pytorch tensor to surface for encoding?

I believe this issue is a duplicate of #109.
Unfortunately, the reverse procedure isn't implemented and there's no way to convert a Pytorch tensor to VPF surface (which is plain `CUdeviceptr`).

**Comment by hive-cas** [comment]
Thanks for the reply. I see.
Then for encoding, I think the only way is: pytorch tensor--> numpy on CPU --> surface on GPU --> encode.
