### ISSUE TITLE
NvDecoder failed,not call NvDecoder's three callback function when decode rtsp stream

### ISSUE THREAD

**Issue by xinyi61** [NVIDIA/VideoProcessingFramework#120]
**Describe the bug**

**To Reproduce**
1. build rtsp server use ffserver and get a rtsp stream
2. use the rtsp stream to decode

problem:
not call NvDecoder's three callback function:HandleVideoSequence and HandlePictureDecode, the pack send to cuvidParseVideoData  payload_size is valid,but p_impl->m_nDecodedFrame is always 0.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
OS: ubuntu 18.04
Nvidia driver version: 440.33.01
CUDA Version: 10.2
Video Codec SDK Version:Video_Codec_SDK_10.0.26
C++

**Additional context**
the rtsp stream send to decode info is:
```shell
ffprobe rtsp://192.168.90.209:5454/sample_video_8.mp4
ffprobe version 4.2.4 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --enable-shared --disable-static --disable-yasm --disable-doc --enable-gpl --enable-swscale --enable-pthreads --disable-w32threads --disable-os2threads --enable-debug --enable-nvenc --enable-cuda --enable-cuvid --enable-avresample --extra-cflags='-Invidia_sdk -I/usr/local/cuda-10.2/include' --extra-ldflags='-Lnvidia_sdk -L/usr/local/cuda-10.2/lib64' --enable-nonfree --enable-libfreetype --enable-libnpp
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://192.168.90.209:5454/sample_prison_video_8.mp4':
  Metadata:
    title           : No Title
  Duration: N/A, start: 10.079000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
```
I am not sure whether NVCODE surpport this Stream (#0:0: Video: h264 (High), yuv420p(progressive), 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc).

what can i do to solve this problem??

**Comment by rarzumanyan** [comment]
Hi @xinyi61 

I recommend you 2-step approach to this problem:

1. Dump the video you're streaming on disk and decode with VPF from file. If that solves the issues it means problem is on ffmpeg side as it can't handle the rtsp input unlike file input

2. If VPF can't decode local file input - upload the video file somewhere, I'll take a closer look at it.

**Comment by xinyi61** [comment]
Thank you for your advice i will try it right now.  I am also have a problem when mult-thread decode, the problem description is in [#112](https://github.com/NVIDIA/VideoProcessingFramework/issues/112)，could you have a look and give some suggestions?

**Comment by rarzumanyan** [comment]
@xinyi61 

`cpp_samples` is outdated feature branch which wasn't merged to master so it makes little sense to fix it as it would be difficult to merge fixes from it to main branch.

**Comment by xinyi61** [comment]
@rarzumanyan 
I read the full source code，it seems that there is no difference between python and cpp branch in TC.The problem is  bound to arise.

**Comment by xinyi61** [comment]
@rarzumanyan 
if i want to use the master branch code to compile c++ library, all i need to do is replace py::array to std::vecor and in cmakelist add NvCodec shared library??

**Comment by rarzumanyan** [comment]
@xinyi61 

Yes, this should be enough.

**Comment by xinyi61** [comment]
@rarzumanyan 
ok i will try it

**Comment by rarzumanyan** [comment]
Closing this issue, please use SampleDecodeRTSP.py for reference.
