### ISSUE TITLE
call EncodeSingleSurface without messageSEI but with sync=True

### ISSUE THREAD

**Issue by sniklaus** [NVIDIA/VideoProcessingFramework#123]
The interface for `EncodeSingleSurface` has changed and it now has an additional `messageSEI`. However, I am under the impression that it is currently not possible to call `EncodeSingleSurface` without a `messageSEI` but with `sync` set to true. I tried passing `None` for `messageSEI` but then pybind complaints that `None` is not a Numpy array. I solved this issue on my end by adding another interface for `EncodeSingleSurface` that has `sync` but no `messageSEI` in its signature. This is not an elegant solution though which is why I refrained from opening up a corresponding pull request.

**Comment by rarzumanyan** [comment]
Hi @sniklaus 

Thanks for bringing this up.
Yes, after VPF interface refactoring this feature was missed. I've uploaded the patch to `issue_123` branch. Please check if it resolves the issue and I will merge to master then.

**Comment by sniklaus** [comment]
That works, thank you!
