### ISSUE TITLE
"decoder not initialized" with H264 and YUV444

### ISSUE THREAD

**Issue by sniklaus** [NVIDIA/VideoProcessingFramework#124]
I just wanted to decode a H264 video that uses YUV444 as the pixel format but I am getting a "decoder not initialized" error. However, when the decoding works just fine with a HEVC video that uses YUV444 as well. Is this expected? I am happy to provide a minimal code example to reproduce this error in case it is a bug and you need help with tracking it down. Thanks!

**Comment by rarzumanyan** [comment]
Hi @sniklaus 

H.264 YUV444 isn't supported, please take a look at the [Nvdec support matrix](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) unlike HEVC YUV444 which does have Nvdec support.

**Comment by sniklaus** [comment]
Thank you for clarifying! I figured as much but was fooled by `ffmpeg -h encoder=h264_nvenc` which lists it as being supported.

```
Encoder h264_nvenc [NVIDIA NVENC H.264 encoder]:
    General capabilities: delay hardware 
    Threading capabilities: none
    Supported pixel formats: yuv420p nv12 p010le yuv444p p016le yuv444p16le bgr0 rgb0 cuda
```

**Comment by sniklaus** [comment]
Wait, I am confused. The support matrix you linked lists H264 with YUV444 being supported on the hardware I use for debugging.

![Screenshot_2020-10-20_09-29-05](https://user-images.githubusercontent.com/1238034/96616233-28ef0400-12b7-11eb-98cd-fe176d84c2bb.png)

This seems like a bug in the Video Processing Framework after all, and FFMPEG is perfectly happy to encode YUV444 frames with the h264_nvenc encoder on my system. Would you mind looking into this again? Thanks!

**Comment by rarzumanyan** [comment]
Hi @sniklaus 

>I just wanted to decode a H264 video that uses YUV444
>FFMPEG is perfectly happy to encode YUV444 frames with the h264_nvenc encoder

So what do you want to do? Decode or encode?

**Comment by sniklaus** [comment]
Both. :upside_down_face: 

I first encode videos using the Video Processing Framework and them decode them later again. The mentioned error surfaces during decoding but it may be due to a corrupted encoding and I haven't yet investigated this further. My apologies for not having been clear about this. The support matrix does not list the pixel formats separately for decoding H264, so I am under the impression that it supports all (common) formats.

![Screenshot_2020-10-20_09-43-42](https://user-images.githubusercontent.com/1238034/96617851-ff36dc80-12b8-11eb-95b5-dd472cfc610f.png)

**Comment by rarzumanyan** [comment]
NP with that.

VPF supports H.264 and H.265 YUV444 encoding:
https://github.com/NVIDIA/VideoProcessingFramework/blob/b64e09db34149697a86c4aefe693e88b262aa22b/PyNvCodec/src/PyNvCodec.cpp#L1145-L1148

But H.265 YUV444 decoding only. So generally I recommend you just stick to H.265 if that's acceptable for your project.

**Comment by sniklaus** [comment]
Thanks for clarifying that!
