### ISSUE TITLE
How to extract the Y channel in YUV420 format and convert it to tensor

### ISSUE THREAD

**Issue by hive-cas** [NVIDIA/VideoProcessingFramework#128]
Dear colleague,
Thanks again for the wonderful project!

Is there any way to convert only Y channel to pytorch tensor? I found all the conversion is for RGB format as in :
`        nvPlanar = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(), nvc.PixelFormat.RGB, nvc.PixelFormat.RGB_PLANAR, gpuID)`

I want to extract the Y channel after the color conversion and convert it to pytorch tensor.

Thanks.

**Comment by rarzumanyan** [comment]
Hi @hive-cas 

PytorchNvCodec accepts any 2D-chunk of CUDA memory for export.
I've never tested the grayscale channel image export myself but planar RGB is basically 3xY so you shouldn't have problems with that.

**Comment by ValZapod** [comment]
You can use ffplay -vf extractplanes=y

:)

**Comment by rarzumanyan** [comment]
Resurrecting this after a while.
Recently the NV12->Y color conversion was added so marking this as fulfilled.
