### ISSUE TITLE
How to install the VPF

### ISSUE THREAD

**Issue by vujadeyoon** [NVIDIA/VideoProcessingFramework#129]
Dear all,

I hope to use the Video Processing Framework (VPF), but cannot install or build it.
Also, I cannot find any instructions.

I have two questions:
- Could you please give me some instructions to install the VPF, especially the PyNvCodec?
- Is the [NVIDIA video codec SDK](https://developer.nvidia.com/nvidia-video-codec-sdk) required for the VPF?

Best,
Vujadeyoon

**Comment by rarzumanyan** [comment]
Hi @vujadeyoon 

>Could you please give me some instructions to install the VPF

Please follow the [wiki guide](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source).

>Is the NVIDIA video codec SDK required for the VPF?

Yes, it is.
