### ISSUE TITLE
Compiling with older Video_Codec_SDK

### ISSUE THREAD

**Issue by tetelias** [NVIDIA/VideoProcessingFramework#13]
Not able to update NVidia driver I'm forced to use Video_Codec_SDK_8.2.16.
So "cmake .." goes without a hitch. ffmpeg was compiled from source with --enable-nvenc after installing correct version of nv-codec-headers
![1](https://user-images.githubusercontent.com/29153358/75111829-26b4a700-564f-11ea-88db-c1fcee7ce7b4.jpg)
But at "make" stage it breaks and can't figure out what's wrong.
![2](https://user-images.githubusercontent.com/29153358/75111920-ebff3e80-564f-11ea-87e1-dcf449b222c7.png)
Any ideas?

**Comment by rarzumanyan** [comment]
Error is caused by SDK being too old, it doesn’t have mentioned symbols defined (NV_ENC_BUFFER_USAGE and NV_ENC_INPUT_IMAGE).

**Comment by tetelias** [comment]
Thanks! Will look into what's going on in newer SDKs.
