### ISSUE TITLE
Why the GPU cuda core util is so high when encoding or decoding without color conversion?

### ISSUE THREAD

**Issue by TracelessLe** [NVIDIA/VideoProcessingFramework#131]
**Problem**
When I run the encode or decode (such as SampleDecode.py or SampleEncode.py) using VPF without color space conversion, the "Volatile GPU-Util" is so high (~40%). It means the encode/decode process consume many GPU cuda cores. To the best of my knowledge, VPF utilizes [NVIDIA Video Codec SDK](https://developer.nvidia.com/nvidia-video-codec-sdk#NVENCFeatures) as backend for flexibility and performance. 

As said on the webpage of NVIDIA Video Codec SDK, "NVIDIA GPUs contain one or more hardware-based decoder and encoder(s) (separate from the CUDA cores) which provides fully-accelerated hardware-based video decoding and encoding for several popular codecs. With decoding/encoding offloaded, the graphics engine and the CPU are free for other operations." 

What puzzles me is what process uses CUDA cores to do a lot of calculation in the whole decode/encode process, 
I thought it should consume a little GPU computing power. Can you give some explanation.

Thanks a lot.

**Screenshots**
<img width="681" alt="截屏2020-11-04 22 43 36" src="https://user-images.githubusercontent.com/22371026/98127582-d554fb00-1ef1-11eb-9cca-9b12795cf5d5.png">

**Desktop (please complete the following information):**
- OS: ubuntu 18.04
- Nvidia driver version: 440.82
- CUDA Version: 10.1
- Video Codec SDK Version: 9.1.23
- Python Version: 3.6.10

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

Please run `nvidia-smi dmon` alongside script and upload the output.
It will show detailed load level of nvdec, nvenc, cuda cores and overall amount of memory used.

**Comment by TracelessLe** [comment]
Hi @rarzumanyan 

Firstly, I run the decode process 5 times in a loop, the log of "nvidia-smi dmon" command is attached:
[Decode Log.txt](https://github.com/NVIDIA/VideoProcessingFramework/files/5491518/Decode.Log.txt)

Then, the encode process also runs 5 times and the log is  attached:
[Encode Log.txt](https://github.com/NVIDIA/VideoProcessingFramework/files/5491524/Encode.Log.txt)

The codes I use are attached:
[SampleDecode and SampleEncode.zip](https://github.com/NVIDIA/VideoProcessingFramework/files/5491544/SampleDecode.and.SampleEncode.zip)

From the log attached above, it is showed that the sm(%) is consumed a lot when the enc(%) or dec(%) is used.

I feel confused. :(

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

These results are strange indeed. 
When I run SampleDecode.py I see slight sm usage (color conversion between Nvdec internal format and NV12 is done via CUDA kernel):
![Capture](https://user-images.githubusercontent.com/45193474/98211314-e7b35100-1f52-11eb-8e97-c1e11ba6d17a.JPG)

Can you update the driver and Video Codec SDK?

**Comment by TracelessLe** [comment]
OK, I will try to update the driver and Video Codec SDK soon. Would you tell me what version of those packages you use in your reproduce?

By the way, the GPU I use is GeForce RTX 2080Ti, dose the GPU type matter?

**Comment by rarzumanyan** [comment]
@TracelessLe 

>Would you tell me what version of those packages you use in your reproduce?

Video Codec SDK 10, CUDA 11 and 452.06 video driver.
I recommend you to update to latest driver, CUDA SDK and Video Codec SDK versions possible.
>dose the GPU type matter?

No, it doesn't. You shall see low sm usage on any modern GPU, especially on 2080Ti which is quite powerful.

**Comment by TracelessLe** [comment]
@rarzumanyan 👍 

Extremely grateful, I will have a try.

**Comment by TracelessLe** [comment]
Hi @rarzumanyan 

I have upgrade the Video Codec SDK to v10, CUDA to v11.0 and driver to 450.51.05 on my ubuntu 18.04 laptop, but the sm usage is still high.

When I run SampleDecode.py, the sm usage is still ~40%  while the dec usage is nearly 30%.
[Decode Log Laptop.txt](https://github.com/NVIDIA/VideoProcessingFramework/files/5499632/Decode.Log.Laptop.txt)

When the SampleEncode.py is running, the sm(%) is ~50% while the enc(%) is ~60%.
[Encode Log Laptop.txt](https://github.com/NVIDIA/VideoProcessingFramework/files/5499640/Encode.Log.Laptop.txt)

After further thinking, I realized that the 2080Ti GPU I use is connected with my laptop by docking station with thunderbolt. May be the connect method makes the difference.

So I use my cloud GPU server to reproduce, which has a Tesla V100 GPU. Those dependent packages are still in old version. 

On the V100 machine, the sm usage is slight (~8%) as in your reproduce in decode process, the log is attached:
[Decode Log V100 GPU.txt](https://github.com/NVIDIA/VideoProcessingFramework/files/5499686/Decode.Log.V100.GPU.txt)

When I run SampleEncode.py, the sm(%) is nearly 15% while enc(%) is ~30%.
[Encode Log V100 GPU.txt](https://github.com/NVIDIA/VideoProcessingFramework/files/5499709/Encode.Log.V100.GPU.txt)

Does these consumptions are normal on the V100 machine? And may the thunderbolt connection method affect the consumptions of GPU cuda cores?

I'm still puzzled... -_-

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

>Does these consumptions are normal on the V100 machine?

IMO these are bit higher than it should be.

>And may the thunderbolt connection method affect the consumptions of GPU cuda cores?

Very interesting question which I don't know how to answer :)
Can you run the encoding sample under Visual Profiler? It's shipped as part of CUDA SDK.
To launch Python sample under profiler, simply set the Python interpreter as application and script + it's arguments as app args.
You can export the application timeline as file and upload it or simply share the screenshots.

**Comment by TracelessLe** [comment]
I run the Visual Profiler on my 2080Ti laptop and V100 machine, the decode and encode profilers are attached as follow:
[Decode_and_Encode_profiles.zip](https://github.com/NVIDIA/VideoProcessingFramework/files/5500102/Decode_and_Encode_profiles.zip)

Please check it and point what's wrong in the processes, thanks a lot.

**Comment by rarzumanyan** [comment]
@TracelessLe 
Your RTX2080Ti is badly limited by Thunderbolt connection, memory bandwidth is ~5 times slower then that for V100:
![Capture](https://user-images.githubusercontent.com/45193474/98358797-4b637a00-2038-11eb-9787-4d0ad874ba54.PNG)

versus
![Capture1](https://user-images.githubusercontent.com/45193474/98358810-51595b00-2038-11eb-9bb2-c46bbd478748.PNG)

**Comment by TracelessLe** [comment]
Oops, so is it means that the Thunderbolt connection aggravates the sm usage? 😧

And I wonder why the consumptions (include sm and enc) in encoding on the V100 machine  is so high, does there some advice (such as use some control parameters) to avoid large consumptions of these resources when VPF does encode? I want to do deep learning inference on the GPU but VPF consumes a lot computing power. :(

**Comment by rarzumanyan** [comment]
@TracelessLe 

>Thunderbolt connection aggravates the sm usage?

I'm not 100% sure of that as GPU shall support DMA but it's connected via Thunderbolt so I'm running out of depth here to be honest. Given that my RTX5000 has less CUDA cores then yours RTX2080Ti although it doesn't show high sm usage, this is the only explanation which comes to my head.

**Comment by TracelessLe** [comment]
Thanks for reply. May be the Thunderbolt makes the performance of RTX2080Ti is not playing out. 

How about the performance of my V100 machine, does the VPF encode process has any possibility of optimization for sm usage?

**Comment by rarzumanyan** [comment]
>How about the performance of my V100 machine, does the VPF encode process has any possibility of optimization for sm usage?

VPF uses only NPP functions for color conversion and `cuMemcpy` for IO so I don't see too much room for improvement. 
Frankly I doubt I can write better color conversion kernels then our NPP people who are CUDA experts.

**Comment by TracelessLe** [comment]
Haha, excellent! 👍👍👍
