### ISSUE TITLE
fatal error: nvEncodeAPI.h: No such file or directory

### ISSUE THREAD

**Issue by xiaoyang-coder** [NVIDIA/VideoProcessingFramework#137]
<img width="935" alt="WX20201208-142009@2x" src="https://user-images.githubusercontent.com/43001198/101447620-88d16500-3960-11eb-8e22-6f9aeb61b66c.png">
<img width="710" alt="WX20201208-142134@2x" src="https://user-images.githubusercontent.com/43001198/101447743-c59d5c00-3960-11eb-9603-6a62c0588baa.png">
I installed it completely according to the tutorial, why this error occurred, please help

**Comment by xiaoyang-coder** [comment]
export PATH_TO_SDK=/home/xiaoyang03/.jupyter/Video_Codec_SDK_9.0.20 
export PATH_TO_FFMPEG=/usr/local 
export CUDACXX=/usr/local/cuda/bin/nvcc   
# If you want to generate Pytorch extension, set up corresponding CMake value GENERATE_PYTORCH_EXTENSION 
cmake .. \   -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
   -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \ 
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
   -DGENERATE_PYTORCH_EXTENSION:BOOL="0" \ 
  -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m\
   -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \ 
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"
make && make install

**Comment by xiaoyang-coder** [comment]
@rarzumanyan

**Comment by xiaoyang-coder** [comment]
> <img alt="WX20201208-142009@2x" width="935" src="https://user-images.githubusercontent.com/43001198/101447620-88d16500-3960-11eb-8e22-6f9aeb61b66c.png">
> 
> <img alt="WX20201208-142134@2x" width="710" src="https://user-images.githubusercontent.com/43001198/101447743-c59d5c00-3960-11eb-9603-6a62c0588baa.png">
> 
> I installed it completely according to the tutorial, why this error occurred, please help

**Comment by niaoyu** [comment]
I suggest you use nvidia ngc tensorrt docker as base image which has a good pre-build environment.

**Comment by contentis** [comment]
Can you check with the current master branch to see if this issue has been resolved? We do have a docker container using TRT.
