### ISSUE TITLE
How to encode into  TRMP/TRSP streams

### ISSUE THREAD

**Issue by baconLIN001** [NVIDIA/VideoProcessingFramework#141]
Hi! This is a nice project and thanks for your contribution!
I have a question. My intent is to read RTSP/RTMP stream into my pytorch models, and encode the outputs to a new RTSP/RTMP stream. I find your decoder `PyNvDecoder` supports network input such as RTSP. But how can I use your encoder to generate RTMP video stream. I read your code in `PyNvCodec.cpp` and `PytorchNvCodec.cpp`, but it seems have not been achieved? May you show me how to encode RTMP video streams?
Thank you!

**Comment by rarzumanyan** [comment]
Hi @baconLIN001 

VPF doesn't support muxing. You can only obtain Annex.B elementary video stream from GPU. You have to use 3rd-party libraries if you want to mux the video.

**Comment by lilong-epfl** [comment]
> Hi! This is a nice project and thanks for your contribution!
> I have a question. My intent is to read RTSP/RTMP stream into my pytorch models, and encode the outputs to a new RTSP/RTMP stream. I find your decoder `PyNvDecoder` supports network input such as RTSP. But how can I use your encoder to generate RTMP video stream. I read your code in `PyNvCodec.cpp` and `PytorchNvCodec.cpp`, but it seems have not been achieved? May you show me how to encode RTMP video streams?
> Thank you!

I am also looking for solution for this issue. Please let me know if you have any idea. Thanks!

**Comment by lamhoangtung** [comment]
Can you suggest some 3rd lib that can help achieve this ? @rarzumanyan

**Comment by baconLIN001** [comment]
您好，我是林文根，您的邮件我已收到，谢谢

**Comment by rarzumanyan** [comment]
Hi @lamhoangtung 

PyAV may be used for that. 
There are some code snippets illustrating how to mux with PyAV, please search for that in closed issues.

**Comment by rarzumanyan** [comment]
> 您好，我是林文根，您的邮件我已收到，谢谢

Apologies, but I'm not speaking your language. Please translate to English.

**Comment by lamhoangtung** [comment]
Thanks for the quick response. Are you talking about this https://github.com/NVIDIA/VideoProcessingFramework/issues/96 @rarzumanyan ?

**Comment by rarzumanyan** [comment]
@lamhoangtung 

Yes, this one.

Also it turned that I've already put the code sample into a wiki article :)
https://github.com/NVIDIA/VideoProcessingFramework/wiki/How-to-put-elementary-video-stream-into-container%3F
