### ISSUE TITLE
Huge gpu resource increase if adding import torch 

### ISSUE THREAD

**Issue by niaoyu** [NVIDIA/VideoProcessingFramework#142]
**Describe the bug**
Just using the code, [https://github.com/NVIDIA/VideoProcessingFramework/blob/master/SampleDecode.py](url)
if adding "import torch " in the first line, the gpu usage will increase too much.

**To Reproduce**

0.  Install
Build VPF as the instruction here with https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source
Get PyNvCodec.cpython-36m-x86_64-linux-gnu.so and PytorchNvCodec.cpython-36m-x86_64-linux-gnu.so successly.

1. Regular decoding
```python
import PyNvCodec as nvc
import numpy as np
import sys
```
python SampleDecode.py 0 rtsp://admin:dxxxx6@1xxxx132:554/h264/ch1/main/av_stream test.mp4

2. Adding import torch in the first line
```python
import torch
import PyNvCodec as nvc
import numpy as np
import sys
```
python SampleDecode.py 0 rtsp://admin:dxxxx6@1xxxx132:554/h264/ch1/main/av_stream test.mp4

**Expected behavior**
The gpu usage is the same.

**Screenshots**
However,
In the first decoding process, the gpu usage is 314M.
In the second decoding process, the gpu usage is 1872M

**Desktop (please complete the following information):**
 - OS: Linux
 - Nvidia driver version: 440.64.00
 - CUDA Version: 10.2
 - Video Codec SDK Version: 10.0.26
 - Python Version: 3.6

**Comment by rarzumanyan** [comment]
Hi @niaoyu 

Can you isolate this issue from VPF?
E. g. import `torch` from another Python file which doesn't import any of the VPF Python modules and check GPU memory consumption?

**Comment by niaoyu** [comment]
@rarzumanyan 
You are absolutely right. 

While creating a torch.cuda.tensort after import torch, the gpu memory will be increased a lot due to the cuda issue itself.

This is not  a bug and sry for that.
