### ISSUE TITLE
Proper method for encoding JPEG after downloadSingleSurface

### ISSUE THREAD

**Issue by niaoyu** [NVIDIA/VideoProcessingFramework#144]
1. Hi, vpf is great while I used in my project which is build a server to decode more than 80 rtsp urls in T4.It shows high efficiency to break out GIL limitation just using python thread after my test.

2. However, after downloadSingleSurface,  I need to transform the output raw_frame to a jpeg bytes in python or string in c++ for the corresponding client.
But whether use cv2.encode or PIL image, the fps decrease a lot from 25FPS to 4fps in 20rtsp urls. (Maybe the reason is GIL in python here)
```python
# PIL method
img0_pil = Image.fromarray(img0)
buf = BytesIO()
img0_pil.save(buf, format='JPEG')
img_binary_pil = buf.getvalue()
buf.close()

# Opencv method
status, encode_frame = cv2.imencode('.jpg', img0)
img_binary_pil = encode_frame.tobytes()
```

3. To avoid the GIL problems with python encoding and achieve high efficiency,  nvjpegEncodeImage maybe a good solution.
And the sample code is simple shown here,
https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpeg-encode-examples

The main issue will be 
1) the jpeg string length is not known until get the length after commpress using nvjpegEncodeRetrieveBitstream.
So I could not malloc a numpy frame and then put it as input just  downloadSingleSurface.
2) Thread safe
https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpeg-thread-safety
"When using encoder APIs across multiple threads, nvjpegEncoderState_t should be instantiated separately for each thread."

Honestly speaking, I am not familiar with c++ and VPF architecture design. 
If I want to use nvjpeg to transfer frame to a jpeg string, could you give me some advice for that ?

Best wishes!

**Comment by rarzumanyan** [comment]
Hi @niaoyu 

>If I want to use nvjpeg to transfer frame to a jpeg string, could you give me some advice for that ?

IMO the "cleanest" way to implement this is to add another `Task` which will accept YUV420 `Surface` and then call JPEG encoder without any excessive memory copies between Host and Device. 

>Thread safe

This can be addressed easily. There's a NPP global mutex class implemented here: https://github.com/NVIDIA/VideoProcessingFramework/blob/38b9953840be8b7b97330117d49f3e682d171c28/PyNvCodec/TC/src/NppCommon.cpp#L41-L43

The same thing for `nvJPEG` can be added as well.
NPP global mutex is actually no longer needed, its still there since the non-managed NPP context calls time.

**Comment by niaoyu** [comment]
> Hi @niaoyu
> 
> > If I want to use nvjpeg to transfer frame to a jpeg string, could you give me some advice for that ?
> 
> IMO the "cleanest" way to implement this is to add another `Task` which will accept YUV420 `Surface` and then call JPEG encoder without any excessive memory copies between Host and Device.
> 
> > Thread safe
> 
> This can be addressed easily. There's a NPP global mutex class implemented here:
> 
> https://github.com/NVIDIA/VideoProcessingFramework/blob/38b9953840be8b7b97330117d49f3e682d171c28/PyNvCodec/TC/src/NppCommon.cpp#L41-L43
> 
> The same thing for `nvJPEG` can be added as well.
> NPP global mutex is actually no longer needed, its still there since the non-managed NPP context calls time.

Thx for your suggestions! I will check it soon.

**Comment by contentis** [comment]
@niaoyu Can this be closed?
