### ISSUE TITLE
Why does a green screen appear when I use VPF to convert RGB frames to flat RGB?

### ISSUE THREAD

**Issue by SubMarineas** [NVIDIA/VideoProcessingFramework#146]
I have a requirement, first resize the resolution to (1080, 720), then crop and transform the image and throw it to pytorch, but I found that no matter what I do, the image recorded with opencv is always a green screen. What else can I do? After getting the RGB split, pass it to pytorch?
![image](https://user-images.githubusercontent.com/33534492/103600931-8c4a1300-4f43-11eb-85fb-31e6e0177aa9.png)

**Comment by SubMarineas** [comment]
width, height = 1080,720

nvDec = nvc.PyNvDecoder("01.mp4", 0)
# nvCvt = nvc.PySurfaceResizer(1080, 720, nvDec.Format(), 0)
x_width, x_height = nvDec.Width(), nvDec.Height()
nvCvt = nvc.PySurfaceConverter(x_width, x_height, nvDec.Format(), nvc.PixelFormat.YUV420, 0)
cvtNV12_RGB = nvc.PySurfaceConverter(width, height, nvDec.Format(), nvc.PixelFormat.RGB, 0)
nvRes = nvc.PySurfaceResizer(width, height, nvCvt.Format(), 0)
count = 0
nvDwn = nvc.PySurfaceDownloader(width, height, nvc.PixelFormat.RGB, 0)
while count <= 20:

    rawSurface = nvDec.DecodeSingleSurface()

    cvtSurface = nvCvt.Execute(rawSurface)
    if (cvtSurface.Empty()):
        print('Failed to do color conversion')
        break

    resSurface = nvRes.Execute(cvtSurface)
    if (resSurface.Empty()):
        print("failed to resize surface")
        break

    cvtRGBface = cvtNV12_RGB.Execute(resSurface)

    frameRGB = np.ndarray(shape=(cvtRGBface.HostSize()), dtype=np.uint8)
    success = nvDwn.DownloadSingleSurface(cvtRGBface, frameRGB)
    cv2.imwrite('/picture/test/{0}.jpg'.format(count), frameRGB.reshape((720,1080, 3)))
    count += 1

**Comment by SubMarineas** [comment]
```python
width, height = 1080,720

nvDec = nvc.PyNvDecoder("/home/runone/104#20200914-01.mp4", 0)
# nvCvt = nvc.PySurfaceResizer(1080, 720, nvDec.Format(), 0)
x_width, x_height = nvDec.Width(), nvDec.Height()
nvCvt = nvc.PySurfaceConverter(x_width, x_height, nvDec.Format(), nvc.PixelFormat.YUV420, 0)
cvtNV12_BGR = nvc.PySurfaceConverter(width, height, nvDec.Format(), nvc.PixelFormat.RGB, 0)
nvRes = nvc.PySurfaceResizer(width, height, nvCvt.Format(), 0)
count = 0
nvDwn = nvc.PySurfaceDownloader(width, height, nvc.PixelFormat.RGB, 0)
while count <= 20:

    rawSurface = nvDec.DecodeSingleSurface()

    cvtSurface = nvCvt.Execute(rawSurface)
    if (cvtSurface.Empty()):
        print('Failed to do color conversion')
        break

    resSurface = nvRes.Execute(cvtSurface)
    if (resSurface.Empty()):
        print("failed to resize surface")
        break

    cvtRGBface = cvtNV12_BGR.Execute(resSurface)

    frameRGB = np.ndarray(shape=(cvtRGBface.HostSize()), dtype=np.uint8)
    success = nvDwn.DownloadSingleSurface(cvtRGBface, frameRGB)
    cv2.imwrite('/picture/test/{0}.jpg'.format(count), frameRGB.reshape((720,1080, 3)))
    count += 1
```

**Comment by SubMarineas** [comment]
From the issue of [139](https://github.com/NVIDIA/VideoProcessingFramework/issues/139) I can experiment to convert the RGB to be successful, but as long as I resize, I can’t get this picture. Why? ?

**Comment by niaoyu** [comment]
Becasue the proper format for resizing in vpf is yuv420.
just resize with YUV420, resize it and convert to rgb/bgr at last

**Comment by SubMarineas** [comment]
> Becasue the proper format for resizing in vpf is yuv420.
> just resize with YUV420, resize it and convert to rgb/bgr at last

Yes, I found that I have a converter written in reverse. VPF is in NV12 format by default. I thought it was YUV. If the format of the video stream is used directly, the U and V in the sampling frequency will be reversed, resulting in channel conversion Mismatch
