### ISSUE TITLE
undefined symbol: ff_ue_golomb_vlc_code

### ISSUE THREAD

**Issue by ltm920716** [NVIDIA/VideoProcessingFramework#150]
**Describe the bug**
there is a undefined error when run “import PyNvCodec as nvc”

**Screenshots**
![image](https://user-images.githubusercontent.com/12007227/104142058-c8262200-53f4-11eb-8f48-dc50ab39b614.png)
![image](https://user-images.githubusercontent.com/12007227/104142079-dd02b580-53f4-11eb-80c7-1a09a9daa9c9.png)
![image](https://user-images.githubusercontent.com/12007227/104142115-015e9200-53f5-11eb-93ab-597f4bcd2838.png)

**Desktop (please complete the following information):**
 - OS: Linux 9d91d2a30178 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Nvidia driver version： 440.100
 - CUDA Version: 10.1
 - Video Codec SDK Version: 9.1.23
 - Python Version: 3.7
 - ffmpeg version: master

**Additional context**
hello，
     I have installed ffmped successfully，then I installed VPF successfully too. When I run commond <python -c 'import PyNvCodec as nvc'>, it shows the undefine error, please help! thanks

**Comment by rarzumanyan** [comment]
Hi @ltm920716 

Please provide full output of `ldd -r libTC.so`
I can see CUDA & Video Codec SDK libs locations but not the libavcodec location.

**Comment by ltm920716** [comment]
hello @rarzumanyan ,
![image](https://user-images.githubusercontent.com/12007227/104158731-e9a10100-5428-11eb-8a68-a75520c2da70.png)

**Comment by rarzumanyan** [comment]
@ltm920716 

Thanks. Can you please also upload the output of CMake configure stage?
I wan to make sure that VPF was compiled  using the same `libavcodec` library which is loaded in runtime.

**Comment by ltm920716** [comment]
Hi @rarzumanyan 
Thank you！It is very kind of you！

[build.zip](https://github.com/NVIDIA/VideoProcessingFramework/files/5794652/build.zip)

**Comment by ltm920716** [comment]
bellow is the libavcodec path
![image](https://user-images.githubusercontent.com/12007227/104161254-7e0d6280-542d-11eb-850a-80eebeace231.png)

**Comment by rarzumanyan** [comment]
Hi @ltm920716 

This isn't the CMake configure output.
If possible, please delete the CMake cache and re-build the VPF again. First stage will be `configure`, it happens when you run the `cmake` from terminal or press `Configure` in CMake GUI client.

At this stage CMake will output where it searches for ffmpeg libraries. Chances are it finds `libavcodec` and others outside the `/usr/local/ffmpeg/lib`.

**Comment by ltm920716** [comment]
Hi @rarzumanyan 
![image](https://user-images.githubusercontent.com/12007227/104162886-65527c00-5430-11eb-94ab-d018c4b323aa.png)

**Comment by ltm920716** [comment]
![image](https://user-images.githubusercontent.com/12007227/104163321-2ffa5e00-5431-11eb-9130-c1a6bfe61459.png)

**Comment by rarzumanyan** [comment]
@ltm920716 

Thanks for the update.
Let's try one last check before we go into ffmpeg build configuration and such.
Please do the following:

1. export `LD_LIBRARY_PATH` to the VPF installation directory + `/usr/local/lib/ffmpeg/lib`
2. run `ldd -r PyNvCodec.so` from VPF installation directory
3. run one of the VPF samples

**Comment by ltm920716** [comment]
@rarzumanyan 
![image](https://user-images.githubusercontent.com/12007227/104166780-41923480-5436-11eb-9732-169af21d5343.png)

![image](https://user-images.githubusercontent.com/12007227/104167236-ff1d2780-5436-11eb-9483-718b7e12755b.png)

![Uploading image.png…]()

**Comment by ltm920716** [comment]
@rarzumanyan 
![image](https://user-images.githubusercontent.com/12007227/104166780-41923480-5436-11eb-9732-169af21d5343.png)

![image](https://user-images.githubusercontent.com/12007227/104167236-ff1d2780-5436-11eb-9483-718b7e12755b.png)

![image](https://user-images.githubusercontent.com/12007227/104167318-178d4200-5437-11eb-8d02-64d0bf6b8ed6.png)

**Comment by ltm920716** [comment]
@rarzumanyan 
![image](https://user-images.githubusercontent.com/12007227/104167593-8cf91280-5437-11eb-922c-8b45904b3713.png)

![image](https://user-images.githubusercontent.com/12007227/104167635-a69a5a00-5437-11eb-98d0-7b84dc2bbb13.png)

![image](https://user-images.githubusercontent.com/12007227/104167671-b44fdf80-5437-11eb-96c1-61144f981cfc.png)

**Comment by rarzumanyan** [comment]
@ltm920716 

Thanks for the update,
Can you please upload your ffmpeg configuration?

**Comment by ltm920716** [comment]
Hello @rarzumanyan 
./configure --prefix=/usr/local/ffmpeg --disable-asm --disable-x86asm \
 --enable-cuda --enable-cuvid --enable-nvenc \
 --enable-nonfree --enable-libnpp \
 --extra-cflags=-I/usr/local/cuda/include \
 --extra-cflags=-fPIC --extra-ldflags=-L/usr/local/cuda/lib64 \
 --enable-gpl --enable-libx264  --enable-libx265 \
 --enable-shared \
 --enable-libass \
 --enable-libfdk-aac \
 --enable-libfreetype \
 --enable-libmp3lame \
 --enable-libopus \
 --enable-libtheora \
 --enable-libvorbis \
 --enable-pic \
 --disable-static \
 --disable-stripping \
 --disable-doc

**Comment by rarzumanyan** [comment]
@ltm920716 

Please try to build & run VPF using the ffmpeg configuration as it's described in project's wiki [here](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source#build-procedure-details-for-linux-users):

```bash
mkdir -p $(pwd)/build_x64_release_shared 

./configure \
 --prefix=$(pwd)/build_x64_release_shared \
 --disable-static \
 --disable-stripping \
 --disable-doc \
 --enable-shared
 
make -j -s && make install
```

I assume the undefined symbol issue may be caused by one of 3rd party ffmpeg dependencies.

**Comment by ltm920716** [comment]
@rarzumanyan 
![image](https://user-images.githubusercontent.com/12007227/104172997-14e31a80-5440-11eb-8e2b-b5eb84c521b0.png)

it is still the same error

**Comment by rarzumanyan** [comment]
@ltm920716 

Don't get me wrong with this, but you've already rebuilt both ffmpeg and vpf from scratch, exported the env variables, checked the ldd and launched the sample?

**Comment by ltm920716** [comment]
Hi @rarzumanyan 
yes, I have done all the pipline. 
I hear that cuda10.2 would be ok, I will try and verify it. Thank you very much!

**Comment by ltm920716** [comment]
hello @rarzumanyan
I have verified that cuda10.1 and cuda10.2 are all ok！ I make this by the new initial environment，vpf has no problem！
It is my mistake before，thanks for your support！
Thanks again and good luck！
