### ISSUE TITLE
 why nvidia tesla t4 decode perfermance so good 

### ISSUE THREAD

**Issue by ald2004** [NVIDIA/VideoProcessingFramework#154]
![image](https://user-images.githubusercontent.com/4443533/105805546-277f5700-5fdd-11eb-935e-3f416a4f3457.png)

we are build a project for some ai detector, 
can you help me why t4 decode so fast?
thank you

**Comment by rarzumanyan** [comment]
Hi @ald2004 

How these results are obtained? What's the resolution, HW and SW configuration?

**Comment by ald2004** [comment]
from https://developer.nvidia.com/nvidia-video-codec-sdk,
about half of the page.

![image](https://user-images.githubusercontent.com/4443533/105815633-34f10d00-5fee-11eb-8052-9934032339a8.png)

**Comment by rarzumanyan** [comment]
@ald2004 

Long story short: Turing decoder performance is significantly improved in comparison to Pascal.
BTW this is outside the scope of VPF project so closing as irrelevant.
