### ISSUE TITLE
Support for audio extraction

### ISSUE THREAD

**Issue by prclibo** [NVIDIA/VideoProcessingFramework#155]
Hi, Does VPF have API to extract audio data from video? I did not find any related info. Thanks!

**Comment by rarzumanyan** [comment]
Hi @prclibo 

VPF only supports video decoding and encoding to Annex.B elementary format. No muxing and audio support.
Take a look at this issue: https://github.com/NVIDIA/VideoProcessingFramework/issues/99, it's shown there how to use PyAV in conjunction with VPF. 

As an option you can demux audio packets with PyAV separately from video packets and decode audio with PyAV.
Although audio is outside the scope of this project, so I've never tried this approach myself and can't provide you with any kind of help on this topic.
