### ISSUE TITLE
About timestamp

### ISSUE THREAD

**Issue by zhangmo123** [NVIDIA/VideoProcessingFramework#156]
Hi ,I try decode rtsp and rtmp with VPF, I have a question  about VPF API:
1. How to get the timestamp of the frame?
2. Could you provide API Documentation or API  Interface Description?
  Thank you very much for your reply!

**Comment by rarzumanyan** [comment]
Hi @zhangmo123 

This feature was recently added to `master` branch.
Please take a look at `SampleDecode.py` which illustrates how to get frame timestamp and seek for particular frame.
