### ISSUE TITLE
Failed to read frame: End of file

### ISSUE THREAD

**Issue by hubeichenxing** [NVIDIA/VideoProcessingFramework#157]
Hi, i run the SampleDecode.py unsuccessful with log:
```
This sample decodes input video to raw NV12 file on given GPU.
Usage: SampleDecode.py $gpu_id $input_file $output_file.
Decoding on GPU 0
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
No more video frames.
```
I print the frameSize, it is a right number, what‘s wrong potential?

**Comment by hubeichenxing** [comment]
My environment:
Python 3.6.5 |Anaconda
pytorch1.4.0
Video_Codec_SDK_11.0.10
Cuda compilation tools, release 10.1, V10.1.243
ffmpeg version c9f3835 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 8 (Ubuntu 8.4.0-1ubuntu1~16.04.1)
configuration: --enable-cuda --enable-cuvid --enable-shared --disable-static --disable-doc --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --extra-libs=-lpthread --nvccflags='-gencode arch=compute_75,code=sm_75'
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100

**Comment by hubeichenxing** [comment]
I fix it by uninstall & recompile ffmpeg, make sure where only one ffmpeg version in this os can avoid this problem.

**Comment by ADongGu** [comment]
but i cant
