### ISSUE TITLE
cmake can not find cuda

### ISSUE THREAD

**Issue by leonselina** [NVIDIA/VideoProcessingFramework#16]
-- The CUDA compiler identification is unknown
CMake Error at PyNvCodec/TC/CMakeLists.txt:20 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

but I had set the CUDA path to the environment, but it not work
could you show the complete command build on linux? Thank you:)

**Comment by rarzumanyan** [comment]
Hi,
As per console log, you need to export `CUDACXX` variable in shell prior to running cmake:
```bash
# Place where you have the CUDA compiler installed
export CUDACXX=/usr/local/cuda/bin/nvcc

# Now your usual cmake command
cmake -DFFMPEG_DIR:PATH=$PATH_TO_FFMPEG -DVIDEO_CODEC_SDK_DIR:PATH=$PATH_TO_SDK ...
```

**Comment by leonselina** [comment]
It works! Thank u very much:)
