### ISSUE TITLE
How to start decoding the input video from a particular frame?

### ISSUE THREAD

**Issue by courtfu** [NVIDIA/VideoProcessingFramework#160]
That is to say, i just need to decode the last frames in the video, then how can I avoid decoding the previous undesirable  frames?

**Comment by rarzumanyan** [comment]
Hi @courtfu 
Please take a look at the issue #99 

I'd really like to substitute all the VPF demuxer functionality which isn't related to the very Annex.B packets decoding (including seek, audio support, subtitles, RTSP connection keep-alive, etc.) with the PyAV interoperability as this doesn't really relate to the Video Codec SDK & CUDA which are base technologies under the VPF.

PyAV developers are now merging one of their experimental branches with ffmpeg bitstream filters support into main branch (https://github.com/PyAV-Org/PyAV/pull/565). This will allow to demux Annex.B packets in familiar ffmpeg fashion and feed VPF video decoder with Annex.B encoded NAL units. This merge is in progress, and as soon as it's done I'll update VPF master branch with PyAV interoperability support and will add samples as well.

You can check out `pyav_support` VPF branch and https://github.com/PyAV-Org/PyAV/commit/44195b62092fcfcf684a07c802cee3d1b8b80b60 PyAV commit to try interoperability right now although you will have to build PyAV from sources.
