### ISSUE TITLE
From where I can download Zeranoe FFMpeg build for Windows?

### ISSUE THREAD

**Issue by theyashl** [NVIDIA/VideoProcessingFramework#163]
I went through wiki page and for building project I wanted to download FFmpeg Build. But the link given in Wiki i.e. [https://ffmpeg.zeranoe.com/builds/](url) is not working anymore!
I tried to find the resource on Google, but there are so many results and I can't figure out which one is authorized! So can you please tell me the new link to get the Builds.!

![image](https://user-images.githubusercontent.com/49603432/108028634-28426080-7052-11eb-9580-b4cfb986b9f2.png)

**Comment by rarzumanyan** [comment]
Hi @theyashl 

To my best knowledge, Zeranoe builds are discontinued.

**Comment by theyashl** [comment]
@rarzumanyan can you please recommend me another build provider!?

**Comment by rarzumanyan** [comment]
You can build it under Windows from sources, it's not very complicated.
