### ISSUE TITLE
MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by zhangmo123** [NVIDIA/VideoProcessingFramework#164]
**Describe the bug**
Run this SampleDecode.py, and it has memory error
This sample decodes input viSampleDecode.pydeo to raw NV12 file on given GPU.
Usage: SampleDecode.py $gpu_id $input_file $output_file.
Decoding on GPU 6
Traceback (most recent call last):
  File "SampleDecode.py", line 55, in <module>
    decode(gpuID, encFilePath, decFilePath)
  File "SampleDecode.py", line 22, in decode
    nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
MemoryError: std::bad_alloc

 free -m
                    total        used           free           shared      buff/cache   available
Mem:         385554      108138      223737       25403       53677         249450
Swap:         32767           0             32767

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
OS: Ubuntu LTS 18.04
Nvidia driver version: 418.165.02
CUDA Version: 10.1
Video Codec SDK Version: 9.1.23
Python Version: 3.6
GCC: 7.4.0
VPF Version: branch issue_95
**Additional context**

**Comment by rarzumanyan** [comment]
hi @zhangmo123 

Why do you use `issue_95` branch?

**Comment by rarzumanyan** [comment]
No reply from issue originator for a long time, closing the issue. Please reopen in case it's not resolved.
