### ISSUE TITLE
 Inconsistent video frames decoding speed

### ISSUE THREAD

**Issue by callmeScarlett** [NVIDIA/VideoProcessingFramework#165]
**Describe the bug**
I was using the PyNvDecoder to get gpu memory address of each frame from a grayscale video. Each frame has a dimension of 4096-by-4096. The runtime was inconsistent for different frames. It took only 1-2 ms for some frames, but as high as 55-60 ms for some others (excluding the first warm up frame, which took even longer). How can I make the loading speed more consistent?

**Laptop:**
 - OS: [Windows 10]
 - Graphics Card: GTX 960M
 - Nvidia Driver Version: 451.48
 - CUDA Version: 11.0
 - Video Codec SDK Version: 11.0.10
 - FFmpeg Version: 4.3.2
 - Python Version: 3.8
 
![bug](https://user-images.githubusercontent.com/45907990/108939322-860d1480-761f-11eb-84e1-849cb31bb855.png)

**Comment by rarzumanyan** [comment]
Hi @callmeScarlett 

`PyNvDecoder` returns video frames in display order which is often different from decoding order.
This is caused by presence of B frames which use frames both from 'future' and 'past' for better inter-frame prediction.

E. g. let's take a look at picture with display number 2. If GOP has usual structure of 
`IBBPBBPBBP...` then picture with display number 2 (P frame) will have decode number 4.
So `PyNvDecoder` has actually to decode 2 more frames before it returns you 2nd frame. This causes decoding time inconsistency. 
This is not a big deal for latency-tolerant scenarios but can cause issues if consistent decoding time is needed.

Before delving too deep into VFP internals I recommend you to do the same test on file which is encoded with low-latency preset without B frames. The easiest way to do this is with ffmpeg:
`ffmpeg -i clip1.mkv -c:v nvenc_h264 -preset p4 -tune ll -b:v 20M -y clip1_ll.mkv`

**Comment by callmeScarlett** [comment]
Hi @rarzumanyan Thank you for the quick response! The solution you provided worked. The decoding speed is now maintained at a somehow consistent speed of 13-15 ms per frame, with occasional slow down to 20-22 ms or speedup to 1-6 ms per frame. However, this performance was still below my expectation. I used to use the video reader from ImageIO to get frames from hard disk to cpu. Then upload each frame to gpu using CUDA sequential memcpy, it took only an average 5 ms per frame for a 8-bit video. The speed was also more consistent (e.g., +- 1 ms).  The sequential data exchange between cpu and gpu, however, became an issue when it comes to higher bit-depth video. The CUDA asynchronized memcpy did not help, so I turned to this SDK. It seemed like it did even a poorer job?

**Comment by rarzumanyan** [comment]
Hi @callmeScarlett 

So the next step in your investigation is to check Nvdec utilization.
Run the decoding script alongside `nvidia-smi dmon` and upload the output.
Before you come to conclusion Nvdec is too slow you need to make sure your script maxes it out.

**Comment by callmeScarlett** [comment]
Hi @rarzumanyan 

Please see attached screen shot. I suspect it might be the issue of the clip itself, but can not confirm. I switched the loop condition to nvDec.DecodeSingleSurface().Empty() and the loop broke at the 100th frame for a 200 frame video.

The original video was downloaded from Youtube as a 4K video, the codec of which was V9. Nvdec was not able to recognize the original video. So I I extracted the first 200 frames and converted them to grayscale using the video reader and writer from python ImageIO. I used the default video writer yesterday and had the above issues. I forced video writer to use h264 codec with pixel format of yuv420p for today and the performance seemed to have improved some. I did try to write the grayscale one as gray8 instead of yuv420p, but the entire video became black. So I switched back to yuv420p. 

I attached the link to the clips if you don't mind to take a look at of them? Thank you!

clip rgb (869 KB)
https://drive.google.com/file/d/1eRCJdasjziSWXHFn8qyE9jO4FyhA-IWg/view?usp=sharing

clip grayscale (855 KB)
https://drive.google.com/file/d/1IoKy2w4KoV_mEDIbz7OsqvXW-ikDkuLn/view?usp=sharing

original video (2.2 GB)
https://drive.google.com/file/d/1qKDTa_p4UIht73RQGgoKyL7JSGEfo3Ls/view?usp=sharing

![nvidia-smi2](https://user-images.githubusercontent.com/45907990/109106551-0144f800-76fe-11eb-9fe6-20d42fd71d51.png)

**Comment by rarzumanyan** [comment]
Hi @callmeScarlett 

I recommend you to start from transcoding the VP9 2160p clip to H.264 2160p YUV420 with following ffmpeg command (choose whatever bitrate you find appropriate):
`ffmpeg.exe -i vp9_clip.mkv -c:v h264_nvenc -profile:v high -preset p4 -tune ll -b:v 20M -y h264_clip.h264`

Don't make video too short, `nvidia-smi dmon` doesn't collect data too often and you will end up with just 5-6 readings per whole decoding session. Let video be at least 1 minute long.

FFmpeg command above shall produce 2160p H.264 clip with YUV420 pixel format without any B frames.
Then decode it with your script while collecting `nvidia-smi dmon` output alongside.
Please upload the results of `nvidia-smi dmon` and your script if possible.

**Comment by callmeScarlett** [comment]
Hi @rarzumanyan 

Thanks for the suggestion. I updated my driver to 461.09 and transcoded the video using the following command:

ffmpeg.exe -i clip_vp9.mkv -c:v h264_nvenc -vf fps=fps=25 -profile:v high -preset slow -tune zerolatency -b:v 20M -y clip_h264_nvenc.mkv

The length of the clip was 9 min 11 sec and has more than 13700 frames. However, again the program broke at the 6885th frame. I attached the screen shot of my current code, console output, and the nvidia-smi dmon output of the last few frames. Would you please let me know what can we do next? 

The program should have processed the entire video instead of breaking in the middle of it. The decoding performance looks better (mean 7.82 ms per frame for 3840 x 2160 rgb video, with 3.25 ms standard deviation), but not sure if there is still any room to improve? My input video size has has to be read in as 4096 x 4096 gray (i.e., the upscaling from 3840 x 2160 to 4096 x 4096 has to be done prior to entering the GPU).

![2021-02-25_15-39-38](https://user-images.githubusercontent.com/45907990/109214668-1d897900-7780-11eb-9c6a-2ce79d3d5910.png)
![2021-02-25_15-37-35](https://user-images.githubusercontent.com/45907990/109214678-21b59680-7780-11eb-86b7-25e9520e91b7.png)

**Comment by callmeScarlett** [comment]
Hi @rarzumanyan 

I also tried the following ffmpeg command to transcode the original 3840 x 2160 rgb video to 4096 x 4096 gray video

`ffmpeg.exe -i Flowers4K.mkv -c:v h264_nvenc -frames:v 13000 -vf "fps=fps=25, scale=4096:4096, format=gray" -profile:v high -preset slow -tune zerolatency -b:v 20M -y clip_h264_gray.mkv`

In addition to the same early termination issue, the speed of decoding the grayscale video was also 3 times slower than the rgb video of smaller frame size (see attached screen shot). Not sure if that makes sense. 14 ms per frame seemed to be too slow to me. 

![2021-02-25_17-22-26](https://user-images.githubusercontent.com/45907990/109227604-9394dc80-778e-11eb-8781-755262bf451d.png)

**Comment by rarzumanyan** [comment]
Hi @callmeScarlett 

Don't get me wrong with this but you're not following the recommendations and not happy with result.
I still recommend to transcode to 2160p H.264 YUV420 first, then do following:

- Decode with `DecodeSingleSurface()` to 3820x2160 YUV420 `Surface` to GPU memory.
- Resize with `ResizeSingleSurface()` to 4096x4096 YUV420 `Surface` in GPU memory on CUDA cores.
- Just use the Y plane and discard UV planes.

If you like to do it your way - that's perfectly fine, but it means I can't help you with it.

P. S.
Old nvenc presets aren't desirable, please use new `P1 ... P7` presets.
`-tune zerolatency` is nonsensical. Valid options for `tune` parameter are `hq, ll, ull, lossless`.

**Comment by callmeScarlett** [comment]
Hi @rarzumanyan 

I made two comments yesterday, my [first comment]  (https://github.com/NVIDIA/VideoProcessingFramework/issues/165#issuecomment-786191937) was about the 2160p H.264 YUV420, while the [second comment](https://github.com/NVIDIA/VideoProcessingFramework/issues/165#issuecomment-786269780) was about the 4096p. I upsampled the video in CPU because of the nature of our project, and doing upscaling in GPU after the data exchange is not an option. Let's put the speed thing aside for now. The first issue needs to be solved is the early termination regardless of the video resolution. The input video has 13000 frames, but the script break out of the loop at the 6500th frame (a half of 13000). I can't tell what happened, and if that affect the performance (e.g., each call of  nvDec.DecodeSingleSurface().PlanePtr().GpuMem() actually read two frames). Would you be able to provide me any sample video that I could give it a try?

I am not sure which ffmpeg you are referring to. I have tried multiple versions of ffmpeg. They include V4.3.2, V4.2.2, and V4.2.1, in which the V4.2.2 was the one in the python imageio-ffmpeg folder. None of them accepts the options you suggested for preset and tune, and suggested the following options instead. 

```
[libx264 @ 000002b330b1dbc0] Error setting preset/tune slow/ll.

[libx264 @ 000002b330b1dbc0] Possible presets: ultrafast superfast veryfast faster fast medium slow slower veryslow placebo

[libx264 @ 000002b330b1dbc0] Possible tunes: film animation grain stillimage psnr ssim fastdecode zerolatency
```

**Comment by rarzumanyan** [comment]
Hi @callmeScarlett 

>`libx264 @ 000002b330b1dbc0`

Your ffmpeg build doesn't support Nvenc and you're using libx264 sw encoder instead.

Regarding the grayscale input video - tbh I've never tested the grayscale video support since this topic is the first time somebody needs it. People do need Y plane only sometimes and I recommend just discard the UV planes. BTW in your script you're actually getting the cudeviceptr of Y plane. You can access other planes like this:

```python
yuv_surface= nvDec.DecodeSingleSurface()
y, u, v = 0, 1, 2

y_plane = yuv_surface.PlanePtr(y)
y_cuptr = y_plane.GpuMem()

u_plane = yuv_surface.PlanePtr(u)
u_cuptr = u_plane.GpuMem()

v_plane = yuv_surface.PlanePtr(v)
v_cuptr = v_plane.GpuMem()
```
Each plane of YUV420 `Surface` is separate CUDA 2D memory allocation. You can also download whole YUV420 frame to numpy array or do it individually to each image plane.

>Would you be able to provide any video sample that I could give it a try?

There are open source videos like Big Buck Bunny, Tears Of Steel etc. They have usual YUV420 / YUV444 format and I've been testing VPF on them extensively.

P. S.
This is very unusual project if it requires to use Python bindings for decoding speed consistency estimation and forbids to use video processing framework for video processing...

**Comment by callmeScarlett** [comment]
Hi @rarzumanyan 
Thanks for the suggestions. nvCodec does not seem to be my best option at this moment, have pursue other options.
