### ISSUE TITLE
please help me understand RGB and RGB_PLANAR

### ISSUE THREAD

**Issue by ald2004** [NVIDIA/VideoProcessingFramework#166]
@rarzumanyan hi:
i have some test code list below,and i got the image like 3x3 small images like this,
 i can get correct image when i download pixel format RGB, but this correct image can not infer by tritonserver 
cuda sheared_memory mechanism. tritonserver can only infer RGB_PLANAR picure ,
so i guess the problem is gpu memory storage is different from cpu memory.

my question is can i use cv2.imwrite generate a correct image with a downloaded 
RGB_PLANAR pixel format numpy array?

![image](https://user-images.githubusercontent.com/4443533/109268909-b71b5e00-7846-11eb-8596-de699d290fc6.png)

```python
import PyNvCodec as nvc
import numpy as np
import cv2

encFile ="rtsp://admin:abcd1234@192.168.8.34"
gpuId=0
model_w = 640
model_h = 384
model_c = 3
input_w = 1280
input_h = 720

nvDec = nvc.PyNvDecoder(encFile, gpuId,
                                    {'rtsp_transport': 'tcp', 'max_delay': '5000000', 'bufsize': '30000k'})
nvCvt = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(), nvDec.Format(), nvc.PixelFormat.YUV420, gpuId)
nvRes = nvc.PySurfaceResizer(model_w, model_h, nvCvt.Format(), gpuId)
to_rgb = nvc.PySurfaceConverter(model_w, model_h, nvc.PixelFormat.YUV420, nvc.PixelFormat.RGB, gpuId)
to_planar = nvc.PySurfaceConverter(model_w, model_h, nvc.PixelFormat.RGB, nvc.PixelFormat.RGB_PLANAR, gpuId)
nvDwn = nvc.PySurfaceDownloader(model_w, model_h, nvc.PixelFormat.RGB_PLANAR, 0)

rawSurface = nvDec.DecodeSingleSurface()
yuvSurface = nvCvt.Execute(rawSurface)
resSurface = nvRes.Execute(yuvSurface)
rgb_byte = to_rgb.Execute(resSurface)
rgb_planar = to_planar.Execute(rgb_byte)
frameRGB = np.ndarray(shape=(model_w * model_h * model_c), dtype=np.uint8)
success = nvDwn.DownloadSingleSurface(rgb_planar, frameRGB)


if not (success):
	print('Failed to download surface')
frameRGB.resize(model_h,model_w,model_c)
cv2.imwrite('/dev/shm/111.jpg',frameRGB)
```

**Comment by ald2004** [comment]
convert to RGB_PLANAR use function : nppiCopy_8u_C3P3R_Ctx which Split a packed multi-channel image into multiple single channel planes. When this splited picture was copied into gpu memory infered correctly by triton server was just by luck.

**Comment by rarzumanyan** [comment]
Hi @ald2004 

So what is exactly the issue here?
Do you still want to download Planar RGB `Surface` into numpy array and then do the processing with OpenCV?
Or Triton server is happy with Planar RGB `Surface`?

**Comment by ald2004** [comment]
thank you for your time.
It is true , Triton server is happy with Planar RGB Surface. At the same time i need the original frame for next move.
My current solution is download 2 Surface , frameDown[:rgb] is original frame, frameDown[rgb:] is Planar RGB Surface,
and pass them all to another function(process)  through shared_memory.

But this solution i think is not good, it consume 2 times shared memory capacity, 
So the issue is i can decode rtsp frame and this frame into  Planar RGB Surface feed to Triton server , and the time i need 
download this frame from gpu and convert to RGB Surface and i tried to write some c function like your code nvc.PySurfaceConverter to do that, but it is too complicate to me to read doc like nppiCopy_8u_C3P3R_Ctx function.

i notice that this is not a "ISSUE",  i try to get some help if you have free time.
Thank you.

**Comment by rarzumanyan** [comment]
Hi @ald2004 

Not sure if I fully understand you, please correct me if I'm wrong.
If you want to make a copy of `Surface`, there's a `Clone()` method for that:
```python
rgb_byte = to_rgb.Execute(resSurface)

# This will create a deep copy: CUDA 2D memory allocation + CUDA memcpy.
gpu_id = int(0)
rgb_copy = rgb_byte.Clone(gpu_id)

# pass the copy surface with shared memory, do the following on receiver side:
rgb_planar = to_planar.Execute(rgb_copy)
frameRGB = np.ndarray(shape=(model_w * model_h * model_c), dtype=np.uint8)
success = nvDwn.DownloadSingleSurface(rgb_planar, frameRGB)
if not (success):
	print('Failed to download surface')

# do other stuff
```

As far as I understand the request, you can simply `Clone()` any `Surface` you want, pass the copy using shared memory and continue the processing on receiver side.
