### ISSUE TITLE
Please help me, Segmentation fault

### ISSUE THREAD

**Issue by MichealZhang** [NVIDIA/VideoProcessingFramework#167]
Follow the tutorial, i run the sample SampleDecode.py. It causes a Segmentation fault error
![image](https://user-images.githubusercontent.com/18044753/109962573-54363500-7d26-11eb-851c-152095498329.png)

**Comment by MichealZhang** [comment]
it occurs in the command——nvDec = nvc.PyNvDecoder(encFilePath, gpuID)

**Comment by rarzumanyan** [comment]
Hello @MichealZhang 

JPEG still image format isn't supported.
`PyNvDecoder` supports H.264 and HEVC video codecs.
