### ISSUE TITLE
error in make :recompile with -fPIC

### ISSUE THREAD

**Issue by leonselina** [NVIDIA/VideoProcessingFramework#17]
Another error :
[ 28%] Linking CXX shared library libTC.so
/usr/bin/ld: /usr/local/lib/libavutil.a(error.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
should I modify the makefile or CMakeList?

**Comment by rarzumanyan** [comment]
Hi,

VPF uses dynamic linkage against FFmpeg libraries to conform with LGPL license requirements. 

You see this error because static libraries are installed in your system (/usr/local/lib/libavutil.a). So you basically need to install shared ffmpeg libraries.

**Comment by leonselina** [comment]
I recomplied ffmpeg and add " --enable-shared" to ./configure .
It fixed :)

**Comment by Andresso** [comment]
Hi
Even when I use --enable-shared I get the following error:

/usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against "ff_pw_9" can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: vinculação final falhou: Wrong value
collect2: error: ld returned 1 exit status
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/build.make:226: PyNvCodec/TC/libTC.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:358: PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Any ideia how to solve?

-    OS: Ubuntu LTS 20.04
-   Nvidia driver version: 455.32
-    CUDA Version: 11.1
-    Video Codec SDK Version: 11.0.10
-    Python Version: 3.7
-    GCC: 9.3.0

**Comment by rarzumanyan** [comment]
Hi @Andresso 

Please check that folder where you have your ffmpeg libraries doesn't contain *.a static libraries.
After that please delete the CMake cache and re-configure + rebuild VPF.

**Comment by Andresso** [comment]
I solved that issue following this tutorial https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/ and setting

export PATH_TO_FFMPEG=/usr/bin/ffmpeg

instead of the VPF tutorial steps.

Thank you, @rarzumanyan

**Comment by Nain555** [comment]
/usr/bin/ld: /usr/local/lib/libmpb.a(mpi_utils.o): warning: relocation against `stdout@@GLIBC_2.2.5' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libmpb.a(libmatrices_la-eigensolver.o): relocation R_X86_64_PC32 against symbol `mpb_verbosity' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:590: libmeep.la] Error 1
make[4]: Leaving directory '/home/zulnorain/meep-1.28.0/src'
make[3]: *** [Makefile:728: all-recursive] Error 1
make[3]: Leaving directory '/home/zulnorain/meep-1.28.0/src'
make[2]: *** [Makefile:511: all] Error 2
make[2]: Leaving directory '/home/zulnorain/meep-1.28.0/src'
make[1]: *** [Makefile:518: all-recursive] Error 1
make[1]: Leaving directory '/home/zulnorain/meep-1.28.0'
make: *** [Makefile:425: all] Error 2
 any idea how to solve this problem, i'm tryin to install meep using ubuntu, all the dependencies are ok but still when i try to install meep at the end i'm having this problem again and again.
