### ISSUE TITLE
Wrong surface type is returned fro RGB planar

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#170]
**Wrong surface type is returned for RGB planar surfaces**

https://github.com/NVIDIA/VideoProcessingFramework/blob/master/PyNvCodec/TC/inc/MemoryInterfaces.hpp
 in class

`class DllExport SurfaceRGBPlanar : public Surface {`

line no 441

` Pixel_Format PixelFormat() const override { return RGB; }`

I think it should be changed to as follows:

` Pixel_Format PixelFormat() const override { return RGB_PLANAR; }`

`return RGB_PLANAR;` instead of `return RGB;`

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

Thanks, it was a bug indeed. Fixed and pushed to master.
Just in case you catch a bug and know how to fix it, please submit a pull request.
