### ISSUE TITLE
Encoding of frame getting slower with number of streams. 

### ISSUE THREAD

**Issue by rizwanishaq** [NVIDIA/VideoProcessingFramework#176]
I am trying to encode video frames with threading, just to check how many streams my system can have.
My system has 4 Tesla T4, but as I am increasing streams, suppose, I am trying 12 streams on 4 GPU, but encoding speed is getting slower, as well, gpu usage is very low, don't know why it is happening, sometime GPU usage is 0% but it take the memory, Is it normal behaviour? Does number of streams decrease the speed of encoding? 

```
import PyNvCodec as nvc
import numpy as np
import sys
import cv2
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
from datetime import datetime



def threaded_decoding(i):
    

    video_stream = cv2.VideoCapture("abc.mp4")
    encFile = open(f"test/{i}.mp4", "wb")

    ret, frame = video_stream.read()

    H,W,c = frame.shape
    
    gpuID = i/4
    # gpuID = 0

    nvUpl = nvc.PyFrameUploader(int(W), int(H), nvc.PixelFormat.RGB, gpuID)
    nvCvt = nvc.PySurfaceConverter(int(W), int(H), nvc.PixelFormat.RGB, nvc.PixelFormat.YUV420, gpuID)
    nvCvt1 = nvc.PySurfaceConverter(int(W), int(H), nvc.PixelFormat.YUV420, nvc.PixelFormat.NV12, gpuID)
    nvEnc = nvc.PyNvEncoder({'profile': 'baseline', 'fps': '25','preset': 'bd', 's': f"{W}x{H}", 'codec': 'h264', 'gop':'50'}, gpu_id=gpuID)





    encFrame = np.ndarray(shape=(0), dtype=np.uint8)

    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    # frame = cv2.cvtColor(frame, cv2.COLOR_BGR2YUV_I420)

    while True:
        rawSurface = nvUpl.UploadSingleFrame(frame)
        cvtSurface = nvCvt.Execute(rawSurface)
        cvtSurface = nvCvt1.Execute(cvtSurface)
        # success = nvEnc.EncodeSingleFrame(frame, encFrame, sync = True)
        success = nvEnc.EncodeSingleSurface(cvtSurface, encFrame)
        if success:
            encByteArray = encFrame.tobytes()
            # print(i,encFrame.shape, success)
            encFile.write(encByteArray)
        
        ret, frame = video_stream.read()
        if not ret:
            break
        # frame = cv2.cvtColor(frame, cv2.COLOR_BGR2YUV_I420)
        frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)



    success = nvEnc.Flush(encFrame)
    if(success):
        encByteArray = encFrame.tobytes()
        encFile.write(encByteArray)
    
    encFile.close()

    return i
        

if __name__=="__main__":
    start = datetime.now()
    number_of_streams = list(np.arange(0,12))
    with ThreadPoolExecutor() as ex:
        res = ex.map(threaded_decoding, number_of_streams)
    
    for r in res:
        print(r)
    print('done')
    end = datetime.now()
    time_taken = end - start
    print('Time: ',time_taken) 


```

OS: Ubuntu 18.04
Nvidia driver version 455.32.00
CUDA Version [11.1] (actually is 10.2) but shown 11.1 (when I do nvidia-smi)
Video Codec SDK Version [9.1.23]
Python Version [3.6]

**Comment by rizwanishaq** [comment]
@rarzumanyan 
Basically, in reality, I am getting BGR image from one of my model, and want to stream that with h264, and trying that... i.e. I am getting BGR image every 50msec, i.e. and making h264 stream.

It is actually something like that...
1) Every 50msec 1 BGR image
2) make h264 streams from there i.e. get the encoded frames bytes, and stream through gRPC. 
3) In the example I am reading video only imitation my problem i.e. I am getting BGR images, one by one.

**Comment by rarzumanyan** [comment]
@rizwanishaq 

My advice here is to approach this problem as follows:

run `htop` and `nvidia-smi dmon` in parallel to see what component of your system is maxed out during the execution of the script. If it's the CPU it means you need to optimize whatever runs on it, be it ML and/or OpenCV module which encodes frames to video.

VPF doesn't use CPU for anything computationally expensive, so if `nvidia-smi dmon` readings show that GPU isn't maxed out it means that VPF is basically waiting for data from CPU.

**Comment by rarzumanyan** [comment]
@rizwanishaq 

Please check out latest `master` branch, Python GIL release was added to majority of VPF calls + CUDA runtime API calls were removed from `PyNvCodec`. That shall both reduce amount of GPU #0 memory occupancy and increase multi-threaded performance.

**Comment by contentis** [comment]
@rizwanishaq Can this be closed?
