### ISSUE TITLE
method DecodeSurfaceFromPacket() crashes

### ISSUE THREAD

**Issue by lferraz** [NVIDIA/VideoProcessingFramework#177]
I have problems using the method `DecodeSurfaceFromPacket()`.  First, I get the packet with `DemuxSinglePacket()` and it looks correct, but when the method is called everything crashes without an error message.

what I am doing is:

```
nvDmx = nvc.PyFFmpegDemuxer(encFilePath)
nvDec = nvc.PyNvDecoder(nvDmx.Width(), nvDmx.Height(), nvDmx.Format(), nvDmx.Codec(), gpuID)
packet = np.ndarray(shape=(0), dtype=np.uint8)
nvDmx.DemuxSinglePacket(packet)
rawSurface = nvDec.DecodeSurfaceFromPacket(bytearray(packet.data))
```

I think in the past this was working fine.

**Comment by rarzumanyan** [comment]
What branch do use, is it `master` or `seek_support_new`?

**Comment by lferraz** [comment]
> What branch do you use, is it `master` or `seek_support_new`?

Yes, sorry, I forgot to mention.

**Comment by rarzumanyan** [comment]
@lferraz 

I've just launched `SampleDemuxDecode` on `seek_support_new` ToT and it works just fine.

>`rawSurface = nvDec.DecodeSurfaceFromPacket(bytearray(packet.data))`

There's no need to do that, you can feed the packet right to decoder as it's shown here:
https://github.com/NVIDIA/VideoProcessingFramework/blob/67c2ef385ff33a09b9cb2ece2edd32535a32b132/SampleDemuxDecode.py#L20-L49

**Comment by lferraz** [comment]
Very weird now it is also working to me!!!! XD
Thank you so much!!!
