### ISSUE TITLE
SampleDemuxDecode.py is broken

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#180]
Hi @rarzumanyan,
The `SampleDemuxDecode.py` is broken now.
Probably due to the following line is trying to access the demuxer which is not initialized in the separate demux and decode mode.

https://github.com/NVIDIA/VideoProcessingFramework/blob/c99d42954469222328d2ab28fd22359c9493a0bc/PyNvCodec/src/PyNvCodec.cpp#L660

of the function:
https://github.com/NVIDIA/VideoProcessingFramework/blob/c99d42954469222328d2ab28fd22359c9493a0bc/PyNvCodec/src/PyNvCodec.cpp#L630-L705

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

Most probably you’re right.
Allow me some time, I’ll fix it within couple hours.

**Comment by rarzumanyan** [comment]
@vtpl1 

Please check out latest `master` branch, I've just pushed a commit.
You were right, the `upDemuxer` pointer was without a check. With `master` ToT I was able to run `SampleDemuxDecode` without any issues on my local machine.

**Comment by vtpl1** [comment]
Thanks @rarzumanyan ,
I see similar potential issue here:

https://github.com/NVIDIA/VideoProcessingFramework/blob/fd99838e1eaabee980136bd0214317be1fdd3b88/PyNvCodec/src/PyNvCodec.cpp#L535-L541

**Comment by rarzumanyan** [comment]
@vtpl1 
Indeed, that was also not checking the pointer.
Fixed & pushed to `master`.

**Comment by vtpl1** [comment]
@rarzumanyan thanks, fixed.
