### ISSUE TITLE
Encoding Profile always high

### ISSUE THREAD

**Issue by rizwanishaq** [NVIDIA/VideoProcessingFramework#183]
I am trying to set the profile to baseline, 
`nvEnc = nvc.PyNvEncoder({'profile': 'baseline', 'fps': '25','preset': 'default', 's': f"{W}x{H}", 'codec': 'h264'}, gpu_id=gpuID)`

but it always gives me high profile. 

OS: Ubuntu 18.04
Nvidia driver version 455.32.00
CUDA Version [11.1] (actually is 10.2) but shown 11.1 (when I do nvidia-smi)
Video Codec SDK Version [9.1.23]
Python Version [3.6]

**Comment by rarzumanyan** [comment]
Hi @rizwanishaq 

Check out `issue_183` branch in which I've addressed the issue.
Please test it in your environment and confirm that it's resolved.

**Comment by rizwanishaq** [comment]
Hi @rarzumanyan 
Thanks... it is working now.
