### ISSUE TITLE
Jetson Device Support

### ISSUE THREAD

**Issue by avn3r** [NVIDIA/VideoProcessingFramework#185]
Will this work on jetson devices, following installation instructions?

If so how will it compare in performance with deepstream?

**Comment by sbbug** [comment]
Top one!

**Comment by rarzumanyan** [comment]
Hello world,
I’ve never built and tested VPF on Jetson.

**Comment by rarzumanyan** [comment]
ARM CPU + iGPU combination (such as Jetson) isn't supported by Video Codec SDK and hence by VPF.
Closing the issue.
