### ISSUE TITLE
Some RTSP, unreadable, causes the program to block, max_delay does not work, what should I do

### ISSUE THREAD

**Issue by weibangqian** [NVIDIA/VideoProcessingFramework#191]
**Describe the bug**
nvDec = nvc.PyNvDecoder(rtsp, 0,{'rtsp_transport': 'tcp', 'max_delay': '2000', 'bufsize': '30000k',"pix_fmt ": "NV12"})

**Comment by rarzumanyan** [comment]
Hello @weibangqian 

Please read this wiki [page](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Decoding-video-from-RTSP-camera) first.

**Comment by rarzumanyan** [comment]
Hi @weibangqian 

Please confirm if external demuxer allows you to work around the issue.

**Comment by rarzumanyan** [comment]
No response from issue originator, hence closing this. Please reopen in case it repeats.
