### ISSUE TITLE
Support for VP9

### ISSUE THREAD

**Issue by lferraz** [NVIDIA/VideoProcessingFramework#192]
Hi @rarzumanyan, 

I tried to open a video with format vp9 and I couldn't. As far as I know nvenc & nvdec support this format.
Do you plan to add this format? How complex could be to add this format to VPF?

Thank for this nice lib :)

**Comment by lferraz** [comment]
I did some very weird changes and now I can decode VP9 with `DecodeSingleSurface()` but not with `DecodeSurfaceFromPacket()`. XDXD
Basically I disabled the bsf.
Tomorrow I will try to solve the problem with `DecodeSurfaceFromPacket()`.
I love VPF!!!!

**Comment by rarzumanyan** [comment]
Hi @lferraz 

You're basically right in your approach to this.
There are 2 features need to be added to support VP9:

- Expose corresp. `cudaVideoCodec` enum
- Remove bitstream filter which converts packets to Annex.B format.

I've pushed a patch to `vp9_support` branch, please check it out. It decodes `.webm` file using built-in demuxer, probably shall do the same with external demuxer as well.

**Comment by lferraz** [comment]
It works perfectly!!!!
I did another change in my code but I've seen it is not required. I will copy/paste here the code and feel free to decide if it is required or not.
In `task.cpp`line[`722`](https://github.com/NVIDIA/VideoProcessingFramework/blob/master/PyNvCodec/TC/src/Tasks.cpp#L722):
```
    case cudaVideoCodec_VP9:
      videoCodecParams->codec_id = AV_CODEC_ID_VP9;
      break;
```

Thanks!!!!

**Comment by lferraz** [comment]
I checked the `PacketData()` returned by `DecodeSingleSurface()` and it is wrong for VP9 (I do not know the internals of vp9 so, maybe does not make sense). I recheck for `hevc` and the `dts` and `pos` are always zero ('pts' and `duration` are correct).

**Comment by rarzumanyan** [comment]
@lferraz 

>In task.cppline722:

Thanks for bringing this up. Fixed & pushed to `vp9_support`.

>I recheck for hevc and the dts and pos are always zero ('pts' and duration are correct).

Nvdec returns frames in display order so I assume that dts (decode timestamp) being zero may not be bug.

>I checked the PacketData() returned by DecodeSingleSurface() and it is wrong for VP9

Need to check.

**Comment by rarzumanyan** [comment]
@lferraz 

Please check out latest `vp9_support` branch, I've pushed the patch which copies input video packet properties (such as timestamp) in case bitstream filters aren't applied (which happens for vp9).

On my machine it produces valid pts values for test sequence.

**Comment by lferraz** [comment]
for testing I use [this](https://test-videos.co.uk/vids/bigbuckbunny/webm/vp9/1080/Big_Buck_Bunny_1080_10s_30MB.webm) video.
For this video I am getting always:
```
dts:0
duration:33
pos:0
pts:0
```

In the case of `hevc`. The values for  `dts` and `pos` are not the same as the ones provided using `ffprobe`.

**Comment by rarzumanyan** [comment]
@lferraz 

Is the video you’re referencing HEVC or VP9?
Just to make it clear, you’re now having issues with hevc only or vp9 is impacted as well?

**Comment by lferraz** [comment]
@rarzumanyan
this is the VP9 one. The other is the one sent you some weeks ago (but the issue should appear in any hevc video).

**Comment by rarzumanyan** [comment]
So the incorrect pts issue reproduces on both vp9 and hevc?

**Comment by lferraz** [comment]
ups sorry. I wanted to tell you so many things in the same message. 

In VP9 I am getting always the same values. 
```
dts:0
duration:33
pos:0
pts:0
````

in HEVC only 2 values change:
```
dts:0
duration:4500
pos:0
pts:5400
```

**Comment by rarzumanyan** [comment]
@lferraz 

Ok, let's take this one by one.
Please check out `vp9_support` ToT, I've added `Tests.py` file which is stub for kinda testing suite.
On my local machine it decodes VP9 file with proper pts information.

>for testing I use this video.

This site is inaccessible from my network. 
If it's big buck bunny I think you can cut it to dozen frames and attach to this thread. GitHub supports video attachments.

**Comment by rarzumanyan** [comment]
Hi @lferraz 

I've submitted issue #195 for wrong PTS values to keep it clear.
Closing this one as VP9 support is basically added.
