### ISSUE TITLE
How to use 'PyNvEncoder' output the 'Processed video' from opencv?

### ISSUE THREAD

**Issue by kjhgfdsaas** [NVIDIA/VideoProcessingFramework#194]
Hello
If I have some images in opencv RGB type like "np.array([width,height,3],dtype=np.uint8)".
How can I transfer this to  "np.ndarray(shape=(nvDec.Framesize()), dtype=np.uint8)"
I find the nvDec.Framesize()=width*height*3/2
But I don't know how to convert it.

Please Help.

**Comment by rarzumanyan** [comment]
Hi @kjhgfdsaas 

You may approach this in 3 steps:

1. upload your RGB numpy array to GPU with `PyFrameUploader` class
2. convert RGB to YUV420 on GPU with `PySurfaceConverter`
3. convert YUV420 to NV12 on GPU  with `PySurfaceConverter`
3. encode NV12 with `PyNvEncoder`

You can find the samples in VPF install dir which illustrate how to use those classes.
Most of this is covered by `SampleEncodeMultiThread.py`

**Comment by rarzumanyan** [comment]
@kjhgfdsaas 
Closing as resolved, please open more specific issue in case you're still having troubles.
