### ISSUE TITLE
Wrong PTS values for some VP9 & HEVC sequences

### ISSUE THREAD

**Issue by rarzumanyan** [NVIDIA/VideoProcessingFramework#195]
**Describe the bug**
PyNvDecoder provides wrong PTS values on some VP9 & HEVC sequences.

**To Reproduce**
1.`nv_dmx.DemuxSinglePacket(self.packet)`
2. `nv_dmx.LastPacketData(self.packet_data)`
3. `packet_data.pts` field is broken

**Expected behavior**
`packet_data.pts` to show correct frame PTS value

**Screenshots**

**Desktop (please complete the following information):**
 - Windows, Linux
 - CUDA Version 11.2
 - Video Codec SDK Version 11.0
 - Python Version 3.7

**Comment by rarzumanyan** [comment]
@lferraz 

Updated:
Demuxer was flushed in the `PyFFmpegDemuxer::PyFFmpegDemuxer()` constructor call which caused file position being flushed after it's advanced in `avformat_find_stream_info()`. Please check out latest `issue_195` ToT.

**Comment by lferraz** [comment]
@rarzumanyan 

I've tested in VP9 and HEVC and using your test code works fine :). I can get the correct values and see all the frames.

However, using the approach:
```
nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
p = nvc.PacketData()
rawSurface = nvDec.DecodeSingleSurface(packet_data=p)
```
the packet data is still incorrect for `hevc` where `dts` and `pos` are 0. In the `vp9` case everything is 0 except the `duration` that looks correct.

**Comment by rarzumanyan** [comment]
Thanks for the update @lferraz 

Any chance you can add these kind of tests to SampleDecode.py and Tests.py? That would be a good place to start the automated regression testing.

**Comment by lferraz** [comment]
Tomorrow I will add the tests :)

**Comment by lferraz** [comment]
while I was thinking how to reorganice the code I realise that method `Seek` is not public in the `PyFFmpegDemuxer`. Look at line  75 in  `SampleDecode.py` (`self.nv_dmx.Seek(seek_ctx)`).

**Comment by lferraz** [comment]
Now I've seen that you already added the code for the `PyNvDecoder` code. XD
I will test it now.

**Comment by lferraz** [comment]
Output for the VP9 video:

With `InitMode.BUILTIN`
```
Decoding on GPU 0
curr_frame:      0
frame pts:       0
frame dts:       0
frame pos:       0
frame duration:  33

curr_frame:      1
frame pts:       0
frame dts:       0
frame pos:       0
frame duration:  33

curr_frame:      2
frame pts:       0
frame dts:       0
frame pos:       0
frame duration:  33
```

With `InitMode.STANDALONE`:

```
Decoding on GPU 0
curr_frame:      0
frame pts:       0
frame dts:       0
frame pos:       1077
frame duration:  33

curr_frame:      1
frame pts:       33
frame dts:       33
frame pos:       415953
frame duration:  33

curr_frame:      2
frame pts:       67
frame dts:       67
frame pos:       416977
frame duration:  33
```

here you can see the issue I mention.

**Comment by rarzumanyan** [comment]
Hi @lferraz 

With the `Big_Buck_Bunny_1080_10s_1MB.webm` you've uploaded, output in `dec.InitMode.STANDALONE` is as follows:
```cmd
curr_frame:      0
frame pts:       0
frame dts:       0
frame pos:       1077
frame duration:  33

curr_frame:      1
frame pts:       33
frame dts:       33
frame pos:       81000
frame duration:  33

curr_frame:      2
frame pts:       67
frame dts:       67
frame pos:       81132
frame duration:  33

...
```

And in the `dec.InitMode.BUILTIN` it's like this:
```cmd
curr_frame:      0
frame pts:       0
frame dts:       0
frame pos:       0
frame duration:  33

curr_frame:      1
frame pts:       33
frame dts:       0
frame pos:       0
frame duration:  33

curr_frame:      2
frame pts:       67
frame dts:       0
frame pos:       0
frame duration:  33

...
```

Both modes show sane pts & duration modes. 
What are your OS, driver, Video Codec SDK & ffmpeg versions?

**Comment by lferraz** [comment]
OS: Ubuntu 18.04
Driver Version: 440.100
CUDA Version: 10.2
Video Codec SDK: 9.1
ffmpeg: 4.2.2

**Comment by lferraz** [comment]
hevc video:
dec.InitMode.STANDALONE: 
```
Decoding on GPU 0
curr_frame:      0
frame pts:       0
frame dts:       0
frame pos:       44
frame duration:  1

curr_frame:      1
frame pts:       1
frame dts:       1
frame pos:       569620
frame duration:  5399

curr_frame:      2
frame pts:       5400
frame dts:       5400
frame pos:       588442
frame duration:  5400
```
With InitMode.BUILTIN:
```
Decoding on GPU 0
curr_frame:      0
frame pts:       0
frame dts:       0
frame pos:       0
frame duration:  5400

curr_frame:      1
frame pts:       1
frame dts:       0
frame pos:       0
frame duration:  7200

curr_frame:      2
frame pts:       5400
frame dts:       0
frame pos:       0
frame duration:  4500
```

The numbers here are very weird. Looks like both demuxers demux different frames

**Comment by rarzumanyan** [comment]
@lferraz 

Could you please send me your hevc file.
Will test both it & vp9 files on my Ubuntu machine.
Meanwhile I also recommend you to update to latest Video Codec SDK version.

**Comment by lferraz** [comment]
> P. S.
> If you take a closer look at `dec.InitMode.STANDALONE` you will see that numbers are quite weird yet they make some sense:
> 1st frame pts is `0`, duration is `1`
> 2nd frame pts = `0+1` = `1`. Duration is `5399`.
> 3rd frame pts = `1 + 5399` = `5400` etc.

This numbers are correct I checked with ffprobe.

**Comment by lferraz** [comment]
> Could you please send me your hevc file.

Done, you have the link in your email

**Comment by rarzumanyan** [comment]
Hi @lferraz 

Please check out `issue_195` ToT, I've slightly changed the logic which obtains `PacketData`.
Now on sequences without frame reordering, output of both modes is same on my machine (including both VP9 and HEVC sequences).

Please note that on sequences with frame reordering (with B frames) output will be different for `dec.InitMode.STANDALONE` and `dec.InitMode.BUILTIN` modes. This is caused by Nvdec operation mode. It outputs the video frames in display order, so frame pts values will increase like this:
```cmd
...
curr_frame:      3
frame pts:       300
frame dts:       0
frame pos:       0
frame duration:  0

curr_frame:      4
frame pts:       400
frame dts:       0
frame pos:       0
frame duration:  0

curr_frame:      5
frame pts:       500
frame dts:       0
frame pos:       0
frame duration:  0
...
```

While in `dec.InitMode.STANDALONE` operational mode you get `PacketData` from demuxer which reads packets in decode order, so frames will be ordered like below:
```cmd
...
curr_frame:      3
frame pts:       400
frame dts:       200
frame pos:       448026
frame duration:  100

curr_frame:      4
frame pts:       300
frame dts:       300
frame pos:       592358
frame duration:  100

curr_frame:      5
frame pts:       600
frame dts:       400
frame pos:       840445
frame duration:  100
...
```

**Comment by lferraz** [comment]
This are the results I am getting now. According to your previous explanation everything make sense except the VP9/BUILTIN. If you are getting good results for this video probably the problem is that I am using an old VideoCodecSDK.

with the H265/STANDALONE
```
curr_frame                    : 0
frame pts (decode order)      : 0
frame dts (decode order)      : 0
frame pos (decode order)      : 44
frame duration (decode order) : 1

curr_frame                    : 1
frame pts (decode order)      : 1
frame dts (decode order)      : 1
frame pos (decode order)      : 569620
frame duration (decode order) : 5399

curr_frame                    : 2
frame pts (decode order)      : 5400
frame dts (decode order)      : 5400
frame pos (decode order)      : 588442
frame duration (decode order) : 5400

curr_frame                    : 3
frame pts (decode order)      : 10800
frame dts (decode order)      : 10800
frame pos (decode order)      : 681396
frame duration (decode order) : 7200
```

with the H265/BUILTIN
```
curr_frame                     : 0
frame pts (display order)      : 0
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

curr_frame                     : 1
frame pts (display order)      : 1
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

curr_frame                     : 2
frame pts (display order)      : 5400
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

curr_frame                     : 3
frame pts (display order)      : 10800
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```

with the VP9/STANDALONE
```
curr_frame                    : 0
frame pts (decode order)      : 0
frame dts (decode order)      : 0
frame pos (decode order)      : 1077
frame duration (decode order) : 33

curr_frame                    : 1
frame pts (decode order)      : 33
frame dts (decode order)      : 33
frame pos (decode order)      : 415953
frame duration (decode order) : 33

curr_frame                    : 2
frame pts (decode order)      : 67
frame dts (decode order)      : 67
frame pos (decode order)      : 416977
frame duration (decode order) : 33
```

with the VP9/BUILTIN

```
curr_frame                     : 0
frame pts (display order)      : 0
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

curr_frame                     : 1
frame pts (display order)      : 0
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

curr_frame                     : 2
frame pts (display order)      : 0
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```

**Comment by lferraz** [comment]
@rarzumanyan 
another comment, I realised that method `Seek` is not public in the `PyFFmpegDemuxer`. Look at line 141 in `SampleDecode.py` (`self.nv_dmx.Seek(seek_ctx)`).

**Comment by rarzumanyan** [comment]
@lferraz 

Let me check VP9 video on other Video Codec SDK releases.
Meanwhile if it's possible to update your VC SDK please do so because if something is wrong inside - it's not going to be fixed in old version.

>I realised that method Seek is not public in the PyFFmpegDemuxer.

You're right. Will add it to the module API & push the patch soon.

**Comment by lferraz** [comment]
> Meanwhile if it's possible to update your VC SDK please do so because if something is wrong inside - it's not going to be fixed in old version.

I will try with Video Codec SDK 10

**Comment by rarzumanyan** [comment]
Hi @lferraz 

I've got to heavily refactor `Seek` method because it's acting weird on some sequences (including big buck bunny encoded in VP9). Check out `issue_195` ToT.

Seek now is available for both demuxer and decoder and it supports 2 different modes: 

- To nearest previous key frame 
- To exact frame given in seek context

**Comment by lferraz** [comment]
@rarzumanyan 
👏 👏 👏 👏 👏 👏 👏 👏 
monday or tuesday I will have time to check everything: Video Codec SDK 10 and Seek(). 
Now  I am integrating VPF in our main project 🕺💃. I will let you know the final speed up wrt OpenCV. 😁

**Comment by lferraz** [comment]
Hi @rarzumanyan ,

I did an initial test of the `Test.py` and there are some issues:

****1.** Issue in `SampleDecode()` in STANDALONE mode**
       This is very easy to solve. Since you need to flush frames the `dec_frames()` is not the best way to validate that `frames_to_decode` is achieved.
       The solution is as simple as in line 243 in file `SampleDecode.py`:
```
        dec_iters: int = 0
        while (dec_iters < frames_to_decode) if (frames_to_decode > 0) else True:
            dec_iters += 1
```
Since it is very simple I consider I do not need to create a new branch/commit/PR. Anyway, if you prefer this approach I can do it.

****2.** In BUILTIN mode `nvc.SeekMode.PREV_KEY_FRAME` is not working fine. It is going to the EXACT_FRAME.**

I added `print('We are at frame with pts', str(seek_ctx.out_frame_pts))` in `decode_frame_builtin()`.

```
Decoding on GPU 0
Seeking for the frame  7
We are at frame with pts 54000
frame pts (display order)      : 40500
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 46800
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

10  frames decoded.
```
I feel there are 2 issues here:
a. is not going to the PREV_KEY_FRAME. (the line `10  frames decoded.` should be `2 frames decoded.` since in this test I am asking for 2 frames being decoded. The seek is to frame 7 which is related with the iframe 0)
b. something weird with the pts is happening. (I will eval better today)

****3.** in STANDALONE with `nvc.SeekMode.EXACT_FRAME`**
   The system is blocked at line ` if not self.nv_dmx.Seek(seek_ctx, self.packet):` in `SampleDecode.py` 

****4.** in BUILTIN with `nvc.SeekMode.EXACT_FRAME`** 
   I got this error: `Decoder can only seek to closest previous key frame`
   I asusme that this is not true since passing`nvc.SeekMode.PREV_KEY_FRAME` is going to the exact frame...

NOTE: this tests are run with Video_Codec_SDK_10.0.26

**Comment by rarzumanyan** [comment]
Hi @lferraz 
Thanks for the detailed reply.

Regarding the 
>I got this error: Decoder can only seek to closest previous key frame

It's not an error, it's expected behavior. 
When decoder uses built-in demuxer it can't just jump to arbitrary frame because inter-frame dependencies may not be resolved.
In stand-alone mode you can seek with demuxer to any frames to your liking.

Regarding the other points - allow me some time to reproduce & test on my machine, I'll update as I find solution.

**Comment by lferraz** [comment]
@rarzumanyan 
more tests with VP9 (the same video al always):
1. STANDALONE + EXACT_FRAME returned:
```
Seeking for the frame  7
[matroska,webm @ 0x5630c63fd980] File is broken, keyframes not correctly marked!
We are at frame with pts 233
/VideoProcessingFramework-dev/PyNvCodec/TC/src/NvDecoder.cpp:333
CUDA error: CUDA_ERROR_INVALID_VALUE
invalid argument

frame pts (decode order)      : 233
frame dts (decode order)      : 233
frame pos (decode order)      : 539815
frame duration (decode order) : 33

Cuvid parser faced error.
frame pts (decode order)      : 267
frame dts (decode order)      : 267
frame pos (decode order)      : 608222
frame duration (decode order) : 33

Cuvid parser faced error.
0  frames decoded.
```
This error only appears in STANDALONE + EXACT_FRAME .
The other cases are similar to the previous list of issues.
I need to verify the pts in BUILTIN + PREV_KEY_FRAME
I also need to run some tests on the seek method.

**Comment by rarzumanyan** [comment]
@lferraz 

This is the thing I was talking in my previous post.
You've got the exact frame that you've asked from demuxer. It's you responsibility to check if it can be decoded.
If you feed decoder with P or B frame first time or if inter-frame depencencies aren't resolved there's not guarantee the decoder will be able to reconstruct given frame.
If you want to be sure, seek for previous key frame.

**Comment by rarzumanyan** [comment]
@lferraz 

Regarding the 
>In BUILTIN mode nvc.SeekMode.PREV_KEY_FRAME is not working fine. It is going to the EXACT_FRAME.

Decoder actually returns right frame.
I've seek for frame 11 in `dec.InitMode.BUILTIN` mode, then decoded it & saved to file.
Also decoded whole file in `dec.InitMode.BUILTIN` mode and saved 11th frame with raw video player - frames are same.

Regarding the `av_seek_frame()` FFmpeg function which is used for seek - by default it seeks for key frames only (this is what they say in the doc) so `AVSEEK_FLAG_ANY` is set on exclusively in `EXACT_FRAME` mode. In `PREV_KEY_FRAME` the `AVSEEK_FLAG_BACKWARD` set to seek for closes previous key frame. I have no idea why does it search for the key frame sometimes and for exact frame in other cases but somehow it does the job.

**Comment by lferraz** [comment]
Hi @rarzumanyan ,
I misunderstood the meaning of PREV_KEY_FRAME and EXACT_FRAME. Sorry. 
I thought the meaning for  PREV_KEY_FRAME was returning the prev keyframe (**which I think is happening in STANDALONE+PREV_KEY_FRAME)** and for EXACT_FRAME I understood that was decoding form the prev keyframe.

I run some tests on h265 and vp9 and `seek` methods work perfect there!!! :)

Next you can see the issue I think there is with STANDALONE+PREV_KEY_FRAME. This test is run on the vp9 video asking for frame 7 (only 2 frames being decoded).

STANDALONE+PREV_KEY_FRAME:
```
Decoding on GPU 0
Seeking for the frame  7
We are at frame with pts 0
frame pts (decode order)      : 0
frame dts (decode order)      : 0
frame pos (decode order)      : 1077
frame duration (decode order) : 33

frame pts (decode order)      : 33
frame dts (decode order)      : 33
frame pos (decode order)      : 415953
frame duration (decode order) : 33

2  frames decoded.
```

BUILTIN + PREV_KEY_FRAME
```
Decoding on GPU 0
Seeking for the frame  7 
frame pts (display order)      : 233
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 267
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

9  frames decoded.
```

The first one decoded only two frames starting from 0 (which is the key frame).
The second one decoded from the 7th frame. It decodes 9 frames, 7 from the keyframe + the 2 requested frames.
