### ISSUE TITLE
Decode video frame to numpy array

### ISSUE THREAD

**Issue by Sayyam-Jain** [NVIDIA/VideoProcessingFramework#196]
Hi, thank you for your wonderful work. 

I'm trying to Decode an RTSP stream to rgb frame  in opencv python but unable to do so.
Can you please help?

Thanks!

**Comment by rarzumanyan** [comment]
Hi @Sayyam-Jain 

This issue is basically a duplicate of #38.
Please take a closer look at that and [this wiki page](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Decoding-video-from-RTSP-camera).
