### ISSUE TITLE
About rtsp

### ISSUE THREAD

**Issue by Songpenglei123** [NVIDIA/VideoProcessingFramework#198]
Hello, I would like to ask, there are specific packets in my RTSP data stream. I want to get the binary data stream of each frame before decoding it, so as to find the data I need, so as to match my image. I'd like to ask you what I should do.
Abd which sample should i use.

**Comment by rarzumanyan** [comment]
Hi @Songpenglei123 

>I want to get the binary data stream of each frame before decoding it

For that you can use `SampleDemuxDecode.py`:

https://github.com/NVIDIA/VideoProcessingFramework/blob/b138cc89dd25ad1751105dce6e0f9d689f539b78/SampleDemuxDecode.py#L33

`packet` is numpy array with compressed video frame in Annex.B format.

You can dump such video packets to disk and open file with VLC player. Please note that `packet` only contains video data (no sound, closed captions and such).

**Comment by rarzumanyan** [comment]
No update from issue originator, closing this issue as resolved.
Please reopen in case it's still reproduces.
