### ISSUE TITLE
import error, leak memory

### ISSUE THREAD

**Issue by leigh-plt** [NVIDIA/VideoProcessingFramework#20]
When try run with colab:
`import PytorchNvCodec`
ImportError: /content/VideoProcessingFramework/install/bin/PytorchNvCodec.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

No error if passing code throw this: https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.load_inline

**Comment by leigh-plt** [comment]
Found some memory leak (seems like after NvDecoder init operation):
https://colab.research.google.com/drive/1hgz6VdHOJ24rqkgnnuva4v7_-SoU6eXO

**Comment by rarzumanyan** [comment]
Hi,

You don't need to delete surface returned by `DecodeSingleSurface`.
VPF returns pointer to surface which is allocated & released within C++ internals. You can use this surface until next call to `DecodeSingleSurface`.

This is done for performance sake as otherwise `cudaMallocPitch` would have been called every time you call `DecodeSingleSurface`. If you want to save surface copy, you may use `Clone` method which will call `cudaMallocPitch` and `cudaMemcpy2D` to make a deep copy of the object.

BTW, you may also opt-in `TRACK_TOKEN_ALLOCATIONS` CMake variable, which will check number of constructors & destructors calls within VPF insides.

There's also a [devblogs article](https://devblogs.nvidia.com/vpf-hardware-accelerated-video-processing-framework-in-python/) article which describes main API functions.

**Comment by leigh-plt** [comment]
> BTW, you may also opt-in `TRACK_TOKEN_ALLOCATIONS` CMake variable, which will check number of constructors & destructors calls within VPF insides.

Result:
```
Checking token allocation counters: No leaks dectected
========= LEAK SUMMARY: 3317760 bytes leaked in 1 allocations
========= ERROR SUMMARY: 1 error
```

**Comment by rarzumanyan** [comment]
What tool do you use?
I'll try to reproduce on my machine.

**Comment by leigh-plt** [comment]
```
$ gcc --version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2
```
Colab link  have same problem.

**Comment by rarzumanyan** [comment]
I've modified SampleDecode and tested on my machine:
```python
import PyNvCodec as nvc

gpuID = 0
encFile = "big_buck_bunny_1080p_h264.mov"
decFile = open("big_buck_bunny_1080p_h264.nv12", "wb")

nvDec = nvc.PyNvDecoder(encFile, gpuID)
frame = 0

while frame < 500:
    rawFrame = nvDec.DecodeSingleSurface()
    if not (rawFrame.Empty()):
        break
    
    frame += 1
```
Shows no errors:
```cmd
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cuda-memcheck.exe" python SampleDecode.py
========= CUDA-MEMCHECK
Decoding on GPU 0
========= ERROR SUMMARY: 0 errors
```
You don't need to delete decoded surfaces and decoder class instance by hand

**Comment by leigh-plt** [comment]
with or w/o del same result
Linux bug reprodused with colab:
https://colab.research.google.com/drive/1hQGhHbonLNf0a5e6Ykr5S0hYk_mFwilO

**Comment by leigh-plt** [comment]
NvDecoder.cpp leak in this file. One of pFrame don't release

**Comment by rarzumanyan** [comment]
Hi @leigh-plt,
Thank you for this update. 

I'm working on this bug now. On my machine, cuda-memcheck shows mem leak only when full memchek is opted-in via CLI, otherwise it says everything is fine. I'll ask our CUDA people for help.

**Comment by leigh-plt** [comment]
I fix it with new variable for stored all allocation w/o erase operation as current. +1 list but no leak.
Bug here:
```
    {
      lock_guard<mutex> lock(p_impl->m_mtxVPFrame);
      p_impl->m_nDecodedFrame++;
      bool isNotEnoughFrames =
          (p_impl->m_nDecodedFrame > p_impl->m_vpFrame.size());

      if (isNotEnoughFrames) {
        p_impl->m_nFrameAlloc++;
        CUdeviceptr pFrame = 0;
        ThrowOnCudaError(cuCtxPushCurrent(p_impl->m_cuContext), __LINE__,
                         __FILE__);

        if (p_impl->m_bDeviceFramePitched) {
          auto const height =
              p_impl->m_nLumaHeight +
              p_impl->m_nChromaHeight * p_impl->m_nNumChromaPlanes;
          ThrowOnCudaError(
              cuMemAllocPitch(&pFrame, &p_impl->m_nDeviceFramePitch,
                              p_impl->m_nWidth * p_impl->m_nBPP, height, 16),
              __LINE__, __FILE__);
        } else {
          ThrowOnCudaError(cuMemAlloc(&pFrame, GetFrameSize()), __LINE__,
                           __FILE__);
        }

        ThrowOnCudaError(cuCtxPopCurrent(nullptr), __LINE__, __FILE__);
        p_impl->m_vpFrame.push_back(pFrame);
        p_impl->m_vpFrameAll.push_back(pFrame);
      }
      pDecodedFrame = p_impl->m_vpFrame[p_impl->m_nDecodedFrame - 1];
    }
```

**Comment by rarzumanyan** [comment]
Hi @leigh-plt ,
Please check the latest commit in master branch.
After some triage, I've found that last frame wasn't released by decoder.
On my maching `cuda-memcheck --leak-check full` doesn't show any leaks after the patch.

**Comment by leigh-plt** [comment]
Thank you! All good, no leak

just small error (not used anywhere):
ffmpeg demuxer:
framerate = fmtc->streams[videoStream]->r_frame_rate.num; 
It's not full framerate, skipped denominator.

**Comment by rarzumanyan** [comment]
Hi,
Glad that it worked out. Closing the issue.
