### ISSUE TITLE
cudaMallocHost is called before cuCtxCreate is called

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#204]
Hi @rarzumanyan ,
Thank you for the [nvtx_support](https://github.com/NVIDIA/VideoProcessingFramework/tree/nvtx_support)

I have modified the code a bit to give more detailed function call sequence.
This reveals `DemuxFrame`  constructor allocates a memory in the default context, which is not managed by `CudaResMgr`
 
![Screenshot from 2021-05-06 23-28-07](https://user-images.githubusercontent.com/21025427/117344187-c19b4900-aec2-11eb-9faa-d8932f1de0df.png)

**Comment by rarzumanyan** [comment]
Yes, `Buffer` class uses `cudaMallocHost()` to allocate memory on host side. It's CUDA runtime API function. What's the exact problem with it?

**Comment by vtpl1** [comment]
@rarzumanyan
I am trying to have exact estimation of GPU memory creation and its release. I am finding there is always some GPU memory not getting freed even after all `Surfaces` and `PyNvDecoder` are set to `None`.

**Comment by rarzumanyan** [comment]
@vtpl1 

You can track allocations if you opt-in TRACK_TOKEN_ALLOCATION cmake option

**Comment by vtpl1** [comment]
Thanks @rarzumanyan for the pointer.
Can't we avoid this?
> GPU0 default context

**Comment by rarzumanyan** [comment]
@vtpl1 

I’m not sure I fully understand the question.
What are you trying to avoid?

**Comment by vtpl1** [comment]
The `cudaMallocHost` of `Buffer` class will use default context, the default context will be allocated in GPU0, even if rest of the operations can be directed to run in GPU1 using CudaResMgr and gpu id.

So even if we provide the GPU1 id as argument , GPU0 will always be used to create default context, so a memory of 50-100MB will be allocated in GPU0 due to default context allocation.

**Comment by rarzumanyan** [comment]
@vtpl1 

Ok, check out latest `nvtx_support`, I've replaced runtime API `cudaMallocHost()` with driver API `cuMemAllocHost()` which accepts given CUDA context.

**Comment by vtpl1** [comment]
@rarzumanyan ,
`SampleDecode.py` is failing in `nvtx_support` branch with the following error: `free(): invalid next size (fast)` and call stack:

```
libTC.so!VPF::Buffer::Deallocate(VPF::Buffer * const this) (/workspaces/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:220)
libTC.so!VPF::Buffer::~Buffer(VPF::Buffer * const this) (/workspaces/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:158)
libTC.so!VPF::Buffer::~Buffer(VPF::Buffer * const this) (/workspaces/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:163)
libTC.so!VPF::NvdecDecodeFrame_Impl::~NvdecDecodeFrame_Impl(VPF::NvdecDecodeFrame_Impl * const this) (/workspaces/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:248)
libTC.so!VPF::NvdecDecodeFrame::~NvdecDecodeFrame(VPF::NvdecDecodeFrame * const this) (/workspaces/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:279)
libTC.so!VPF::NvdecDecodeFrame::~NvdecDecodeFrame(VPF::NvdecDecodeFrame * const this) (/workspaces/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:280)
PyNvCodec.cpython-36m-x86_64-linux-gnu.so!std::default_delete<VPF::NvdecDecodeFrame>::operator()(const std::default_delete<VPF::NvdecDecodeFrame> * const this, VPF::NvdecDecodeFrame * __ptr) (/usr/include/c++/7/bits/unique_ptr.h:78)
PyNvCodec.cpython-36m-x86_64-linux-gnu.so!std::unique_ptr<VPF::NvdecDecodeFrame, std::default_delete<VPF::NvdecDecodeFrame> >::~unique_ptr(std::unique_ptr<VPF::NvdecDecodeFrame, std::default_delete<VPF::NvdecDecodeFrame> > * const this) (/usr/include/c++/7/bits/unique_ptr.h:263)
PyNvCodec.cpython-36m-x86_64-linux-gnu.so!PyNvDecoder::~PyNvDecoder(PyNvDecoder * const this) (/workspaces/VideoProcessingFramework/PyNvCodec/inc/PyNvCodec.hpp:163)
PyNvCodec.cpython-36m-x86_64-linux-gnu.so!std::default_delete<PyNvDecoder>::operator()(const std::default_delete<PyNvDecoder> * const this, PyNvDecoder * __ptr) (/usr/include/c++/7/bits/unique_ptr.h:78)
PyNvCodec.cpython-36m-x86_64-linux-gnu.so!std::unique_ptr<PyNvDecoder, std::default_delete<PyNvDecoder> >::~unique_ptr(std::unique_ptr<PyNvDecoder, std::default_delete<PyNvDecoder> > * const this) (/usr/include/c++/7/bits/unique_ptr.h:263)
PyNvCodec.cpython-36m-x86_64-linux-gnu.so!pybind11::class_<PyNvDecoder>::dealloc(pybind11::detail::value_and_holder & v_h) (/workspaces/VideoProcessingFramework/PyNvCodec/pybind11-2.1.1/include/pybind11/pybind11.h:1341)
PyNvCodec.cpython-36m-x86_64-linux-gnu.so!pybind11::detail::clear_instance(PyObject * self) (/workspaces/VideoProcessingFramework/PyNvCodec/pybind11-2.1.1/include/pybind11/detail/class.h:327)
PyNvCodec.cpython-36m-x86_64-linux-gnu.so!pybind11::detail::pybind11_object_dealloc(PyObject * self) (/workspaces/VideoProcessingFramework/PyNvCodec/pybind11-2.1.1/include/pybind11/detail/class.h:347)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
PyDict_Clear (Unknown Source:0)
```

**Comment by rarzumanyan** [comment]
@vtpl1 

I suspect this happens because CUDA context isn’t copied in Buffer copy constructor and assignment operator - will fix later this day.

Surprisingly it didn’t fail on my Windows machine.

**Comment by rarzumanyan** [comment]
@vtpl1 

Please confirm if this is resolved and code from `nvtx_support` can be merged to `master`.

**Comment by vtpl1** [comment]
@rarzumanyan ,
It looks fixed for now. It can be merged to the `master`

**Comment by rarzumanyan** [comment]
Closing as resolved.
