### ISSUE TITLE
Feature request: add support of BT601 color conversion in VPF

### ISSUE THREAD

**Issue by Jie-Fang** [NVIDIA/VideoProcessingFramework#209]
Hi @rarzumanyan ,
We found jpegs obtained from VPF through nv12->rgb->jpeg were very different from the jpegs obtained from ffmpeg or opencv.
In breif, the jpegs from ffmpeg or opencv had higher saturation. Someone also found similar phenomenon, like [issue 139](https://github.com/NVIDIA/VideoProcessingFramework/issues/139) and [issue 63](https://github.com/NVIDIA/VideoProcessingFramework/issues/63).

We have checked our video has BT601 color space, while VPF's nv12->rgb only supports BT709. We doubt this different color conversion causes this gap between VPF and FFmpeg. Could you add support of BT601 color conversion in VPF? We want to verify it using this kind of conversion.

**Comment by rarzumanyan** [comment]
@Jie-Fang 

Please check out latest `rgb_bt709` branch and test if it closes the gap between different color conversion options.

**Comment by Jie-Fang** [comment]
@rarzumanyan 
I pulled `rgb_bt709` and compiled it, but met below compile error:
![Capture](https://user-images.githubusercontent.com/10357969/117975637-74572580-b361-11eb-89ef-a24fdd6353c3.PNG)

How can I fix it?

**Comment by rarzumanyan** [comment]
@Jie-Fang 

Allow me some time, I'll fix it.
This is a compiler-specific error, looks like it doesn't want the function name to be same as type name.
I'll rename them in C++ land, Python interface will remain the same.

**Comment by rarzumanyan** [comment]
@Jie-Fang 

Please check out latest `rgb_bt709`.
I've changed the `ColorSpace()` and `ColorRange()` methods names, now it shall be fine.
If you still have issues with compilation - please let me know. I'm mostly developing under Windows, MSVC have no problems with such naming so I didn't notice it.

**Comment by Jie-Fang** [comment]
Thanks Roman, I build it successfully.

But unfortunately, our video has BT601 color space and mpeg color range. There’s no corresponding conversion to match it.
I have tested the new VPF branch, the results still remain the same.
After digging some material out, I think the root of this issue isn’t related to BT601 or BT709.
The videos which has BT709 and mpeg get the same gap too.
I have to doubt that nv12->rgb color conversion in VPF is unsuitable for such videos.

When I look through ffmpeg source code, I find all conversions in ffmpeg involving YUV actually use YCbCr. https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/pixfmt.h#L66
As I know, YCbCr->RGB and YUV->RGB have different conversion matrix. FFmpeg actually uses YCbCr->RGB internally, while VPF uses YUV->RGB.
After changing yuv420_rgb’s api from nppiYUV420ToRGB_8u_P3C3R_Ctx to nppiYCbCr420ToRGB_8u_P3C3R_Ctx, I get the similar result through nv12->yuv->rgb conversion. I think that’s the major reason which leads to the gap.

**Comment by rarzumanyan** [comment]
@Jie-Fang 
YCbCr has the same pixel format as YUV, the difference between them is the color range. 

YCbCr has narrower range (which is called MPEG range). This may actually be the clue to results you've obtained - `nppiYCbCr420ToRGB_8u_P3C3R_Ctx` shall do a "yuv420 bt601 mpeg" -> rgb conversion.

Let us do the following: please upload 2 videos, one of bt701 colorspace, another of bt601.
I'll decode them & convert to rgb on my machine with both ffmpeg and vpf and will update you with the latest findings.

**Comment by Jie-Fang** [comment]
@rarzumanyan 
Videos are too big to upload, I put them on the google drive. You can get them following below links:
[BT709 video](https://drive.google.com/file/d/1L2TZxg4A3VunEVJFgm82F1Z3d88LiDig/view?usp=sharing)
[BT601 video](https://drive.google.com/file/d/10uxXrG3mVKNWcgE4ZbUW1i57TMGe1nwz/view?usp=sharing)

**Comment by rarzumanyan** [comment]
Hi @Jie-Fang 

Please check out latest `rgb_bt709`.
I've made some changes to code and checked rgb files decoded by FFmpeg and VPF - they are visually same.

**Comment by Jie-Fang** [comment]
Hi @rarzumanyan ,

I have test the latest `rgb_bt709`, it worked perfectly. It's decoded rgb files are what we want. They are visually same as FFmpeg's result. 
Thanks!

**Comment by rarzumanyan** [comment]
@Jie-Fang 
Great news. Fixing this issue as closed, merging changes to `master` branch.
