### ISSUE TITLE
ValueError: No AVFormatContext provided.

### ISSUE THREAD

**Issue by dexception** [NVIDIA/VideoProcessingFramework#21]
```
root@ashutosh-GL553VE:/opt/github/VideoProcessingFramework/install/bin# python3 SampleDecode_rtsp.py 
Decoding on GPU 0
Can't open rtsp://ashutosh:ashu1234@192.168.1.250:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif: Protocol not found
Traceback (most recent call last):
  File "SampleDecode_rtsp.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
ValueError: No AVFormatContext provided.

```

```
import PyNvCodec as nvc

gpuID = 0
encFile = "rtsp://ashutosh:ashu1234@192.168.1.250:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif"
#decFile = open("big_buck_bunny_1080p_h264.nv12", "wb")

nvDec = nvc.PyNvDecoder(encFile, gpuID)

while True:
    rawFrame = nvDec.DecodeSingleFrame()
    # Decoder will return zero-size frame if input file is over;
    if not (rawFrame.size):
        break

    frameByteArray = bytearray(rawFrame)
    print(type(frameByteArray))
    #decFile.write(frameByteArray)

```

**Comment by rarzumanyan** [comment]
Hi,
Take a look at the same [issue](https://github.com/NVIDIA/VideoProcessingFramework/issues/9) that was closed some time ago:

**Comment by dexception** [comment]
@rarzumanyan 
Do i need to edit ffmpeg c++ code and build it again to resolve this issue ? I don't understand.

**Comment by rarzumanyan** [comment]
Hi @dexception 

As I've replied you in [ other issue thread](https://github.com/NVIDIA/VideoProcessingFramework/issues/9#issuecomment-601645573), this error:
`Can't open rtsp://ashutosh:ashu1234@192.168.1.250:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif: Protocol not found`

is FFmpeg error. It happens at FFmpegDemuxer.cpp:198
```Cpp
AVFormatContext *FFmpegDemuxer::CreateFormatContext(const char *szFilePath) {
  avformat_network_init();

  AVFormatContext *ctx = nullptr;
  auto err = avformat_open_input(&ctx, szFilePath, nullptr, nullptr);
  if (err < 0) {
    std::cerr << "Can't open " << szFilePath << ": " << AvErrorToString(err)
               << "\n";
    return nullptr;
  }

  return ctx;
}
```

VPF uses FFmpeg for obtaining elementary H.264 and H.265 bitstreams from various input formats. If it's API returns error, my advice is to open same url with ffmpeg application and check ffmpeg build options if you've built it from source.

**Comment by dexception** [comment]
Now i am getting the following..

Traceback (most recent call last):
  File "SampleDecode_rtsp.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: CUDA error: CUDA_ERROR_UNKNOWN
unknown error

**Comment by dexception** [comment]
@rarzumanyan 
./ffmpeg -rtsp_transport tcp -i rtsp://admin:innefu12345@192.168.1.194:554/streaming/channels/101 -f image2 -vf fps=fps=1 hello/img%03d.png

ffmpeg seems to be working perfectly fine.

**Comment by dexception** [comment]
New Laptop with Ubuntu 18.04
apt-get install ffmpeg

Still getting the same error for every file i have tested on
https://www.clipcanvas.com/a/video-clip-formats-and-codec-samples

Even getting the same error on rtsp streams for hikvision, cpplus. But when i play via ffmpeg/vlc every file is working file.

Are you planning to fixing your bugsssssssssssssssssssssssss ??????????
If not just rename this repo to big migraine.

**Comment by dexception** [comment]
Closing as nobody is bothering to solve issue. 

Don't waste your time on VPF. It is crap.
