### ISSUE TITLE
Meet an error when encoding showed that "Description: Frame Dimension less than the minimum supported value."

### ISSUE THREAD

**Issue by TracelessLe** [NVIDIA/VideoProcessingFramework#214]
**Describe the problem**
Hi @rarzumanyan , I meet an error when use VPF encoding today.

The error showed as follow:

> RuntimeError: CreateEncoder : m_nvenc.nvEncInitializeEncoder(m_hEncoder, &m_initializeParams) returned error 8
> Description: Frame Dimension less than the minimum supported value.
>  at ./VideoProcessingFramework/PyNvCodec/TC/src/NvEncoder.cpp:243

I read the Line 243 of NvEncoder.cpp, it is calling the nvenc api:

`NVENC_API_CALL(      m_nvenc.nvEncInitializeEncoder(m_hEncoder, &amp;m_initializeParams),      m_nvenc.nvEncGetLastErrorString(m_hEncoder));`

From the error log, I guess that my video size is too small. So I check the video, the size is "144*80". 

I find the nvenc header file "nvEncodeAPI.h" has set a minimum input size limit as follow:

>     /**
>      * Minimum input width supported.
>      */
>     NV_ENC_CAPS_WIDTH_MIN,
> 
>     /**
>      * Minimum input height supported.
>      */
>     NV_ENC_CAPS_HEIGHT_MIN,

Do you know what the numbers of "NV_ENC_CAPS_WIDTH_MIN" and  "NV_ENC_CAPS_HEIGHT_MIN" are?

Waiting for reply.  :)

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

Check out latest `issue_214` branch, it now validates the input resolution and returns meaningful error message in resolution isn't valid:
```bash
python SampleEncode.py 0 bbb.nv12 bbb.h264 32 16
This sample encodes first  444  frames of input raw NV12 file to H.264 video on given GPU.
It reconfigures encoder on-the fly to illustrate bitrate change, IDR frame force and encoder reset.
Usage: SampleEncode.py $gpu_id $input_file $output_file $width $height
Encoding on GPU 0
Video frame width is too small: 32<33
Video frame height is too small: 16<17
Traceback (most recent call last):
  File "SampleEncode.py", line 116, in <module>
    encode(gpuID, decFilePath, encFilePath, width, heihgt)
  File "SampleEncode.py", line 76, in encode
    success = nvEnc.EncodeSingleFrame(rawFrame, encFrame, sync = False)
RuntimeError

```

**Comment by TracelessLe** [comment]
Verified the branch. I get message with the small resolution video:

`
Video Resolution 80x144

Encoding on GPU 0
Video frame width is too small: 80<145

Traceback (most recent call last):
  File "SampleEncode.py", line 301, in <module>
    encode(gpuID, decData, encFilePath, width, height, num_frames, fps)
  File "SampleEncode.py", line 154, in encode
    success = nvEnc.EncodeSingleSurface(rawSurface, encFrame, sync = False)
RuntimeError
`

Thanks for your update.

By the way, when the input is 80x144, the error is "width is too small: 80<145". And when I try your input size such as "32*16", the error is "Video frame width is too small: 32<145; Video frame height is too small: 16<49" which is different from your message "Video frame width is too small: 32<33;Video frame height is too small: 16<17".  So what is the value of min_w and min_h actually, or what is the relationship of input resolution and the min_w/min_h/max_w/max_h?

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

Video frame resolution support depends on HW gen. Message above was obtained on my laptop with GTX 1050 which is Pascal.

P. S.
Closing as resolved.
