### ISSUE TITLE
Single I-Frame in encoded stream

### ISSUE THREAD

**Issue by revalo** [NVIDIA/VideoProcessingFramework#215]
**Describe the bug**
The output h264 only seems to have a single I-Frame at the start. I am not sure how to manipulate the encoder settings to insert I-Frames periodically. This makes it very slow for media players to seek on the output.

**To Reproduce**
1. `python SamplePyTorch.py 0 input.mp4 output.h264`
2. `ffprobe -select_streams v -show_frames -show_entries frame=pict_type output.h264 | grep -n I`

Only has single I-Frame,

```
2:pict_type=I
```

**Expected behavior**
The encoder should add I-Frames automatically.

**Desktop (please complete the following information):**
 - OS: Windows
 - Nvidia driver version: 466.47
 - CUDA Version: 10.2
 - Video Codec SDK Version: 11.0.10
 - Python Version: 3.6 [Conda]

**Comment by rarzumanyan** [comment]
Hi @revalo 

You can select GOP size with corresp. `PyNvEncoder` option like shown below:
```python
nvEnc = nvc.PyNvEncoder({'preset': 'P5', 'tuning_info' : 'high_quality', 'codec': 'h264', 
                         'profile' : 'high', 's': res, 'bitrate' : '10M',
                         'gop' : '15'}, gpuID)
```
Dictionary entries order doesn't matter.

Below is the `ffprobe -select_streams v -show_frames -show_entries frame=pict_type output.h264` output on the file encoded with settings shown above. As you can see, GOP size is equal to 15.
```
[FRAME]
pict_type=I
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=P
[/FRAME]
[FRAME]
pict_type=I
[/FRAME]
[FRAME]
pict_type=P
...
```
