### ISSUE TITLE
Version conflicts

### ISSUE THREAD

**Issue by ashuezy** [NVIDIA/VideoProcessingFramework#22]
Can you please confirm which versions of the following are compatible as i have already tried 6 times with different combinations of drivers, cuda and ffmpeg. There is missing information that is causing delay and headache which should be provided for easy work. 

GTX 1060 
Ubuntu 18.04
Nvidia Driver: 430.50
Cuda: 10.1 [Cannot change 10.1 because of some dependency with other library]
Cudnn: 7.6.5
Video_Codec_SDK_9.0.20
nv-codec-headers-n9.0.18.3

**ffmpeg** latest but configured using the following because command given in wiki is not creating shared libraries.
./configure --enable-pic --enable-shared --cc="gcc -m64 -fPIC" --prefix=$(pwd)/build_release

VideoProcessingFramework
======================
Only command that was changed

cmake \
 -DFFMPEG_DIR:PATH="/opt/github/FFmpeg" \
 -DVIDEO_CODEC_SDK_DIR:PATH="/home/ashutosh/Downloads/Video_Codec_SDK_9.0.20" \
 -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
 -DCMAKE_INSTALL_PREFIX:PATH="/usr/local/vpf"\
 -DAVCODEC_INCLUDE_DIR:PATH="/opt/github/FFmpeg/build_release/include" \
 -DAVFORMAT_INCLUDE_DIR:PATH="/opt/github/FFmpeg/build_release/include" \
 -DAVUTIL_INCLUDE_DIR:PATH="/opt/github/FFmpeg/build_release/include" \
 -DSWRESAMPLE_LIBRARY="/opt/github/FFmpeg/build_release/lib/libswresample.so" \
 -DAVFORMAT_LIBRARY="/opt/github/FFmpeg/build_release/lib/libavformat.so" \
 -DAVCODEC_LIBRARY="/opt/github/FFmpeg/build_release/lib/libavcodec.so" \
 -DAVUTIL_LIBRARY="/opt/github/FFmpeg/build_release/lib/libavutil.so" \
 .. &&\

python3 SampleDecode.py

python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)

**Comment by rarzumanyan** [comment]
Hi @ashuezy 

I'm testing patches on multiple Linux machines before uploading and I've never run into issues like this. So to be honest I don't have a ready made answer to your question.
Below is how I build ffmpeg & VPF on clean testing machine from scratch.
I'm using Anaconda Python as I also use Pytorch bindings, but it shouldn't make a huge difference.

FFmpeg build:
```bash
cd ~/Git/FFmpeg
mkdir -p $(pwd)/build_x64_release_shared 
./configure \
 --prefix=$(pwd)/build_x64_release_shared \
 --disable-static \
 --disable-stripping \
 --disable-doc \
 --enable-shared
 
make -j -s && make install
```

```bash
# Export paths to Video Codec SDK and FFMpeg
export PATH_TO_SDK=~/Video_Codec_SDK_9.1.23
export PATH_TO_FFMPEG=~/Git/FFmpeg/build_x64_release_shared

# Clone repo and start building process
cd ~/Git
git clone https://github.com/NVIDIA/VideoProcessingFramework.git

# Export path to Cmake:
export PATH=$PATH:/home/rarzumanyan/cmake-3.16.4-Linux-x86_64/bin

# Export path to CUDA compiler (I'm installing drivers from Nvidia site):
export CUDACXX=/usr/local/cuda/bin/nvcc

#Now the VPF build
cd VideoProcessingFramework
export INSTALL_PREFIX=$(pwd)/install
mkdir -p install
mkdir -p build
cd build
cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DPYTHON_LIBRARY=/home/rarzumanyan/anaconda3/lib/libpython3.7m.so \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"
make && make install

# Launch samples
cd ~/Git/VideoProcessingFramework/install/bin
export LD_LIBRARY_PATH=$PATH_TO_FFMPEG/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
python3 ./SampleDecode.py
```

Can you also upload your CMake configure output?
I've seen couple times that when 2 or more Python versions are installed, CMake may compile VPF against Python libs version which are not used by default when you launch the sample.
That's the actual reason I'm setting `PYTHON_LIBRARY` variable when building VPF.
