### ISSUE TITLE
Using nvc.Surface as a GPUArray

### ISSUE THREAD

**Issue by AdamGreen424** [NVIDIA/VideoProcessingFramework#220]
**Describe the bug**
Very simple bug i have a decoded frame of the type`nvc.Surface` and i wish to cast it into a numpy array. However when i run the code below it does not work and i get the following error: `pycuda._driver.LogicError: cuMemcpyDtoH failed: invalid argument
`. The hope is to have the image turned into a numpy array, im aware of the downloader but doing it this way is needed due to my usecase. Note the surface is in a RGB format. If you need more code or any other details ill try and get back to you asap.

**My Code**
```# Some Constants
VIDEO_PATH = "video_1.mp4"
REQUIRED_INPUT_TYPE = np.float32
REQUIRED_INPUT_SHAPE = (1, 160, 160, 3)

# Get Surface
surface = get_single_surface(
    VIDEO_PATH, REQUIRED_INPUT_SHAPE[1], REQUIRED_INPUT_SHAPE[2]
)

plane_ptr = surface.PlanePtr()

surface_ptr = plane_ptr.GpuMem()
surface_height = surface.Height()
surface_width = surface.Width() 

# More low level testing if we get the correct vals
numpy_array = cuda.from_device(surface_ptr, (160, 160, 3), dtype=np.uint8)`
```

**Comment by rarzumanyan** [comment]
Hi @AdamGreen424 

I'm not familiar with pycuda so I can only comment the VPF code:

```python
VIDEO_PATH = "video_1.mp4"
REQUIRED_INPUT_TYPE = np.float32
REQUIRED_INPUT_SHAPE = (1, 160, 160, 3)

# Get Surface
# I assume surface is 160x160 RGB sutface of type uint8
surface = get_single_surface(
    VIDEO_PATH, REQUIRED_INPUT_SHAPE[1], REQUIRED_INPUT_SHAPE[2]
)

# This is 2D CUDA memory chunk with RGB pixels
plane_ptr = surface.PlanePtr()

# This is CUdeviceptr
surface_ptr = plane_ptr.GpuMem()

# Not correct.
# Please use surface_ptr height, width and pitch.
# I don't see this variables being used anywhere else, however.
surface_height = surface.Height()
surface_width = surface.Width() 

# More low level testing if we get the correct vals
numpy_array = cuda.from_device(surface_ptr, (160, 160, 3), dtype=np.uint8)`
```

Please note the `surface_ptr` is pitched 2D CUDA mem allocation.
So for 160x160 RGB uint8 it's actual resolution may be e. g. 512x160 (160x3=480, then round up to closest power of 2). I don't know how does that reflect in pycuda API so I leave it up to you.

**Comment by AdamGreen424** [comment]
Thanks for you help.
