### ISSUE TITLE
Multithreaded Surface use behaviour

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#221]
Hi @rarzumanyan,

I have a query about use of `Surface` from a different thread.

Can we use the `Surface` created in one thread be used in a different thread? Can we use `DownloadSingleSurface` from the other thread?

This is not happening always. I am trying to reproduce the same.

https://github.com/NVIDIA/VideoProcessingFramework/blob/19b87eddc0539d90ae4025629bac7c93c1387d56/SampleEncodeMultiThread.py#L70-L78

**Comment by rarzumanyan** [comment]
Hi @vtpl1,

Please check out latest `master` ToT, it now allows to use external CUDA context & stream with the help of `pycuda`:
https://github.com/NVIDIA/VideoProcessingFramework/blob/897ffb899a464ff7809e8eceb27bf4c448b47c68/SampleEncodeMultiThread.py#L51-L76

Easiest way to do that would be to use same CUDA  context & stream from multiple threads (or joggle with CUDA stream sync).

Just don't forget to protect your data in multi-threaded environment, the rest shall be fine. You can basically get `CUdeviceptr` of desired `SurfacePlane` to access the data. There are no artificial limitations on that.

**Comment by vtpl1** [comment]
@rarzumanyan ,
Thank you for elaboration will update on the issue soon.
Is there a method to `Export` gpu memories to supplied context?

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

It’s not implemented yet, but it can be added.
Right now `Export()` uses context provided when object instance is created.

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

This feature was added to `master` branch, please check it out.
