### ISSUE TITLE
Min QP setting in NvCodecCliOptions.cpp

### ISSUE THREAD

**Issue by frank840306** [NVIDIA/VideoProcessingFramework#222]
**Describe the bug**
In `VideoProcessingFramework/PyNvCodec/TC/src/NvCodecCliOptions.cpp` from the master branch, it seems like there is a bug on line 909. While setting the variable `params.minQP` using `ParseQpMode ` function, variable `min_qp ` should be passed to this function, not the `init_qp`. Thanks.

**To Reproduce**

**Expected behavior**
on line 909, the variable `init_qp` should be replaced with `min_qp`.

**Screenshots**
![Screen Shot 2021-07-07 at 4 08 40 PM](https://user-images.githubusercontent.com/6989178/124723572-c8375280-df3d-11eb-955c-327b4c4fd203.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Nvidia driver version: 460.73.01
 - CUDA Version: 11
 - Video Codec SDK Version: 11.0.10
 - Python Version: 3.7.4

**Additional context**

**Comment by rarzumanyan** [comment]
Hi @frank840306 

Thanks for bringing this up.
Please check out latest `master`, it has the fix.

**Comment by frank840306** [comment]
Thanks!!!
