### ISSUE TITLE
will the color conversion between bgr and yuv444p be provided in VPF?

### ISSUE THREAD

**Issue by frank840306** [NVIDIA/VideoProcessingFramework#226]
I would like to do some video processing algorithm to videos encoded with YUV444p pixel format. I need to decode YUV444p video and convert the color to BGR/RGB first and do some video processing algorithms. After that, the processed frames will be encoded to a YUV444p video. 

I have found that VPF provides h265 video encoding and decoding with YUV444p pixel format. What I haven't found is the color conversion between YUV444p and RGB/BGR. I would like to ask if there is a plan to provide color conversion between YUV444p and RGB/BGR. Thanks in advance.

<img width="618" alt="Screen Shot 2021-08-02 at 11 54 37 AM" src="https://user-images.githubusercontent.com/6989178/127802356-395320a7-5b30-4cda-932e-b67e07538be9.png">

**Comment by rarzumanyan** [comment]
Hi @frank840306 

That's possible to add such conversion.
Check out latest `issue_226` branch with the patch which adds YUV444->BGR support. As I add BGR->YUV444 I'll update you in this thread.

**Comment by frank840306** [comment]
Thanks you so much for updating so fast! I have tested the color conversion between yuv444 <--> bgr. I did an experiment that I have a input video `input.mp4` encoded in yuv444p with color space bt601 and color range mpeg (limited range) and do the following steps.

1. Decode the video `input.mp4`
2. convert the read frame from yuv444 to bgr format frame using `yuv444_bgr`
2. convert the bgr frame back to yuv444 format using `bgr_yuv444`
3. re-encode the video to `re-encode-1.mp4`

I re-encoded the video four times, like input.mp4 --> re-encode-1.mp4 --> re-encode-2.mp4 --> ... --> re-encode-4.mp4. I found that the color is slightly different. The images are shown below. The brighter one is from `input.mp4` while the darker one is from `re-encode-4.mp4`.

So I have two questions.

1. Does the conversion between yuv444 and bgr provided by VPF use color space BT_601?
2. Is it normal that the video will become darker after multiple times of re-encoding?
3. BTW, the functions `nppiYCbCrToBGR_8u_P3C3R_Ctx` and `nppiYUVToBGR_8u_C3R_Ctx` in `yuv444_bgr` mean color range MPEG (limited range) and JPEG (full range). So, when I look at the [NPP](https://docs.nvidia.com/cuda/npp/group__image__color__model__conversion.html) APIs, does every function name with "YCbCr" means MPEG and that with "YUV" means JPEG?

Thanks.

![test-yuv444p-2 pngsmall](https://user-images.githubusercontent.com/6989178/128111741-5894cbd6-0d9b-4903-98b0-cd53d356bb81.png)

![test-yuv444p-5 pngsmall](https://user-images.githubusercontent.com/6989178/128111777-5e63916a-f2b8-41f8-861d-ee04f639a97d.png)

**Comment by rarzumanyan** [comment]
Hi @frank840306 

>Does the conversion between yuv444 and bgr provided by VPF use color space BT_601?
>does every function name with "YCbCr" means MPEG and that with "YUV" means JPEG?

NPP colorspace conversions are a bit of pain in the back.
Generally YCbCr stands for MPEG range which is narrow and YUV stands for JPEG range which is full.

Regarding the BT601 and BT709 conversions, some of functions implemented in NPP has color space coded in their name (often done for NV12 and YUV420), some not. I determine the colorspace from the transform coefficients. 
So [these](https://docs.nvidia.com/cuda/npp/group__yuvtobgr.html) are coefficients for YUV <> BGR conversion:
```
*  Npp32f nY = (Npp32f)Y;
*  Npp32f nU = (Npp32f)U - 128.0F;
*  Npp32f nV = (Npp32f)V - 128.0F;
*  Npp32f nR = nY + 1.140F * nV; 
*  if (nR < 0.0F)
*      nR = 0.0F;
*  if (nR > 255.0F)
*      nR = 255.0F;    
*  Npp32f nG = nY - 0.394F * nU - 0.581F * nV;
*  if (nG < 0.0F)
*      nG = 0.0F;
*  if (nG > 255.0F)
*      nG = 255.0F;    
*  Npp32f nB = nY + 2.032F * nU;
*  if (nB < 0.0F)
*      nB = 0.0F;
*  if (nB > 255.0F)
*      nB = 255.0F;    
*  
```

From snippet below I assume that it's BT_601 colorspace conversion. Please correct me if I'm wrong.
Below are the [coefficients](https://docs.nvidia.com/cuda/npp/group__ycbcrtorgb.html) for YCbCr <> RGB conversion:
```
*  Npp32f nY = 1.164F * ((Npp32f)Y - 16.0F);
*  Npp32f nR = ((Npp32f)Cr - 128.0F); Npp32f nB = ((Npp32f)Cb
*  - 128.0F); Npp32f nG = nY - 0.813F * nR - 0.392F * nB; if (nG > 255.0F)
*      nG = 255.0F;
*  nR = nY + 1.596F * nR; 
*  if (nR > 255.0F)
*      nR = 255.0F;
*  nB = nY + 2.017F * nB;
*  if (nB > 255.0F)
*      nB = 255.0F;
*  
```

Moreover, information about the color space and range isn't integral part of the video coding standards, so it can be missing from the video sequence.

I'm not sure if this addresses your question but hope it helps you to understand the guts of the color conversion code in VPF. The more I deal with the NPP conversions, the more I like to move towards CUDA for better flexibility.

**Comment by frank840306** [comment]
I think the color conversion YUV <> RGB and YCbCr <> RGB you provide is correct.

Every time I finish encoding a video using VPF, I will use a ffmpeg command to wrap the h265 stream into a mp4 container. During the wrapping function, I will add color space information in this mp4. like the command below is for adding bt_601 (smpte170m) tag.

`ffmpeg -i input.h265 -c:v copy -tag:v hvc1 -f mp4 -bsf:v hevc_metadata=colour_primaries=6:transfer_characteristics=6:matrix_coefficients=6 output.mp4`

I am not sure whether it is the correct way to add color space information. If you have better way, please tell me. Thanks.

Besides, in my use case, I have multiple video processing algorithms so I have to decode and re-encode the video many times. The quality degradation issue is important to me. I would like to preserve the good quality of the video after multiple re-encodings. So I also compare the video generated from ffmpeg command.

The ffmpeg command is below
`ffmpeg -hwaccel cuda -c:v hevc_cuvid -i input.mp4 -f rawvideo -pix_fmt bgr24 -sws_flags full_chroma_int+accurate_rnd - | ffmpeg -hwaccel cuda -f rawvideo -pix_fmt bgr24 -framerate 29.97 -s 5376x2688 -i - -c:v hevc_nvenc -tag:v hvc1 -g 30 -preset:v p5 -tune:v hq -rc:v vbr -cq:v 12 -qmin 1 -qmax 12 -b:v 0 -pix_fmt yuv444p re-encode-1.mp4`

The encoder parameter of PyNvEncoder is
`{'preset': 'P5', 'tuning_info': 'high_quality', 'rc': 'vbr', 'multipass': 'qres', 'cq': '12', 'qmin': '1', 'qmax': '12', 'bitrate':
 '0', 'profile': 'high', 'gop': '30', 'fps': '29.97', 'codec': 'hevc', 's': '5376x2688'}` and `format = nvc.PixelFormat.YUV444`

For both ffmpeg re-encoding and VPF re-encoding, I will run 4 times each. Then the output videos are generated as below.

1. input.mp4 --> re-encode-vpf-1.mp4 --> re-encode-vpf-2.mp4 --> ... --> re-encode-vpf-4.mp4
2. input.mp4 --> re-encode-ffmpeg-1.mp4 --> re-encode-ffmpeg-2.mp4 --> ... --> re-encode-ffmpeg-4.mp4

After that, compare the quality between `input.mp4` and `re-encode-vpf-4.mp4` and between `input.mp4` and `re-encode-ffmpeg-4.mp4` using ffmpeg `-filter_complex psnr`.

PSNR between `input.mp4` and `re-encode-vpf-4.mp4` is 34.49
PSNR between `input.mp4` and `re-encode-ffmpeg-4.mp4` is 37.67

The result is slightly different even if I use the same preset and rate control parameter like, `preset: P5`, `tuning_info: high_quality`, `rc: vbr`, `cq: 12` and etc. I am wondering

1.  if there is any default encoding setting that is different between VPF and ffmpeg. And those settings is important to output quality.
2. maybe there exist other settings that can preserve more video quality. If you know, please let me know.

Thanks.

**Comment by rarzumanyan** [comment]
Hi @frank840306 

Nvdec and Nvenc work with NV12 and YUV444 as their native HW formats.
So every time you use bgr24, conversion is done like this:
```
nv12 > bgr24
yuv444 > bgr24
```
on decoder side, and

```
bgr24 > yuv444
```
on encoder side.

When each and every conversion is done, color space and range information is taken into account by ffmpeg color conversion code. I don't have information about the `input.mp4` file, what's the sampling format, color space and color range of it so it's difficult to tell what's happening with conversion even on 1st step of the pipeline. Imagine what may happen after you do it many times.

In order to investigate, I assume you may save all interim videos produced by vpf and ffmpeg to find where the quality degradation begins.

Regarding the quality setting of ffmpeg and vpf: although ffmpeg presets and coding settings map pretty close to VC presets & settings I can't guarantee that when the actual encoding begins both vpf and ffmpeg ends up using exactly same Nvenc settings. To investigate that, you can launch vpf encoding with verbose flag on and ffmpeg with debug level of output.

Nvenc doesn't use any stochastic algos during encoding so if configured exactly the same, it shall produce equivalent output files every time if one and the same input is given.

If you can build the ffmpeg from sources, you can see what are the exact settings Nvenc is initialized with in `libavcodec/nvenc.c/ff_nvenc_encode_init()` function. The same for vpf is located at `PyNvCodec/TC/src/NvEncoder::Reconfigure()` and `PyNvCodec/TC/src/NvEncoder::CreateEncoder()`

**Comment by frank840306** [comment]
The pixel_format of input.mp4 is yuv444p, the color space bt_601 and color range mpeg. 

As for the ffmpeg and vpf configurations, I will check it later as well as the degradation experiments. Thanks.

**Comment by ValZapod** [comment]
> -hwaccel cuda -c:v hevc_cuvid

This is wrong. You should use -hwaccel cuvid. Also, hevc_cuvid is old, use -hwaccel  nvdec -hwaccel_output_format cuda 

> ffmpeg -hwaccel cuda -f rawvideo

I do not think this makes any sense.

**Comment by rarzumanyan** [comment]
Hi @ValZapod 

>This is wrong. You should use -hwaccel cuvid. Also, hevc_cuvid is old, use -hwaccel nvdec -hwaccel_output_format cuda
>I do not think this makes any sense.

As a frequent contributor to both nvdec / cuvid modules I strongly disagree with these statements.

Long story short, `-hwaccel cuda` uses open source elementary video stream parsers developed by community and Video Codec SDK API for video frames decoding. Unlike that, `-hwaccel cuvid -c:v %codec_name%_cuvid` uses Video Codec SDK API for both elementary video stream parsing and decoding. Both options are viable, none of them is declared legacy and / or deprecated. 

E. g. first AV1 NV-accelerated decoder was submitted in form of patch for `cuvid` path.

Please find more information regarding the NVIDIA technology support in FFMpeg via these links:
https://developer.nvidia.com/blog/nvidia-ffmpeg-transcoding-guide/
https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

P. S.

In the documentation above, we most frequently use `-hwaccel cuda -hwaccel_output_format cuda` because it allows for automatic decoder selection. Both `nvdec` and `cuvid` paths are perfectly fine to enable HW-accelerated video decoding features.

**Comment by ValZapod** [comment]
> Unlike that, `-c:v %codec_name%_cuvid` uses Video Codec SDK API

That is not what I was talking about, only -hwaccel. Of course -c:v are all good (except for close captions) It is the only codec that supports hack for interlaced hevc.

> Both `nvdec` and `cuvid` paths are perfectly fine

cuvid and nvdec and just shorthands to cuda now. See: https://github.com/FFmpeg/FFmpeg/commit/60b1f85b67ccb907e4eba3e2c98839769690ed24

**Comment by rarzumanyan** [comment]
Hiding comments which are outside the scope of YUV444 <-> color conversion.

**Comment by frank840306** [comment]
Sorry for late reply. I have test the color conversion yuv444 <-> bgr. The color space used is correct. The reason that causes the degradation is just numeric issue every time conducting the color conversion. It is normal. So I think maybe we could close this issue if you agree. Thanks.

**Comment by rarzumanyan** [comment]
Thanks for the update, @frank840306 
I'm closing this as fixed. Please feel free to re-open in case you find something suspicious in this piece of color conversion functionality.

**Comment by ValZapod** [comment]
> color conversion yuv444 <-> bgr. The color space used is correct. The reason that causes the degradation is just numeric issue

This is not a numerical issue, there is no way to convert from 444 to rgb and back without losing quality, you need 10 bits RGB to get to zero changes.

**Comment by frank840306** [comment]
Sorry for the imprecise word "numerical issue" that I used. I know there always exists quality loss after each conversion between yuv and rgb. Like the result reported in this https://discoverybiz.net/enu0/faq/faq_YUVbyBreeze_test_00.html. Although it is just a PSNR result from comparing between images not videos, the result still shows the degradation after color conversion. Compared to the reported PSNR in this website, I would think that the PSNR results in my experiment are suffered from similar quality loss. Therefore, I would think that the color conversion provided by VPF is correct. If there is still anything that I miss, please tell me. Thanks.

**Comment by frank840306** [comment]
Recently, I try to decode the video (pix_fmt=yuv444p, color_space=bt601, color_range=jpeg) and convert the color to bgr. However, I faced a problem that the conversion failed like the screenshot below.

<img width="935" alt="Screen Shot 2021-08-25 at 1 45 30 PM" src="https://user-images.githubusercontent.com/6989178/130733612-f8e127a2-813e-4910-bc93-15d7738c0de5.png">

I saw the function used in `PyNvCodec/TC/src/TasksColorCvt.cpp` is `nppiYUVToBGR_8u_C3R_Ctx `. Is it supposed to be `nppiYUVToBGR_8u_P3C3R_Ctx`? Thanks.

![Screen Shot 2021-08-25 at 1 51 39 PM](https://user-images.githubusercontent.com/6989178/130733975-56155063-6542-49a7-891e-454b5aac4627.png)
