### ISSUE TITLE
How can we use PyNvEncoder to encode lossless HEVC?

### ISSUE THREAD

**Issue by aniongithub** [NVIDIA/VideoProcessingFramework#227]
[This](https://superuser.com/a/1236387) StackExchange answer shows how to modify an ffmpeg CLI command to encode lossless video, but how does one convert that CLI to [`kwargs`](https://github.com/NVIDIA/VideoProcessingFramework/blob/1012c8fdf0f2e0051a3025c1e9a98e4af0fe204d/SampleEncode.py#L54) for PyNvEncoder?

My primary need is to convert a series of images (in numpy arrays) to a lossless, H265 YUV444 video. Any examples would be much appreciated, thanks!

**Comment by rarzumanyan** [comment]
Hi @aniongithub 

You need to create `PyNvEncoder` class instance with parameters similat to this:
```
nvEnc = nvc.PyNvEncoder({
  'preset': 'P5', 
  'tuning_info' : 'lossless', 
  'fmt' : 'YUV444',
  'codec': 'hevc',  
  's': '1920x1080', 
}, gpu_id=0)

```

>how does one convert that CLI to kwargs for PyNvEncoder?

Encoding parameters are Python dictionary which are then passed to C++ land as `map<string, string>`. 
List of all supported parameters can be found in `PyNvCodec/TC/src/NvCodecCliOptions.cpp` file.
All unsupported parameters are ignored.

**Comment by aniongithub** [comment]
Excellent, will try these settings. Thanks!

**Comment by rarzumanyan** [comment]
@aniongithub 

Apologies, my code sample was wrong. It shall be like this instead:
```
nvEnc = nvc.PyNvEncoder({
  'preset': 'P5', 
  'tuning_info' : 'lossless', 
  'codec': 'hevc',  
  's': '1920x1080', 
}, gpu_id=0, format=nvc.PixelFormat.YUV444)
```
