### ISSUE TITLE
AttributeError: module 'PyNvCodec' has no attribute 'SeekMode'

### ISSUE THREAD

**Issue by bralat** [NVIDIA/VideoProcessingFramework#228]
**Describe the bug**
After building vpf from source in windows using the [instructions in the wiki](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source), I got the following error when I tried to run `python SampleDecode.py`

```
AttributeError: module 'PyNvCodec' has no attribute 'SeekMode'
```

**To Reproduce**
1. Follow instructions to install on windows
2. go to the build folder
4. run `python SampleDecode.py`
5. see the error

**Expected behavior**
I expected SampleDecode.py to print a description of the file and options it expects

**Desktop:**
 - OS: Windows 10 Home
 - Nvidia driver version 471.21
 - CUDA Version 11.0
 - Video Codec SDK Version 9.1.23
 - Python Version 3.8
 - Visual Studio 17

**Additional context**
I started with python 3.7 as stated in the wiki but I got a different error that was only resolved after switching to python 3.8

**Comment by rarzumanyan** [comment]
Hi @bralat 

Did you re-built the VPF after you've switched from Python 3.7 to Python 3.8?

**Comment by bralat** [comment]
@rarzumanyan Yes I did. Eventually, I figured I was supposed to run the command in the bin folder and not the build folder. That  gave me a new error previously reported [here](https://github.com/NVIDIA/VideoProcessingFramework/issues/92). Using procman as you recommended helped resolve the dependency issues. Thanks!

I know the wiki is probably aimed at experienced C developers but there might be novices like me who may not know the obvious. It will be great if the instructions were a little more specific in some areas. For example `Run one of the Samples to check that build is fine`. Every folder I run it in gave me an error so I had no idea where to even start looking for solutions.

Also, the zeranoe website has been shutdown and the alternative ffmpeg builds have many variants. It will be nice to point users to the right one. What worked for me was `ffmpeg-n4.4-80-gbf87bdd3f6-win64-gpl-shared-4.4` on this [github page](https://github.com/BtbN/FFmpeg-Builds/releases)

**Comment by rarzumanyan** [comment]
Hi @bralat 

Please take a look at #237, it looks like a duplicate.

**Comment by riaqn** [comment]
I'm seeing the same issue - how can I provide more information? 

Also when compiling I see that  void PyEval_InitThreads() is deprecated. I think this is because I'm using python3.9 and pybind 2.1.1 is simply too old - is that related to my problem?

**Comment by riaqn** [comment]
Copying `/usr/lib/python3.9/site-packages/PyNvCodec/PyNvCodec.cpython-39-x86_64-linux-gnu.so` to the same directory as `SampleDecode.py` works... wierd shit...

**Comment by ilia-chelak** [comment]
Hello, I came across this issue as well but was able to solve it. In case it helps anyone in the future, this is how I done it:

Run sample scripts not from your `VideoProcessingFramework/` folder but from the `VideoProcessingFramework/install/bin` folder. Likewise, to use VPF in your scripts add `VideoProcessingFramework/install/bin` to the system path. Hope it helps, cheers!
