### ISSUE TITLE
Request for variable framerate videos support

### ISSUE THREAD

**Issue by Jie-Fang** [NVIDIA/VideoProcessingFramework#230]
Hi Roman,

VPF returns max framerate on videos have variable framerate which is inconsistent with ffprobe result.
Could you add features to support variable framerate videos?

**Comment by rarzumanyan** [comment]
Hi Jie,

Please check out `issue_230` branch, I've added `AvgFramerate() and `IsVFR()` methods:
https://github.com/NVIDIA/VideoProcessingFramework/blob/9dfa3ec87992c1360efcca9d05fd491c1be31abd/SampleDecode.py#L120-L139

I've checked it locally on one of VFR videos I have, works fine:
https://github.com/NVIDIA/VideoProcessingFramework/blob/9dfa3ec87992c1360efcca9d05fd491c1be31abd/Tests.py#L56-L59

produces output like follows:
```
framerate             :  60.0
avg framerate         :  51.136974037600716
has variable framerate:  True
```

**Comment by Jie-Fang** [comment]
Hi Roman,

It works well, thanks!

**Comment by rarzumanyan** [comment]
Thanks for the update.
Merged to `master`. Closing as fixed.
