### ISSUE TITLE
Feature request: Add seek by time stamp

### ISSUE THREAD

**Issue by Jie-Fang** [NVIDIA/VideoProcessingFramework#232]
Hi Roman,
Could you add a feature of seeking frame by time stamp. It can be used on variable frame rate videos.
Thanks!

**Comment by Jie-Fang** [comment]
Hi Roman,

Sorry for replying late.
I have tested this feature, it works well when I set the timestamp less than video duration. 
But if I set timestamp exceeds the video length, the VPF print `Failed to read frame: End of file` infinitely and can't kill the process(I run it in a docker container). FFmpeg will print the timestamp is invalid. So I think VPF should throw this info if the timestamp is invalid and stops executing.

**Comment by rarzumanyan** [comment]
Thanks for the update, @Jie-Fang 

You're right, there was a bug which caused decoder to flush in infinite loop. It's fixed and pushed to `issue_232`.
Following code now works fine and doesn't cause infinite loop:
```python
decoder = dec.NvDecoder(gpu_id, input, output, dec.InitMode.BUILTIN)

# Seeking for frame with timestamp of 65536 seconds which is more then input video length.
decoder.seek(seek_frame=65536, seek_mode=nvc.SeekMode.PREV_KEY_FRAME,
             seek_criteria=nvc.SeekCriteria.BY_TIMESTAMP)

decoder.decode(frames_to_decode = 256, verbose=True)
num_frames = decoder.dec_frames()
print (str(num_frames), ' frames decoded.')
```

Outputs:
```
Decoding on GPU 0
Seeking for the frame  65536
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
0  frames decoded.
Checking token allocation counters: No leaks dectected
```
In the end of decoding loop, decoder submits 5 empty frames because it's the size of queue, don't worry about that. It does not reconstruct a single frame as it's said in the output.

**Comment by Jie-Fang** [comment]
It's fixed and works well now, thanks Roman!

**Comment by rarzumanyan** [comment]
You're welcome!
Closing and fixed and merging to master.
