### ISSUE TITLE
BGR to RGB color conversion

### ISSUE THREAD

**Issue by dasing** [NVIDIA/VideoProcessingFramework#235]
I saw there is color conversion from RGB to BGR in rgb8_swapchannel, but BGR to RGB is not provided. I'm wondering if this feature could be provided or not.

**Comment by rarzumanyan** [comment]
Hi @dasing 

Please check out branch `issue_229`, it has bgr > rgb conversion. Let me know if it works fine, I'll merge to master then.

**Comment by dasing** [comment]
Hi @rarzumanyan 

Thanks you very much, the bgr to rgb conversion works fine! Besides, it's just a kind reminder that this branch should rebase the master branch.

**Comment by rarzumanyan** [comment]
Thanks for the update.
Closing as fixed.
