### ISSUE TITLE
which branch can support cuda10.2

### ISSUE THREAD

**Issue by git3210** [NVIDIA/VideoProcessingFramework#236]
**Describe the bug**
VideoProcessingFramework/PyNvCodec/TC/src/TasksColorCvt.cpp:115:15: error: ‘nppiNV12ToRGB_709CSC_8u_P2C3R_Ctx’ was not declared in this scope
I want to use VPF which support cuda 10.2, thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - Nvidia driver version
 - CUDA Version [e.g. 10.2]
 - Video Codec SDK Version [e.g. 9.1.23]
 - Python Version [e.g. 3.7]

**Additional context**

**Comment by rarzumanyan** [comment]
Hi @git3210 

As per project's wiki it's recommended to use latest CUDA version.

If your CUDA version doesn't have the `nppiNV12ToRGB_709CSC_8u_P2C3R_Ctx` function implemented, the only way to get away with it is to comment out this function call or put it under conditional compilation. However in that case MPEG BT709 NV12 > RGB color conversion will not be supported. 

NV12 > RGB conversion is a core feature so I'm not sure there's any recent VPF branch which doesn't have `nppiNV12ToRGB_709CSC_8u_P2C3R_Ctx`. If you use other frameworks like e. g. OpenCV you may work this around by doing nv12 > rgb or nv12 > yuv420 > rgb conversion with OpenCV. It will be slower, but it will work with legacy CUDA versions.
