### ISSUE TITLE
I want to decode frame with many policy，how to realize.

### ISSUE THREAD

**Issue by git3210** [NVIDIA/VideoProcessingFramework#238]
**Describe the bug**
I want to decode frame with many policy，how to realize.
For example: decode frame 1 second 1 frame. 
I use PyFFmpegDemuxer to demux packet and counter i to step some packet. with this method, I see some saved frame is so vague or damaged

if __name__ == "__main__":
    gpu_id = int(sys.argv[1])
    enc_filePath = sys.argv[2]
    decFilePath = sys.argv[3]

    nvDmx = nvc.PyFFmpegDemuxer(enc_filePath)
    nvDec = nvc.PyNvDecoder(nvDmx.Width(), nvDmx.Height(), nvDmx.Format(), nvDmx.Codec(), gpu_id)
    to_rgb = nvc.PySurfaceConverter(nvDmx.Width(), nvDmx.Height(), nvDmx.Format(), nvc.PixelFormat.YUV420, cuda_ctx.handle, cuda_str.handle)
    nvDwn = nvc.PySurfaceDownloader(nvDmx.Width(), nvDmx.Height(), nvCvt.Format(), cuda_ctx.handle, cuda_str.handle)
    packet = np.ndarray(shape=(0), dtype=np.uint8)

    i = 0
    while True:
        try:
            i += 1
            # demux + decoder
            if not nvDmx.DemuxSinglePacket(packet):
                break
            if i % 25 != 0:
                continue

            rawSurface = nvDec.DecodeSurfaceFromPacket(packet)
            if rawSurface.Empty():
                #print('No more video frames')
                continue

            # convert to rgb
            cvtSurface = to_rgb.Execute(rawSurface, None)
            if (cvtSurface.Empty()):
                print('Failed to do color conversion')
                break

            bgr = np.ndarray(shape=(cvtSurface.HostSize()), dtype=np.uint8)
            success = nvDwn.DownloadSingleSurface(cvtSurface, bgr)
 
            if not success:
                print('Failed to download surface', success)
                break

            bgr = bgr.reshape(nvDmx.Height(), nvDmx.Width(), 3)
            cv2.imwrite("tmp/"+str(i)+".jpg", bgr)
        except nvc.HwResetException:
            print('Continue after HW decoder was reset')
            continue
    print("count =============", i)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Nvidia driver version
 - CUDA Version 10.2
 - Video Codec SDK Version 9.1.23
 - Python Version 3.7

**Additional context**

**Comment by rarzumanyan** [comment]
Hi @git3210 

This approach:
```python
i = 0
while True:
    try:
        i += 1
        # demux + decoder
        if not nvDmx.DemuxSinglePacket(packet):
            break
        if i % 25 != 0:
            continue

        rawSurface = nvDec.DecodeSurfaceFromPacket(packet)
        if rawSurface.Empty():
            #print('No more video frames')
            continue
```
Will cause decoder to crash. 

There are data dependencies between video frames. E. g. frame 25 may require multiple previous video frames to be decoded (say, 21 and 23) because it uses pixels from frames 21 and 23 for inter-frame prediction.

If you want to go specific frame, you need to use `Seek()` method which is illustrated in SampleDecode.py and Tests.py. It will take care of mentioned inter-frame dependencies.
