### ISSUE TITLE
real-time frame encode/decode

### ISSUE THREAD

**Issue by wuyangzhang** [NVIDIA/VideoProcessingFramework#24]
Hi Roman, Thank you for the great work! Can you please provide a short example if I would like to encode and decode frames from cameras in real-time? Also, the frame size may change over the time. Should I always create a new encode instance for the change? Thank you!

**Comment by rarzumanyan** [comment]
Hi @wuyangzhang 

I've added a RTSP sample, check the latest commit. 
BTW you can also use SampleDecode for that as well, just replace input filepath with rtsp stream URL.

As for now, nvEncoder doesn't support reconfigure feature. 
So if you want to change encoding params you have to create new instance. 
On-the-fly encoder reconfigure is supported by underlying Video Codec SDK, it's just not implemented in VPF yet.

**Comment by wuyangzhang** [comment]
Thanks a lot @rarzumanyan for the sample code. It is really helpful! 
Also thank you for the suggestions of configuring the underlying video codec sdk. I am able to achieve the on-the-fly encoder now.

**Comment by rarzumanyan** [comment]
Hi @wuyangzhang 
You're welcome!
