### ISSUE TITLE
Decode Error!!!

### ISSUE THREAD

**Issue by cg82616424** [NVIDIA/VideoProcessingFramework#25]
File "SampleDecode.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: CUDA error with code -1No error string available

gcc version: Python 3.7.6
cuda info
     NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2
linux version: CentOS release 6.3 (Final)

**Comment by rarzumanyan** [comment]
Hi @cg82616424,

Filename and string number also should be in error message.
Can you please upload the full error message text & CMake configure output?

**Comment by cg82616424** [comment]
okay, 
first, RuntimeError: CUDA error with code -1No error string available, this is full error message
second, my build command:
`export PATH_TO_SDK=/home/work/videocodecsdk
export PATH_TO_FFMPEG=/home/work/ffmpeg
export CUDAHOSTCXX="/opt/compiler/gcc-8.2/bin/g++"
export CC=/opt/compiler/gcc-8.2/bin/gcc
export CXX=/opt/compiler/gcc-8.2/bin/g++
export CUDACXX=/home/work/cuda-10.2/bin/nvcc
export INSTALL_PREFIX=/home/work/VideoProcessingFramework/install
INSTALL_PREFIX=/home/work/VideoProcessingFramework/install
 mkdir -p install
 mkdir -p build
 cd build
 /home/work/cmake/cmake/bin/cmake ..  -DCMAKE_CUDA_HOST_LINK_LAUNCHER=/opt/compiler/gcc-8.2/bin/g++ -DFFMPEG_DIR:PATH=/home/work/ffmpeg -DVIDEO_CODEC_SDK_DIR:PATH=/home/work/videocodecsdk -DGENERATE_PYTHON_BINDINGS:BOOL="1" -DPYTHON_LIBRARY=/home/work/python/lib/libpython3.7m.a -DCMAKE_INSTALL_PREFIX:PATH=/home/work/VideoProcessingFramework/install -DCMAKE_INSTALL_OLDINCLUDEDIR=/opt/compiler/gcc-8.2/include -DPYTHON_EXECUTABLE=/home/work/python/bin/python3`
for some environment reason, I changed some path in /PyNvCodec/TC/CMakeLists.txt:
`set(CUDA_TOOLKIT_ROOT_DIR "/home/work/cuda-10.2")`
last , my cmake and make output:
[build.tar.gz](https://github.com/NVIDIA/VideoProcessingFramework/files/4430316/build.tar.gz)

**Comment by rarzumanyan** [comment]
Hi @cg82616424 

> first, RuntimeError: CUDA error with code -1No error string available, this is full error message

I've uploaded a patch which adds more verbose error messages. Can you update to latest version and try again to see where exactly error happens?
>my cmake and make output:

Please upload what CMake outputs to console, not the files that  were built.

**Comment by cg82616424** [comment]
my cmake output, and my export path infos:
thanks very much
+ export PATH_TO_SDK=/home/work/videocodecsdk
+ PATH_TO_SDK=/home/work/videocodecsdk
+ export PATH_TO_FFMPEG=/home/work/ffmpeg
+ PATH_TO_FFMPEG=/home/work/ffmpeg
+ export CUDAHOSTCXX=/opt/compiler/gcc-8.2/bin/g++
+ CUDAHOSTCXX=/opt/compiler/gcc-8.2/bin/g++
+ export CC=/opt/compiler/gcc-8.2/bin/gcc
+ CC=/opt/compiler/gcc-8.2/bin/gcc
+ export CXX=/opt/compiler/gcc-8.2/bin/g++
+ CXX=/opt/compiler/gcc-8.2/bin/g++
+ export CUDACXX=/home/work/cuda-10.2/bin/nvcc
+ CUDACXX=/home/work/cuda-10.2/bin/nvcc
+ export INSTALL_PREFIX=/home/work/VideoProcessingFramework/install
+ INSTALL_PREFIX=/home/work/VideoProcessingFramework/install
+ INSTALL_PREFIX=/home/work/VideoProcessingFramework/install
+ mkdir -p install
+ mkdir -p build
+ cd build
+ /home/work/cmake/cmake/bin/cmake .. -DCMAKE_CUDA_HOST_LINK_LAUNCHER=/opt/compiler/gcc-8.2/bin/g++ -DFFMPEG_DIR:PATH=/home/work/ffmpeg -DVIDEO_CODEC_SDK_DIR:PATH=/home/work/videocodecsdk -DGENERATE_PYTHON_BINDINGS:BOOL=1 -DPYTHON_LIBRARY=/home/work/python/lib/libpython3.7m.a -DCMAKE_INSTALL_PREFIX:PATH=/home/work/VideoProcessingFramework/install -DCMAKE_INSTALL_OLDINCLUDEDIR=/opt/compiler/gcc-8.2/include -DPYTHON_EXECUTABLE=/home/work/python/bin/python3
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /opt/compiler/gcc-8.2/bin/gcc
-- Check for working C compiler: /opt/compiler/gcc-8.2/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/compiler/gcc-8.2/bin/g++
-- Check for working CXX compiler: /opt/compiler/gcc-8.2/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Check for working CUDA compiler: /home/work/cuda-10.2/bin/nvcc
-- Check for working CUDA compiler: /home/work/cuda-10.2/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Searching for FFmpeg libs in /home/work/ffmpeg/lib
-- Searching for FFmpeg headers in /home/work/ffmpeg/include
-- Found PythonLibs: /home/work/python/lib/libpython3.7m.a (found suitable version "3.7.6", minimum required is "3.5")
-- Found PythonInterp: /home/work/python/bin/python3 (found version "3.7.6")
-- Found PythonLibs: /home/work/python/lib/libpython3.7m.a
-- pybind11 v2.3.dev0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/work/VideoProcessingFramework/build

**Comment by cg82616424** [comment]
> I've uploaded a patch which adds more verbose error messages. Can you update to latest version and try again to see where exactly error happens?

ok, I will try it later today

**Comment by cg82616424** [comment]
new version error messages:
Traceback (most recent call last):
  File "SampleDecode.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: /home/work/VideoProcessingFramework/PyNvCodec/src/PyNvCodec.cpp:61
CUDA error with code -1
No error string available

**Comment by rarzumanyan** [comment]
So the error happens at
```cpp
cuInit(0)
```
function call. It means the app struggles to initialize CUDA. However, -1 isn't a valid CUDA error code.
Give me some time, I'll try to reproduce it & will update you as I get answer.

BTW, do you have any issues with other CUDA applications or it's just VPF-specific problem?

**Comment by cg82616424** [comment]
I think it's just VPF-specific problem, I have a self build ffmpeg used cuda and nvdec/nvenc, it runs properly。
and i dont think it is a hardware problem, because I have 4 P4 card, I tried gpu index from 0 to 3, no one works.
>Give me some time, I'll try to reproduce it & will update you as I get answer.
when will you give me a new version?   days later or weeks later?

**Comment by cg82616424** [comment]
I have about 10 thousand P4 and V100 cards and a millions of videos to decode, this is a little urgent problem 🤣

**Comment by rarzumanyan** [comment]
Hi @cg82616424 ,
Please contact me via email displayed in my GitHub profile.

**Comment by rarzumanyan** [comment]
Got the feedback from user, loading libcuda.so and libnvcuvid.so from GPU driver and CUDA toolkit locations solved the issue. Closing.
