### ISSUE TITLE
Wrong resolution when decoding video

### ISSUE THREAD

**Issue by mfoglio** [NVIDIA/VideoProcessingFramework#251]
This simple code returns a numpy array:

```
import numpy as np
import PyNvCodec as nvc

rtsp_url = "....m3u8"
nvDec = nvc.PyNvDecoder(encFile, 0)

rawFrameYUV = np.ndarray(shape=(0), dtype=np.uint8)
success = nvDec.DecodeSingleFrame(rawFrameYUV)
```
The video is `1280x720` as confirmed by `nvDec.Height()` and `nvDec.Width()`. However, the `np_frame` has shape `(1382400,)` and `1382400 / 1280 / 720 = 1.5`. How is that possible?

I also tried to follow the wiki tutorial on RTSP stream with the same results.

I am looking for a public rtsp that you can use to reproduce the error. I don't have lots of experience with video decoding in rtsp so I hope it is a common issue and you'll know that answer already.

**Comment by rarzumanyan** [comment]
Hi @mfoglio 

please take a closer look at nv12 and yuv420 pixel format description, frame size is 1382400 = 1280x720 + 640x360 + 640x360 which is just what it should be.

**Comment by mfoglio** [comment]
So I need to decode the video using `nvc.PixelFormat.YUV420` or `nvc.PixelFormat.NV12` and then I need to convert it to RGB?

**Comment by rarzumanyan** [comment]
Hi @mfoglio 

Native pixel format for Nvdec is `nvc.PixelFormat.NV12` which can be converted to RGB.

>I can't find any example

There are multiple color conversion examples including very NV12 > RGB in sample python scripts. 
Please take a look at them. It's just 9 files altogether, I'm sure it won't take too long and be very helpful.

**Comment by mfoglio** [comment]
Yes, thank you. I got the example `SampleDecodeMultiThread` running on a `https://...m3u8` stream. However, with a rtsp stream with url starting as `rtsp://....` I got the error:
`rtsp @ 0x2c0b760] method SETUP failed: 461 Unsupported transport`.
Do you know what could possibly cause this?
I really appreciate your help

**Comment by rarzumanyan** [comment]
@mfoglio 

It means that your ffmpeg build (which is used to get encoded video packets from source file or over the network) doesn’t support the network protocol.
