### ISSUE TITLE
CudaContext and Cuda Stream is garbage collected while in use

### ISSUE THREAD

**Issue by riaqn** [NVIDIA/VideoProcessingFramework#254]
**Describe the bug**
Cuda Context and Cuda Stream are garbaged collected while being used by some decoder.

**To Reproduce**
Consider the following code:
```
class Dec:
    def __init__(self, ...):
        cuda_ctx = cuda.Device(gpuID).retain_primary_context()
        cuda_ctx.push()
        cuda_str = cuda.Stream()
        cuda_ctx.pop()
        self.nvDec = nvc.PyNvDecoder(width, height, format, codec, cuda_ctx.handle, cuda_str.handle)

    def decode(packet):
        self.nvDec.DecodeSurfaceFromPacket(packet)
```
After the `__init__` is finished, `cuda_ctx` and `cuda_str` is garbage collected, while still being used by `self.nvDec`. Further calling `decode` produces SIGSEGV.

**Expected behavior**
Inside `self.nvDec` there should be some reference to both `cuda_ctx` and `cuda_str`, so that they are not GC-ed.

**Desktop (please complete the following information):**
not relevant.

**Comment by riaqn** [comment]
Also a small comment: do you think it makes sense to move a lot of the wrapper functions (such as `DecodeFrameFromPacket`) to python, and keep only the core part in C++?

**Comment by rarzumanyan** [comment]
>After the `__init__` is finished, `cuda_ctx` and `cuda_str` is garbage collected

They are garbage collected because their lifetime come to an end as the control flow leaves the scope.
Make them class members:
https://github.com/NVIDIA/VideoProcessingFramework/blob/fad275347e24f017b9c4aec796806aa0a124b846/SampleDecodeMultiThread.py#L49-L60

**Comment by riaqn** [comment]
Yes I solved it using that - but still quite unusual from a python perspective - can you make it referenced by the decoder?

In python one usually don't have to worry about memory management - that's a major reason why python is easier than C++, and why this project is useful.

**Comment by rarzumanyan** [comment]
>can you make it referenced by the decoder?

I have no idea how to pass PyCuda objects to C++ land via pybind11.
Even if I make this possible I assume it will introduce dependencies against PyCuda C++ API with all the consequences.

**Comment by riaqn** [comment]
Sure - it's your call. In that case I guess some comment about keeping context and stream in scope should be added to some of the samples? :smiley:

**Comment by rarzumanyan** [comment]
@riaqn 

We're accepting PRs ;)
Feel free to add corresp. comments to the samples.
