### ISSUE TITLE
When is a python surface object invalidated?

### ISSUE THREAD

**Issue by riaqn** [NVIDIA/VideoProcessingFramework#255]
Is it valid as long as the object is in scope? Asking this because I hope to use GPU memory as cache; this is better than cache on CPU memory because transmitting the frames from GPU to CPU can be costy.

For example, can I have like 10 surfaces in the GPU at the same time, and decide to download some of them when I need them?

**Comment by rarzumanyan** [comment]
Hi @riaqn 

Most of VPF classes such as `PyNvDecoder` own the surfaces they return for the sake of best performance. So these `Surface`s will never be invalidated but may be reused upon next call. 

To avoid opaque memory re-use, one can clone them using `Surface.Clone` method which is combination of CUDA malloc and deep copy. Such surface behaves just as any regular Python object.

**Comment by riaqn** [comment]
HI @rarzumanyan  Thanks for the quick reply! 

I assume the cloning is done on the GPU, and the new copy will sit in GPU? Also how is the new Surface free-ed? By Python GC automatically?

**Comment by rarzumanyan** [comment]
Hi @riaqn 

>I assume the cloning is done on the GPU, and the new copy will sit in GPU?

There's no need to assume, you can see the actual sources and run VPF code in Nsight profiler to see what's happening on GPU side. Long story short: every `Buffer` lives in RAM, every `Surface` lives in vRAM. Hence CUDA API is used inside the `Surface` class to manage it's memory.

I encourage you to opt-in `USE_NVTX` CMake flag & see the application timeline in Nsight Systems. All VPF `Task`s are surrounded by NVTX markers. Take a look at [this post](https://github.com/NVIDIA/VideoProcessingFramework/issues/242#issuecomment-929986041) to see how to profile your python code.

>Also how is the new copy free-ed? By Python GC automatically?

Yes, pybind11 `take_ownership` policy is applied to cloned `Surface`, so it's lifetime is determined by python interpreter:
https://github.com/NVIDIA/VideoProcessingFramework/blob/fad275347e24f017b9c4aec796806aa0a124b846/PyNvCodec/src/PyNvCodec.cpp#L1852-L1864


If you like to track memory (de)allocations you can opt-in `TRACK_TOKEN_ALLOCATION` CMake option.

P. S.
Although VPF has a Python facet to it, it's a typical C/C++ project under the hood so it doesn't do anything behind your back. The best way to see how this or that component works is to inspect `PyNvCodec.cpp` as an entry point to C++ land.
