### ISSUE TITLE
cmake fails due to linker error

### ISSUE THREAD

**Issue by prabhat00155** [NVIDIA/VideoProcessingFramework#260]
I get linker error as cmake is trying to find libraries under `lib64` instead of `lib`. I can't find a flag to set this.
```
LIBRARIES=  "-L/home/prabhatroy/fbsource/fbcode/third-party-buck/platform010/build/cuda/bin/..//lib64/stubs" "-L/home/prabhatroy/fbsource/fbcode/third-party-buck/platform010/build/cuda/bin/..//lib64" 
...
/bin/ld: cannot find -lcudadevrt
/bin/ld: cannot find -lcudart_static
collect2: error: ld returned 1 exit status
```
I have set LD_LIBRARY_PATH.
```
echo $LD_LIBRARY_PATH
/home/prabhatroy/fbsource/fbcode/third-party-buck/platform010/build/cuda/lib:/home/prabhatroy/fbsource/fbcode/third-party-buck/platform010/build/cudnn/lib
```
This is an internal hardware and there are some restrictions with permissions, so I can't make a symlink called `lib64` work. Can someone help me with this? Thank you!

**Comment by rarzumanyan** [comment]
Hi @prabhat00155 

Did Docker build work for you?

**Comment by prabhat00155** [comment]
No, I couldn't use docker on internal hardware. However, I can close this issue as I was able to complete my task using NVDECODE API directly.
