### ISSUE TITLE
How to Extract (Raw or Encoded) Video Frames from any GPU Memory directly for Current Program?

### ISSUE THREAD

**Issue by mail2chromium** [NVIDIA/VideoProcessingFramework#263]
I have been working on `Camera Video Frame Capturing` for the past year. I am trying to make a video streaming plugin using `webrtc` and its associated technologies. I know that there are some certain plugins already in the market to stream video i.e. `PixelStreaming`. 

Recently, I came up with new research which is required in order to perform the following; 

> As the `latency` is the key factor in order to develop more reliable
> streaming plugins. So, I was trying my best to optimize every process
> running during *Camera Video Frame Capturing*. I am also trying to reduce the number
> of extra hops during this procedure.

----------

This current system which I have developed is working `100` percent **fine without any crash** as you can see here;

[![enter image description here][2]][2]

My concerning point here is that Is there any possibility that I can extract camera video frames either `RAW` or `Encoded` from GPU directly?

As I want to run `Camera` using GPU i.e. `Nvidia GPU (GTX GEFORCE)` and I can get some details using a Python module for getting the GPU status from NVIDIA GPUs using Nvidia-SMI programmatically in Python. But It does not give me any access to get, fetch or extract video frames of that Camera running on GPU. 

----------

**Simple Example:**

As an example, let's take an example of a simple camera and its frames being processed by `GPU` instead of `CPU` such as;

[![enter image description here][3]][3]

I have visited this pretty cool answer:

- [Lowest overhead camera to CPU to GPU approach on android][4]

> As far as the `Nvidia Encoder` is concerned, I have also worked with
> this pretty cool encoder and successfully managed to encode raw video
> frames using `NvEnc`. I am also aware of its C/C++ implementation
> directly.

Let's take another very simple example. I have tried to allocate memory in GPU using `cudaMalloc` CUDA C++ Programming. I am also able to copy allocated GPU memory into Host Program using `cudaMemcpy` such as;

    int main()
    {
        const unsigned int N = 1048576;
        const unsigned int bytes = N * sizeof(int);
        int *h_a = (int*)malloc(bytes);
        int *d_a;
        cudaMalloc((int**)&d_a, bytes);
    
        memset(h_a, 0, bytes);
        cudaMemcpy(d_a, h_a, bytes, cudaMemcpyHostToDevice);
        cudaMemcpy(h_a, d_a, bytes, cudaMemcpyDeviceToHost);
    
        return 0;
    }

Is there any `plugin`, `module`, `library`, or some piece of advice someone can give me about extracting frames directly from GPU without taking frames from Camera every time for the **current running process/program**.?

  [1]: https://i.stack.imgur.com/oveFI.png
  [2]: https://i.stack.imgur.com/sKboq.jpg
  [3]: https://i.stack.imgur.com/dOJ6q.jpg
  [4]: https://stackoverflow.com/a/37513328/10413749

**Comment by mail2chromium** [comment]
Thank you so much for the nice explanation of this topic @rarzumanyan. It's really helpful and appreciated.

> I have managed to edit my question again. I know my question was off-topic but your guidance was a huge help for me. 

Actually, I was looking for a solution that If my program is running on GPU then I can transfer Data from Host to GPU memory and from GPU memory to Host Program again. I know that we cannot access the GPU memory of other running processes on GPU. It would be a security breach that GPU providers won't allow me. 

I have tried to allocate memory in GPU using `cudaMalloc` CUDA C++ Programming. I am also able to copy allocated GPU memory into the Host Program using `cudaMemcpy`. 

> But I will continue my research to find some more possible ways or robust approaches to obtain what is required.


It's working fine. Thanks for your help.

**Comment by npkhgl** [comment]
Hi, it's nice to find this issue. I have some troubles about GPU memory copy. 
`rgb24.PlanePtr().Export(surface_tensor.data_ptr(), w * 3, gpuID) # this works fine for me`
However, when I tried to use `pycuda` to perform the GPU memory copy, it **failed**. The codes I used:
`import pycuda.autoinit
 import pycuda.driver as cudrv
 texbufs_memcpy = cudrv.Memcpy2D()
 # texbufs_memcpy.width_in_bytes = w * 3
 texbufs_memcpy.width = w * 3
 # texbufs_memcpy.height = h
 texbufs_memcpy.set_src_device(rgb24.PlanePtr().GpuMem())
 texbufs_memcpy.set_dst_device(surface_tensor.data_ptr())
 texbufs_memcpy(aligned=True)`  
Could you give me some help? Thanks a lot.
