### ISSUE TITLE
Cant Build on windows

### ISSUE THREAD

**Issue by acschristoph** [NVIDIA/VideoProcessingFramework#267]
Hey Guys,

I am very interrested to try out the python bindings, but I cant build it. 
Hope and looking forrward that you guys can help me.

**Describe the bug**
When I try to build PyNvCodec there are a lots of erros.

Errors on build are:
syntax error: module                                       (numpy.h:194)
'm': undeclared identifier                                (numpy.h:195)
'c: cannot be used before it ist initialized       (numpy.h:197)
'DecodeContext': designated initialization can only be used to initialize aggregate class types 
etc...

**To Reproduce**
Follow the wiki build instructions for windows.
After starting visual studio change project c++ to latest.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8537032/139521548-c4a8babf-6d59-4549-b465-378e92e4d876.png)
![image](https://user-images.githubusercontent.com/8537032/139521553-8dd53fff-40e8-460e-8144-6dc602af7b2d.png)
![image](https://user-images.githubusercontent.com/8537032/139521563-581c3fe9-b9cf-4c3e-873d-f9b87e2a884d.png)

**Desktop:**
 - Windows 10
 - Visual Studio 2019, 16.8.6
 - Driver: Latest
 - CUDA Version 11.5.0_496.13_win10
 - Video Codec SDK Version 11.1.5
 - Python Version 3.10.0

Thanks

**Comment by rarzumanyan** [comment]
Hi @acschristoph 

There was an issue with `DecodeContext` assignment which was fixed in #266 .
After that was fixed, VPF now builds fine under Windows (at least on the testing machine I use).
Could you please get latest `master` ToT and try again? Please LMK if you still have issues after that.

**Comment by acschristoph** [comment]
Hi @rarzumanyan 

Thank you after fetching new master it works, but I have to downgrade my python version to 3.9.7

with 3.10 there was an error during build that looks after googling realeted to python version 3.10

Error: 'ssize_t': undeclared identifier 

br

**Comment by rarzumanyan** [comment]
Hi @acschristoph 

>Error: 'ssize_t': undeclared identifier

Please provide more details, where does this error happens etc.

**Comment by RobertAtQuestacon** [comment]
This seemed like the right place to comment, correct me if I'm wrong.
I've managed to build for Windows 10 using the wiki advice, but I tried remove the requirement for pytorch, as I only need to decode and display frames from video.
Here is the build line I used:
`cmake .. -G"Visual Studio 16 2019" -A"x64" -DFFMPEG_DIR:PATH="C:\Users\User\Documents\Visual Studio 2019\Projects\Nivdia\ffmpeg-n5.0-latest-win64-gpl-shared-5.0\ffmpeg-n5.0-latest-win64-gpl-shared-5.0" -DVIDEO_CODEC_SDK_DIR:PATH="C:\Users\User\Documents\Visual Studio 2019\Projects\Nivdia\Video_Codec_SDK_11.1.5\Video_Codec_SDK_11.1.5" -DGENERATE_PYTHON_BINDINGS:BOOL="1" -DGENERATE_PYTORCH_EXTENSION:BOOL="0"  -DCMAKE_INSTALL_PREFIX:PATH=..`
I then opened Video_Processing_Framework.sln and selected the INSTALL project to build. I get repeated errors that I believe all relate to the first error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2143	syntax error: missing ';' before '*'	TC	C:\Users\User\Documents\Visual Studio 2019\Projects\Nivdia\VideoProcessingFramework-master\VideoProcessingFramework-master\PyNvCodec\TC\inc\FFmpegDemuxer.h	158	
Warning	C4267	'=': conversion from 'size_t' to 'uint32_t', possible loss of data	TC	C:\Users\User\Documents\Visual Studio 2019\Projects\Nivdia\VideoProcessingFramework-master\VideoProcessingFramework-master\PyNvCodec\TC\src\MemoryInterfaces.cpp	500	
Warning	C4251	'VPF::NvEncoderClInterface::options': class 'std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<const std::string,std::string>>>' needs to have dll-interface to be used by clients of class 'VPF::NvEncoderClInterface'	TC	C:\Users\User\Documents\Visual Studio 2019\Projects\Nivdia\VideoProcessingFramework-master\VideoProcessingFramework-master\PyNvCodec\TC\inc\NvCodecCLIOptions.h	58	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	TC	C:\Users\User\Documents\Visual Studio 2019\Projects\Nivdia\VideoProcessingFramework-master\VideoProcessingFramework-master\PyNvCodec\TC\inc\FFmpegDemuxer.h	158	
Error	C2238	unexpected token(s) preceding ';'	TC	C:\Users\User\Documents\Visual Studio 2019\Projects\Nivdia\VideoProcessingFramework-master\VideoProcessingFramework-master\PyNvCodec\TC\inc\FFmpegDemuxer.h	158	
W` 
I've tried modifying the file, but I don't actually understand what is wrong with line 158:
`AVBSFContext *bsfc_annexb = nullptr, *bsfc_sei = nullptr;
`

**Comment by gedoensmax** [comment]
@RobertAtQuestacon did you resolve the issue and if so what was the issue ? If there is still help needed i can try to investigate this further otherwise i would like to close the issue.

**Comment by RobertAtQuestacon** [comment]
Hi Maximilian,
No solution, so I switched to using a Nvidia CUDA example as the basis for our application.
Yes, you can close the issue, thank you.
Regards
RobertAtQuestacon
UNOFFICIAL
