### ISSUE TITLE
ImportError: No module named torch.utils.cpp_extension

### ISSUE THREAD

**Issue by create-li** [NVIDIA/VideoProcessingFramework#268]
**Describe the bug**
**An error is reported when compiling, and the error content is as follows**
`File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
CMakeFiles/PytorchNvCodec.dir/build.make:72: recipe for target 'Pytorch_Nv_Codec' failed`

I refer to the installation tutorial on the [wiki，](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source)

**My configuration is as follows**：
` sudo cmake .. \
  -DFFMPEG_DIR:PATH=/home/soft/FFmpeg-master/build_x64_release_shared \
  -DVIDEO_CODEC_SDK_DIR:PATH=/home/soft/Video_Codec_SDK_11.1.5 \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DGENERATE_PYTORCH_EXTENSION:BOOL="1" \
  -DPYBIND11_INSTALL:BOOL="1" \
  -DPYTHON_LIBRARY=/home/lyq/anaconda3/lib/python3.8 \
  -DPYTHON_INCLUDE_DIR=/home/lyq/include/python3.8 \
  -DPYTHON_EXECUTABLE=/home/lyq/anaconda3/bin/python3.8 \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"`

**Desktop (please complete the following information):**
 - OS: Linux
 - Nvidia driver version
 - CUDA Version  11.2
 - Video Codec SDK Version  Video_Codec_SDK_11.1.5
 - Python Version 3.8

**I tried the answers to the previous questions and there is no effective solution**

**Comment by rarzumanyan** [comment]
Hi @create-li 

As your error log say, please install `torch.utils.cpp_extension`.
Without that you can't build `PytorchNvCodec` which is Torch C++ extension.

**Comment by create-li** [comment]
HI @rarzumanyan 
I  have installed torch1.8,as follows:
`>>> import torch
>>> from setuptools import setup
>>> from torch.utils.cpp_extension import BuildExtension, CUDAExtension
>>> 
`
But the error result is the same.

**Comment by rarzumanyan** [comment]
@create-li 

If you have multiple Python interpreters installed on you machine (e. g. multiple Python versions) please make sure the version which is used for VPF build has the `torch.utils.cpp_extension` installed.

**Comment by mfoglio** [comment]
Hi @create-li , I experienced before a similar problem. I am not an expert, and what I am telling you might be wrong, but you probably have specified a wrong `DPYTHON_LIBRARY` path.
I used this to setup VPF:
```
cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DGENERATE_PYTORCH_EXTENSION:BOOL="1" \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" \
  -DPYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so \
  -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 \
  -DPYTHON_EXECUTABLE=/home/ubuntu/pycharm/venv/bin/python3
```
I don't know where you would find `libpython3.8.so` with anaconda. Try to run `sudo find / -name libpython3.8.so` and then replace the value of `DPYTHON_LIBRARY` accordingly.

**Comment by create-li** [comment]
The virtual environment configuration using conda has failed all the time. Finally, it can succeed without anaconda env. 
  sudo cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG"  \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DGENERATE_PYTORCH_EXTENSION:BOOL="1" \
  -DPYBIND11_INSTALL:BOOL="1" \
  -DPYTHON_INCLUDE_DIR=/usr/include/python3.6  \
  -DPYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so \
   -DPYTHON_EXECUTABLE=//usr/bin/python3 \
  -DCMAKE_INSTALL_PREFIX:PATH="$(pwd)/install"
