### ISSUE TITLE
PyTorch extension fails to build (permission denied error)

### ISSUE THREAD

**Issue by dbermond** [NVIDIA/VideoProcessingFramework#270]
**Describe the bug**
The PyTorch extension fails to build on a GNU/Linux system for me (and possibly on other UNIXes), giving a permission denied error:

```
g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fno-semantic-interposition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/opt/cuda/lib64 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/PytorchNvCodec.o -L/usr/lib/python3.9/site-packages/torch/lib -L/opt/cuda/lib64 -L/usr/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o /usr/bin/PytorchNvCodec.cpython-39-x86_64-linux-gnu.so
/usr/bin/ld: cannot open output file /usr/bin/PytorchNvCodec.cpython-39-x86_64-linux-gnu.so: Permission denied
collect2: error: ld returned 1 exit status
error: command '/usr/bin/g++' failed with exit code 1
make[2]: *** [CMakeFiles/PytorchNvCodec.dir/build.make:73: Pytorch_Nv_Codec] Error 1
```

This is happening because the `CMakeLists.txt` file is configured to output the PyTorch extension directly to the  `${CMAKE_INSTALL_PREFIX}/bin` directory. `CMAKE_INSTALL_PREFIX` is not typically used for placing the produced outputs, but mostly for installing files during an install stage. The default path for `CMAKE_INSTALL_PREFIX` is typically write protected on GNU/Linux systems and other UNIXes (`/usr/local`), and many package maintainers use write protected paths on it.

**To Reproduce**
```
$ git clone https://github.com/NVIDIA/VideoProcessingFramework.git
$ export CUDAToolkit_ROOT='/opt/cuda'
$ export CXXFLAGS+=' -I/opt/cuda/include'
$ export  LDFLAGS+=' -L/opt/cuda/lib64'
$ cmake -B build -S VideoProcessingFramework \
        -DCMAKE_BUILD_TYPE:STRING='None' \
        -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
        -DCMAKE_CUDA_COMPILER:FILEPATH='/opt/cuda/bin/nvcc' \
        -DCMAKE_SKIP_RPATH:BOOL='YES' \
        -DGENERATE_PYTHON_BINDINGS:BOOL='TRUE' \
        -DGENERATE_PYTORCH_EXTENSION:BOOL='TRUE' \
        -DVIDEO_CODEC_SDK_INCLUDE_DIR:PATH='/usr/include/nvidia-sdk' \
        -Wno-dev
$ make -C build
```

The same error also happens when omitting `-DCMAKE_INSTALL_PREFIX`, since it defaults to the write protected path `/usr/local`.

**Expected behavior**
The build process to complete without errors, including the PyTorch extension.

**Screenshots**
Not applicable. Terminal only.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Nvidia driver version: 495.44
 - CUDA Version: 11.4.2
 - Video Codec SDK Version: 11.1.5
 - Python Version: 3.9.7
 - python-pytorch-cuda: 1.10.0
 - Compiler: gcc 11.1.0
 - CMake: 3.21.4

**Additional context**
This can be fixed with the following patch:

```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -66,9 +66,13 @@ if(GENERATE_PYTORCH_EXTENSION)
 	#Extension will be built using torch.utils.cpp_extension;
 	#So we just launch python script;
 	add_custom_command(	OUTPUT Pytorch_Nv_Codec
-						COMMAND cd ${PYTORCH_EXTENSION_SOURCES_DIR} && python setup.py build --build-lib="${CMAKE_INSTALL_PREFIX}/bin")
+						COMMAND cd ${PYTORCH_EXTENSION_SOURCES_DIR} && python setup.py build --build-lib="${CMAKE_CURRENT_BINARY_DIR}/PytorchNvCodec")
 
 	add_custom_target(	PytorchNvCodec
 						DEPENDS Pytorch_Nv_Codec)
 	add_dependencies(PyNvCodec PytorchNvCodec)
+	
+	find_package(Python REQUIRED)
+	execute_process(COMMAND python-config --extension-suffix OUTPUT_VARIABLE PYTHON_EXTENSION_SUFFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
+	install(FILES ${CMAKE_CURRENT_BINARY_DIR}/PytorchNvCodec/PytorchNvCodec${PYTHON_EXTENSION_SUFFIX} DESTINATION bin)
 endif(GENERATE_PYTORCH_EXTENSION)

```

If this patch is suitable, I can open a pull request.

Note: setted `DESTINATION` as `bin` to follow the other paths on `CMakeLists.txt`. A better place would be `${Python_SITEARCH}`.

**Comment by rarzumanyan** [comment]
Hi @dbermond,
Thanks for bringing this up.

>If this patch is suitable, I can open a pull request.

Please go ahead and submit a PR.

>Note: setted `DESTINATION` as bin to follow the other paths on CMakeLists.txt. A better place would be `${Python_SITEARCH}`.

I think this shall be done, but a bit later.
In the end of the day I'd like to have VPF as "proper" Python module to allow for IDE syntax highlight etc. 
Hadn't discovered how to do that with pybind11 yet.

**Comment by dbermond** [comment]
Thank you for the reply.

Pull request created.

**Comment by rarzumanyan** [comment]
@dbermond 

Unfortunately, new `CMakeLists.txt` causes installation issues.
Output on my Kubuntu 20.04 machine with python 3.8.10:

```bash
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/libTC_CORE.so
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/libTC.so
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/PyNvCodec.cpython-38-x86_64-linux-gnu.so
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SampleDecode.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SampleEncode.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SampleDecodeSw.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SampleDecodeMultiThread.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SampleEncodeMultiThread.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SampleDemuxDecode.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SamplePyTorch.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SampleTensorRTResnet.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/SampleTorchResnet.py
-- Installing: /home/roman/Git/VideoProcessingFramework/install/bin/Tests.py
CMake Error at cmake_install.cmake:93 (file):
  file INSTALL cannot find
  "/home/roman/Git/VideoProcessingFramework/build/PytorchNvCodec/PytorchNvCodec":
  No such file or directory.
```

I suppose this happens because `PYTHON_EXTENSION_SUFFIX` isn't defined.

**Comment by dbermond** [comment]
It works fine for me on Arch Linux.

The `PYTHON_EXTENSION_SUFFIX` variable is not being populated. Or `python-config` is not installed, or it's not giving any output for `--extension-suffix`. On Arch Linux, `pyhon-config` is installed alongside with the python package, but on Ubuntu it mostly requires extra packages.

Could you please try to change `find_package(Python REQUIRED)` to `find_package(Python 3.4 COMPONENTS Interpreter REQUIRED)`, and also change `python-config --extension-suffix` to `python -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))"` and test again? This also works fine for me on Arch Linux. Do you want me update the pull request with these changes for another shot?

**Comment by rarzumanyan** [comment]
@dbermond 

>Do you want me update the pull request with these changes for another shot?

Yes, please.
I've changed target branch to `pr_271`, so feel free to submit more PR targeting it.

**Comment by dbermond** [comment]
I ask for a reopen of this issue.

The issue still persists, as the commits that fixed it were reverted.

Current output:
```
/usr/bin/ld: cannot open output file /usr/PytorchNvCodec.cpython-310-x86_64-linux-gnu.so: Permission denied
```

**Comment by OmkarShidore** [comment]
I had the same issue
`/usr/bin/ld: cannot open output file /usr/PytorchNvCodec.cpython-310-x86_64-linux-gnu.so: Permission denied`

as `/usrbin` has write permission for root user only, so changing the `CMAKE_INSTALL_PREFIX` works fine.

Fixed it by doing the following steps

`cd VideoProcessingFramework`
`mkdir -p build`
`mkdir -p install`
`cd install`
``export $INSTALL_PREFIX=`pwd` ``
`cd ../build`

Now while cmake use `-DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"`
