### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by heathcliffYang** [NVIDIA/VideoProcessingFramework#277]
I wrote a simple code to compare this framework performance with OpenCV's VideoCapture():
read 5 min video,  VideoProcessingFramework takes 12.4 sec while OpenCV takes 16.1 sec.
I wonder how much faster is this framework than OpenCV? Does this meet your expectation? Or is there any facility I haven't used properly?

Thank you!

* VideoProcessingFramework
```python
def decode(gpuID, encFilePath):

    nvDmx = nvc.PyFFmpegDemuxer(encFilePath)
    nvDec = nvc.PyNvDecoder(nvDmx.Width(), nvDmx.Height(), nvDmx.Format(), nvDmx.Codec(), gpuID)#, cuda_ctx.handle, cuda_str.handle)
    nvCvt = nvc.PySurfaceConverter(nvDmx.Width(), nvDmx.Height(), nvDmx.Format(), nvc.PixelFormat.YUV420, gpuID)#, cuda_ctx.handle, cuda_str.handle)
    nvDwn = nvc.PySurfaceDownloader(nvDmx.Width(), nvDmx.Height(), nvCvt.Format(), gpuID)#, cuda_ctx.handle, cuda_str.handle)

    packet = np.ndarray(shape=(0), dtype=np.uint8)
    frameSize = int(nvDmx.Width() * nvDmx.Height() * 3 / 2)
    rawFrame = np.ndarray(shape=(frameSize), dtype=np.uint8)
    pdata_in, pdata_out = nvc.PacketData(), nvc.PacketData()

    # Determine colorspace conversion parameters.
    # Some video streams don't specify these parameters so default values
    # are most widespread bt601 and mpeg.
    cspace, crange = nvDmx.ColorSpace(), nvDmx.ColorRange()
    if nvc.ColorSpace.UNSPEC == cspace:
        cspace = nvc.ColorSpace.BT_601
    if nvc.ColorRange.UDEF == crange:
        crange = nvc.ColorRange.MPEG
    cc_ctx = nvc.ColorspaceConversionContext(cspace, crange)
    print('Color space: ', str(cspace))
    print('Color range: ', str(crange))

    while True:
        # Demuxer has sync design, it returns packet every time it's called.
        # If demuxer can't return packet it usually means EOF.
        if not nvDmx.DemuxSinglePacket(packet):
            break

        # Get last packet data to obtain frame timestamp
        nvDmx.LastPacketData(pdata_in)

        raw_w, raw_h = nvDmx.Width(), int(nvDmx.Height() * 3 / 2)

        # Decoder is async by design.
        # As it consumes packets from demuxer one at a time it may not return
        # decoded surface every time the decoding function is called.
        surface_nv12 = nvDec.DecodeSurfaceFromPacket(pdata_in, packet, pdata_out)
        if not surface_nv12.Empty():
            surface_yuv420 = nvCvt.Execute(surface_nv12, cc_ctx)
            if surface_yuv420.Empty():
                break
            if not nvDwn.DownloadSingleSurface(surface_yuv420, rawFrame):
                break

            rawFrame = rawFrame.reshape((raw_h, raw_w))
            yuv420_mat = cv2.cvtColor(rawFrame, cv2.COLOR_YUV2BGR_I420)
```

* OpenCV
```python
cap = cv2.VideoCapture(encFilePath)
while True:
    ret_val, img = cap.read()
    if not ret_val:
        break
cap.release()
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Nvidia driver version: 455.32.00
 - CUDA Version: 11.1
 - Video Codec SDK Version: 11.1.5
 - Python Version: 3.8.8
 - CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

**Comment by rarzumanyan** [comment]
Hi @heathcliffYang 

A good place to start would be to take a look at this page in project's [wiki](https://github.com/NVIDIA/VideoProcessingFramework/wiki/VPF-Performance-analysis).

>Does this meet your expectation?

Performance expectation for the VPF is to max out the HW performance. I don't know if this is purpose of your code.
If you're looking for a benchmark, then code shall be stripped out of color conversion, Device <> Host memory transfer and many more as it's illustrated in wiki.

>Or is there any facility I haven't used properly?

It solely depends on the problem you're addressing with your code.\
If you aim on VPF <> OpenCV interoperability, the code LGTM. There's a CUDA support to OpenCV however, so you can squeeze extra speed if you use GPU-side `Mat` instances and avoid Device <> Host memory copies. 

But once again - more information is needed.

**Comment by heathcliffYang** [comment]
Thank you for your quick reply. I'm sorry to miss this important page in wiki. Now I'm reading it.

In my case, it will be better if GPU could do the decoding and color conversion. I have read your article in this [link](https://developer.nvidia.com/blog/vpf-hardware-accelerated-video-processing-framework-in-python/), `pySurfaceConverter` supports NV12 to RGB, it's what I need.
GPU-side `Mat` is a good enhancement and I will do it later.

I encountered segmentation fault when running `SampleDecodeMultiThread.py`. Is it similar with issue #219? Should I use multi-processing instead?

**Comment by rarzumanyan** [comment]
Hi @heathcliffYang 

Absolutely NP, you're welcome.

>I encountered segmentation fault when running SampleDecodeMultiThread.py

There was an issue #275 where `SampleDecodeMultiThread.py` was seg-faulting but it's now fixed, please try the latest `master` code.

**Comment by heathcliffYang** [comment]
Hi, I pulled a new commit `e185794` and built it.
Segmentation fault has been fixed. However I ran a test case, different from `SampleDecodeMultiThread.py` : n threads read n videos concurrently. 
```python
from multiprocessing.dummy import Pool as ThreadPool

p = ThreadPool(2)
# videos is list of 2 video names
p.map(decode, videos)
```
Execution time in multi-threading program seems to be n times longer than single-thread one. (10.8 sec vs. 5.8 sec)

**Comment by rarzumanyan** [comment]
@heathcliffYang 

A good place to start would be to make a minimal change to `SampleDecodeMultiThread.py` so that each thread takes it's own video file as function argument.

**Comment by heathcliffYang** [comment]
Hi, I use `SampleDecodeMultiThread.py` to read the same video.
If I pass 1 to `$num_threads` and it takes about 5.5 sec; I pass 2 to `$num_threads` and it takes about 10.6 sec.

Would it be possible that some resources/codes are locked and it takes nearly all time in thread's task?

Following is a bit output:
- num_threads = 2
```
4200
4200
4260
4260
4320
4320
4380
4380
4440
4440
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
No more video frames
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
No more video frames
10.621599674224854
```
- num_threads = 1
```
4080
4140
4200
4260
4320
4380
4440
Failed to read frame: End of file
Failed to read frame: End of file
Failed to read frame: End of file
No more video frames
5.479534864425659
```

**Comment by rarzumanyan** [comment]
@heathcliffYang 

What GPU do you use?

**Comment by heathcliffYang** [comment]
My gpu is GeForce RTX 3070.
```
# threads = 5
real	0m10.781s
user	0m6.167s
sys	0m1.989s
# threads = 1
real	0m5.572s
user	0m2.839s
sys	0m1.397s
```

**Comment by rarzumanyan** [comment]
According to [Nvdec support matrix](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) your GPU has 1 Nvdec chip.

Run `nvidia-smi dmon` in parallel with `python3 ./SampleDecodeMultiThread.py 0 /path/to/your/video 1` and check Nvdec utilization. Most probably it will be maxed out. If so, `SampleDecodeMultiThread.py` maxes out your Nvdec in single threaded mode and second thread will not increase Nvdec utilization, hence will not bring any acceleration.

**Comment by heathcliffYang** [comment]
Yes, you're right! The former impulse belongs to threads = 1 while the later one belongs to threads = 2.
Case threads = 1 has maxed out the Nvdec.
```
# gpu   pwr gtemp mtemp    sm   mem   enc   dec  mclk  pclk
# Idx     W     C     C     %     %     %     %   MHz   MHz
    0    18    46     -     6     4     0     0   405   210
    0    18    46     -     6     4     0     0   405   210
    0    18    46     -     6     4     0     0   405   210
    0    18    46     -    12     5     0     0   405   210
    0    18    46     -    13     4     0     0   405   210
    0    18    46     -    17     5     0     0   405   210
    0    65    50     -    28    11     0   100  6800  1980
    0    82    50     -    28    11     0   100  6800  1980
    0    82    51     -    28    11     0   100  6800  1995
    0    83    51     -    28    11     0   100  6800  1995
    0    83    51     -    28    11     0   100  6800  1995
    0    66    50     -     1     0     0     0  7000  1995
    0    57    49     -     1     0     0     0  5000   870
    0    28    48     -     4     2     0     0   810   570
    0    58    51     -    29    11     0   100  6800  1995
    0    83    52     -    28    11     0   100  6800  1995
    0    83    52     -    27    11     0   100  6800  1995
    0    83    52     -    27    11     0   100  6800  1995
    0    84    53     -    28    11     0   100  6800  1995
    0    84    53     -    26    11     0   100  6800  1995
    0    83    53     -    26    11     0   100  6800  1995
    0    83    53     -    26    11     0   100  6800  1995
    0    83    53     -    27    11     0   100  6800  1995
    0    84    54     -    27    11     0   100  6800  1995
```

In this case of reading multiple videos, I also used 2 x Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz to run the OpenCV's VideoCapture() in multi-thread and it's faster than I use my GPU to decode in multi-thread.

So is it proper to say that my gpu's Nvdec chip cannot afford multi-thread decoding?

Thank you very much!

**Comment by rarzumanyan** [comment]
>So is it proper to say that my gpu's Nvdec chip cannot afford multi-thread decoding?

It does, you can decode multiple videos simultaneously.

You may think of Nvdec as a single-core processor which decodes videos instead of running your C code. You can have multiple decoding sessions, but they will not run in parallel. E. g. if Nvdec decodes 1080p video at 400 FPS you may run 4 1080p sessions 100 FPS each. Beside that, if you take a lower resolution video, one thread may not be enough to max out Nvdec.

Other cards have up to 5 Nvdec units per GPU chip which will be some sort of equivalent to 5-core processor.

>I also used 2 x Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz to run the OpenCV's VideoCapture() in multi-thread and it's faster than I use my GPU to decode in multi-thread.

RTX 3070 is a gaming GPU, it only has a single Nvdec. Professional-grade cards like Teslas and Quadros usually have 2+ Nvdec units per GPU chip and can process at least twice more video streams. Your GPU will shine if you add more CUDA processing like color conversion, resize, ML inference and many more.

**Comment by heathcliffYang** [comment]
Putting this type of GPU in the right place, such as NN inference, it really impresses me. And for the need of decoding multiple videos at the same time, I should use more suitable series of GPUs.

I will close this issue and truly appreciate your detailed explanation!
