### ISSUE TITLE
How can I get frame metadata by VPF?

### ISSUE THREAD

**Issue by woodenwatcher** [NVIDIA/VideoProcessingFramework#28]
The metadata such as "pts"

**Comment by rarzumanyan** [comment]
Hi @woodenwatcher 

It's not implemented in current API, decoder returns only reconstructed pixels.
There are no fundamental limitations on returning PTS / DTS and other metadata, it's just not done yet.

**Comment by woodenwatcher** [comment]
Are there any development plans to support this in the near future?

**Comment by rarzumanyan** [comment]
Currently there are no such plans.

**Comment by riaqn** [comment]
Hi @rarzumanyan - is there any news on this feature? This project is super useful, but without surface/packet metadata such as PTS my application can't make good use of the pixels...

**Comment by rarzumanyan** [comment]
Hi @riaqn 

It was actually implemented some time ago, you can see it in `SampleDecode.py`:
https://github.com/NVIDIA/VideoProcessingFramework/blob/fad275347e24f017b9c4aec796806aa0a124b846/SampleDecode.py#L200-L236

**Comment by riaqn** [comment]
@rarzumanyan Thanks for the quick reply. It seems in this example, we are simply printing the packet dts? But in the case of B-frames, frames might be in different order than packets, right? 

Maybe I should just simply describe the goal I try to achieve - I want to acquire the pixels of a frame of certain PTS. I use PyAV to demux, and pass packets to VPF. The packets will have DTS and PTS provided by PyAV, which is lost in the frames given by VPF. Therefore I simply don't know which frame given by VPF is the one I need.

**Comment by rarzumanyan** [comment]
Hi @riaqn 
I recommend you to _actually_ run the sample, it answers the _exact_ questions you are asking.

>It seems in this example, we are simply printing the packet dts?

No, we are not. 
By looking at the lines I'm referencing one may assume decoder returns some data related to decoded frame:
https://github.com/NVIDIA/VideoProcessingFramework/blob/fad275347e24f017b9c4aec796806aa0a124b846/SampleDecode.py#L231-L236


>The packets will have DTS and PTS provided by PyAV, which is lost in the frames given by VPF. 

I'm curious how did you come to such conclusion, but that's not true. If decoder returns pts and dts it clearly means they are not lost.

**Comment by riaqn** [comment]
Can I assume that if I run this program, the PTS printed might be out of order?

**Comment by riaqn** [comment]
Thank you @rarzumanyan yes, indeed after running the sample I have a better understanding. So it seems that if I use the builtin demuxer, the packet_data is given by `DecodeSingleFrame` and will match the frame that returns, and therefore packet_data.pts will be in order. But if I use standalone demuxer, the packet_data is given by the demuxer and pts will be out of order.

Question: Is it possible to get the pts of frames if I use standalone demuxer such as pyav?

**Comment by rarzumanyan** [comment]
@riaqn 

>Question: Is it possible to get the pts of frames if I use standalone demuxer such as pyav?

That's not implemented yet, but such feature is easy to add because internal decoding API always returns decoded packet data.
Please submit a feature request issue.

**Comment by riaqn** [comment]
Yes I will submit a feature request - that should be more reliable than infering frame order by packets.

I haven't actually written the code. But in pyav a packet has buffer_ptr from which I can construct a numpy array, and pass to VPF? This is just my plan and might not work.
