### ISSUE TITLE
build error, Couldn't find CUDA library root

### ISSUE THREAD

**Issue by stepstep123** [NVIDIA/VideoProcessingFramework#282]
hello, i follow the steps:
```bash
# Export paths to Video Codec SDK and FFMpeg
export PATH_TO_SDK=~/Video_Codec_SDK_9.1.23
export PATH_TO_FFMPEG=~/Git/FFmpeg/build_x64_release_shared

# Clone repo and start building process
cd ~/Git
git clone https://github.com/NVIDIA/VideoProcessingFramework.git

# Export path to Cmake:
export PATH=$PATH:/home/rarzumanyan/cmake-3.16.4-Linux-x86_64/bin

# Export path to CUDA compiler (I'm installing drivers from Nvidia site):
export CUDACXX=/usr/local/cuda/bin/nvcc

#Now the VPF build
cd VideoProcessingFramework
export INSTALL_PREFIX=$(pwd)/install
mkdir -p install
mkdir -p build
cd build
cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DPYTHON_LIBRARY=/home/rarzumanyan/anaconda3/lib/libpython3.7m.so \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"
make && make install
```

but build error, cannot find cuda root

![build_error](https://user-images.githubusercontent.com/43130195/142362263-eb940b9a-74ce-417e-9228-526da937aab8.jpg)
![build_error](https://user-images.githubusercontent.com/43130195/142362426-4c848cee-1d42-4cc2-928c-5eb06e128303.jpg)

**Comment by rarzumanyan** [comment]
Hi @stepstep123 

I've edited the issue topic slightly to fix broken syntax.
Looks like your system is missing some of necessary environmental variables. For some reason they were not exported during the driver install.

Take a look at [these lines](https://github.com/Kitware/CMake/blob/5e269798cc893a2f5048a6b84c471c424ce83b02/Modules/CMakeDetermineCUDACompiler.cmake#L213-L228) within CMake file which throws error and check what environmental & CMake variables are known during the configure process:
```cmake
    # In a non-scattered installation the following are equivalent to CMAKE_CUDA_COMPILER_TOOLKIT_ROOT.
    # We first check for a non-scattered installation to prefer it over a scattered installation.


    # CMAKE_CUDA_COMPILER_LIBRARY_ROOT contains the device library.
    if(DEFINED CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR)
      set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR}")
    elseif(EXISTS "${CMAKE_CUDA_COMPILER_TOOLKIT_ROOT}/nvvm/libdevice")
      set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_CUDA_COMPILER_TOOLKIT_ROOT}")
    elseif(CMAKE_SYSROOT_LINK AND EXISTS "${CMAKE_SYSROOT_LINK}/usr/lib/cuda/nvvm/libdevice")
      set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_SYSROOT_LINK}/usr/lib/cuda")
    elseif(EXISTS "${CMAKE_SYSROOT}/usr/lib/cuda/nvvm/libdevice")
      set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_SYSROOT}/usr/lib/cuda")
    else()
      message(FATAL_ERROR "Couldn't find CUDA library root.")
    endif()
    unset(CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR)
```

P. S.
If possible, I recommend to install driver with your package manager, that's an easier option.

**Comment by stepstep123** [comment]
> Hi @stepstep123 I've edited the issue topic slightly to fix broken syntax.
> 
> Looks like your system is missing necessary environmental variables. For some reason they were not exported during the driver install.
> 
> Take a look at [these lines](https://github.com/Kitware/CMake/blob/5e269798cc893a2f5048a6b84c471c424ce83b02/Modules/CMakeDetermineCUDACompiler.cmake#L213-L228) within CMake file which throws error and check what environmental & CMake variables are set during the configure process:
> 
> ```cmake
>     # In a non-scattered installation the following are equivalent to CMAKE_CUDA_COMPILER_TOOLKIT_ROOT.
>     # We first check for a non-scattered installation to prefer it over a scattered installation.
> 
> 
>     # CMAKE_CUDA_COMPILER_LIBRARY_ROOT contains the device library.
>     if(DEFINED CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR)
>       set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR}")
>     elseif(EXISTS "${CMAKE_CUDA_COMPILER_TOOLKIT_ROOT}/nvvm/libdevice")
>       set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_CUDA_COMPILER_TOOLKIT_ROOT}")
>     elseif(CMAKE_SYSROOT_LINK AND EXISTS "${CMAKE_SYSROOT_LINK}/usr/lib/cuda/nvvm/libdevice")
>       set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_SYSROOT_LINK}/usr/lib/cuda")
>     elseif(EXISTS "${CMAKE_SYSROOT}/usr/lib/cuda/nvvm/libdevice")
>       set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_SYSROOT}/usr/lib/cuda")
>     else()
>       message(FATAL_ERROR "Couldn't find CUDA library root.")
>     endif()
>     unset(CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR)
> ```
> 
> P. S. If possible, I recommend to install driver with your package manager, that's an easier option.

yes, i did it. and soved that.
but new problem came out.

**Comment by stepstep123** [comment]
new problem.
when i follow steps by docker ways.
![python_error](https://user-images.githubusercontent.com/43130195/142567834-d6f38e63-47b4-4758-975d-3a9e2616b151.jpg)
![run_error](https://user-images.githubusercontent.com/43130195/142567839-bade38fd-574b-4003-8ebf-dd26bec185dc.jpg)


could you please give me detail steps. ths so much.

**Comment by stepstep123** [comment]
![filenot_found](https://user-images.githubusercontent.com/43130195/142574495-33d29cb7-c893-483e-ba9a-1e4684471b60.jpg)

my local nvidia driver is too old, i dont want to updat
![nvidia-docker_error](https://user-images.githubusercontent.com/43130195/142576924-34264523-50d2-4f0f-acb2-3b3181385ef8.jpg)

so 
i run
docker run  -it -e NVIDIA_DRIVER_CAPABILITIES=video,compute,utility nvidia/videoprocessingframework:vpf

and then lImportError: libcuda.so.1: cannot open shared object file: No such file or directory
i copy local old libcuda.so.1 to container, fixed.
then ImportError: libnvcuvid.so.1: cannot open shared object file: No such file or directory
i copy local old libnvcuvid.so.1: again, and ln -s. i doesnot work.

can i do like above way ? 
or any other ways can i work  if i dont updat local driver

by the way, the container cuda is cuda-11.2

**Comment by stepstep123** [comment]
i just update the driver version and solved it

**Comment by yuxx0218** [comment]
> > Hi @stepstep123 I've edited the issue topic slightly to fix broken syntax.
> > Looks like your system is missing necessary environmental variables. For some reason they were not exported during the driver install.
> > Take a look at [these lines](https://github.com/Kitware/CMake/blob/5e269798cc893a2f5048a6b84c471c424ce83b02/Modules/CMakeDetermineCUDACompiler.cmake#L213-L228) within CMake file which throws error and check what environmental & CMake variables are set during the configure process:
> > ```cmake
> >     # In a non-scattered installation the following are equivalent to CMAKE_CUDA_COMPILER_TOOLKIT_ROOT.
> >     # We first check for a non-scattered installation to prefer it over a scattered installation.
> > 
> > 
> >     # CMAKE_CUDA_COMPILER_LIBRARY_ROOT contains the device library.
> >     if(DEFINED CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR)
> >       set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR}")
> >     elseif(EXISTS "${CMAKE_CUDA_COMPILER_TOOLKIT_ROOT}/nvvm/libdevice")
> >       set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_CUDA_COMPILER_TOOLKIT_ROOT}")
> >     elseif(CMAKE_SYSROOT_LINK AND EXISTS "${CMAKE_SYSROOT_LINK}/usr/lib/cuda/nvvm/libdevice")
> >       set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_SYSROOT_LINK}/usr/lib/cuda")
> >     elseif(EXISTS "${CMAKE_SYSROOT}/usr/lib/cuda/nvvm/libdevice")
> >       set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "${CMAKE_SYSROOT}/usr/lib/cuda")
> >     else()
> >       message(FATAL_ERROR "Couldn't find CUDA library root.")
> >     endif()
> >     unset(CMAKE_CUDA_COMPILER_LIBRARY_ROOT_FROM_NVVMIR_LIBRARY_DIR)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > P. S. If possible, I recommend to install driver with your package manager, that's an easier option.
> 
> yes, i did it. and soved that. but new problem came out.

hi, I use "set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT "/usr/local/cuda" CACHE INTERNAL "Global variable description")" to set variable, but it not work, raised the same exception.

**Comment by yuxx0218** [comment]
I also use 
 export CUDA_HOME=/usr/local/cuda
 export PATH=$CUDA_HOME/bin:$CUDA_HOME/include:$PATH
 export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
It does not work either.
