### ISSUE TITLE
`CUDA error with code` after successful build

### ISSUE THREAD

**Issue by deepsworld** [NVIDIA/VideoProcessingFramework#286]
I am trying to build and run VPF in miniconda environment with python3.9 and pytorch1.10. The build and installation goes through without any issue but when I try to run the `SampleDecode.py` script it results in below error. Based on other issues, I have verified my driver version is compatible with the codec sdk. The cuda error seems to be out of range so no string value is available. I appreciate your help. 

DRIVER_VERSION: 465.19.01
VIDEO_CODEC_SDK: 10.0.26
PYTHON:3.9
PYTORCH:1.10

```log
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3 
|-------------------------------+----------------------+----------------------+
```

```log
(test39) root@27edfcc3d494:~/VideoProcessingFramework# python install/bin/SampleDecode.py 0 install/bin/test.mp4 test2.mp4
This sample decodes input video to raw NV12 file on given GPU.
Usage: SampleDecode.py $gpu_id $input_file $output_file.
Traceback (most recent call last):
  File "/home/VideoProcessingFramework/install/bin/SampleDecode.py", line 298, in <module>
    dec = NvDecoder(gpu_id, enc_filePath, decFilePath)
  File "/home/VideoProcessingFramework/install/bin/SampleDecode.py", line 73, in __init__
    self.nv_dec = nvc.PyNvDecoder(self.nv_dmx.Width(), self.nv_dmx.Height(), 
RuntimeError: /home/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:626
CUDA error with code -1296170512
No error string available
```

```log
(test39) root@27edfcc3d494:~/VideoProcessingFramework# ldd /home/VideoProcessingFramework/install/bin/PyNvCodec.cpython-39-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffca7bf1000)
        libTC.so => /home/VideoProcessingFramework/build/PyNvCodec/TC/libTC.so (0x00007f0c4d535000)
        libpython3.9.so.1.0 => /home/miniconda3/envs/test39/lib/libpython3.9.so.1.0 (0x00007f0c4d181000)
        libTC_CORE.so => /home/VideoProcessingFramework/build/PyNvCodec/TC/TC_CORE/libTC_CORE.so (0x00007f0c4cf7b000)
        libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f0c4b859000)
        libstdc++.so.6 => /home/miniconda3/envs/test39/lib/libstdc++.so.6 (0x00007f0c4dbdb000)
        libgcc_s.so.1 => /home/miniconda3/envs/test39/lib/libgcc_s.so.1 (0x00007f0c4dbc4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0c4b468000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0c4b249000)
        libnvcuvid.so.1 => /home/Video_Codec_SDK_10.0.26/Lib/linux/stubs/x86_64/libnvcuvid.so.1 (0x00007f0c4b048000)
        libavutil.so.56 => /home/miniconda3/envs/test39/lib/libavutil.so.56 (0x00007f0c4ad8e000)
        libavcodec.so.58 => /home/miniconda3/envs/test39/lib/libavcodec.so.58 (0x00007f0c49a8b000)
        libavformat.so.58 => /home/miniconda3/envs/test39/lib/libavformat.so.58 (0x00007f0c4980d000)
        libnppig.so.11 => /home/miniconda3/envs/test39/lib/libnppig.so.11 (0x00007f0c47830000)
        libnppicc.so.11 => /home/miniconda3/envs/test39/lib/libnppicc.so.11 (0x00007f0c47024000)
        libnppidei.so.11 => /home/miniconda3/envs/test39/lib/libnppidei.so.11 (0x00007f0c464e9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0c462e5000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0c460e2000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0c45eda000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0c45b3c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0c4db64000)
        libva-drm.so.2 => /home/miniconda3/envs/test39/lib/./libva-drm.so.2 (0x00007f0c4dbbb000)
        libva.so.2 => /home/miniconda3/envs/test39/lib/./libva.so.2 (0x00007f0c4db8f000)
        libswresample.so.3 => /home/miniconda3/envs/test39/lib/./libswresample.so.3 (0x00007f0c45b1c000)
        libvpx.so.7 => /home/miniconda3/envs/test39/lib/./libvpx.so.7 (0x00007f0c458fd000)
        libiconv.so.2 => /home/miniconda3/envs/test39/lib/./libiconv.so.2 (0x00007f0c45817000)
        liblzma.so.5 => /home/miniconda3/envs/test39/lib/./liblzma.so.5 (0x00007f0c457ee000)
        libz.so.1 => /home/miniconda3/envs/test39/lib/./libz.so.1 (0x00007f0c457d4000)
        libaom.so.3 => /home/miniconda3/envs/test39/lib/./libaom.so.3 (0x00007f0c450c7000)
        libmp3lame.so.0 => /home/miniconda3/envs/test39/lib/./libmp3lame.so.0 (0x00007f0c4504c000)
        libSvtAv1Enc.so.0 => /home/miniconda3/envs/test39/lib/./libSvtAv1Enc.so.0 (0x00007f0c440d0000)
        libx264.so.161 => /home/miniconda3/envs/test39/lib/./libx264.so.161 (0x00007f0c43e0e000)
        libx265.so.199 => /home/miniconda3/envs/test39/lib/./libx265.so.199 (0x00007f0c42b8c000)
        libopenh264.so.6 => /home/miniconda3/envs/test39/lib/./libopenh264.so.6 (0x00007f0c42a68000)
        libxml2.so.2 => /home/miniconda3/envs/test39/lib/./libxml2.so.2 (0x00007f0c42900000)
        libbz2.so.1.0 => /home/miniconda3/envs/test39/lib/./libbz2.so.1.0 (0x00007f0c428ea000)
        libgnutls.so.30 => /home/miniconda3/envs/test39/lib/./libgnutls.so.30 (0x00007f0c42718000)
        libnppc.so.11 => /home/miniconda3/envs/test39/lib/libnppc.so.11 (0x00007f0c423a2000)
        libdrm.so.2 => /home/miniconda3/envs/test39/lib/././libdrm.so.2 (0x00007f0c4238a000)
        libicuuc.so.68 => /home/miniconda3/envs/test39/lib/././libicuuc.so.68 (0x00007f0c42196000)
        libnettle.so.8 => /home/miniconda3/envs/test39/lib/././libnettle.so.8 (0x00007f0c42155000)
        libhogweed.so.6 => /home/miniconda3/envs/test39/lib/././libhogweed.so.6 (0x00007f0c420ff000)
        libicudata.so.68 => /home/miniconda3/envs/test39/lib/./././libicudata.so.68 (0x00007f0c405bd000)
```
NOTE: I had to create the symlink for `libnvcuvid.so.1` from `libnvcuvid.so` because there was no such file available in codec sdk and VPF was looking for this specific name. Also, the import of pynvcodec works fine

```py
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyNvCodec as nvc
>>> 
```

**Comment by rarzumanyan** [comment]
Hi @deepsworld 

>libnvcuvid.so.1 => /home/Video_Codec_SDK_10.0.26/Lib/linux/stubs/x86_64/libnvcuvid.so.1

This is the reason why you get meaningless error code. Your `PyNvCodec` module loads stub `libnvcuvid` library.
`Video_Codec_SDK_10.0.26/Lib/linux/stubs/x86_64/libnvcuvid.so.1` is a stub library which allows one to build applications on a machine without GPU and / or GPU driver. It shall not be used in runtime, only during compile time.

Your `PyNvCodec` module shall load actual `libnvcuvid` library which is part of the GPU driver. 
If you install GPU driver with package manager, check that you have libnvcuvid in place. Below is how to do that in Ubuntu 20.04:

```bash
$ find / -name *cuvid*
/usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
/usr/lib/x86_64-linux-gnu/libnvcuvid.so
/usr/lib/x86_64-linux-gnu/libnvcuvid.so.495.29.05

$ dpkg -S /usr/lib/x86_64-linux-gnu/libnvcuvid.so
libnvidia-decode-495:amd64: /usr/lib/x86_64-linux-gnu/libnvcuvid.so
```

It means you need to install `libnvidia-decode-495` apt package. IIRC in previous driver versions available via apt, Video Codec SDK runtime was not extracted to separate package, but now it is.

**Comment by deepsworld** [comment]
@rarzumanyan Thank you for your help. 

I installed my driver from `.run` file and not with `apt or apt-get` and that could be why I don't see the `libcuvid.so` in my user libraries. I can install the `libnvidia-decode` from `apt` but I am trying to maintain all my dependencies within the miniconda environmnet. Do you know if there is any alternative way to get this runtime library?

**Comment by rarzumanyan** [comment]
Hi @deepsworld 

>I do see the library in my host os but for some reason it is not loaded with nvidia-runtime in the docker container.

That's a different story ;)
What driver capabilities do you run your image with? To use VPF you need `utility`, `video` and `compute`. 
Please note that `all` capabilities doesn't work sometimes so I recommend to list them explicitly.

**Comment by rarzumanyan** [comment]
@deepsworld 

>If the .so file is specific to a particular nvidia driver

I would rather say that in previous `nvidia-driver` package versions available through `apt` this problem didn't exist. If I understand correctly, `libnvidia-decode` package became separate not that long ago. To my best knowledge, those gpu driver versions which are distributed in form of *.run files aren't affected by this change.

I'll investigate on this a bit later and will add more information to build-from-source wiki page. This is unpleasant surprise for me as well.

**Comment by deepsworld** [comment]
> If you could share your experience regarding conda package build, that would be great. I'm looking for approaches to simplify VPF build procedure but unfortunately I don't have too much experience in this topic. Your help is much appreciated!

Sure! I am thinking since most of the dependencies including FFMPEG, Pytorch, Cudatoolkit, etc are already available in the anaconda repo, we should be able to create a conda package for VPF. The other dependency is the VIDEO-CODEC-SDK which can be downloaded on the fly. Only weird dependency is the `libnvcuvid.so` which may or may not be available from anaconda. I will try to build the package on my end and if successful, I can share it.

**Comment by deepsworld** [comment]
@rarzumanyan 

I was able to build the conda package for VPF. Please try and install it with
```sh
conda install -c dpatel-nec vpf
```
I had to add a setup.py that builds the extension by using setuptools extension for cmake. I have added the changes to my personal fork at https://github.com/deepsworld/VideoProcessingFramework. I can submit a pull request as soon as I get some more time.

**Comment by rarzumanyan** [comment]
Thanks for update, @deepsworld  that's very interesting!

> I can submit a pull request

That would be great, please submit PR.
