### ISSUE TITLE
problem about "FFmpegDemuxer: no AVFormatContext provided"

### ISSUE THREAD

**Issue by TracelessLe** [NVIDIA/VideoProcessingFramework#287]
**Describe the bug**
Hi @rarzumanyan , why did you remove "av_register_all( )" in [this commit](https://github.com/NVIDIA/VideoProcessingFramework/commit/bb1fcc0df975f51433018040979ff380db5ecd5d#diff-a31d03ae2cf896d61149c5d64a704dbd7ab285edeec3aae0d3eeceaa56d17076L414)? I meet the question about "ValueError: FFmpegDemuxer: no AVFormatContext provided." which is related with #8 and #104, and I solved the problem when I add [this line ](https://github.com/NVIDIA/VideoProcessingFramework/commit/bb1fcc0df975f51433018040979ff380db5ecd5d#diff-a31d03ae2cf896d61149c5d64a704dbd7ab285edeec3aae0d3eeceaa56d17076L414)return to the code "FFmpegDemuxer.cpp". 

**To Reproduce**
1. Compile and install
2. Run ``` python SampleDecode.py 0 test.mp4 result.h264 ```

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Nvidia driver version: 440.64.00
 - CUDA Version : 10.2
 - Video Codec SDK Version: 9.1.23
 - Python Version: 3.7.7
 - FFmpeg Version: 4.4

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

This function call was removed in preparation to ffmpeg 4.4 migration, but was never done completely - my fault.
Could you please submit a PR which brings this back?

**Comment by TracelessLe** [comment]
> Hi @TracelessLe
> 
> This function call was removed in preparation to ffmpeg 4.4 migration, but was never done completely - my fault. Could you please submit a PR which brings this back?

Sure, I submit a PR #289 to bring it back into FFmpegDemuxer.cpp :)
