### ISSUE TITLE
Does VPF support gbrp (GBR Planal) pixel format?

### ISSUE THREAD

**Issue by aniongithub** [NVIDIA/VideoProcessingFramework#288]
I need to decode gbrp encoded videos using VPF, is this currently possible?

**Comment by rarzumanyan** [comment]
Hi @aniongithub 

**Long story short:** 
No.

**Detailed explanation:**
VPF gives a Python bindings to Nvdec and Nvenc API.
Nvdec can decode video streams compressed with lossy codecs such as H.264, H.265, VP9 etc. in YUV420 and YUV444 pixel formats, it doesn't support GBR Planar. Full list of supported codecs and pixel formats can be found [here](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new).

**Workarounds:**
- Use Python bindings to OpenCV / FFMpeg or any other framework to decode GBRP frame, then upload it to GPU with `PyFrameUploader`. Please note that GBRP pixel format isn't yet supported by VPF, but you can use `RGB_PLANAR` instead, it has same layout in memory.
- Add GBRP support to `PyFfmpegDecoder` class which is SW decoder fallback based on `libavcodec` library.
