### ISSUE TITLE
RTSP video steam decode

### ISSUE THREAD

**Issue by NNsauce** [NVIDIA/VideoProcessingFramework#291]
I saw nearly all the test demo was decoding from a mp4 video file.

**Comment by NNsauce** [comment]
So, I want ask if there is a demo show how to decode a RTSP video stream address, just like cv2.VideoCapture() in opencv-python,  many thanks!

**Comment by rarzumanyan** [comment]
Hello @NNsauce 

VPF relies on libavformat & libavcodec FFMpeg libraries to get video stream from source. These libraries takes care of actual access to data, be it local file or RTSP stream. Hence you can use any decoding sample to decode RTSP stream just by providing camera URL as file path.

Also, there's a dedicated SampleDecodeRTSP.py file which illustrates how to decode multiple RTSP streams in parallel.

**Comment by NNsauce** [comment]
@rarzumanyan Very nice,I find it . Thank you!  those colorful building errors just tired my eyes......
