### ISSUE TITLE
torch install error in docker build

### ISSUE THREAD

**Issue by NNsauce** [NVIDIA/VideoProcessingFramework#293]
###################################################
Step 11/23 : RUN make -f docker/Makefile build_env EXTRAS=vpf
 ---> Running in 67b9c9fc45c9
poetry install --extras vpf
Creating virtualenv vpf in /opt/.venv
Installing dependencies from lock file

Package operations: 17 installs, 0 updates, 0 removals

  • Installing appdirs (1.4.4)
  • Installing markupsafe (2.0.1)
  • Installing numpy (1.21.1)
  • Installing typing-extensions (3.10.0.2)
  • Installing click (8.0.1)
  • Installing mako (1.1.5)
  • Installing mypy-extensions (0.4.3)
  • Installing pathspec (0.9.0)
  • Installing pillow (8.3.2)
  • Installing platformdirs (2.3.0)
  • Installing pytools (2021.2.8)
  • Installing regex (2021.8.28)
  • Installing tomli (1.2.1)
  • Installing torch (1.9.0)

  RuntimeError

  Invalid hash for torch (1.9.0) using archive torch-1.9.0-cp38-cp38-manylinux1_x86_64.whl

  at poetry/venv/lib/python3.8/site-packages/poetry/installation/executor.py:613 in _download_link
      609│ 
      610│         if package.files:
      611│             archive_hash = "sha256:" + FileDependency(package.name, archive).hash()
      612│             if archive_hash not in {f["hash"] for f in package.files}:
    → 613│                 raise RuntimeError(
      614│                     "Invalid hash for {} using archive {}".format(package, archive.name)
      615│                 )
      616│ 
      617│         return archive
###################################################

hi, man!   I may need your help.
These contents between two  long "#####" lines above is the error I got when I was building a docker image in step 11/23.
you know torch installing is really tough and long.  SO, how can I ignore installing torch and torchvison in step 11/23. I just don't want to waste too much time on it.  
(I want only use this VPF to decode a RTSP url, MUST I install torch? If must, how can I fix this error? )
Thanks so much!!!

**Comment by rarzumanyan** [comment]
Hi @NNsauce 

Pytorch isn't required unless you opt-in GENERATE_PYTORCH_EXTENSION cmake option.

The option is set up here:
https://github.com/NVIDIA/VideoProcessingFramework/blob/869316dc3e027796e607eca065b961c64ae7364e/docker/Makefile#L10-L16

The dependency is added here:
https://github.com/NVIDIA/VideoProcessingFramework/blob/869316dc3e027796e607eca065b961c64ae7364e/poetry.lock#L245-L251

I'll ask the patch author to add the option which enables / disables Pytorch support in user-friendly way. Meanwhile I guess you can only comment those lines out by hand.

**Comment by sandhawalia** [comment]
👋🏽 sure thing. This flag should be setup via an arg to the `docker-compose` command. I'll have something ready by end of the week.

**Comment by rarzumanyan** [comment]
Hi @NNsauce 

Please check `pr_294` branch in which the patch was pushed and let us know if it resolves the issue.
