### ISSUE TITLE
How to perform GPU memory copy.

### ISSUE THREAD

**Issue by npkhgl** [NVIDIA/VideoProcessingFramework#297]
Hi, I got some troubles about GPU memory copy. 
`rgb24.PlanePtr().Export(surface_tensor.data_ptr(), w * 3, gpuID) # this works fine for me`
However, when I tried to use `pycuda` to perform the GPU memory copy, it **failed**. The codes I used:

 ```
import pycuda.autoinit
import pycuda.driver as cudrv
texbufs_memcpy = cudrv.Memcpy2D()
# texbufs_memcpy.width_in_bytes = w * 3
texbufs_memcpy.width = w * 3
# texbufs_memcpy.height = h
texbufs_memcpy.set_src_device(rgb24.PlanePtr().GpuMem())
texbufs_memcpy.set_dst_device(surface_tensor.data_ptr())
texbufs_memcpy(aligned=True)
```
Could you give me some help? Thanks a lot.

**Comment by rarzumanyan** [comment]
Hi @npkhgl 

Thanks for bringing this up.
I'm planning to add one more unit test for `Surface` class which will test (and illustrate) how use pycuda for memcpy.
Will update you a bit later as I test this on my machine.

**Comment by rarzumanyan** [comment]
@npkhgl 

Please check out `issue_297` branch in which I've added `test_PySurface.py` file.
It shows how to use pycuda API for memcpy.

**Comment by npkhgl** [comment]
@rarzumanyan 
Thanks for your effort to write an example code. I read the codes in `test_PySurface.py`, but I still have problems to use pycuda API for memcpy. I found that memcpy between pytorch tensors is correct, however memcpy between pytorch tensor and surface_rgb is failed. Here are my codes, Please correct me if something wrong.

```
import PyNvCodec as nvc 
import torch 
import pycuda.driver as cuda
from pycuda import autoinit

w = 1280 
h = 720
gpuID = 0
surface_rgb = nvc.Surface.Make(nvc.PixelFormat.RGB, w, h, 0)
sp = surface_rgb.PlanePtr()
tensor = torch.zeros((h, w, 3), dtype=torch.uint8).cuda() + 1
sp.Import(tensor.data_ptr(), w*3, 0)
check_tensor = torch.zeros((h, w, 3), dtype=torch.uint8).cuda() 
test_tensor = torch.zeros((h, w, 3), dtype=torch.uint8).cuda() 

# something wrong when memcpy between tensor and surface_rgb
memcpy = cuda.Memcpy2D()
memcpy.width_in_bytes = w * 3
memcpy.height = h
memcpy.src_pitch = w * 3
memcpy.set_src_device(sp.GpuMem())
memcpy.set_dst_device(check_tensor.data_ptr())
memcpy(aligned=True)
print(check_tensor.equal(tensor))   # False

# memcpy performs correctly between tensors
memcpy.set_src_device(tensor.data_ptr())
memcpy.set_dst_device(test_tensor.data_ptr())
memcpy(aligned=True)
print(test_tensor.equal(tensor))   # True

# Export performs correctly
check_tensor[:,:,:] = 0
sp.Export(check_tensor.data_ptr(), w*3, 0)
print(check_tensor.equal(tensor))  # True
```

**Comment by rarzumanyan** [comment]
@npkhgl 

At least one thing I can see is missing destination pitch.
VPF uses pitched allocation, it's actually illustrated in `test_PySurface.py`.
You just need to swap source and destination members in `Memcpy2D` class instance:

https://github.com/NVIDIA/VideoProcessingFramework/blob/d870bfb57815bbb7cc934fec8ab3505e67ca1278/Tests/test_PySurface.py#L124-L132
