### ISSUE TITLE
DecodeSingleFrame operation make high CPU usage ?

### ISSUE THREAD

**Issue by mchl0203** [NVIDIA/VideoProcessingFramework#30]
My code is as follows:
```
...
nvDec = nvc.PyNvDecoder(encFile, gpuID)
try:
    for i in tqdm(range(numFrames)):
        decFrame = nvDec.DecodeSingleFrame()
...
```

When I run this code, the CPU usage is 200 ~ 300% (40 CPUs on the server), does DecodeSingleFrame operation make high CPU usage ?
If so, is there any way to reduce CPU usage when the picture is copied to the local.
Or is there any way to convert the picture(in the GPU memory) into a pytorch tensor?
Looking forward to your reply, thanks~

**Comment by rarzumanyan** [comment]
Hi @mchl0203 

VPF supports on-GPU video frames export to PyTorch tensors. 

Please contact me via my email (in the profile info).

**Comment by xinyi61** [comment]
I have meet the same problems when I use branch cpp_samples.decode mult-thread rtsp stream.

OS: ubuntu 18.04
Nvidia driver version: 440.33.01
CUDA Version: 10.2
Video Codec SDK Version:Video_Codec_SDK_10.0.26
C++
CPU(s): 40

when run 64 thread decoding, the cpu  use is:
  1  [||||||||||||||||||||||||||||||98.2%]   11 [||||||||||||||||||||||||||||||92.5%]   21 [||||||||||||||||||||||||||||||96.9%]   31 [||||||||||||||||||||||||||||||96.3%]
  2  [||||||||||||||||||||||||||||||97.5%]   12 [||||||||||||||||||||||||||||||91.4%]   22 [||||||||||||||||||||||||||||||99.4%]   32 [||||||||||||||||||||||||||||||95.0%]
  3  [||||||||||||||||||||||||||||||98.2%]   13 [||||||||||||||||||||||||||||||94.4%]   23 [||||||||||||||||||||||||||||||98.8%]   33 [||||||||||||||||||||||||||||||97.5%]
  4  [||||||||||||||||||||||||||||||98.2%]   14 [||||||||||||||||||||||||||||||96.3%]   24 [||||||||||||||||||||||||||||||99.4%]   34 [||||||||||||||||||||||||||||||95.1%]
  5  [||||||||||||||||||||||||||||||98.8%]   15 [||||||||||||||||||||||||||||||93.2%]   25 [||||||||||||||||||||||||||||||98.8%]   35 [||||||||||||||||||||||||||||||95.8%]
  6  [||||||||||||||||||||||||||||||98.8%]   16 [||||||||||||||||||||||||||||||97.0%]   26 [||||||||||||||||||||||||||||||98.1%]   36 [||||||||||||||||||||||||||||||93.1%]
  7  [||||||||||||||||||||||||||||||98.2%]   17 [||||||||||||||||||||||||||||||96.3%]   27 [|||||||||||||||||||||||||||||100.0%]   37 [||||||||||||||||||||||||||||||92.0%]
  8  [||||||||||||||||||||||||||||||98.8%]   18 [||||||||||||||||||||||||||||||91.9%]   28 [||||||||||||||||||||||||||||||98.2%]   38 [||||||||||||||||||||||||||||||92.7%]
  9  [||||||||||||||||||||||||||||||98.2%]   19 [||||||||||||||||||||||||||||||95.1%]   29 [|||||||||||||||||||||||||||||100.0%]   39 [||||||||||||||||||||||||||||||95.7%]
  10 [||||||||||||||||||||||||||||||97.5%]   20 [||||||||||||||||||||||||||||||95.7%]   30 [||||||||||||||||||||||||||||||99.4%]   40 [|||||||||||||||||||||||||||||100.0%]
  Mem[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||11.4G/62.6G]   Tasks: 220, 4149 thr; 40 running
  Swp[||||||||                                                            210M/2.00G]   Load average: 67.38 66.58 67.50 
                                                                                        Uptime: 14 days, 05:20:00
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
36651 deploy     20   0 51.5G 2754M 1223M S 2197  4.3  2h36:58 ./cpp_demo

**Comment by rarzumanyan** [comment]
@xinyi61 

Actual decoding doesn't consume too much of CPU cycles.
Build & launch your application with profiling support (e. g. with gprof support) to see the top CPU-heavy functions. 
Usually it's IO operations (disk load/save) and rescale / color conversions done by CPU.

**Comment by xinyi61** [comment]
thank you very much and  i will try it



发自我的小米手机
在 Roman Arzumanyan <notifications@github.com>，2020年9月23日 21:20写道：

@xinyi61<https://github.com/xinyi61>

Actual decoding doesn't consume too much of CPU cycles.
Build & launch your application with profiling support (e. g. with gprof support) to see the top CPU-heavy functions.
Usually it's IO operations (disk load/save) and rescale / color conversions done by CPU.
