### ISSUE TITLE
How to force decoder to be sync or handle input/output queues

### ISSUE THREAD

**Issue by nullket** [NVIDIA/VideoProcessingFramework#306]
**Is your feature request related to a problem? Please describe.**
Hi, I am decoding hvec encoded ffmpeg image packets for a pytorch application. I am doing this in realtime with to wish for minimal latency and also in an accelerated environment where I try to get as much images through the network as possible. I do not have audio and the stream is more or less stored in blobs of single [FFMPEG AVPackets](https://lists.ffmpeg.org/doxygen/2.2/structAVPacket.html). Thus, I am not using any demuxer while I simply feed the `AVPacket.data` to the decoder buffer via 
```python
def __init__(self):
      ...
     self.nvdec = nvc.PyNvDecoder(img_width, img_height, f, c, gpu_dev)

def on_new_AV_Packet(self, msg):
     ....
     enc_packet = np.frombuffer(buffer=msg.data, dtype=np.uint8)
     surface = self.nvdec.DecodeSurfaceFromPacket(in_meta, enc_packet, out_meta)
```

The procedure works but I if I understand [this comment](https://github.com/NVIDIA/VideoProcessingFramework/issues/257#issuecomment-950101080)and the `SampleDecode.py` correctly the Decoder should be async in my implementation right?

Thus calling `DecodeSurfaceFromPacket(Packet_Nr_N)` will return an empty surface or an older Frame `N-x`. If I understand correctly I can use `FlushSingleSurface()` to check if an older packet is already decoded but this function will also not be blocking and will return an empty surface in case the decoder has not decoded a submitted packet yet. 

**Describe the solution you'd like**
Is it possible to make `DecodeSurfaceFromPacket()` blocking without an (internal) demuxer and return the frame for the packet it was given in the very same function call (assuming the order of packets represent the display order)

**Describe alternatives you've considered**
- If it is not possible to make `DecodeSurfaceFromPacket()` blocking (and it might be faster in the overall computation time of the application to stay with the async behavior) will `DecodeSurfaceFromPacket()` queue the incoming packets? Is [this](https://github.com/NVIDIA/VideoProcessingFramework/blob/af211dded91005360d08782c14e1ef92aafecf9b/PyNvCodec/src/PyNvDecoder.cpp#L183) `upDecoder->ClearInputs()` call not clearing the last waiting incoming package(s) before queuing a new one? 
- If it is queuing submitted packets, how big is the input buffer? Can I check if the buffer is close to full? I do not want to overload the input in my accelerated environment.
- How can I detect if there are still packets in the queue waiting to be decoded if `FlushSingleSurface()` is not blocking and might return an empty surface? Due to the async behaviour an empty surface only means no decoded image is available but not that the decoded might currently decode one and has simply not finished yet? 

**Additional context**
In case you are wondering about the storage of "blobs of single FFMPEG AVPackets": We use the publish-subscriber framework [ROS](https://www.ros.org/) to transfer and record video data. The video data is encoded using [ffmpeg this plugin](https://github.com/daniilidis-group/ffmpeg_image_transport) and stored as "messages" per frame in [this](https://github.com/daniilidis-group/ffmpeg_image_transport_msgs/blob/master/msg/FFMPEGPacket.msg) format.

**Comment by nullket** [comment]
Thanks for the quick reply! 

> Generally it's almost impossible to make decoder synchronous unless it handles input data itself.

Makes totally sense. In our case b-frames are [disabled](https://github.com/daniilidis-group/ffmpeg_image_transport/blob/master/src/ffmpeg_encoder.cpp#L91) and thus the order of the packets will be the display order and thus also be the decoder order right? 

> Also, async decoding is much better in terms of performance

That's what I already thought and therefore the suggested alternative. Could you help me finding answers for the above mentioned questions?

**Comment by rarzumanyan** [comment]
Hi @nullket 

>the incoming packets should pile up in some sort of buffer on the gpu right? How can I I avoid an overflow of that input buffer?

Yes, that could happen.
It was investigated and solved in #257. You can see the solution to this problem in RTSP sample:
https://github.com/NVIDIA/VideoProcessingFramework/blob/ec453adcb2c3cd5cd566300d613d3ffd63343dda/SampleDecodeRTSP.py#L174-L189
https://github.com/NVIDIA/VideoProcessingFramework/blob/ec453adcb2c3cd5cd566300d613d3ffd63343dda/SampleDecodeRTSP.py#L197-L205

>But does it also ensure that the decoder is currently not decoding a surface and has simply not finished yet?

The API is designed differently. The moment you call `FlushSingleSurface`, the EOS flag is set which signals decoder that session is over. Then you simply receive decoded surfaces one by one until they are over. I recommend you to go through `test_PyNvDecoder.py` file.

**Comment by nullket** [comment]
Alright, thanks a lot for the whole clarification. Just one question left:
> Yes, that could happen.

"Just" until it runs out of vram?

**Comment by rarzumanyan** [comment]
@nullket 

>"Just" until it runs out of vram?

That's a good question, I've never tried that.
I assume that as soon vRAM is depleted, next Video Codec SDK API function you call will return CUDA out of memory error.

P. S.
If you're using VPF at your job, please feel free to send me an email, I'm trying to track VPF users and projects it's used in to analyze what features could be most useful to develop next. Also that may be a good occasion to establish a contact ;)

Bu of course it's completely optional and totally up to you.
