### ISSUE TITLE
Setting Keyframes in Output Video

### ISSUE THREAD

**Issue by yuval-vi** [NVIDIA/VideoProcessingFramework#307]
Hi @rarzumanyan,
First off, thank you for all the great work on this project.

I was using the [SamplePyTorch.py](https://github.com/NVIDIA/VideoProcessingFramework/blob/master/SamplePyTorch.py) example, on an input with multiple keyframes in it, and noticed that the resulting video has only one keyframe - on the first frame. 

Is there a way to set the Dec/Enc so that the output's keyframes are the same as the input's?

Thanks in advance,
Yuval

**Comment by rarzumanyan** [comment]
Hi @yuval-vi 

>Is there a way to set the Dec/Enc so that the output's keyframes are the same as the input's?

You can configure encoder to have same GOP size as input sequence like this:
```python
#distance between key frames in your input video
gop_size = 30

#use the same value for output
nvEnc = nvc.PyNvEncoder({'preset': 'P5', 'tuning_info' : 'high_quality', 'codec': 'h264', 
                         'profile' : 'high', 's': res, 'idrperiod' : str(gop_size)}, gpuID)
```

**Comment by yuval-vi** [comment]
@rarzumanyan Thanks for the quick response.
Works great!

For future knowledge, can this be done for a varying GOP length?

**Comment by yuval-vi** [comment]
+ Is there a list of possible values to the PyNvEncoder (like 'idrperiod' etc.)? Thanks!

**Comment by rarzumanyan** [comment]
Hi @yuval-vi 

>For future knowledge, can this be done for a varying GOP length?

It's feasible to force IDR key frame with Video Codec SDK API any time, but some decoder API changes would be required to track if decoded frame is key. If these two features are put together, it's possible to mimic any GOP length.

>is there a list of possible values to the PyNvEncoder (like 'idrperiod' etc.)?

Documentation isn't the best one ))
You can find all the options encoder can take in PyNvCodec/TC/src/NvCodecCliOptions.cpp file, although they are scattered across multiple places.

**Comment by yuval-vi** [comment]
Thanks @rarzumanyan 🙏
