### ISSUE TITLE
Using the sdk in multi thread

### ISSUE THREAD

**Issue by niaoyu** [NVIDIA/VideoProcessingFramework#31]
Thanks for your job. I tried the numpy version and torch version successly.

However, in my case I need to decode multi rtmps at the same time  but meet some cuda issues when i initialise second rtmp decoders with python multithreads. What could I do ?

--- I tried the multiprocess version and that's OK

**Comment by rarzumanyan** [comment]
Hi @niaoyu 

I’m aware of VPF issues in multi thread environment. There’s a mt_fixes branch in which I’m pushing various fixes. 

It has slightly different API (numpy arrays are passed by reference and not returned by some methods) so it’s not merged to master yet but you can check it out and try if you like. It also has couple multi-gpu bugs fixed. As soon as the code in it is brushed up, it will be merged with master.

**Comment by niaoyu** [comment]
@rarzumanyan 

wonderful, Iwill try this mt version.

Besides, there is a misunderstanding here about multithread and multiprocess. So i ignore the mt version.

The target is to decode multi rtmps at the same time with torch gpu tensor output. And collect them together just like deepstream nvmux to batch them to the detection model.

So it should be some architecture like this:
1.Decode 10 rtmps in 10 process with torch GPU tensor output,
2.Batch them together in one  model process,
3.deliver theoutput to Another 10 post processing process？doing some tracking issues

However，passing torch GPU tensor to different processing is annoying and seems too many processes here. Any advice？

**Comment by rarzumanyan** [comment]
Hi @niaoyu,

Please reference `SampleDecodeMultiThread.py` which decodes 2 streams in parallel. You can give RTSP stream location to this sample as input. It will work just fine, VPF uses ffmpeg demuxer under the hood which can handle this. 

VPF exports video frames to Pytorch tensors as deep copy (separate CUDA memory object is allocated and `cudaMemcpy2D` is done), so after you get tensor you may pass it to the ML part of your project.

> passing torch GPU tensor to different processing is annoying and seems too many processes here

Running decode & VPF->Pytorch export in separate pool of threads / processes seems reasonable as you will keep you GPU busy. T4 has improved Nvdec, so you need multiple decoding sessions to utilize it fully. 

P. S.
I recommend you to use `nvidia-smi dmon` console utility to track the GPU utilization. It will show Nvdec, Nvenc and CUDA cores load level + other useful stats.

**Comment by niaoyu** [comment]
> Hi @niaoyu,
> 
> Please reference `SampleDecodeMultiThread.py` which decodes 2 streams in parallel. You can give RTSP stream location to this sample as input. It will work just fine, VPF uses ffmpeg demuxer under the hood which can handle this.
> 
> VPF exports video frames to Pytorch tensors as deep copy (separate CUDA memory object is allocated and `cudaMemcpy2D` is done), so after you get tensor you may pass it to the ML part of your project.
> 
> > passing torch GPU tensor to different processing is annoying and seems too many processes here
> 
> Running decode & VPF->Pytorch export in separate pool of threads / processes seems reasonable as you will keep you GPU busy. T4 has improved Nvdec, so you need multiple decoding sessions to utilize it fully.
> 
> P. S.
> I recommend you to use `nvidia-smi dmon` console utility to track the GPU utilization. It will show Nvdec, Nvenc and CUDA cores load level + other useful stats.

Many thanks for your reply! I will try :-)
