### ISSUE TITLE
Copy to openGL texture.

### ISSUE THREAD

**Issue by Yves33** [NVIDIA/VideoProcessingFramework#310]
Hi,
I'm struggling to copy nvdec surface to OpenGL texture. Almost working, but the resulting texture is weird: right 1/4 is black (alpha channel), while left 3/4 represent the texture in grey (I guess wrong order in colors)

[minimal program] https://gist.github.com/Yves33/f39454d3f0038f284a9959c1f8a5c3d8
[image] https://github.com/Yves33/Images/blob/main/Capture%20du%202022-03-18%2010-21-45.png

my initalization code is
```
## load an movie into decoder
self.nvDec = nvc.PyNvDecoder("/home/yves/Bureau/killis_hevc_ffmpeg.mp4", 0)
self.width, self.height = self.nvDec.Width(), self.nvDec.Height()
self.cc_ctx = nvc.ColorspaceConversionContext(self.nvDec.ColorSpace(), self.nvDec.ColorRange())
self.nvYuv = nvc.PySurfaceConverter(self.width, self.height, self.nvDec.Format(), nvc.PixelFormat.YUV420, 0)
self.nvCvt = nvc.PySurfaceConverter(self.width, self.height, self.nvYuv.Format(), nvc.PixelFormat.RGB, 0)
self.nvDwn = nvc.PySurfaceDownloader(self.width, self.height, self.nvCvt.Format(), 0)
self.cuda_img = pycuda.gl.RegisteredImage(int(self.texture), GL_TEXTURE_2D, pycuda.gl.graphics_map_flags.WRITE_DISCARD)

## create texture dof GL display
self.texture = glGenTextures(1)
glActiveTexture(GL_TEXTURE0)
glBindTexture  ( GL_TEXTURE_2D, self.texture )
glTexImage2D(GL_TEXTURE_2D, 0 , GL_RGB, self.width, self.height, 0, GL_RGB, GL_UNSIGNED_BYTE, ctypes.c_void_p(0))
glTexParameterf   ( GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT )
glTexParameterf   ( GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT )
glTexParameteri   ( GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER,GL_LINEAR )
glTexParameteri   ( GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER,GL_LINEAR )
glBindTexture     ( GL_TEXTURE_2D, 0 )

self.data = numpy.zeros((self.width*self.height,3),numpy.uint8) ## for GPu->CPU download
```

and in my renderloop:
```
rawSurface = self.nvDec.DecodeSingleSurface()
yuvSurface = self.nvYuv.Execute(rawSurface, self.cc_ctx)
cvtSurface = self.nvCvt.Execute(yuvSurface, self.cc_ctx)
## texture update through cpu and system memory
method='GPUTEX'
if method=='CPUTEX':
    ## update GL through CPU download and upload. works, but slow!
    success = self.nvDwn.DownloadSingleSurface(cvtSurface, self.data)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, self.texture)
    glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0,self.width, self.height,GL_RGB, GL_UNSIGNED_BYTE, self.data)
elif method=='GPUTEX':
    ## cuda copy from surface.Plane_Ptr() to texture. weird texture!
    src_plane=cvtSurface.PlanePtr()
    buffer_mapping = self.cuda_img.map()
    ary=buffer_mapping.array(0,0)
    cpy = pycuda.driver.Memcpy2D()
    cpy.set_src_device(src_plane.GpuMem())
    cpy.set_dst_array(ary)
    cpy.width_in_bytes = src_plane.Width()
    cpy.width = src_plane.Width() 
    cpy.src_pitch = src_plane.Pitch()
    cpy.dst_pitch = self.nvDec.Width()
    cpy.height = src_plane.Height()
    cpy(aligned=False)
    pycuda.driver.Context.synchronize()
    buffer_mapping.unmap()
```
Transfering through CPU works perfectly.
Could you give me any direction to solve the problem?

Thanks in advance

**Comment by rarzumanyan** [comment]
Hi @Yves33 

Couple things I'd like to clarify first:
- Source code in your GitHub gist is different from code samples attached to this issue. Particularly, color conversion chain is different.
- VPF uses CUDA pitched allocation for `Surface`s and non-pitched allocation for `Buffer`s. Do you take that into account?

**Comment by Yves33** [comment]
> 
the gist had a RGB->RGB_PLANAR, but the resulting surface was not used. I've updated the gist. The color conversion chain is native->YUV420->RGB (adapted and simplified from examples). In any case, the image I get from nvDwn.DownloadSingleSurface(cvtSurface, self.data) is correct (interleaved rgb data as numpy array).

I'm pretty new to cuda/pycuda, but I think (I may be be wrong) that my code takes that into account (as cpy.src_pitch = src_plane.Pitch() and  cpy.dst_pitch = self.nvDec.Width() ). If that's not the case, could you point me to relevant resource discussing pitched allocation?

what I suspect is that in my texture, data is stored as rgbrgbrgbaaa, whereas i would like to get rgbrgbrg or rgbargbargba.

**Comment by rarzumanyan** [comment]
@Yves33 

I'm not an expert in OpenGL, but one thing looks a bit suspicious to me:
```python
        elif method=='GPUTEX':
            ## cuda copy from surface.Plane_Ptr() to texture
            src_plane=cvtSurface.PlanePtr()
            buffer_mapping = self.cuda_img.map()
            ary=buffer_mapping.array(0,0)
            cpy = pycuda.driver.Memcpy2D()
            cpy.set_src_device(src_plane.GpuMem())
            cpy.set_dst_array(ary)
            cpy.width_in_bytes = src_plane.Width()
            cpy.width = src_plane.Width() 
            cpy.src_pitch = src_plane.Pitch()

            #### NOT SURE ABOUT THIS ####
            cpy.dst_pitch = self.nvDec.Width()

            cpy.height = src_plane.Height()
            cpy(aligned=False)
            pycuda.driver.Context.synchronize()
            buffer_mapping.unmap()
```

How do you know if pitch of your mapped OpenGL texture is equal to decoded frames width?

**Comment by Yves33** [comment]
Thanks for you quick responses!
>>How do you know if pitch of your mapped OpenGL texture is equal to decoded frames width?<<
I don't...
I changed the gist to take into account different color space conversion depending on video file, and updated the images to show both the CPU and the GPU copy.
https://github.com/Yves33/Images

However, it seems that dst_pitch is ignored in pycuda.driver.Memcpy2D, as I can give it any int() value (0, 2048, 314159), the resulting image is always the same.
If dst_pitch was incorrect, I would assume to have some diagonal deviation in the resulting image (which is the case if I modify src_pitch)

could it be an issue with glPixelStorei?

**Comment by rarzumanyan** [comment]
@Yves33 

>could it be an issue with glPixelStorei?

The host answer is "I don't know". Apologies, I'm running out of depth here.
I've asked our CUDA experts to take a look at your gist, will come back as soon I get a word back from them.

**Comment by gedoensmax** [comment]
Hey @Yves33, i investigated your problem and found that the number of channels of the underlying data in OpenGL is 4 although the specified fromatter is GL_RGB and not GL_RGBA. I assume this is handeled differently on CPU due to it being copied to a numpy array first - but honestly i am not sure why this works. 
Using the below code you can check the number of channels that the GL buffer is actually using.
```
        elif method=='GPUTEX':
            ## cuda copy from surface.Plane_Ptr() to texture
            src_plane=cvtSurface.PlanePtr()
            buffer_mapping = self.cuda_img.map()
            ary=buffer_mapping.array(0,0)
            descriptor = ary.get_descriptor()
            assert(descriptor.num_channels == (src_plane.Width() // self.nvDec.Width()), "Number of channels do not match")
```
Another nice option to see that this is the error is to modify the fragment shader to be `color = vec4(texture(s,uv * vec2(0.75,1)));`. This way the image is stretched - while colors are still wrong it is reading populated area. To get correct results you will have to write a transition kernel using cuda that writes RGB values and pads them with a zero.
Something like this: 
```
__global__ void conversion_kernel(uchar3 *src_plane, uchar4 *out, int pitch_in, int pitch_out)
{
  const int x = blockIdx.x * blockDim.x + threadIdx.x;
  const int i = blockIdx.y * pitch_out + x;
  if (x < pitch_in)
    out[i] = make_uchar4(src_plane[i].x ,src_plane[i].y ,src_plane[i].z , 0);
}
```
Possibly you will be able to use the GL buffer als out pointer with a pycuda kernel.

![image](https://user-images.githubusercontent.com/44298237/159019540-089f5679-be0f-40d6-8f59-ef3f4236103f.png)

**Comment by Yves33** [comment]
Thank you both for your quick response. I'm totally new to cuda, but I'll try to implement the convertion with the provided kernel. I'll post the code when I suceed.

**Comment by Yves33** [comment]
Responding to myself,

As stated in documentation ([glTexImage2D.xhtml](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml)), if format is GL_RGB `Each element is an RGB triple. The GL converts it to floating point and assembles it into an RGBA element by attaching 1 for alpha. Each component is clamped to the range [0,1].`

Therefore, as spotted by @[gedoensmax](https://github.com/gedoensmax), using cuda Memcpy2D() to copy from surface.PlanePtr() to texture introduces a shift in bytes. The correct way to proceed is to use Memcpy2D to update a GL buffer object (width * height * 3), then use this buffer to update the GL texture, using GL_RGB as format (then glTexImage2D converts to floating point and 0 pads the data). Using a cuda kernel should work also, but requires much more code.

reference: "https://www.nvidia.com/content/GTC/documents/1055_GTC09.pdf".

the correct code is

initialisation:
```
## create texture for GL display
self.texture = glGenTextures(1)
glActiveTexture(GL_TEXTURE0)
glBindTexture  ( GL_TEXTURE_2D, self.texture )
glTexImage2D(GL_TEXTURE_2D, 0 , GL_RGB, self.width, self.height, 0, GL_RGB, GL_UNSIGNED_BYTE, ctypes.c_void_p(0))
glTexParameterf   ( GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT )
glTexParameterf   ( GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT )
glTexParameteri   ( GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER,GL_LINEAR )
glTexParameteri   ( GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER,GL_LINEAR )
glBindTexture     ( GL_TEXTURE_2D, 0 )
self.cuda_img = pycuda.gl.RegisteredImage(int(self.texture), GL_TEXTURE_2D, pycuda.gl.graphics_map_flags.WRITE_DISCARD)

## create gl Buffer for openGL<->CUDA interop
self.pbo = glGenBuffers(1)
glBindBuffer(GL_ARRAY_BUFFER, self.pbo)
glBufferData(GL_ARRAY_BUFFER, self.data, GL_DYNAMIC_DRAW)
glBindBuffer(GL_ARRAY_BUFFER, 0)
self.cuda_pbo = pycuda.gl.RegisteredBuffer(int(self.pbo))
self.cuda_img = pycuda.gl.RegisteredImage(int(self.texture), GL_TEXTURE_2D, pycuda.gl.graphics_map_flags.WRITE_DISCARD)
```

Rendering
```
## update buffer from Surface.PlanePtr()
src_plane=cvtSurface.PlanePtr()
buffer_mapping = self.cuda_pbo.map()
buffptr,buffsize=buffer_mapping.device_ptr_and_size()
cpy = pycuda.driver.Memcpy2D()
cpy.set_src_device(src_plane.GpuMem())
cpy.set_dst_device(buffptr)
cpy.width_in_bytes = src_plane.Width()
cpy.src_pitch = src_plane.Pitch()
cpy.dst_pitch = self.width*3
cpy.height = src_plane.Height()
cpy(aligned=True)
pycuda.driver.Context.synchronize()
buffer_mapping.unmap()
##update texture from buffer
glActiveTexture(GL_TEXTURE0)
glBindTexture(GL_TEXTURE_2D, self.texture)
glBindBuffer(GL_PIXEL_UNPACK_BUFFER, int(self.pbo))
glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0,self.width, self.height,GL_RGB, GL_UNSIGNED_BYTE, ctypes.c_void_p(0))
```


updated gist: https://gist.github.com/Yves33/f39454d3f0038f284a9959c1f8a5c3d8

**Comment by rarzumanyan** [comment]
Thanks a lot @Yves33 

Could you please submit your gist as an OpenGL sample?

**Comment by Yves33** [comment]
> Thanks a lot @Yves33
> 
> Could you please submit your gist as an OpenGL sample?

You mean make a pull request with updated samples? I may try (though not comfortable with git), but i need to polish the code a little bit (at least add command line argument parsing). Won't be able to test in windows or OSX

**Comment by rarzumanyan** [comment]
Hi @Yves33 

>Won't be able to test in windows or OSX

VPF is supported on Linux and Windows, and I will also test the PR before merging to `master` anyway.

**Comment by rarzumanyan** [comment]
Adding @sandhawalia to the thread.

We are planning to clean up existing VPF Samples and this is a good chance to add OpenGL Sample as well.
@sandhawalia, could you please give @Yves33 preparing a PR?

**Comment by rarzumanyan** [comment]
Closing this issue as fixed.
