### ISSUE TITLE
Allow EncodeSingleFrame use PyTorch GPU Tensor directly 

### ISSUE THREAD

**Issue by lamhoangtung** [NVIDIA/VideoProcessingFramework#315]
**Is your feature request related to a problem? Please describe.**
Hi. I had an end to end GPU processing pipeline in Python that based on VPF and PyTorch. Thanks to VPF, the incoming frame was decoded directly into a PyTorch GPU tensor and the final result was also modified directly on the PyTorch GPU tensor. I want VPF to be able to encode it directly instead of copy it to the CPU, thus remove any unnecessary device transfer

**Describe the solution you'd like**
Make `nvEnc.EncodeSingleFrame` allow PyTorch GPU Tensor directly. So something like this will be possible:
```python
encFrame = np.ndarray(shape=(0), dtype=np.uint8)
rawFrame = torch.randint(0, 255, (1080, 1920, 3), dtype=torch.uint8, device='cuda')
success = nvEnc.EncodeSingleFrame(rawFrame, encFrame, sync=False)
```

**Describe alternatives you've considered**
None

**Additional context**
Is this possible? I'm sure it is.
Will it require lots of work to achieve this? I'm happy to help with some guidance. Thanks for checking by ^^

**Comment by rarzumanyan** [comment]
Hi @lamhoangtung 

> want VPF to be able to encode it directly instead of copy it to the CPU, thus remove any unnecessary device transfer

You don't have to download video frame to RAM, `PyNvEncoder` can take input from vRAM as well. There's a `EncodeSingleSurface` method for that. Basically you do this in 2 steps:

1. Import torch tensor in VPF `Surface`
2. Encode VPF `Surface` with `EncodeSingleSurface` method.

Here's how it's done in one of my projects:

```python
def encode_from_tensor(self, tensor: torch.Tensor):
    """Encode single video frame from torch.cuda.FloatTensor.
    Tensor must have planar RGB format and be normalized to range [0.0; 1.0].
    Shape of the tensor must be (3, height, width).
    """
    if len(tensor.shape) != 3 and tensor.shape[0] != 3:
        raise RuntimeError(
            'Shape of the tensor must be (3, height, width)')

    tensor_w, tensor_h = tensor.shape[2], tensor.shape[1]
    if tensor_w != self.width():
        raise RuntimeError('Invalid input width.')

    if tensor_h != self.height():
        raise RuntimeError('Invalid input height.')

    tensor = torch.clamp(tensor, 0.0, 255.0)
    img = torch.multiply(tensor, 255.0)
    img = img.type(dtype=torch.cuda.ByteTensor)

    rgb_planar = nvc.Surface.Make(
        nvc.PixelFormat.RGB_PLANAR, tensor_w, tensor_h, self.gpu_id)
    rgb_planar.PlanePtr().Import(img.data_ptr(), tensor_w, self.gpu_id)

    cc_ctx = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601,
                                                nvc.ColorRange.MPEG)
    yuv444 = self.to_yuv.Execute(rgb_planar, cc_ctx)
    if yuv444.Empty():
        raise RuntimeError('Can not convert to yuv444.')

    encFrame = np.ndarray(shape=(0), dtype=np.uint8)
    success = self.nvEnc.EncodeSingleSurface(yuv444, encFrame)
    if success:
        encByteArray = bytearray(encFrame)
        self.fout.write(encByteArray)
```

For the best quality I'm using YUV444 encode format in this code snippet, but you can do NV12 as well.

**Comment by lamhoangtung** [comment]
Thanks a lot for the quick reply @rarzumanyan
