### ISSUE TITLE
Got Segmentation Fault While Creating PyNvDecoder Instance

### ISSUE THREAD

**Issue by BoRueiHong** [NVIDIA/VideoProcessingFramework#318]
Hi @rarzumanyan,
    First, thank for offer this awesome repo. I just encounter the issue when trying to run the sample code.
Did I miss something?

**Environment Setup**
Basically, I follow [wiki](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source#build-procedure-details-for-linux-users) to setup.
 - OS: Linux Ubuntu 18.04
 - Nvidia driver version: 470.103.01
 - CUDA Version: 11.4
 - Video Codec SDK Version: 11.1.5
 - Python Version: 3.6.9
 - FFMPEG Version: n4.3.3
 
**Description**
When I execute Test.py, I got
![Screenshot from 2022-04-08 15-38-06](https://user-images.githubusercontent.com/17445403/162388898-048f20ce-212e-465a-8c50-b94a3e2c7b16.png)

Finally, I found out that failed start from create ```PyNvDecoder```.
Here is my personal testing code:
```
import PyNvCodec as nvc

encFile="./test.mp4"
nvDec = nvc.PyNvDecoder(encFile, 1)
```
, and the part of gdb backtrace log:
![Screenshot from 2022-04-08 15-40-10](https://user-images.githubusercontent.com/17445403/162389645-d2249043-b258-4796-8077-c4f5e5b74f13.png)

Thank in advance.

**Comment by rarzumanyan** [comment]
Hi @BoRueiHong 
Couple points on this topic:

- I shall remove Tests.py file, it's substitued already with better tests which are located in `Tests` subdirectory.
- If you're willing to see what's happening in the C++ part, could you please build VPF in debug mode to see what's happening in the backtrace?

**Comment by BoRueiHong** [comment]
Hi @rarzumanyan 
  Thank for reply.
- If you're willing to see what's happening in the C++ part, could you please build VPF in debug mode to see what's happening in the backtrace?
  >>After I add the ```CMAKE_BUILD_TYPE=DEBUG``` flag and using gdb to get the info again. The backtrace represent as follow:
![Screenshot from 2022-04-10 17-05-54](https://user-images.githubusercontent.com/17445403/162611015-fac2392c-83ce-4299-84e7-bbece1169266.png)
![Screenshot from 2022-04-10 17-17-42](https://user-images.githubusercontent.com/17445403/162611445-2c3e9662-483a-4f19-a9c9-b8b8bd98721a.png)
![Screenshot from 2022-04-10 17-18-05](https://user-images.githubusercontent.com/17445403/162611449-c4b9ed8b-25f5-42e2-bd1c-75a49a51ec25.png)

  >> Since it crash in FFmpegDemuxer.cpp:523 so I try to check this line. And the problem is my ```codecpar``` is a ```nullptr```.

- The sample code I run:
```
import PyNvCodec as nvc

encFile="./test.mp4"
nvDec = nvc.PyNvDecoder(encFile, 1)
```
This is what I check so far. Still deep diving into the codebase.
