### ISSUE TITLE
Can you provide an example of RTMP'S GPU decoding?

### ISSUE THREAD

**Issue by positive666** [NVIDIA/VideoProcessingFramework#321]
Hello, I decode GPU relative to RTMP to improve the program utilization of GPU. Can you provide an example?

**Comment by rarzumanyan** [comment]
Hi @positive666 

Not sure if I fully understand the request but you may follow `SampleDecodeRTSP.py`. It's not specific to RTSP protocol and shall be fine working with RTMP as well.

**Comment by positive666** [comment]
> Hi @positive666
> 
> Not sure if I fully understand the request but you may follow `SampleDecodeRTSP.py`. It's not specific to RTSP protocol and shall be fine working with RTMP as well.
Ok, I’ll try it, but can this demo link to the model reference?

**Comment by rarzumanyan** [comment]
Hi @positive666 

>can this demo link to the model reference?

I'm not sure if I fully understand you.
If you're interested in running live ML inference on video frames, then the answer is yes.
You can combine `SampleDecodeRTSP.py` with `SampleTorchResnet.py` and run your ML model on decoded video frames in GPU memory without any Host <> Device copies.

**Comment by contentis** [comment]
Can we close this?
