### ISSUE TITLE
Questions about installing VPF with PyTorch extension

### ISSUE THREAD

**Issue by Renzzauw** [NVIDIA/VideoProcessingFramework#322]
Hi!

First, I should mention my knowledge of building using CMake is relatively limited, so perhaps my issues are easily solvable & something went wrong during installation. 

I have managed to install the VideoProcessingFramework as explained by the "Building from source" page, including the PyTorch extension. 
The make process seems to have run successfully, and I am able to run SampleDecode.py. I used the following CMake parameters to install:
```
cmake .. \
-DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
-DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
-DGENERATE_PYTHON_BINDINGS:BOOL="1" \
-DGENERATE_PYTORCH_EXTENSION:BOOL="1" \
-DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" \
-DPYTHON_LIBRARY=/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so \
-DPYTHON_EXECUTABLE=/usr/bin/python3.8 \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.8
```

However, when I try to run SamplePyTorch.py, it states it cannot find the module:
```
/usr/bin/python3.8 /home/renzo/install/VideoProcessingFramework/install/bin/SamplePyTorch.py
Traceback (most recent call last):
  File "/home/renzo/install/VideoProcessingFramework/install/bin/SamplePyTorch.py", line 46, in <module>
    import PytorchNvCodec as pnvc
ModuleNotFoundError: No module named 'PytorchNvCodec'
```
The specified python version (3.8) includes PyTorch, so I am not sure why it is not able to find the module. Did I do something wrong?

A different issue I have is, when I copy SampleDecode.py to a different folder than /install/bin (let's say to ~/Documents/) and try to run this code, it does not seem to recognize the module PyNvCodec:
```
python3 ~/Documents/SampleDecode.py 

/home/renzo/install/VideoProcessingFramework/install/bin:~ffmpeg_build/lib:
Traceback (most recent call last):
  File "/home/renzo/Documents/SampleDecode.py", line 23, in <module>
    import PyNvCodec as nvc
ModuleNotFoundError: No module named 'PyNvCodec'
```
Is there a way to use VPF on different locations on my system, or can I only run code in the /install/bin directory?

Many thanks in advance!

**Comment by rarzumanyan** [comment]
Hi @Renzzauw 

>ModuleNotFoundError: No module named 'PytorchNvCodec'

Can you see a module named like `PytorchNvCodec.cpython-38-x86_64-linux-gnu.so` in your `$INSTALL_PREFIX` folder?

**Comment by Renzzauw** [comment]
Hi @rarzumanyan, thanks for your reply.

I do see it in my $INSTALL_PREFIX directory.

**Comment by rarzumanyan** [comment]
@Renzzauw let's approach it step by step.

>when I copy SampleDecode.py to a different folder than /install/bin (let's say to ~/Documents/) and try to run this code, it does not seem to recognize the module PyNvCodec

>when I try to run SamplePyTorch.py, it states it cannot find the module:

VPF doesn't modify `PYTHONPATH` or put any python modules to system locations. It just export it's C++ libraries to modules `PyNvCodec` and `PytorchNvCodec`. Hence there are 2 possible options:

- Keep VPF modules and libraries in same folder as your script.
- Modify `PYTHONPATH` and  `LD_LIBRARY_PATH` if you want to keep them somewhere else.

First thing first I recommend you to make sure you can run all the samples. 
To do that please verify that you see following libraries and modules in the same folder as your samples:

- libTC_CORE.so
- libTC.so
- PyNvCodec.cpython-38-x86_64-linux-gnu.so
- PytorchNvCodec.cpython-38-x86_64-linux-gnu.so

If all these files are in the same folder as your samples and you still can't run some of them - please let me know.

**Comment by Renzzauw** [comment]
@rarzumanyan 
I am able to find all the files you listed, but in different locations.

The first three are located in the /install/bin/ directory, however the PytorchNvCodec.cpython-38-x86_64-linux-gnu.so was located one level above (in the /install/ directory). 

When I moved this file to the /install/bin/ directory, SamplePytorch.py seems to run error-free now, so I think this is what was causing the problem regarding the PyTorch module. Could this be caused by an error during the CMake installation process, or did I do something wrong?

Additionally, thanks for answering the question about running VPF in other system locations, that makes it a lot more clear for me now!

**Comment by rarzumanyan** [comment]
@Renzzauw 

>Could this be caused by an error during the CMake installation process, or did I do something wrong?

It was caused by small bug in CMake file which I've recently fixed.
All install targets were put into `bin` subdirectory of install folder except `PytorchNvCodec`.
Thanks for bringing this up and please update to latest `master` branch, this issue shall be fixed now.

**Comment by Renzzauw** [comment]
@rarzumanyan 
Thanks for quickly solving the issue & answering my questions! I will close this issue.
