### ISSUE TITLE
SampleDecodeMultiThread.py decode rtsp stream error

### ISSUE THREAD

**Issue by pzyang613** [NVIDIA/VideoProcessingFramework#325]
**Describe the bug**
there is an error when I try to decode camera rtsp stream using SampleDecodeMultiThread.py
the cmd is:
     python3 SampleDecodeMultiThread.py 0 rtsp://admin:admin123@192.168.1.64:554/h264/ch1/main/av_stream 1
the error info is below:
**Expected behavior**
root@ubuntu-ai:/home/VideoProcessingFramework-1.1.2/install/bin# python3 SampleDecodeMultiThread.py 0 rtsp://admin:admin123@192.168.1.64:554/h264/ch1/main/av_stream 1
This sample decodes video streams in parallel threads. It does not save output.
GPU-accelerated color conversion and resize are also applied.
This sample may serve as a stability test.
Usage: python SampleDecodeMultiThread.py $gpu_id $input $num_threads
[rtsp @ 0x1f80800] max delay reached. need to consume packet
[rtsp @ 0x1f80800] RTP: missed 30 packets
[h264 @ 0x1f84480] concealing 4700 DC, 4700 AC, 4700 MV errors in I frame
Color space:  ColorSpace.BT_709
Color range:  ColorRange.JPEG
Decode Error occurred for picture 2
HW decoder faced error. Re-create instance.
HW decoder reset time: 11 milliseconds
Continue after HW decoder was reset
/home/VideoProcessingFramework-1.1.2/PyNvCodec/TC/src/NvDecoder.cpp:213
CUDA error: CUDA_ERROR_INVALID_CONTEXT
invalid device context

Decoder not initialized.Cuvid parser faced error.
Cuvid parser exception happened.
HW reset
Exception in thread Thread-1:
Traceback (most recent call last):
  File "SampleDecodeMultiThread.py", line 96, in run
    self.rawSurface = self.nvDec.DecodeSingleSurface()
PyNvCodec.CuvidParserException: HW reset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "SampleDecodeMultiThread.py", line 130, in run
    fout.close()
NameError: name 'fout' is not defined

**Desktop (please complete the following information):**
 - OS: [Linux]
  - Nvidia driver version 450.51.05
 - CUDA Version [11.0]
 - Video Codec SDK Version [10.0.26]
 - Python Version [3.8]]
 - FFmpeg Version [4.1.6]

**Additional context**
how can i find the problem? thanks a lot.

**Comment by rarzumanyan** [comment]
@pzyang613 

Please follow `SampleDecodeRTSP.py`.
