### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Chen94yue** [NVIDIA/VideoProcessingFramework#33]
I follow the wiki to build.

[root@prod-cloudserver-gpu080 build]# make
Scanning dependencies of target TC_CORE
[  7%] Building CXX object PyNvCodec/TC/TC_CORE/CMakeFiles/TC_CORE.dir/src/Task.cpp.o
[ 14%] Building CXX object PyNvCodec/TC/TC_CORE/CMakeFiles/TC_CORE.dir/src/Token.cpp.o
[ 21%] Linking CXX shared library libTC_CORE.so
[ 21%] Built target TC_CORE
Scanning dependencies of target TC
[ 28%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/MemoryInterfaces.cpp.o
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'void VPF::SurfacePlane::Allocate()':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:224:55: error: 'runtime_error' was not declared in this scope
     throw runtime_error("Failed to do cuMemAllocPitch");
                                                       ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceY::Width(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:308:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceY::WidthInBytes(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:316:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceY::Height(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:324:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceY::Pitch(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:332:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual CUdeviceptr VPF::SurfaceY::PlanePtr(uint32_t)':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:340:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceNV12::Width(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:375:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceNV12::WidthInBytes(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:386:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceNV12::Height(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:398:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceNV12::Pitch(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:409:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual CUdeviceptr VPF::SurfaceNV12::PlanePtr(uint32_t)':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:421:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceYUV420::Width(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:465:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceYUV420::WidthInBytes(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:479:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceYUV420::Height(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:493:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceYUV420::Pitch(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:507:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual CUdeviceptr VPF::SurfaceYUV420::PlanePtr(uint32_t)':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:521:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceRGB::Width(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:567:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceRGB::WidthInBytes(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:575:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceRGB::Height(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:583:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceRGB::Pitch(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:591:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual CUdeviceptr VPF::SurfaceRGB::PlanePtr(uint32_t)':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:599:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceRGBPlanar::Width(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:632:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceRGBPlanar::WidthInBytes(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:640:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceRGBPlanar::Height(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:648:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual uint32_t VPF::SurfaceRGBPlanar::Pitch(uint32_t) const':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:656:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In member function 'virtual CUdeviceptr VPF::SurfaceRGBPlanar::PlanePtr(uint32_t)':
/opt/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:664:48: error: 'invalid_argument' was not declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/src/MemoryInterfaces.cpp.o] Error 1
make[1]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
make: *** [all] Error 2

**Comment by Chen94yue** [comment]
I annotated these lines.

**Comment by rarzumanyan** [comment]
Hi @Chen94yue 
There's a missed `#include <stdexcept>` inclusion in PyNvCodec/TC/src/MemoryInterfaces.cpp file. It's often included by default under both Linux and Windows so I've missed. 

I've added that to **mt_fixes** branch. Please use this branch instead of master for now, it has some multi-gpu and multi-thread issues fixes which I've not yet merged to master.

**Comment by cytheria43** [comment]
> Hi @Chen94yue
> There's a missed `#include <stdexcept>` inclusion in PyNvCodec/TC/src/MemoryInterfaces.cpp file. It's often included by default under both Linux and Windows so I've missed it.
> 
> I've added that to **mt_fixes** branch. Please use this branch instead of master for now, it has some multi-gpu and multi-thread issues fixes which I've not yet merged to master.

Hi @rarzumanyan 
I meet the same build  error ,and it happens the same whatever i make in the mt_fixes branch or master .How can I make success when I have two gpu
