### ISSUE TITLE
Failed to convert decoded RTMP to RGB

### ISSUE THREAD

**Issue by glode515** [NVIDIA/VideoProcessingFramework#331]
I use pysurfaceconverter and pysurfacedownloader to convert the decoded RTSP into RGB image and save it; However, RTMP conversion failed and the following error is output：

This sample decodes multiple videos in parallel on given GPU.
It doesn't do anything beside decoding, output isn't saved.
Usage: SampleDecodeRTSP.py $gpu_id $url1 ... $urlN .
surface_nv12 is not empty!
Rec. 601 NV12 -> BGR MPEG range conversion isn't supported yet.
Convert NV12 -> YUV first and then do Rec. 601 YUV -> BGR MPEG range conversion.
MakeUnsupported pixeld format: 6
Process Process-1:
Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/py38_torch1.7_yolov5/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/psdz/anaconda3/envs/py38_torch1.7_yolov5/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "SampleDecodeRTSP.py", line 232, in rtsp_client
    if surface_bgr.Empty():
AttributeError: 'NoneType' object has no attribute 'Empty'

**Comment by vip404** [comment]
did you resovled this? I also encountered this problem. rtsp camera ,10 cameras can decode normally，one has this  problem and they  'codec_long_name': both are H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
`   params = get_stream_params(url)
             if not len(params):
                 raise ValueError("Can not get " + url + ' streams params')
             gpu_id = 0
             w = params['width']
             h = params['height']
             f = params['format']
             c = params['codec']
             g = gpu_id
             frameSize = int(w*h*3)
             rawFrame = np.ndarray(shape=(frameSize), dtype=np.uint8)
             # Prepare ffmpeg arguments
             if nvc.CudaVideoCodec.H264 == c:
                 codec_name = 'h264'
             elif nvc.CudaVideoCodec.HEVC == c:
                 codec_name = 'hevc'
             bsf_name = codec_name + '_mp4toannexb,dump_extra=all'
             
             cmd = [
                 'ffmpeg',       '-hide_banner',  
                 '-loglevel',   'quiet',
                 '-i',           url,
                 '-c:v',         'copy',
                 '-bsf:v',       bsf_name,
                 '-f',           codec_name,
                 'pipe:1'
             ]
             # Run ffmpeg in subprocess and redirect it's output to pipe
             proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
             
             cuda.init()
             cuda_ctx = cuda.Device(gpu_id).retain_primary_context()
             cuda_ctx.push()
             cuda_str = cuda.Stream()
             cuda_ctx.pop()
             
             # Create HW decoder class
             nvdec = nvc.PyNvDecoder(w, h, f, c, g)
             nvCvt = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.NV12, nvc.PixelFormat.BGR, cuda_ctx.handle, cuda_str.handle)
             nvDwn = nvc.PySurfaceDownloader(w, h, nvCvt.Format(), cuda_ctx.handle, cuda_str.handle)
        
             cc_ctx = None
             
             # Amount of bytes we read from pipe first time.
             read_size = 4096
             # Total bytes read and total frames decded to get average data rate
             rt = 0
             fd = 0
             
             # Main decoding loop, will not flush intentionally because don't know the
             # amount of frames available via RTSP.
             count = 1; 
      
             while runningFlag.value:
               # Pipe read underflow protection
                 count+=1
                 try:
                   if not read_size:
                       read_size = int(rt / fd)
                       # Counter overflow protection
                       rt = read_size
                       fd = 1
                 
                   # Read data.
                   # Amount doesn't really matter, will be updated later on during decode.
                   bits = proc.stdout.read(read_size)
                   if not len(bits):
                       print("Can't read data from pipe")
                       self.imgs[i] = np.zeros_like(self.imgs[i])
                       print(  "now=" +  time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + " error and restart "  + url)
                       nvdec =None
                       nvCvt =None 
                       nvDwn =None            
                       break
                   else:
                       rt += len(bits)
                 
                   # Decode
                   enc_packet = np.frombuffer(buffer=bits, dtype=np.uint8)
                   pkt_data = nvc.PacketData()
             
                   surface_nv12 = nvdec.DecodeSurfaceFromPacket(enc_packet, pkt_data)
                   # and count % 10 == 0
                   if not surface_nv12.Empty(): 
                       fd += 1
                       # Shifts towards underflow to avoid increasing vRAM consumption.
                       if pkt_data.bsl < read_size:
                           read_size = pkt_data.bsl
                       # Print process ID every second or so.
                       fps = int(params['framerate'])
                       #if not fd % fps:
                       #    print(name)
                       #print(params)
             
                       if cc_ctx is None:
                           cspace = params['color_space']
                           crange = nvc.ColorRange.MPEG
                           cc_ctx = nvc.ColorspaceConversionContext(cspace, crange)
             
                       surface_bgr = nvCvt.Execute(surface_nv12, cc_ctx)
                       if surface_bgr == None or surface_bgr.Empty():
                             
                            break
                       if not nvDwn.DownloadSingleSurface(surface_bgr, rawFrame):
                           
                            break
                 
                       img_bgr = rawFrame.reshape((h, w, 3))
                       #frame = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
                       cv2.imshow(str(i), img_bgr)
                       cv2.waitKey(1)  # 1 millisecond`

**Comment by gedoensmax** [comment]
@vip404 am i getting this wrong or is the issue that you would just have to do an intermediate step to 420 ? 
`nvCvt = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.NV12, nvc.PixelFormat.BGR, cuda_ctx.handle, cuda_str.handle)`
Essentially do this in 2 conversion setps.
