### ISSUE TITLE
Cmake build failure on pop_OS

### ISSUE THREAD

**Issue by abyaadrafid** [NVIDIA/VideoProcessingFramework#334]
Hello, 

I am trying to build vpf from source and having some issues. I was following the wiki for installation.
At first make couldn't find cuda.h 
![Screenshot from 2022-05-19 17-43-02](https://user-images.githubusercontent.com/21219461/169341816-14577b88-80ea-4395-af59-47adc732562b.png)
So I found this issue and followed the suggestions: https://github.com/NVIDIA/VideoProcessingFramework/issues/11
I set the CXXFLAGS like so : 
![image](https://user-images.githubusercontent.com/21219461/169344767-dc91d2d4-1099-480f-a652-d878b4074e94.png)
This is the cmake output after doing it : 
![Screenshot from 2022-05-19 17-58-10](https://user-images.githubusercontent.com/21219461/169345390-c2c2b055-0a40-4821-9447-44ea53362675.png)
And this is the output of make :
![image](https://user-images.githubusercontent.com/21219461/169346416-a1d9dc37-cb6e-4a81-8e21-8a421f3d1236.png)

Some pointers on how to solve this would be super helpful.
Thanks.

**Comment by rarzumanyan** [comment]
Hi @abyaadrafid 

What compiler do you use and what's the version?

**Comment by rarzumanyan** [comment]
That's a bit strange honestly.
Any chance you can update to gcc or clang? 

P. S.
This is how you can select default C and C++ compiler:

```
$ update-alternatives --query c++
Name: c++
Link: /usr/bin/c++
Slaves:
 c++.1.gz /usr/share/man/man1/c++.1.gz
Status: auto
Best: /usr/bin/g++
Value: /usr/bin/g++

Alternative: /usr/bin/g++
Priority: 20
Slaves:
 c++.1.gz /usr/share/man/man1/g++.1.gz
```

**Comment by abyaadrafid** [comment]
Thanks for the tip, I tried it but still have the same error. GCC version is 9.4.0. 
I set the cmake compiler to gcc by following [cmake wiki](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#method-1-use-environment-variables) : `export CXX=/usr/bin/gcc`

make output shows the change : 
![Screenshot from 2022-05-24 12-56-49](https://user-images.githubusercontent.com/21219461/170020278-7ad115dc-358e-4476-a81c-a6a33f1b0c5c.png)
But the error is still there : 
![Screenshot from 2022-05-24 12-59-01](https://user-images.githubusercontent.com/21219461/170020332-88f1d98d-c9ed-4bd7-a26b-407aca88153e.png)

**Comment by rarzumanyan** [comment]
@abyaadrafid 

>I set the cmake compiler to gcc by following

Not sure if that helped because console output is same as before.
Could you try `update-alternatives --query c++`?
