### ISSUE TITLE
h264 stream，YUV -> BGR

### ISSUE THREAD

**Issue by wojiazaiyugang** [NVIDIA/VideoProcessingFramework#336]
I have a camera, I get the video frame in the callback function, the video frame is in YUV format, I want to convert it to BGR numpy format of OpenCV, which functions should I call?

**Comment by rarzumanyan** [comment]
Hi @wojiazaiyugang 

Please follow one of the VPF samples which illustrates how to use `PySurfaceConverter` class, e. g. `SampleDemuxDecode.py`.
