### ISSUE TITLE
NTP Timestamp from Frame

### ISSUE THREAD

**Issue by bobbych** [NVIDIA/VideoProcessingFramework#337]
When running `sampleDecodeRTSP` I am able to get images and convert them to RGB. However, I would like to get absolute NTP time stamp of the `PacketData`. Is there a way get this in `vpf`.

Environment: Ubuntu 20.04,  A40 GPU, Docker 20.10.06

Thank you!

**Comment by rarzumanyan** [comment]
Hi @bobbych 

>I would like to get absolute NTP time stamp of the PacketData

VPF uses FFMpeg for demuxing, hence it takes compressed video frames either in form of `AVPacket` or Annex.B NALU. Unfortunately both input structures don't contain NTP timestamps, so your request can't be implemented within VPF.

`SampleDecodeRTSP.py` relies on FFMpeg process to obtain data over network and demux it to Annex.B NALU so I can only recommend you to search if FFMpeg can extract this data (which I assume is part of a network protocol).
