### ISSUE TITLE
Get Wrong SEI message when use DecodeSingleSurface

### ISSUE THREAD

**Issue by zjdneos** [NVIDIA/VideoProcessingFramework#339]
**Describe the bug**
When I want to get decoded frame and it's SEI message, I use nvc.DecodeSingleSurface(sei). But I get the wrong SEI, for example, I get the first frame with the 7th SEI message, they are misplaced. And for the last 7 frame, I got None SEI.

And when I use ffmpeg's av_read_frame() function, and get sei from the packet, I can get all the matched SEI.

**To Reproduce**

`
    import PyNvCodec as nvc
    import numpy as np
    nvDec = nvc.PyNvDecoder('test.h264', 0)
    frame_count = 0
    while True:
        sei = np.ndarray(shape=(0), dtype=np.uint8)
        surf = nvDec.DecodeSingleSurface(sei)
        if surf.Empty():
            break
        print(f'frame_count: {count}, SEI: ', sei.shape, sei)
        frame_count += 1
`

**Expected behavior**
![image](https://user-images.githubusercontent.com/13230707/172286328-14349aac-c303-4579-9b4c-c4d411436aa7.png)

**Desktop (please complete the following information):**
 - OS:  Linux, ubuntu 20.04 LTS
 - Nvidia driver version: 470.82.01
 - CUDA Version: 11.04
 - Video Codec SDK Version: 10.0.26
 - Python Version: 3.8

**Comment by rarzumanyan** [comment]
Hi @zjdneos 

Can you share the video?

**Comment by gedoensmax** [comment]
@zjdneos Can this be closed or can you provide the video ?
