### ISSUE TITLE
new make error

### ISSUE THREAD

**Issue by Chen94yue** [NVIDIA/VideoProcessingFramework#34]
make[2]: *** No rule to make target `/usr/lib64/libpython3.6m.so', needed by `PyNvCodec/PyNvCodec.cpython-36m-x86_64-linux-gnu.so'.  Stop.
make[1]: *** [PyNvCodec/CMakeFiles/PyNvCodec.dir/all] Error 2
make: *** [all] Error 2

**Comment by rarzumanyan** [comment]
Can you upload the cmd lines with which you're building from sources + CMake output?
