### ISSUE TITLE
Fix windows build

### ISSUE THREAD

**Issue by LitingLin** [NVIDIA/VideoProcessingFramework#341]
https://github.com/NVIDIA/VideoProcessingFramework/blob/94d3a05e9732824467448fe774a6f758ac829619/PyNvCodec/TC/inc/NvCodecCLIOptions.h#L31
should be prefixed with ```DllExport```
```C++
DllExport std::list<std::string> GetNvencInitParams(); 
```

**Comment by rarzumanyan** [comment]
Hi @LitingLin 

Do you consider sending a PR with this fix?

**Comment by LitingLin** [comment]
ok, sent PR.
