### ISSUE TITLE
Minimal and Maximal image size

### ISSUE THREAD

**Issue by yuval-vi** [NVIDIA/VideoProcessingFramework#345]
Hi @rarzumanyan,
Thanks for all the great work! 

Can you please inform me / point to a documentation of - what are the minimal and maximal sizes (in terms of resolution) of inputs to the encoder and decoder?

Thanks 🙏

**Comment by rarzumanyan** [comment]
Hi @yuval-vi 

It depends on the HW and can be queried with Video Codec SDK API. There's increasing number of similar requests on this topic.
So I assume I shall add couple methods for that in `issue_345` feature branch and will update you in this thread a bit later.

**Comment by yuval-vi** [comment]
Thanks @rarzumanyan! Will be using this.
