### ISSUE TITLE
Thanks ！Does VPF got method to skip one frame（or Surface） from video stream？

### ISSUE THREAD

**Issue by Airuio** [NVIDIA/VideoProcessingFramework#346]
**Describe the solution you'd like**
In opencv， if i want to skip some frame i would use:
cap.grab()
It would be faster, if this frame is useless for me.

Does VPF got method to skip one frame（or Surface） from video stream？
or
How can i make it faster if i just want gap N frame after every time i really decode a surface with VPF?
Thanks!

**Comment by rarzumanyan** [comment]
Closing as clone of #347
