### ISSUE TITLE
How to build and install on windows

### ISSUE THREAD

**Issue by momohuangsha** [NVIDIA/VideoProcessingFramework#349]
win10 
cuda10.2
Video_Codec_SDK_11.1.5
anaconda env python3.6.3
i follow  https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source 
![1](https://user-images.githubusercontent.com/48303586/177670712-8fe4ff35-8883-47d8-b310-a14f84b4bcd6.jpg)
then, I encountered such a problem when i run SampleDecodeRTSP.py：
![image](https://user-images.githubusercontent.com/48303586/177670773-e600e4a0-d74e-442e-bac8-5c8fc9fd2be9.png)
I don't know how to install：6 “Open Visual Studio project & build the INSTALL target”
![image](https://user-images.githubusercontent.com/48303586/177671018-02bc34e2-2e85-4003-b736-c8193d9d0003.png)
![image](https://user-images.githubusercontent.com/48303586/177672592-9b8cf357-cd07-4226-85fe-934dd3d70349.png)

**Comment by rarzumanyan** [comment]
Hi @momohuangsha 

Unfortunately I can't understand Visual Studio error messages.
To me it looks like context-managed NPP functions can't be found on your machine. Please update your CUDA SDK to latest available version.

**Comment by momohuangsha** [comment]
> Hi @momohuangsha
> 
> Unfortunately I can't understand Visual Studio error messages. To me it looks like context-managed NPP functions can't be found on your machine. Please update your CUDA SDK to latest available version.

@rarzumanyan   Thanks a lot ！Next, I'm going to upgrade CUDA to 11.4, and then try again

**Comment by zhanghongyong123456** [comment]
> win10 cuda10.2 Video_Codec_SDK_11.1.5 anaconda env python3.6.3 i follow https://github.com/NVIDIA/VideoProcessingFramework/wiki/Building-from-source ![1](https://user-images.githubusercontent.com/48303586/177670712-8fe4ff35-8883-47d8-b310-a14f84b4bcd6.jpg) then, I encountered such a problem when i run SampleDecodeRTSP.py： ![image](https://user-images.githubusercontent.com/48303586/177670773-e600e4a0-d74e-442e-bac8-5c8fc9fd2be9.png) I don't know how to install：6 “Open Visual Studio project & build the INSTALL target” ![image](https://user-images.githubusercontent.com/48303586/177671018-02bc34e2-2e85-4003-b736-c8193d9d0003.png) ![image](https://user-images.githubusercontent.com/48303586/177672592-9b8cf357-cd07-4226-85fe-934dd3d70349.png)
Thank you very much for compiling the command.I compiled it according to your Settings，How do I use it

**Comment by gedoensmax** [comment]
Can this be closed or are there more problems?

**Comment by gedoensmax** [comment]
This PR should make usage on windows easier. 
Resolved by #397
