### ISSUE TITLE
Twice the Value

### ISSUE THREAD

**Issue by raokost** [NVIDIA/VideoProcessingFramework#351]
When I used mediainfo on a .h264 file it gave width and height as 400 and 600 respectively, but when I use nvDec.Width() and nvDec.Height() I get these values as 800 and 1200 respectively.

class Worker(Thread):
    global mapper
    global batcher
    def __init__(self, gpuID, encFile, lock, i):
        Thread.__init__(self)
        
        # Basic initializations
        self.lock = lock
        self.width = face_width
        self.height = face_height
        self.gpuID = gpu_id
        self.num_frame = 0
        self.id = i

        # Create Decoder with given CUDA context & stream.
        self.nvDec = nvc.PyNvDecoder(encFile, gpuID)
        
        width, height, format = int(self.nvDec.Width()), int(self.nvDec.Height()), self.nvDec.Format()
        
        # print(width, height)
        self.to_rgb = nvc.PySurfaceConverter(width, height, format, nvc.PixelFormat.RGB, gpuID)
        self.to_yuv = nvc.PySurfaceConverter(width, height, format, nvc.PixelFormat.YUV420, gpuID)
        self.nvDwn = nvc.PySurfaceDownloader(face_width, face_height, self.to_rgb.Format(), gpuID)
        self.cc_ctx = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601, nvc.ColorRange.MPEG)
        self.nvRes = nvc.PySurfaceResizer(face_width, face_height, self.to_yuv.Format(), gpuID)
        self.to_nv12 = nvc.PySurfaceConverter(face_width, face_height, nvc.PixelFormat.YUV420, format, gpuID)

    def run(self):
        try:
            while True:
                try:
                    self.rawSurface = self.nvDec.DecodeSingleSurface()
                    if (self.rawSurface.Empty()):
                        print('No more video frames')
                        break
                except nvc.HwResetException:
                    print('Continue after HW decoder was reset')
                    continue
 
                
                cvtSurface1 = self.to_yuv.Execute(self.rawSurface, self.cc_ctx)
                resSurface = self.nvRes.Execute(cvtSurface1)
                cvtSurface = self.to_nv12.Execute(resSurface, self.cc_ctx)
                
                if (cvtSurface.Empty()):
                    print('Failed to do color conversion')
                    break

                rawFrame = np.ndarray(shape=(3, self.height, self.width), dtype=np.uint8)
                success = self.nvDwn.DownloadSingleSurface(cvtSurface, rawFrame)
                if not (success):
                    print('Failed to download surface')
                    break
                # print(rawFrame)
                
                self.lock.acquire()
                batcher.append(rawFrame)
                mapper.append(self.id)
                self.lock.release()
                
                if len(mapper) > batch_size:
                    to_server()
 
                self.num_frame += 1
                # print(self.num_frame)
                
                
        except Exception as e:
            print(getattr(e, 'message', str(e)))
            exit(2)

Running on GPU using a Linux Machine

**Comment by rarzumanyan** [comment]
Hi @raokost 

Please share the video file.

**Comment by gedoensmax** [comment]
@raokost can we get an update on this or the video file to investigate ?
