### ISSUE TITLE
HW decoder faced error. Re-create instance.

### ISSUE THREAD

**Issue by Airuio** [NVIDIA/VideoProcessingFramework#353]
**Describe the bug**
Run demo SampleDemuxDecode to decode video files under win10， Error：
Decode Error occurred for picture 56
HW decoder faced error. Re-create instance.
HW exception happened. Please reset class instance
I have see isseue #37、#47 and so on， cant help resolve the problem.
If this Frame is decode failed because frame broken，how could i make it just skip instead of exit running.’
By the way, some of video files could finish without error.
**Screenshots**
```
Color space:  ColorSpace.BT_709
Color range:  ColorRange.JPEG
Traceback (most recent call last):

  File "D:\vpf\VideoProcessingFramework\SampleDemuxDecode.py", line 128, in <module>
    decode(0, encFilePath, decFilePath)

  File "D:\vpf\VideoProcessingFramework\SampleDemuxDecode.py", line 90, in decode
    surface_nv12 = nvDec.DecodeSurfaceFromPacket(pdata_in, packet, pdata_out)

HwResetException: HW reset


Decode Error occurred for picture 56
HW decoder faced error. Re-create instance.
HW exception happened. Please reset class instance
Decode Error occurred for picture 50
HW decoder faced error. Re-create instance.
HW exception happened. Please reset class instance
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Nvidia driver version 456.87
 - CUDA Version 11.1
 - Video Codec SDK Version 11.1.5
 - Python Version 3.8

Thanks!

**Comment by Airuio** [comment]
I did，but dosen’t work as expect.
```
ret = nvDmx.DemuxSinglePacket(packet)
nvDmx.LastPacketData(pdata_in)
while ret:
    f = 0
    try:
        surface_nv12 = nvDec.DecodeSurfaceFromPacket(pdata_in, packet, pdata_out)
    except:
        print("Debug-1")
        # break
        ret = nvDmx.DemuxSinglePacket(packet)
        nvDmx.LastPacketData(pdata_in)
        continue
    if p%20 == 0:
        print(pdata_in.pos,pdata_in.pts,pdata_in.duration,pdata_in.bsl,p)
    
    
    while surface_nv12.Empty():
        try:
            surface_nv12 = nvDec.DecodeSurfaceFromPacket(pdata_in, packet, pdata_out)
            
            # print(p,pdata_in.pos,pdata_in.pts,pdata_in.duration,pdata_in.bsl)
        except:
            print("Debug-2")
            ret = nvDmx.DemuxSinglePacket(packet)
            nvDmx.LastPacketData(pdata_in)
            f = 1
            break
    
    if f:
        continue
```
 It just repeat decode failed，once there is a frame decode failed. （repeat print` Debug-1`）
And repeat print ：
```
HW decoder faced error. Re-create instance.
HW exception happened. Please reset class instance
```

**Comment by rarzumanyan** [comment]
>It just repeat decode failed，once there is a frame decode failed

Most likely something's wrong with the video.
This type of exception is thrown all the way from Video Codec SDK C API up to Python.
Try to decode it with different application which uses Video Codec SDK back-end (e. g. ffmpeg with `-hwaccel cuda` flag) to see the app behavior.

**Comment by Airuio** [comment]
`nvdec = nvc.PyNvDecoder(w, h, f, c, g) `
I will try this way, thanks!

**Comment by rarzumanyan** [comment]
@Airuio 

>I have tried to play this vedio with VLC and decode all frame with OpenCv-python (backen ffmpeg), it works well.

Please try Nvdec-accelerated application. Most ffmpeg builds support Video Codec SDK.
