### ISSUE TITLE
Call for feature----decode partially broken frame

### ISSUE THREAD

**Issue by Airuio** [NVIDIA/VideoProcessingFramework#354]
I have applied AI model on many WEB CAMERA , and  most of them would have some broken frames in stream due to different causes and it is unavoidable.
In practice, the broken frames could be play on videoplayer while part of the broken frames were blurry. And i used to use OpenCv to decode all the frames, it could decode most of broken frames while VPF would crash and restart. 
So, would u like to add the feature to VPF to support decode broken frames.
By the way, this project is really fantastic!

**Comment by rarzumanyan** [comment]
Hi @Airuio 

>And i used to use OpenCv to decode all the frames, it could decode most of broken frames while VPF would crash and restart.

VPF doesn't contain any code which does frame decode. It extracts compressed video frames from user input and submit those encoded frames to HW, then it accepts decoded frames as pixel arrays stored in CUDA memory.

Hence if broken frames are decoded with artifacts or cause HW exceptions - there's not to much VPF can do about that. BTW this is the reason I've asked you to decode your input with another application which has Video Codec SDK back-end (such as ffmpeg). I wanted to see if there's something which could be done on application side to mitigate the problem.


>I have applied AI model on many WEB CAMERA

ML inference on video frames taken from web camera(s) is probably one of the most popular VPF use cases and it's also one which causes the most problems. There's a dedicated [SampleDecodeRTSP.py](https://github.com/NVIDIA/VideoProcessingFramework/blob/master/SampleDecodeRTSP.py) which uses external ffmpeg process to deal with network input and put compressed video frames into pipe and VPF for the rest. It's more robust to data losses and decoder exceptions. If your camera uses protocol different from RTSP - that's not a problem, sample just take input URL and relies on ffmpeg for the data access.


>So, would u like to add the feature to VPF to support decode broken frames.

Given the explanation above, right now I think that this feature request isn't feasible. Hence I close the issue.
