### ISSUE TITLE
Encode Rtsp Stream to h264

### ISSUE THREAD

**Issue by Sayyam-Jain** [NVIDIA/VideoProcessingFramework#358]
I'm trying to encode and save RTSP stream to h264 stream, however, I'm getting green colored incorrect video. I've tried converting to YUV420 and NV12 before saving but can't get it work. Can you please help.
Thanks

```python
class NVDEC_Thread(Thread):
    def __init__(self, rtsp_url, file_name):
        super(NVDEC_Thread, self).__init__()
        self.rtsp_url = rtsp_url
        self.file_name = file_name

    def run(self):
        gpu_id = 0
        counter = 0
        # video_stream = self.camera_data['IP']
        res = str(1920) + 'x' + str(1080)
        rtsp_parameters = {'rtsp_transport': 'tcp', 'max_delay': '1', 'bufsize': '30000k',
                             'profile': 'high', 'bitrate': '10M'}

        nvEnc = nvc.PyNvEncoder({'preset': 'P5', 'tuning_info': 'high_quality', 'codec': 'h264',
                             'profile': 'high', 's': res, 'bitrate': '10M'}, 0)
        nv12FrameSize = int(nvEnc.Width() * nvEnc.Height() * 3)

        encFrame = np.ndarray(shape=(0), dtype=np.uint8)
        encFile = open(self.file_name, "wb")



        # Retain primary CUDA device context and create separate stream per thread.
        ctx = cuda.Device(gpu_id).retain_primary_context()
        ctx.push()
        cuda_stream = cuda.Stream()
        ctx.pop()

        # Create Decoder with given CUDA context & stream.
        nvDec = nvc.PyNvDecoder(self.rtsp_url, ctx.handle, cuda_stream.handle, rtsp_parameters)

        width, height = nvDec.Width(), nvDec.Height()

        # Determine colorspace conversion parameters.
        # Some video streams don't specify these parameters so default values
        # are most widespread bt601 and mpeg.
        cspace, crange = nvDec.ColorSpace(), nvDec.ColorRange()
        if nvc.ColorSpace.UNSPEC == cspace:
            cspace = nvc.ColorSpace.BT_601
        if nvc.ColorRange.UDEF == crange:
            crange = nvc.ColorRange.MPEG
        cc_ctx = nvc.ColorspaceConversionContext(cspace, crange)
        print('Color space: ', str(cspace))
        print('Color range: ', str(crange))

        # Initialize colorspace conversion chain
        if nvDec.ColorSpace() != nvc.ColorSpace.BT_709:
            nvYuv = nvc.PySurfaceConverter(width, height, nvDec.Format(), nvc.PixelFormat.YUV420,
                                            ctx.handle, cuda_stream.handle)

            nvCvt = nvc.PySurfaceConverter(width, height, nvYuv.Format(), nvc.PixelFormat.BGR,
                                           ctx.handle, cuda_stream.handle)

            nv12Cvt = nvc.PySurfaceConverter(width, height, nvYuv.Format(), nvc.PixelFormat.NV12,
                                           ctx.handle, cuda_stream.handle)
            nv12Dwn = nvc.PySurfaceDownloader(width, height, nvYuv.Format(), ctx.handle, cuda_stream.handle)
        else:
            # nvYuv = None
            nvYuv = nvc.PySurfaceConverter(width, height, nvDec.Format(), nvc.PixelFormat.YUV420,
                                            ctx.handle, cuda_stream.handle)
            nvCvt = nvc.PySurfaceConverter(width, height, nvDec.Format(), nvc.PixelFormat.BGR,
                                           ctx.handle, cuda_stream.handle)
            nv12Cvt = nvc.PySurfaceConverter(width, height, nvYuv.Format(), nvc.PixelFormat.NV12,
                                           ctx.handle, cuda_stream.handle)
            nv12Dwn = nvc.PySurfaceDownloader(width, height, nvYuv.Format(), ctx.handle, cuda_stream.handle)
            
        nvDwn = nvc.PySurfaceDownloader(width, height, nvCvt.Format(), ctx.handle, cuda_stream.handle)

        try:
            while True:
                try:
                    # rawSurface = nvDec.DecodeSingleSurface()
                    rawSurface = nvDec.DecodeSingleSurface()
                    ######
                    # Nv12Surface = rawSurface
                    # if (nvYuv.Format() == "YUV420"):
                    #     Nv12Surface = yuv2nv12.Execute(rawSurface, cc_ctx)

                    ######
                    if rawSurface.Empty():
                        print('No more video frames')
                        break
                except nvc.HwResetException:
                    print('Continue after HW decoder was reset')
                    continue

                if nvYuv:
                    yuvSurface = nvYuv.Execute(rawSurface, cc_ctx)
                    cvtSurface = nvCvt.Execute(yuvSurface, cc_ctx)
                    # nv12Surface = nv12Cvt.Execute(yuvSurface, cc_ctx)
                else:
                    yuvSurface = nvYuv.Execute(rawSurface, cc_ctx)
                    cvtSurface = nvCvt.Execute(rawSurface, cc_ctx)
                    # nv12Surface = nv12Cvt.Execute(yuvSurface, cc_ctx)
                # nv12Surface = nv12Cvt.Execute(yuvSurface, cc_ctx)
                if cvtSurface.Empty():
                    print('Failed to do color conversion')
                    break
                
                rawFrame = np.ndarray(shape=(nv12FrameSize), dtype=np.uint8)
                success = nv12Dwn.DownloadSingleSurface(yuvSurface, rawFrame)
                # rawFrame = np.ndarray(shape=(nv12FrameSize), dtype=np.uint8)
                # rawFrame = np.ndarray(shape=(nv12FrameSize), dtype=np.uint8)
                
                # rawFrame = np.fromfile(decFile, np.uint8, count=nv12FrameSize)
                # success = nvDwn.DownloadSingleSurface(cvtSurface, rawFrame)

                # enc_success = nvEnc.EncodeSingleFrame(rawFrame, encFrame, sync=False)
                if success:
                    enc_success = nvEnc.EncodeSingleFrame(rawFrame, encFrame, sync=False)
                    if(enc_success):
                        encByteArray = bytearray(encFrame)
                        encFile.write(encByteArray)
                        counter += 1
                        if counter %100 == 0:
                            encFile.close()
                            print("Break")
                            break

        except Exception as e:
            print(getattr(e, 'message', str(e)))
```

**Comment by Sayyam-Jain** [comment]
Hi, sorry to bother you again. I'm trying to save frames and convert them to rgb frames at the same time from RTSP.
However, I'm unable to convert the surface received from DecodeSurfaceFromPacket.

I receive error: **Failed to convert surface. Error code: -8**

My code:

`class NvDecRtspReader(Thread):
    def __init__(self, rtsp_url, file_name, gpu_id=0):
        super(NvDecRtspReader, self).__init__()
        self.rtsp_url = rtsp_url
        self.file_name = file_name
        self.gpu_id = gpu_id
        self.pipe = None
        self.nvdec = None
        self.ctx, self.cuda_stream = self.gpu_context()
        self.stream_parameters = self.get_stream_params()
        # self.cc_ctx = nvc.ColorspaceConversionContext(nvc.ColorSpace.UNSPEC, nvc.ColorRange.UDEF)
        self.cc_ctx = nvc.ColorspaceConversionContext(self.stream_parameters['color_space'], self.stream_parameters['color_range'])
        print(self.stream_parameters['color_space'], self.stream_parameters['color_range'])
        self.pipe_command = self.pipe_command()
        self.nvEnc = None
        self.encFrame = np.ndarray(shape=(0), dtype=np.uint8)
        self.encFile = open(self.file_name, "wb")

    def gpu_context(self):
        ctx = cuda.Device(self.gpu_id).retain_primary_context()
        ctx.push()
        cuda_stream = cuda.Stream()
        ctx.pop()
        return ctx, cuda_stream

    def pipe_command(self):
        if not len(self.stream_parameters):
            raise ValueError("Can not get " + self.rtsp_url + ' streams params')

        # w = params['width']
        # h = params['height']
        # f = params['format']
        # c = params['codec']
        # g = gpu_id

        # Prepare ffmpeg arguments
        if nvc.CudaVideoCodec.H264 == self.stream_parameters['codec']:
            codec_name = 'h264'
        elif nvc.CudaVideoCodec.HEVC == self.stream_parameters['codec']:
            codec_name = 'hevc'
        bsf_name = codec_name + '_mp4toannexb,dump_extra=all'

        cmd = [
            'ffmpeg', '-hide_banner',
            '-i', self.rtsp_url,
            '-c:v', 'copy',
            '-bsf:v', bsf_name,
            '-f', codec_name, 'pipe:1'
        ]
        return cmd
    
    def get_stream_params(self) -> Dict:
        cmd = [
            'ffprobe',
            '-v', 'quiet',
            '-print_format', 'json',
            '-show_format', '-show_streams', self.rtsp_url]
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
        stdout = proc.communicate()[0]

        bio = BytesIO(stdout)
        json_out = json.load(bio)

        params = {}
        if not 'streams' in json_out:
            return {}

        for stream in json_out['streams']:
            print(stream)
            if stream['codec_type'] == 'video':
                params['width'] = stream['width']
                params['height'] = stream['height']
                params['framerate'] = float(eval(stream['avg_frame_rate']))
                # params['color_space'] = stream['color_space']

                codec_name = stream['codec_name']
                is_h264 = True if codec_name == 'h264' else False
                is_hevc = True if codec_name == 'hevc' else False
                if not is_h264 and not is_hevc:
                    raise ValueError("Unsupported codec: " + codec_name +
                                    '. Only H.264 and HEVC are supported in this sample.')
                else:
                    params['codec'] = nvc.CudaVideoCodec.H264 if is_h264 else nvc.CudaVideoCodec.HEVC

                    pix_fmt = stream['pix_fmt']
                    is_yuv420 = pix_fmt == 'yuv420p'
                    is_yuv444 = pix_fmt == 'yuv444p'

                    # YUVJ420P and YUVJ444P are deprecated but still wide spread, so handle
                    # them as well. They also indicate JPEG color range.
                    is_yuvj420 = pix_fmt == 'yuvj420p'
                    is_yuvj444 = pix_fmt == 'yuvj444p'

                    if is_yuvj420:
                        is_yuv420 = True
                        params['color_range'] = nvc.ColorRange.JPEG
                    if is_yuvj444:
                        is_yuv444 = True
                        params['color_range'] = nvc.ColorRange.JPEG

                    if not is_yuv420 and not is_yuv444:
                        raise ValueError("Unsupported pixel format: " +
                                        pix_fmt +
                                        '. Only YUV420 and YUV444 are supported in this sample.')
                    else:
                        params['format'] = nvc.PixelFormat.NV12 if is_yuv420 else nvc.PixelFormat.YUV444

                    # Color range default option. We may have set when parsing
                    # pixel format, so check first.
                    if 'color_range' not in params:
                        params['color_range'] = nvc.ColorRange.MPEG
                    # Check actual value.
                    if 'color_range' in stream:
                        color_range = stream['color_range']
                        if color_range == 'pc' or color_range == 'jpeg':
                            params['color_range'] = nvc.ColorRange.JPEG

                    # Color space default option:
                    params['color_space'] = nvc.ColorSpace.BT_601
                    # Check actual value.
                    if 'color_space' in stream:
                        color_space = stream['color_space']
                        if color_space == 'bt709':
                            params['color_space'] = nvc.ColorSpace.BT_709

                    return params
        return {}

    
    def run(self):
        self.pipe = subprocess.Popen(self.pipe_command, stdout=subprocess.PIPE)
        self.NvDec = nvc.PyNvDecoder(self.stream_parameters['width'], 
                                     self.stream_parameters['height'], 
                                     self.stream_parameters['format'], 
                                     self.stream_parameters['codec'], self.gpu_id)
        # print(self.nvDec.ColorSpace(), self.nvDec.ColorRange())
        res = str(self.stream_parameters['width']) + 'x' + str(self.stream_parameters['height'])
        self.nvEnc = nvc.PyNvEncoder({'preset': 'P5', 'tuning_info': 'high_quality', 'codec': 'h264',
                             'profile': 'high', 's': res, 'bitrate': '10M'}, 0)

        print('NvDec Format', self.NvDec.Format())
        nvdec_format = self.NvDec.Format()
        print('Nvdec Format', nvdec_format)
        nvYuv = nvc.PySurfaceConverter(self.stream_parameters['width'], self.stream_parameters['height'], nvdec_format, nvc.PixelFormat.YUV420,
                                            self.ctx.handle, self.cuda_stream.handle)
        # nvCvt = nvc.PySurfaceConverter(self.stream_parameters['width'], self.stream_parameters['height'], nvdec_format, nvc.PixelFormat.BGR,
        #                                 self.ctx.handle, self.cuda_stream.handle)
        # nv12Cvt = nvc.PySurfaceConverter(self.stream_parameters['width'], self.stream_parameters['height'], nvYuv.Format(), nvc.PixelFormat.NV12,
        #                                 self.ctx.handle, self.cuda_stream.handle)
        # nv12Dwn = nvc.PySurfaceDownloader(self.stream_parameters['width'], self.stream_parameters['height'], nvYuv.Format(), self.ctx.handle, self.cuda_stream.handle)

        
        # Amount of bytes we read from pipe first time.
        read_size = 4096
        # Total bytes read and total frames decded to get average data rate
        rt = 0
        fd = 0

        # Main decoding loop, will not flush intentionally because don't know the
        # amount of frames available via RTSP.
        while True:
        # Pipe read underflow protection
            if not read_size:
                read_size = int(rt / fd)
                # Counter overflow protection
                rt = read_size
                fd = 1

            # Read data.
            # Amount doesn't really matter, will be updated later on during decode.
            bits = self.pipe.stdout.read(read_size)
            if not len(bits):
                print("Can't read data from pipe")
                break
            else:
                rt += len(bits)

            # Decode
            enc_packet = np.frombuffer(buffer=bits, dtype=np.uint8)
            pkt_data = nvc.PacketData()
            try:
                rawSurface = self.NvDec.DecodeSurfaceFromPacket(enc_packet, pkt_data)
                print('Rawsurface Format', rawSurface.Format())
                # yuvSurface = nvYuv.Execute(rawSurface, self.cc_ctx)
                # cvtSurface = nvCvt.Execute(rawSurface, self.cc_ctx)
                # nv12Surface = nv12Cvt.Execute(yuvSurface, self.cc_ctx)




                # print('Surface Format', surf.Format())
                if not rawSurface.Empty():
                    fd += 1
                    # Shifts towards underflow to avoid increasing vRAM consumption.
                    if pkt_data.bsl < read_size:
                        read_size = pkt_data.bsl
                    # Print process ID every second or so.
                    fps = int(self.stream_parameters['framerate'])
                    if not fd % fps:
                        print(fps)

            # Handle HW exceptions in simplest possible way by decoder respawn
            except nvc.HwResetException:
                self.NvDec = nvc.PyNvDecoder(self.stream_parameters['width'], 
                                     self.stream_parameters['height'], 
                                     self.stream_parameters['format'], 
                                     self.stream_parameters['codec'], self.gpu_id)
                continue`

**Comment by rarzumanyan** [comment]
@Sayyam-Jain 

Issues pages are dedicated to project bugs, not fixing user applications.
Please split up your app in multiple parts and make sure they work step by step:

- Decode frames from network input (`SampleDecodeRTSP.py`)
- Convert them to different colorspace (`SampleDemuxDecode.py`)
- Encode them (`SampleEncode.py`)

**Comment by Sayyam-Jain** [comment]
My apologies, I was converting surface before checking it was empty. Thanks for your help.
