### ISSUE TITLE
Where can I find the full version of "Exporting video frame to Pytorch tensor" example script?

### ISSUE THREAD

**Issue by conraddd** [NVIDIA/VideoProcessingFramework#36]
Seems this is just part of the code, I am not able to run it. May you release the full version of that example code? It will be even better if documentations are available.

**Comment by rarzumanyan** [comment]
Hi @conraddd 
>Seems this is just part of the code, I am not able to run it

Can you describe what issue exactly do you have with it?

**Comment by conraddd** [comment]
@rarzumanyan  Here is the code I copied from [Wiki](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Exporting-video-frame-to-Pytorch-tensor) and I don't know where nv12_smaller and pnvc come from.
```
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
    to_rgb = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(), nvc.PixelFormat.NV12, nvc.PixelFormat.RGB, gpuID)
    to_planar = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(), nvc.PixelFormat.RGB, nvc.PixelFormat.RGB_PLANAR, gpuID)

    while True:
        # Obtain NV12 decoded surface from decoder;
        rawSurface = nvDec.DecodeSingleSurface()
        if (rawSurface.Empty()):
            break

        # Convert to RGB interleaved;
        rgb_byte = to_rgb.Execute(nv12_smaller)

        # Convert to RGB planar because that's what to_tensor + normalize are doing;
        rgb_planar = to_planar.Execute(rgb_byte)

        # Create torch tensor from it and reshape because
        # pnvc.makefromDevicePtrUint8 creates just a chunk of CUDA memory
        # and then copies data from plane pointer to allocated chunk;
        surfPlane = rgb_planar.PlanePtr()
        surface_tensor = pnvc.makefromDevicePtrUint8(surfPlane.GpuMem(), surfPlane.Width(), surfPlane.Height(), surfPlane.Pitch(), surfPlane.ElemSize())
        surface_tensor.resize_(3, target_h, target_w)

        # This is optional and depends on what you NN expects to take as input
        # Normalize to range desired by NN. Originally it's 
        # transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        # But we scale that to [0;255] input, so we multiply normalization coefficients
        surface_tensor = surface_tensor.type(dtype=torch.cuda.FloatTensor)
        mean = torch.tensor([123.675, 116.28, 103.53], dtype=torch.float32, device='cuda')
        std = torch.tensor([58.395, 57.12, 65.025], dtype=torch.float32, device='cuda')
```

**Comment by rarzumanyan** [comment]
My apologies, code in wiki indeed has typos and some lines are missed.
I've updated the article, please check out latest version.

**Comment by conraddd** [comment]
@rarzumanyan 
thank you for your immediate response.
I am now getting Segmentation fault from the example script when running this line
`surface_tensor = pnvc.makefromDevicePtrUint8(surfPlane.GpuMem(), surfPlane.Width(), surfPlane.Height(), surfPlane.Pitch(), surfPlane.ElemSize())` 
at the first frame of my mp4 video
I am using python3.6.9, torch1.5.0 and nvcr.io/nvidia/cuda:10.2-devel docker image

**Comment by rarzumanyan** [comment]
That's interesting, never got error like that.
I've uploaded a patch to master branch which adds more verbose error messages output, please check it out.

Video frame export function is tiny, there's not too much places where things can go wrong:
```cpp
torch::Tensor makefromDevicePtrUint8(CUdeviceptr ptr, uint32_t width,
                                     uint32_t height, uint32_t pitch,
                                     uint32_t elem_size_bytes) {
  if (elem_size_bytes != 1) {
    ...
  }

  auto options = torch::TensorOptions()
                     .dtype(torch::kUInt8)
                     .layout(torch::kStrided)
                     .device(torch::kCUDA);

  torch::Tensor tensor = torch::full({height, width}, 128, options);

  uint8_t *devMem = tensor.data_ptr<uint8_t>();
  if (!devMem) {
    ..
  }

  if (!ptr) {
    ...
  }

  auto res = cudaMemcpy2D((void *)devMem, width, (const void *)ptr, pitch,
                          width, height, cudaMemcpyDeviceToDevice);
  if (cudaSuccess != res) {
    ...
  }

  return tensor;
}
```

**Comment by niaoyu** [comment]
I just faced the same issue with a rtmp url which surfPlane.Width(), surfPlane.Height(), surfPlane.Pitch(), surfPlane.ElemSize() are 0.

**Comment by conraddd** [comment]
@rarzumanyan I downloaded the latest code but there is no error message other than segmentation fault. I also tried adding some cout lines in the makefromDevicePtrUint8 function but none of them was executed. I guess segmentation fault occurred before the first line of makefromDevicePtrUint8()

**Comment by rarzumanyan** [comment]
@niaoyu 
>which surfPlane.Width(), surfPlane.Height(), surfPlane.Pitch(), surfPlane.ElemSize() are 0

If decoder fails to decode, it will return empty video surface. Check `Empty()` method, if it returns true, the surface is empty (no memory is allocated for it). Hence you can't export it to Pytorch tensor.

**Comment by conraddd** [comment]
@rarzumanyan any idea about what is happing? May you share your steps to build VPF with PyTorch support? Maybe it is caused by a different environment.

**Comment by rarzumanyan** [comment]
Hi @conraddd 

Apologies, but I don't understand you question.
What exactly is going wrong? Where does segfault happens?

**Comment by mavonox** [comment]
@conraddd @rarzumanyan 

I am also having problems running this after building VPF with amendments to the CMakeCache.txt before the `make install` step:
```
//Generate VPF Pytorch extension
GENERATE_PYTORCH_EXTENSION:BOOL=TRUE
```
This allows for PytorchNvCodec.cpython-37m-x86_64-linux-gnu.so to be created in the install/bin directory.

I placed the code from the "Exporting video frame to Pytorch tensor", with a path to a local video in the same directory and run the example and get:

```
VideoProcessingFramework/install/bin/PytorchNvCodec.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE
```
Are there any other dependencies or Cmake flags that need to be set to build PytorchNvCodec and run this example correctly?

**Comment by rarzumanyan** [comment]
Hi @mavonox 
After googling, I've found couple of similar issues:

- https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/15#issue-437961975

- https://github.com/princeton-vl/CornerNet-Lite/issues/69#issue-443076858

- https://discuss.pytorch.org/t/ubuntu-18-04-anconda3-pytorch1-0-suddently-not-working/37321

Did you try those approaches?

**Comment by mavonox** [comment]
Hi @rarzumanyan 

These links suggested that I had multiple instances of pytorch conflicting. However this shouldn't be the case in a Conda environment. I got over this by looking at how to install pytorch with other dependencies (such as ninja) that you have used and do not come from a single ```conda install pytorch``` but instead:

``` conda install pytorch torchvision cudatoolkit=10.1 -c pytorch ``` from www.pytorch.org

I am now having trouble libc10 and libtorch. A ```ldd PytorchNvCodec.cpython-37m-x86_64-linux-gnu.so``` showed that they were not found. I understand these belong to the pytorch c++ api, so I proceeded to download and build the library following the instructions here (https://gist.github.com/mhubii/1c1049fb5043b8be262259efac4b89d5) for the GPU build from source. 

I am now altering the cmakelist.txt in VPF to find the library.

Please let me know if there is a quicker way to do this, will report on my complete build  method (if managed) for others.

**Comment by rarzumanyan** [comment]
Hi @mavonox,

>I got over this by looking at how to install pytorch with other dependencies (such as ninja) that you have used and do not come from a single `conda install pytorch` but instead `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`

I can't recall referencing the `conda install pytorch` anywhere across the project. However,  `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch` is indeed useful especially for newcomers and shall be added to wiki page. Thank you for mentioning.

>I am now having trouble libc10 and libtorch. A `ldd PytorchNvCodec.cpython-37m-x86_64-linux-gnu.so` showed that they were not found.

PytorchNvCodec module is built using VideoProcessingFramework\PytorchNvCodec\src\setup.py file which facilitates `setuptools` and `torch.utils.cpp_extension` to build .cpp file(s) and automatically resolve dependencies:
```python
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

setup(name='PytorchNvCodec',
    ext_modules=[CUDAExtension('PytorchNvCodec', ['PytorchNvCodec.cpp'])],
    cmdclass={
        'build_ext': BuildExtension
    })
```
BTW I've never received any issues related to PytorchNvCodec build procedure (probably because the build script just runs smooth). It's also possible to build the extension with libtorch C++ API but that will mangle the CMake files as Pytorch itself has lots of dependencies against CUDA etc. So I've decided to kick-off Python build script as external command instead.

**Comment by mavonox** [comment]
Hi @rarzumanyan 

I have hit a similar undefine symbol:

```
VideoProcessingFramework/install/bin/PytorchNvCodec.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv
```
This one shows nothing on a Google search.

My ldd readout for PytorchNvCodec.cpython-37m-x86_64-linux-gnu.so is:

	linux-vdso.so.1 (0x00007fffc32f8000)
	libc10.so => /usr/local/lib/libc10.so (0x00007fa5a3102000)
	libtorch.so => /usr/local/lib/libtorch.so (0x00007fa5a30fd000)
	libtorch_cpu.so => /usr/local/lib/libtorch_cpu.so (0x00007fa59cf90000)
	libtorch_python.so => /usr/local/lib/libtorch_python.so (0x00007fa59c275000)
	libcudart.so.10.1 => /home/mirek/anaconda3/envs/py37_torch/lib/libcudart.so.10.1 (0x00007fa59bff6000)
	libc10_cuda.so => /usr/local/lib/libc10_cuda.so (0x00007fa59bfc4000)
	libtorch_cuda.so => /usr/local/lib/libtorch_cuda.so (0x00007fa58738b000)
	libstdc++.so.6 => /home/mirek/anaconda3/envs/py37_torch/lib/libstdc++.so.6 (0x00007fa587217000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa5870c8000)
	libgcc_s.so.1 => /home/mirek/anaconda3/envs/py37_torch/lib/libgcc_s.so.1 (0x00007fa5870b4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa587091000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa586e9e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa5a31c2000)
	libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fa586e91000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fa586e57000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa586e51000)
	libmpi_cxx.so.40 => /lib/x86_64-linux-gnu/libmpi_cxx.so.40 (0x00007fa586e33000)
	libmpi.so.40 => /lib/x86_64-linux-gnu/libmpi.so.40 (0x00007fa586d2a000)
	libtensorpipe.so => /usr/local/lib/libtensorpipe.so (0x00007fa586ace000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa586ac3000)
	libmkl_intel_lp64.so => /home/mirek/anaconda3/envs/py37_torch/lib/libmkl_intel_lp64.so (0x00007fa585f53000)
	libmkl_gnu_thread.so => /home/mirek/anaconda3/envs/py37_torch/lib/libmkl_gnu_thread.so (0x00007fa584671000)
	libmkl_core.so => /home/mirek/anaconda3/envs/py37_torch/lib/libmkl_core.so (0x00007fa5802f1000)
	libshm.so => /usr/local/lib/libshm.so (0x00007fa5802e3000)
	libnvToolsExt.so.1 => /usr/local/cuda-10.1/lib64/libnvToolsExt.so.1 (0x00007fa5800da000)
	libcusparse.so.10 => /usr/local/cuda-10.1/lib64/libcusparse.so.10 (0x00007fa578e53000)
	libcurand.so.10 => /usr/local/cuda-10.1/lib64/libcurand.so.10 (0x00007fa574df2000)
	libcufft.so.10 => /usr/local/cuda-10.1/lib64/libcufft.so.10 (0x00007fa56c7b8000)
	libcublas.so.10 => /home/mirek/anaconda3/envs/py37_torch/lib/libcublas.so.10 (0x00007fa568a18000)
	libopen-rte.so.40 => /lib/x86_64-linux-gnu/libopen-rte.so.40 (0x00007fa56895f000)
	libopen-pal.so.40 => /lib/x86_64-linux-gnu/libopen-pal.so.40 (0x00007fa5688b5000)
	libhwloc.so.5 => /lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007fa568874000)
	libcublasLt.so.10 => /home/mirek/anaconda3/envs/py37_torch/lib/./libcublasLt.so.10 (0x00007fa5669cc000)
	libz.so.1 => /home/mirek/anaconda3/envs/py37_torch/lib/libz.so.1 (0x00007fa5669ac000)
	libevent-2.1.so.6 => /lib/x86_64-linux-gnu/libevent-2.1.so.6 (0x00007fa56675b000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fa566756000)
	libevent_pthreads-2.1.so.6 => /lib/x86_64-linux-gnu/libevent_pthreads-2.1.so.6 (0x00007fa566553000)
	libltdl.so.7 => /lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fa566546000)
```

and `conda list | grep torch`  for this environment is:

```
pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
torchvision               0.6.0                py37_cu101    pytorch
```
I believe there is a caffe incompatibility with my versions, may I see the same information as provided for your build?

Best,

Mirek

**Comment by rarzumanyan** [comment]
@mavonox 

>may I see the same information as provided for your build?

I'm developing under Windows, below is my CMake configure output.

```cmd
Searching for FFmpeg libs in C:/Install/ffmpeg-20191224-287620f-win64-dev/lib
Searching for FFmpeg headers in C:/Install/ffmpeg-20191224-287620f-win64-dev/include
Found PythonLibs: C:/Users/rarzumanyan/AppData/Local/Continuum/anaconda3/libs/python37.lib (found suitable version "3.7.6", minimum required is "3.5") 
Found PythonInterp: C:/Users/rarzumanyan/AppData/Local/Continuum/anaconda3/python.exe (found version "3.7.6") 
Found PythonLibs: C:/Users/rarzumanyan/AppData/Local/Continuum/anaconda3/libs/Python37.lib
pybind11 v2.3.dev0
Performing Test HAS_MSVC_GL_LTCG
Performing Test HAS_MSVC_GL_LTCG - Success
LTO enabled
Configuring done
```

Wiki page which describes how build the project from source is basically copy-paste from build scripts I use both on Windows & Linux for development & testing so here you won't see anything too much different.

**Comment by mavonox** [comment]
I solved my build issue, I upgraded my OS to ubuntuMATE 20.04 from 19.10, which comes with the nvidia driver 440, opposed to the 435 I was on previously. However, for the Linux build, you definitely need a local build of Pytorch with the corresponding libtorch libs, as well as to ensure that the bin is on the PATH (I updated my ~/.bashrc with ``export PATH="/home/mirek/git/pytorch/build/bin:$PATH"``) and LD_LIBRARY_PATH includes the libraries (included  /home/mirek/git/pytorch/build/lib in  /etc/ld.so.conf , followed by a ``sudo ldconfig``)- standard stuff I'm sure, but a lot of people who I'd expect would want to use the VPF are in the habit of ``conda install xxx `` just working.

This was of great assistance: https://gist.github.com/mhubii/1c1049fb5043b8be262259efac4b89d5

Additionally, I installed everything from the CUDA 10.2 toolkit except the nvidia driver as the OS already has this and makes the inclusion of the nvidia driver much less painful than to add it to a vanilla ubuntu...

Thanks for creating this, I am sure it will be very useful for my further work.

Best,

Mirek

**Comment by rarzumanyan** [comment]
Hi @mavonox 
Glad that you was able to work this around, this is indeed useful. Closing this issue.

**Comment by mfoglio** [comment]
@MirekJan without building PyTorch, I tried the following:
```
export PATH="/usr/local/lib/python3.6/dist-packages/torch/bin:${PATH}"
export LD_LIBRARY_PATH="/usr/local/lib/python3.6/dist-packages/torch/lib:${LD_LIBRARY_PATH}"
```
but I still have the error:
```
[  5%] Generating Pytorch_Nv_Codec
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
CMakeFiles/PytorchNvCodec.dir/build.make:72: recipe for target 'Pytorch_Nv_Codec' failed
make[2]: *** [Pytorch_Nv_Codec] Error 1
CMakeFiles/Makefile2:275: recipe for target 'CMakeFiles/PytorchNvCodec.dir/all' failed
make[1]: *** [CMakeFiles/PytorchNvCodec.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
```
I am trying to build PyTorch but without using conda it is kind of hard to install `magma`.

**Comment by MirekJan** [comment]
It is awhile ago, but I remember building LibTorch from scratch.

Make sure you have got the Nvidia codec SDK installed too

**Comment by mfoglio** [comment]
> /etc/ld.so.conf



> @rarzumanyan
> 
> I solved my build issue, I upgraded my OS to ubuntuMATE 20.04 from 19.10, which comes with the nvidia driver 440, opposed to the 435 I was on previously. However, for the Linux build, you definitely need a local build of Pytorch with the corresponding libtorch libs, as well as to ensure that the bin is on the PATH (I updated my ~/.bashrc with `export PATH="/home/mirek/git/pytorch/build/bin:$PATH"`) **and LD_LIBRARY_PATH includes the libraries (included /home/mirek/git/pytorch/build/lib in /etc/ld.so.conf , followed by a `sudo ldconfig`**)- standard stuff I'm sure, but a lot of people who I'd expect would want to use the VPF are in the habit of `conda install xxx ` just working.
> 
> This was of great assistance: https://gist.github.com/mhubii/1c1049fb5043b8be262259efac4b89d5
> 
> Additionally, I installed everything from the CUDA 10.2 toolkit except the nvidia driver as the OS already has this and makes the inclusion of the nvidia driver much less painful than to add it to a vanilla ubuntu...
> 
> Thanks for creating this, I am sure it will be very useful for my future work.
> 
> Best,
> 
> Mirek

@MirekJan what do you exactly mean by that? The following?
```
export PATH="/home/ubuntu/pytorch/build/bin:$PATH"  # /home/mirek/git/pytorch/build/bin
export LD_LIBRARY_PATH="/home/ubuntu/pytorch/build/lib:$LD_LIBRARY_PATH"  # /home/mirek/git/pytorch/build/lib
sudo ldconfig
```
Or should I edit `/etc/ld.so.conf` somehow?
Thank you
