### ISSUE TITLE
 Are there any offline installation and use tutorials?

### ISSUE THREAD

**Issue by Fly-hub** [NVIDIA/VideoProcessingFramework#360]

**Comment by rarzumanyan** [comment]
Hi @Fly-hub 

Installation instructions are available online.
Offline API documentation is available in the doc sub-folder, you can build it with Sphinx.
Tutorials are available offline in the form of code samples.

**Comment by yogendra-yatnalkar** [comment]
Hi @rarzumanyan , this is an amazing library. Regarding the documentation, I understand that it's provided within the repo and can be built, but I do not have access to GPU at least as of now and would love to read the documentation internally to understand the Api working. Can you please point to some online resource where documentation might be hosted ? 

I came to this article after reading this article: https://developer.nvidia.com/blog/vpf-hardware-accelerated-video-processing-framework-in-python/

**Comment by theHamsta** [comment]
Sorry, at the moment we don't have documentation. You can build a API documentation https://github.com/NVIDIA/VideoProcessingFramework#documentation or have a look into our wiki https://github.com/NVIDIA/VideoProcessingFramework/wiki
