### ISSUE TITLE
nvidia driver = 450

### ISSUE THREAD

**Issue by Fly-hub** [NVIDIA/VideoProcessingFramework#364]
**My nvidia driver is 450**
My nvidia driver is 450. I succeeded in executing SampleDecode.py, but failed in executing SamplePyTorch.py.

python3 ./SamplePyTorch.py  

RuntimeError：LoadNvEncAPI：Current Driver Version does not support this NvEncodeAPI version, please upgrade driver at /root/Git/VideoProcessingFramework/PvNvCodec/TC/src/NvEncoder.cpp:125

**Expected behavior**
Can I use VideoProcessingFramework without upgrading the driver ?

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20]
 - Nvidia driver version [450]
 - CUDA Version [11.4]
 - Video Codec SDK Version [ 9.1.23]
 - Python Version [3.8]
 - FFmpeg Version [4.3]

**Comment by Fly-hub** [comment]
Is there a VideoProcessingFramework version  that supports nvidia driver 450 ？

**Comment by rarzumanyan** [comment]
The error you see isn't caused by VPF.
You need to update your Video Codec SDK at least (as it's shown in the error message).
