### ISSUE TITLE
Difference in color when decoding rtsp and converting surface to BGR frame

### ISSUE THREAD

**Issue by Sayyam-Jain** [NVIDIA/VideoProcessingFramework#365]
**Describe the bug**
When decoding an rtsp stream to a rawframe, I converted rawframe to bgr numpy frame and saved it to a numpy file and wrote the same rawframe (NV12) to an encoded file as well. 

Later, when I read the same NV12 file and the numpy file as well and found there was a difference of colors between the two frames. Both files (NV12 and numpy file) frames were written using same base rawframe

**Expected behavior**
Expected both frames read from NV12 file and numpy file to be same color

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Nvidia driver version: 470
 - CUDA Version: 11.1, V11.1.105
 - Video Codec SDK Version [e.g. 9.1.23]
 - Python Version: 3.7

**Additional context**
It seems NV12 file has more accurate color, as my NN performs well on it, but fails to work on converted bgr frame, which converted in realtime from rawsurface

**Comment by rarzumanyan** [comment]
@Sayyam-Jain 

>It seems NV12 file has more accurate color

This is incorrect comparison.

NV12 is a pixel format which contains planar Y channel (luminosity) and interleaved U+V channels (blue and red color difference).
Unlike that BGR is a pixel format which contains blue, red and green channels information.

One can convert from NV12 to BGR using `PySurfaceConverter` class. There are 2 variables which define the color conversion process:

1. Color range (NV12 could have limited or full range).
2. Color space (defines the coefficients of nv12 > bgr conversion).

So you need to know these values prior to conversion process. If you don't know them you can guess, but the colors may be slightly off. BGR won't be crippled and visually will look OK but the subtle difference is sometimes enough to cause NN inference precision penalty.

Please only submit this type of issue if you know for sure your color space and color range information.
