### ISSUE TITLE
How to get the encoded video keyframe field

### ISSUE THREAD

**Issue by Iamlearn** [NVIDIA/VideoProcessingFramework#367]
I used this code from wiki and found no keyframe information：

# 1. init
dstFile = av.open(dstFilePath, 'w')
out_stream = dstFile.add_stream('h264', rate = 25)
out_stream.width = w
out_stream.height = h

# 2. mux
encByteArray = bytearray(encFrame)  # encFrame from EncodeSingleSurface
pkt = av.packet.Packet(encByteArray)
pkt.pts = pts_time
pkt.dts = pts_time
pkt.stream = out_stream  # attach pkt to the stream
dstFile.mux(pkt)

If there is key frame information, the video saved by VPF can directly read the frame of interest。

**Comment by rarzumanyan** [comment]
Hi @Iamlearn 

VPF produces elementary video bit stream defined by Annex B of H.264 and H.265 video codec standards. 
It's kinda blob which doesn't contain metadata like `AVPacket` does. 
So this feature is currently unsupported. You can't tell if encoded frame returned by `PyNvEncoder` is key or not.

Please feel free to submit a new feature request in Discussions page. I'll analyze if it's feasible to implement and will get back to you with more detailed answer answer.
