### ISSUE TITLE
Can't seek by frame number in VFR sequences. Seek by timestamp instead.

### ISSUE THREAD

**Issue by Iamlearn** [NVIDIA/VideoProcessingFramework#369]
Error in reading the specified position of the video. Video files are below.Code:

def decode(gpuID, encFilePath):
    nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
    seek_ctx = nvc.SeekContext(1, nvc.SeekMode.PREV_KEY_FRAME, nvc.SeekCriteria.BY_NUMBER)
    surf = nvDec.DecodeSingleSurface(seek_ctx)
    w = nvDec.Width()
    h = nvDec.Height()
    # f = nvc.PixelFormat.NV12
    # c = nvc.CudaVideoCodec.H264
    # nvDec = nvc.PyNvDecoder(w, h, f, c, gpuID)
    to_rgb = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.NV12, nvc.PixelFormat.RGB, gpuID)
    cc1 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_709, nvc.ColorRange.JPEG)
    nv_dwn = nvc.PySurfaceDownloader(w, h, nvc.PixelFormat.RGB, gpuID)

if __name__ == "__main__":
    decode(0, 'CCCNew2.mp4')

https://user-images.githubusercontent.com/46410827/185030993-5c32f8bc-9392-4ead-b7c1-af44ba639279.mp4

The video encoding code is as follows：

    res = str(width) + 'x' + str(height)
    nvEnc = nvc.PyNvEncoder({'preset': 'P5', 'tuning_info': 'high_quality', 'codec': 'h264', 'gop': str(16), 'bf': '2',
                             'profile': 'high', 's': res, 'bitrate': '10M', 'fps': str(fps)}, gpuID)
    encFrame = np.ndarray(shape=(0), dtype=np.uint8)
    cc1 = nvc.ColorspaceConversionContext(color_space=nvc.ColorSpace.BT_601, color_range=nvc.ColorRange.MPEG)
    nvUpl = nvc.PyFrameUploader(width, height, nvc.PixelFormat.YUV420, gpuID)
    nvCvt = nvc.PySurfaceConverter(width, height, nvc.PixelFormat.YUV420, nvc.PixelFormat.NV12, gpuID)
    s1 = time.time()
    # readTime = 0
    count = 0
    for frame in imgs:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2YUV_I420)
        frame = frame.reshape(-1)
        rawSurface = nvUpl.UploadSingleFrame(frame)
        cvtSurface = nvCvt.Execute(rawSurface, cc1)
        success = nvEnc.EncodeSingleSurface(cvtSurface, encFrame)
        if success:
            encByteArray = bytearray(encFrame)
            pkt = av.packet.Packet(encByteArray)
            pkt.pts = 256 * count
            pkt.dts = 256 * count
            pkt.stream = out_stream
            pkt.time_base = av.utils.Fraction(1, fps)
            encFile.mux(pkt)
            count += 1
            # encFile.write(encByteArray)
    while True:
        success = nvEnc.FlushSinglePacket(encFrame)
        if success:
            encByteArray = bytearray(encFrame)
            pkt = av.packet.Packet(encByteArray)
            pkt.pts = 256 * count
            pkt.dts = 256 * count
            pkt.stream = out_stream
            pkt.time_base = av.utils.Fraction(1, fps)
            encFile.mux(pkt)
            count += 1
            # encFile.write(encByteArray)
        else:
            break

**Comment by gedoensmax** [comment]
Do i understand correctly that the expected behavior is to seek by Frame but this fails and your temporary fix is to seek by timestep ?

**Comment by rnaskulwar** [comment]
Taking a look

**Comment by rnaskulwar** [comment]
This is as per design, to get the target frames closest timestamp, we divide the frame index by frame rate, this could go wrong in case of VFR sequence

**Comment by rnaskulwar** [comment]
closing this issue for now
