### ISSUE TITLE
How do I use this framework

### ISSUE THREAD

**Issue by zhanghongyong123456** [NVIDIA/VideoProcessingFramework#371]
**Describe the bug**
I compiled it according to the source code，But I don't know how to use it，
I want to load a video to get each frame of RGB image for processing, get the corresponding alpha through the Videomatting  model, and output it as a video about  alpha？ how to  do？
![image](https://user-images.githubusercontent.com/48466610/185339379-5f76d08c-1363-41f0-aefe-9d85aec088b2.png)

**Comment by rarzumanyan** [comment]
Hi @zhanghongyong123456 

Please follow samples which are part of this repository.
Also you can build offline API doc with Sphinx.
