### ISSUE TITLE
Just need a best practice recommendation

### ISSUE THREAD

**Issue by OmkarShidore** [NVIDIA/VideoProcessingFramework#379]
### Discussed in https://github.com/NVIDIA/VideoProcessingFramework/discussions/378

<div type='discussions-op-text'>

<sup>Originally posted by **OmkarShidore** September 14, 2022</sup>
Hi, Thanks for making this framework available.
I wanted to know how to apply filters on the decoded frame before encoding it.

Input Frame (webCam) -> PyFrameUploader(on GPU) -> *Apply some filters here* -> nvEnc.EncodeSingleSurface

I wanted to apply multiple filters like RGB-HSV, guassian blur, histogram equalization. What would be the best practice for such operation, once the frame is on device. I don't want to move it back to the host.
PS: I've tried torch.cuda.tensor conversion and and applying filters in torchvision there. but those filters are very very slow.
Need a throughput of 4k 60 FPS.</div>

**Comment by rarzumanyan** [comment]
I've duplicated same response, let's continue this thread in Discussions.
