### ISSUE TITLE
How do I convert a read RTSP to numpy RGB

### ISSUE THREAD

**Issue by sbbug** [NVIDIA/VideoProcessingFramework#38]
hello!
thank you for  your contribution,
how do I convert a read RTSP to numpy RGB?

**Comment by rarzumanyan** [comment]
Hi @sbbug,
Take a look at SampleDecodeMultiThread, it can also work with RTSP input. You will also see color conversion features there. After you do the color conversion, use the PySurfaceDownloader to get numpy array from GPU.

**Comment by sbbug** [comment]
hi,
i modify the SampleDecodeMultiThread.py:
 self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.**YUV420**, gpuID)
        self.nvRes = nvc.PySurfaceResizer(hwidth, hheight, self.nvCvt.Format(), gpuID)
        self.nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, self.nvRes.Format(), gpuID)
to
 self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.rgb, gpuID)
        self.nvRes = nvc.PySurfaceResizer(hwidth, hheight, self.nvCvt.Format(), gpuID)
        self.nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, self.nvRes.Format(), gpuID)

when i run the script,i meet a interrupte:
Decoding on GPU 0

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
why?

**Comment by sbbug** [comment]
i got it ,thanks

**Comment by Henry-Dg** [comment]
> i got it ,thanks

I also encountered this problem. Can you elaborate on how you solved it here?
thinks

**Comment by rarzumanyan** [comment]
`SampleDecodeMultiThread.py` covers such topics as decoding video to GPU memory and CUDA-accelerated color conversion:

```python
self.nvDec = nvc.PyNvDecoder(encFile, gpuID)
self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.YUV420, gpuID)
self.nvRes = nvc.PySurfaceResizer(hwidth, hheight, self.nvCvt.Format(), gpuID)
self.nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, self.nvRes.Format(), gpuID)

...

# decoding video frame to GPU memory:
rawSurface = self.nvDec.DecodeSingleSurface()
if (rawSurface.Empty()):
	print('No more video frames')
	break

# GPU-accelerated color conversion:
cvtSurface = self.nvCvt.Execute(rawSurface)
if (cvtSurface.Empty()):
	print('Failed to do color conversion')
	break

# GPU-accelerated resize:
resSurface = self.nvRes.Execute(cvtSurface)
if (resSurface.Empty()):
	print('Failed to resize surface')
	break

# Downloading image from GPU memory to numpy array:
rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)
success = self.nvDwn.DownloadSingleSurface(resSurface, rawFrame)
if not (success):
	print('Failed to download surface')
	break
```

**Comment by Henry-Dg** [comment]
@rarzumanyan
many thanks I solved the it

**Comment by yuluhan** [comment]
@rarzumanyan @dongdongqiang2018 
Hi, did you know how to get the numpy array with which shape is [width, height, 3] ?
from the code `rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)` I only got 1 dimension array,
and I don't know what kind of info it save
