### ISSUE TITLE
Convert Surface to CuPy mat

### ISSUE THREAD

**Issue by Renzzauw** [NVIDIA/VideoProcessingFramework#383]
Hi @rarzumanyan,

I'm researching into CuPy's capabilities and how it might operate together with VPF. With VPF there are direct ways to convert a Surface to a PyTorch Tensor on the GPU with minimal costs (using the PyTorch extension). According to the [CuPy docs](https://docs.cupy.dev/en/stable/user_guide/interoperability.html#pytorch), both PyTorch and CuPy support `__cuda_array_interface__`, so they can also be converted to each other with minimal cost. 
To my limited understanding, does this mean that technically a VPF Surface can directly be converted to a CuPy mat? If so, do you know a way how to do this or if this is possible with VPF?

Thanks in advance!

**Comment by RomanArzumanyan** [comment]
Hi @Renzzauw 

@gedoensmax is now PIC for everything VPF and I'm continuing to support it as a community member. Max is a CUDA expert so this question will go to him anyway ;)

WRT the CuPy interop. I'm not 100% sure if I understand you correctly but this is a sample which shows the pytorch tensor <> pycuda interop. Is it same for CuPy?

https://github.com/NVIDIA/VideoProcessingFramework/blob/2b69dc597882c9f40a67c55ebd9e259523a9e1dc/SampleTensorRTResnet.py#L1064-L1147

**Comment by Renzzauw** [comment]
Hi @RomanArzumanyan thanks for the update and your support in the past!

I unfortunately do not know exactly if something similar is possible with CuPy. I did find support for low-level CUDA operations in [their docs on this page](https://docs.cupy.dev/en/stable/reference/cuda.html#low-level-cuda-support), where they provide functions/classes for interacting with CUDA memory. It also appears there are some objects related to memory management, e.g. `cupy.cuda.MemoryPointer` or `cupy.cuda.UnownedMemory`, but I don't know how I can use these to access my VPF Surface's contents. 

I tried accessing the memory location of the Surface as follows:
```py
vpf_mem = rgb_planar.PlanePtr().GpuMem()

mem = cp.cuda.UnownedMemory(vpf_mem, width * height * 3, None, 0)
mem_ptr = cp.cuda.MemoryPointer(mem, 0)
frame_cp = cp.ndarray(shape=(3, height, width), dtype=np.float32, memptr=mem_ptr)

```
I did not have any luck so far to convert this to a CuPy mat/ndarray or if I'm doing this the right way at all, so I was hoping perhaps you or @gedoensmax would be more familiar with CuPy. If not, I'll try at the CuPy issue board. I'd like to prevent having to convert Surface <-> PyTorch <-> CuPy and instead convert Surface <-> CuPy. Luckily these steps are not very costly, but it would be nice if I could skip the extra step :)

**Comment by gedoensmax** [comment]
Hey i can definetly take a look, but will be on vacation the next 2 weeks. 
Have you tried simply using `vpf_mem = rgb_planar.PlanePtr()` as pointer ? Because that should be supported if i understand this correctly: https://github.com/cupy/cupy/issues/4644
Sorry for not being able to investigate further right now but i will get back to it if the problem persists

**Comment by Renzzauw** [comment]
@gedoensmax Thanks for your reply! 
It seems the CuPy functions expect an integer, so that's why I did ```vpf_mem = rgb_planar.PlanePtr().GpuMem()```.
No worries, enjoy your vacation! If I manage to find the solution in the meantime, I'll close this issue with what I found!

**Comment by sandhawalia** [comment]
Hi there, I have been using this, maybe it will help. `rgb_frame` is `Surface` of type `nvc.PixelFormat.RGB`.

```
def get_cupy_array(rgb_frame):

    plane = rgb_frame.PlanePtr()

    # cuPy array zero copy non ownned
    H, W, pitch = (plane.Height(), plane.Width(), plane.Pitch())

    cupy_mem = cupy.cuda.UnownedMemory(get_memptr(rgb_frame), H * W * 1, rgb_frame)
    cupy_memptr = cupy.cuda.MemoryPointer(cupy_mem, 0)

    cupy_frame = cupy.ndarray(
        (H, W // 3, 3), np.uint8, cupy_memptr, strides=(pitch, 3, 1)
    )

    return cupy_frame
```

**Comment by Renzzauw** [comment]
@sandhawalia hi, thanks for your reply! 

After a small test, your piece of code seems to do the trick on my end, so thank you so much!

I would like to encode the frames again to a new video using VPF after doing various CuPy operations on the decoded video frames. Do you perhaps know if it's also possible to convert back from CuPy -> Surface? 

If so, I can completely remove PyTorch from my pipeline and get back a bit of claimed CUDA memory as a bonus :)

**Comment by sandhawalia** [comment]
Hey @Renzzauw. You can modify the `cupy_frame` like a regular `ndarray` the changes you'd make will be in the `Suface` as well, since they share the same underlying `Memory` and CuPy doesn't own it. 

As long as you don't go outside the valid pixel - When done you can simply re-encode the `Surface` (`rgb_frame`)

**Comment by Renzzauw** [comment]
Hi @sandhawalia, that makes a lot of sense, thank you for clarifying. Really happy to hear I can remove my dependency on PyTorch via this way. 

I'll be closing this issue as for now my questions have been answered!

**Comment by sandhawalia** [comment]
Hey there. 

Yes this is possible within VPF. In fact you don't need to take the CuPy route at all. VPF exposes a convenient callback for [cropping Surfaces](https://github.com/NVIDIA/VideoProcessingFramework/blob/master/PyNvCodec/src/PySurface.cpp#L445). 

Here's code to shed light on this. 

```
import PyNvCodec as nvc
# you'd replace surface with frame you read from video file 
# rgb/rgb_planar/nv12 etc
surface = nvc.Surface.Make(nvc.PixelFormat.RGB, 1920, 1080, 0)
# call `.Crop` instead of cupy_frame[:720, :1280, :]
cropped_surface = surface.Crop(0, 0, 1280, 720, 0)
cropped_surface.Width()
1280
cropped_surface.Height()
720
```

here's the `docstring` to help with arguments. 

```
import inspect
print(inspect.getdoc(surface.Crop))
Crop(*args, **kwargs)
Overloaded function.

1. Crop(self: PyNvCodec.Surface, x: int, y: int, w: int, h: int, gpu_id: int) -> PyNvCodec.Surface


        Crop = select ROI + CUDA mem alloc + CUDA mem copy

        :param x: ROI top left X coordinate
        :param y: ROI top left Y coordinate
        :param w: ROI width in pixels
        :param h: ROI height in pixels
        :param gpu_id: GPU to use


2. Crop(self: PyNvCodec.Surface, x: int, y: int, w: int, h: int, context: int, stream: int) -> PyNvCodec.Surface


        Crop = select ROI + CUDA mem alloc + CUDA mem copy

        :param x: ROI top left X coordinate
        :param y: ROI top left Y coordinate
        :param w: ROI width in pixels
        :param h: ROI height in pixels
        :param context: CUDA contet to use
        :param stream: CUDA stream to use


```

**Comment by sandhawalia** [comment]
Hi there. Interesting use case. If you don't mind multiple copies of your assets i'd do the following. Let's says your assets in CuPy is of the shape `NHWC`. calling it `assets_arr_cupy`

1. Create a `N` x Surfaces `nvc.Surface.Make(format, width, height, gpu_id)`
2. Use the [function above](https://github.com/NVIDIA/VideoProcessingFramework/issues/383#issuecomment-1308692284) to get a CuPy array for each Suface and [stack them](https://docs.cupy.dev/en/stable/reference/generated/cupy.stack.html?highlight=stack#cupy.stack) call the resulting array `vpf_surfaces_cupy`
3. [copy data](https://docs.cupy.dev/en/stable/reference/generated/cupy.copyto.html) over `cupy.copyto(vpf_surfaces_cupy, assets_arr_cupy)`

Another option would be read your assets into the `vpf_surfaces_cupy` directly and then encode the video with VPF. Hope this helps.

**Comment by Renzzauw** [comment]
@sandhawalia Thanks for the extensive explanation, this is really useful!
