### ISSUE TITLE
ffmpeg libavcodec/avcodec.h no such file or directory

### ISSUE THREAD

**Issue by swkms** [NVIDIA/VideoProcessingFramework#388]
I have set "PATH_TO_FFMPEG". I am very sure that the "libavcodec/avcodec. h" file already exists in this path. Why is it prompted that it cannot be found?

`mm@mm:~/soft/FFmpeg/build_x64_release_shared/include/libavcodec$ ls

ac3_parser.h   **avcodec.h**  avfft.h  codec_desc.h  codec_id.h   d3d11va.h  dirac.h       dxva2.h  mediacodec.h  qsv.h    version.h        videotoolbox.h   xvmc.h
adts_parser.h  avdct.h    bsf.h    codec.h       codec_par.h  defs.h     dv_profile.h  jni.h    packet.h      vdpau.h  version_major.h  vorbis_parser.h`

cmake ..   -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG"   -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK"   -DGENERATE_PYTHON_BINDINGS:BOOL="1"   -DGENERATE_PYTORCH_EXTENSION:BOOL="1"   -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 11.7.99
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Searching for FFmpeg libs in /home/mm/soft/FFmpeg/build_x64_release_shared/lib
-- Searching for FFmpeg headers in /home/mm/soft/FFmpeg/build_x64_release_shared/include
-- Searching for Video Codec SDK headers in /home/mm/soft/Video_Codec_SDK_11.1.5/include folder
-- Searching for Video Codec SDK headers in /home/mm/soft/Video_Codec_SDK_11.1.5/Interface folder
-- Found Python3: /usr/bin/python3.8 (found suitable version "3.8.10", minimum required is "3.6") found components: Interpreter Development Development.Module Development.Embed 
-- pybind11 v2.10.0 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mm/soft/VideoProcessingFramework/build

VideoProcessingFramework/PyNvCodec/TC/inc/FFmpegDemuxer.h:23:10: fatal error: libavcodec/avcodec.h: No such file or directory

**Comment by sandhawalia** [comment]
Hey there, Can you try setting the `AVCODEC_INCLUDE_DIR` path explicitly [like here](https://github.com/NVIDIA/VideoProcessingFramework/blob/master/docker/Makefile#L13)
