### ISSUE TITLE
PyNvCodec.CuvidParserException: HW reset

### ISSUE THREAD

**Issue by better629** [NVIDIA/VideoProcessingFramework#392]
**Describe the bug**
```
Resolution          : 5120x1440
Max Supported (wxh) : 4096x4096
Resolution not supported on this GPU
Decoder not initialized.Cuvid parser faced error.
Cuvid parser exception happened.
Process VPFProcess-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
PyNvCodec.CuvidParserException: HW reset
av_interleaved_write_frame(): Broken pipe
Error muxing a packet for output file #0
Error writing trailer of pipe:1: Broken pipe
```

**To Reproduce**
decode RTSP and pass cuda tensor to the model (refs to SamplePyTorch.py)
The program is ok with one RTSP but failed with other RTSP(could be the same configuration) and the program runs in the same image.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Ubuntu20.04
 - Nvidia driver version: 515.65.01
 - CUDA Version: 11.7
 - Video Codec SDK Version: 11.0.10
 - Python Version: 3.8

**Comment by gedoensmax** [comment]
How can i reproduce this ? Are you saying that it fails when there are multiple RTSP or that one RTSP stream works and when usig a  different stream it fails?
Can i get a repro script for this ?

**Comment by better629** [comment]
> How can i reproduce this ? Are you saying that it fails when there are multiple RTSP or that one RTSP stream works and when usig a different stream it fails? Can i get a repro script for this ?

Hi, I have solved the problem due to the different RTSP configuration.
The success RTSP stream using sub channel which produce 1920x544 shape, but the failed RTSP configuration using main channel which produce 5120x1440 shape causing `Resolution not supported on this GPU`.

**Comment by better629** [comment]
BTW, I found the VPF decoding seems a little slow. The duration from get ffmpeg buffer to cuda tensor may cost 10ms-100ms. How can I to find it out?

**Comment by contentis** [comment]
You can try using nsight systems in combination with NVTX ranges. This will allow you to measure marked parts of your code . Going to close for now.
