### ISSUE TITLE
Add setup.py to simplify setup

### ISSUE THREAD

**Issue by contentis** [NVIDIA/VideoProcessingFramework#395]
Make VPF installable via pip to avoid library path errors.

**Comment by theHamsta** [comment]
I think it would be easiest with https://scikit-build.readthedocs.io/en/latest/usage.html#basic-usage. Then, we could do it also pyproject.toml and also the logic of building with cmake would be abstracted away. For pytorch, it could be a separate package using PyTorch's `CudaExtension` https://github.com/theHamsta/pyronn-torch/blob/master/setup.py#L34
