### ISSUE TITLE
How to execute resize operation directly by calling CUDA interface? 

### ISSUE THREAD

**Issue by LuletterSoul** [NVIDIA/VideoProcessingFramework#41]
Hello, thanks very much for your amazing job! I finished building process and linked dynamic library with python binding successfully

If 4K RTSP stream is plugged as input source, it brings high CPU usage when I use opencv resize operation.

So, I try input hwidth,hheight to PySurfaceResizer to execute downsample directly as you show in `SampleDecodeMultiThread`.I convert raw image to RGB space.

```
width, height = self.nvDec.Width(), self.nvDec.Height()
print(width, height)
hwidth, hheight = int(width / 2), int(height / 2)
self.w = hwidth
self.h = hheight
print(self.nvDec.Format())
self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.RGB, gpuID)
self.nvRes = nvc.PySurfaceResizer(hwidth, hheight, self.nvCvt.Format(), gpuID)
self.nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, self.nvRes.Format(), gpuID)
```

But, I encountered issue as follow:
```
rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)
success = self.nvDwn.DownloadSingleSurface(resSurface, rawFrame)
if not success:
print('Failed to download surface')
break
```
the program exited when download rawFrame from surface.

```
/home/jt1/miniconda3/bin/python /home/jt1/VideoProcessingFramework/install/bin/test.py
Decoding on GPU 0
[hls @ 0x556f553a4e40] Skip ('#EXT-X-VERSION:3')
[hls @ 0x556f553a4e40] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0x556f553a4e40] Skip ('#EXT-X-VERSION:3')
[hls @ 0x556f553a4e40] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0x556f553a4e40] Opening 'http://10.196.118.36:9054/live/cHZnNjcxLWF2LzE2LzU%3D/0.ts' for reading
[hls @ 0x556f553a4e40] Opening 'http://10.196.118.36:9054/live/cHZnNjcxLWF2LzE2LzU%3D/1.ts' for reading
3840 2160
PixelFormat.NV12
24883200
Failed to download surface
```

Where I made a mistake? It will be very helpful if you could provide some information about it.

**Comment by rarzumanyan** [comment]
Hi @LuletterSoul,

This is known issue, NPP resize for RGB format sometimes return error -14 (invalid image line size) though the line size is actually correct.  If you're exporting video frames to Pytorch tensors, you may skip the VPF resize and do that on the tensor.

Otherwise you may workaround this feature as follows:

- convert nv12->yuv420

- resize yuv420

- convert yuv420->nv12

- convert nv12->rgb

Unfortunately NPP doesn't support resize for nv12, so back and forth conversion to yuv420 is required.

**Comment by LuletterSoul** [comment]
@rarzumanyan Thanks, good tips you are post! 

Is it possible that execute yuv420  to RGB conversion?

I need resized RGB numpy array instead of Pytorch tensors.

**Comment by rarzumanyan** [comment]
@LuletterSoul 
>Is it possible that execute yuv420 to RGB conversion?

I've added it to master branch, check out latest revision.

**Comment by LuletterSoul** [comment]
@LuletterSoul Great! I see it.But it seems to be C++ implementation.How could I use this new feature by calling Python interface? Sorry, I am not good at C++ programming.

**Comment by rarzumanyan** [comment]
@LuletterSoul 
The same way as usual, you just select desired formats:
```python
self.nvCvt = nvc.PySurfaceConverter(width, height, nvc.PixelFormat.YUV420, nvc.PixelFormat.RGB, gpuID)
```
VPF itself is written in C++ and exported to Python module.

**Comment by rarzumanyan** [comment]
Hi @LuletterSoul,
I assume the issue is solved and can be closed. Please reopen in case it’s not.
