### ISSUE TITLE
How to specify CRF for PyNvEncoder

### ISSUE THREAD

**Issue by InkosiZhong** [NVIDIA/VideoProcessingFramework#410]
I'm currently trying to specify the CRF used by `PyNvCodec.PyNvEncoder`.
I tried the following code,
```python
self.nvEnc = nvc.PyNvEncoder({'codec': 'hevc', 'crf': '23'}, self.ctx.handle, self.str.handle)
```
When I adjust the value of the CRF (from 0 to 51), I find that the output file has not changed.
What is the correct way to specify it?

**Comment by theHamsta** [comment]
This does not seem to be supported at the moment. Invalid dictionary parameters don't cause an error at the moment.
See the supported https://github.com/theHamsta/VideoProcessingFramework/blob/89e5f0faf024cf9b3e64e97a567b30361f050903/src/TC/src/NvCodecCliOptions.cpp#L76-L45 options. As a workaround, you could work with constant Q mode.

**Comment by InkosiZhong** [comment]
Thank you very much. 
So if I want to control the reconstruction quality (e.g. PSNR), I should use  `vbr`/`cbr` with `bitrate`, or specify a `constqp`.
```python
{'rc': 'vbr', 'bitrate': '10M'}
{'rc': 'constqp', 'constqp': '27'}
```

**Comment by theHamsta** [comment]
Apparently, you can also specify a `cq` parameter like in ffmpeg.
