### ISSUE TITLE
Found Python3: /home/super/anaconda3/bin/python3.9 (found suitable version "3.9.12", minimum required is "3.6") found components: Interpreter Development Development.Module Development.Embed

### ISSUE THREAD

**Issue by JunkangLiu** [NVIDIA/VideoProcessingFramework#414]
`cmake ..   -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG"  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK"   -DGENERATE_PYTHON_BINDINGS:BOOL="1"   -DGENERATE_PYTORCH_EXTENSION:BOOL="1"  -DPYTHON_LIBRARY=/home/super/anaconda3/envs/py38/lib/libpython3.8.so   -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"  -DPYTHON_EXECUTABLE=/home/super/anaconda3/envs/py38/bin/python3  -DPYTHON_INCLUDE_DIR=/home/super/anaconda3/envs/py38/include/python3.8/`
I use the above command for cmake, but
`Found Python3: /home/super/anaconda3/bin/python3.9 (found suitable version "3.9.12", minimum required is "3.6") found components: Interpreter Development Development.Module Development.Embed`
If this happens, it will not continue.
It seems that PYTHON_LIBRARY is not taking effect either

**Comment by gedoensmax** [comment]
Have you tried omitting all python variables and just running:
```
conda activate py38
cmake .. -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" -DGENERATE_PYTHON_BINDINGS:BOOL="1" -DGENERATE_PYTORCH_EXTENSION:BOOL="1" -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" 
```

**Comment by JunkangLiu** [comment]
Thank you very much.It work for me.
