### ISSUE TITLE
can you help me write push rtsp simple code

### ISSUE THREAD

**Issue by sxfmusic** [NVIDIA/VideoProcessingFramework#417]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gedoensmax** [comment]
If there is an issue with a sample you wrote that can be fixed inside VPF, we are happy to help. However, we will not produce code from scratch that uses VPF to solve your explicit problem.
