### ISSUE TITLE
Cannot import PyNvCodec after pip installation.

### ISSUE THREAD

**Issue by quqixun** [NVIDIA/VideoProcessingFramework#429]
**Describe the bug**
Cannot import PyNvCodec after pip installation.

**To Reproduce**
Install VPF as shown in README, then import.
```bash
apt install -y \
    libavfilter-dev \
    libavformat-dev \
    libavcodec-dev \
    libswresample-dev \
    libavutil-dev\
    wget \
    cmake \
    build-essential \
    git \
    libnvidia-encode-525 \
    libnvidia-decode-525

pip3 install git+https://github.com/NVIDIA/VideoProcessingFramework
```
```python
import PyNvCodec
```

**Expected behavior**
After installation and import, the following error occured.
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/vpf/lib/python3.9/site-packages/PyNvCodec/__init__.py", line 17, in <module>
    from ._PyNvCodec import *  # noqa
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Nvidia driver version: 525.78.01
 - CUDA version: 12.0
 - Python version: 3.9
 - FFmpeg (apt install) version: 4.4.3 with libavfilter 7.110.100
 - FFmpeg (compiled from source) version: latest with libavfilter 8.55.100

**Comment by theHamsta** [comment]
Can you check whether you did the pip install and the import in the same environment? Either both inside the vpf environment or both outside and that the pip you were using is the pip of the anaconda env? To be sure you could run `python -mpip install .`.

Does the installation work outside of your anaconda environment? Anaconda changes several environment variables that affect library discovery. It should have access to the same libraries as during pip install. The only dependency of vpf is numpy. So it shouldn't mess up your global environment. 

Since it's printing libgobject.so, could you run `ldd` on the mentioned library. Ffmpeg could maybe use libgobject when build with certain extensions. I'm not aware that python would use glib. You can also run ldd on the vpf python extension itself.

**Comment by theHamsta** [comment]
@quqixun could you solve your problem?

**Comment by quqixun** [comment]
@theHamsta I wil try later. Please wait.

**Comment by quqixun** [comment]
@theHamsta Did you reproduce the error ?
In my system, /lib/x86_64-linux-gnu/libgobject-2.0.so.0 is a link to /usr/lib/i386-linux-gnu/libgobject-2.0.so.0.6400.6 .

**Comment by theHamsta** [comment]
What I was suggesting was to try to compile and import without the conda environment. I assume that your Anaconda environment provides a different libffi version than you system. ffmpeg was probably configured to use your systems' libgobject which would use your systems's libffi.

I have very bad experience with Anaconda setting environement variables or compiling packages with Anaconda. Even when you're in this `base` environment, Anaconda has already manipulated a lot of library paths which cause a lot of problems. Try to install and compile everything without Anaconda changing anything in your `.bashrc`/`.profile`. If this works and you still want to use a virual environment, then I would also recommend to run ffmpeg's configure inside the Python environment. 

You can also run ldd on `/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.6` to see whether the loaded deps are different inside and outside your Anaconda environment.

**Comment by quqixun** [comment]
@theHamsta Thanks for the suggestion.
I just update my os from ubuntu 20.04 to 22.04 (keep conda environment), then everything is fine.
It looks good that compile VPF from source and run import in the save conda environment under ubuntu 22.04.
All tests pass.

**Comment by theHamsta** [comment]
> @theHamsta Thanks for the suggestion. I just update my os from ubuntu 20.04 to 22.04 (keep conda environment), then everything is fine. It looks good that compile VPF from source and run import in the save conda environment under ubuntu 22.04. All tests pass.

I assume that the system ffmpeg and the self-compiled one got mixed up in some way

**Comment by quqixun** [comment]
It maybe not the problem with system ffmpeg, because I cleaned the system ffmpeg before compilling ffmpeg from source.
