### ISSUE TITLE
CUDA ERORR SYSTEM DRIVER MISMATCH on docker

### ISSUE THREAD

**Issue by Wenlong0913** [NVIDIA/VideoProcessingFramework#431]
**Describe the bug**
Built docker image from scrach by using docker/Dockerfile.gpu, and got errors after trying SampleDecodeRTSP.py.
It says CUDA driver mismatch which make me confused.

**To Reproduce**
1. Build a docker image by using the followinng command and Dockerfile
docker build --tag vpf-gpu-all -f docker/Dockerfile.gpu --build-arg GEN_PYTORCH_EXT=1 --build-arg GEN_OPENGL_EXT=1 .
```
# syntax=docker/dockerfile:experimental
FROM docker.io/jrottenberg/ffmpeg:snapshot-ubuntu as ffmpeg
FROM nvidia/cuda:11.4.1-cudnn8-devel-ubuntu20.04 as build

ENV POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_VERSION=1.1.13

ENV PATH="/opt/.venv/bin:$POETRY_HOME/bin:$PATH" \
    PYTHON_BINARY="/opt/.venv/bin/python"

ARG GEN_PYTORCH_EXT
ARG GEN_OPENGL_EXT

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv A4B469963BF863CC

RUN apt update && DEBIAN_FRONTEND=noninteractive \
    apt -y install \
    git wget cmake \
    build-essential curl \
    libmp3lame-dev libtheora-dev libvorbis-dev \
    libglu1-mesa-dev freeglut3-dev \
    libnvidia-decode-470 \
    ninja-build \
    pkg-config \
    python3 python3-pip python3-venv && \
    rm -rf /var/lib/apt/lists/*

# https://python-poetry.org/docs/
WORKDIR $POETRY_HOME
RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR /opt

COPY docker/Makefile docker/Makefile
COPY poetry.lock poetry.lock
COPY pyproject.toml pyproject.toml
COPY docker/poetry-env.sh docker/poetry-env.sh

RUN python3 -mpip install cmake
# Build poetry virtual environment
RUN bash docker/poetry-env.sh PYTHON_BINARY=$PYTHON_BINARY GEN_PYTORCH_EXT="$GEN_PYTORCH_EXT" GEN_OPENGL_EXT="$GEN_OPENGL_EXT"

# Build vpf
COPY src src
COPY pyproject.toml pyproject.toml
COPY setup.py setup.py
COPY CMakeLists.txt CMakeLists.txt
COPY --from=ffmpeg /usr/local /opt/ffmpeg
# We need to patch pkgconfig since we rectlessly moved the whole directory
RUN sed -i 's/\/usr\/local/\/opt\/ffmpeg/g' /opt/ffmpeg/lib/pkgconfig/*

RUN PKG_CONFIG_PATH=/opt/ffmpeg/lib/pkgconfig/ python3 -mpip wheel . --verbose

FROM nvidia/cuda:11.4.1-cudnn8-devel-ubuntu20.04

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv A4B469963BF863CC
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    git build-essential libbsd0 \
    wget cmake vim libtbb-dev \
    libjpeg8-dev libpng-dev libtiff-dev \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    libdc1394-22-dev libssl-dev \
    libnvidia-decode-470 \
    libxine2-dev libv4l-dev \
    libboost-all-dev libdc1394-22-dev \
    libglu1-mesa-dev freeglut3-dev \
    python3 python3-pip python3-venv curl

WORKDIR /opt

COPY --from=build /opt/PyNvCodec-*.whl /opt

COPY --from=build /opt/poetry /opt/poetry
# COPY --from=build /opt/ffmpeg/lib/lib*.so.* /opt/ffmpeg/lib/
COPY --from=build /opt/ffmpeg /opt/ffmpeg
# Normally we'd reinstall the enviroment but pycuda is built with cuda headers
# which are not available in the nvidia runtime image
COPY --from=build /opt/.venv /opt/.venv
COPY . .

ENV POETRY_HOME="/opt/poetry"

ENV PATH="/opt/.venv/bin:$POETRY_HOME/bin:/opt/ffmpeg/bin:$PATH" \
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/dist:/opt/ffmpeg/lib:/opt/dist/bin:/usr/local/cuda-11.4/compat/:/opt/.venv/lib/python3.8/site-packages/torch/lib" \
    PYTHONPATH=/opt/.venv/bin:/opt/dist:/opt/dist/bin

RUN python3 --version && python3 -mpip install PyNvCodec-*.whl && rm *.whl
RUN python3 -c "import PyNvCodec"

ENTRYPOINT ["/bin/bash"]

```
2. Try python sample/SampleDecodeRTSP.py 0 10000 rtsp://xxxx
3. See error
<img width="987" alt="image" src="https://user-images.githubusercontent.com/17941167/215726797-23011ace-933d-44fd-b479-7381ad6c5f9a.png">

I have checked the cuda lib is matching the driver version.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/17941167/215729276-2156036e-7ec3-46da-8ad3-fda5c0fd7d46.png">

Can anyone help me how to fix this problem? Any information will be greatly appriciated.

**Expected behavior**
Decode rtsp stream normally.

**Desktop (please complete the following information):**
 - Driver version: 470.161.03
 - Docker image: nvidia/cuda:11.4.1-cudnn8-devel-ubuntu20.04 
 - GPU: RTX 2070

**Comment by gedoensmax** [comment]
There are different issues at play - first of all your driver is quite old and no longer supported by video codec SDK12. 
Please see issue #432. 
Furthermore this sound a little like your `docker run` command might be missing some driver capabilities: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#driver-capabilities
Just try to set `-e NVIDIA_DRIVER_CAPABILITIES=all`.

**Comment by Wenlong0913** [comment]
> There are different issues at play - first of all your driver is quite old and no longer supported by video codec SDK12. Please see issue #432. Furthermore this sound a little like your `docker run` command might be missing some driver capabilities: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#driver-capabilities Just try to set `-e NVIDIA_DRIVER_CAPABILITIES=all`.

kk, I'll try to update driver/dependency and try again. Thanks.
