### ISSUE TITLE
CUDA error: CUDA_ERROR_NO_DEVICE

### ISSUE THREAD

**Issue by SubMarineas** [NVIDIA/VideoProcessingFramework#433]
**Describe the bug**

CUDA error: CUDA_ERROR_NO_DEVICE. no CUDA-capable device is detected

When decoding, the error is cuda error. The detailed log is:

```python
(base) '/xxx/program/VideoProcessingFramework# python3 ceshi3.py
0 ............gpu_id
/tmp/pip-req-build-pmp9vnfi/src/TC/src/NvDecoder.cpp:215
CUDA error: CUDA_ERROR_NO_DEVICE
no CUDA-capable device is detected

Decoder not initialized.Cuvid parser faced error.
Cuvid parser exception happened.
Exception in thread Thread-1:
0 ............gpu_id
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ceshi3.py", line 209, in run
    src_surface = nvDec.DecodeSingleSurface()
PyNvCodec._PyNvCodec.CuvidParserException: HW reset
/tmp/pip-req-build-pmp9vnfi/src/TC/src/NvDecoder.cpp:215
CUDA error: CUDA_ERROR_NO_DEVICE
no CUDA-capable device is detected

Decoder not initialized.Cuvid parser faced error.
Cuvid parser exception happened.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "ceshi3.py", line 209, in run
    src_surface = nvDec.DecodeSingleSurface()
PyNvCodec._PyNvCodec.CuvidParserException: HW reset
```

**Comment by SubMarineas** [comment]
At first, I thought there was a problem with my version, because I had been using VPF: v1.0 before, and then I updated cuda and ffmpeg to the latest version, using ` pip install-- Verbose ` After compiling, there is no problem, but once running, it still reports an error. The error line I locate is:

```python
        while True:
            t1 = time.time()
            # Decode NV12 surface
            with self.message_lock:
                src_surface = nvDec.DecodeSingleSurface()
                frame_p += 1
                if frame_p % 25 != 0:
                    continue
                if src_surface.Empty():
                    break

                # Convert to planar RGB
                rgb_pln = to_rgb.run(src_surface)
                if rgb_pln.Empty():
                    break

```

`src_surface = nvDec.DecodeSingleSurface()`  In this sentence

**Comment by SubMarineas** [comment]
The Docker image version in my machine is:
![image](https://user-images.githubusercontent.com/33534492/215942740-6349edd7-2467-4297-af21-8f2d72d0fc5f.png)

**Comment by gedoensmax** [comment]
Your driver is the problem here. As we are using video codec SDK headers version 12 the minimum requirements are:
‣ Windows: Driver version 522.25 or higher
‣ Linux: Driver version 520.56.06 or higher
It is not an issue to compile VPF with different video codec headers by either replacing the local files in: https://github.com/NVIDIA/VideoProcessingFramework/tree/master/src/TC/third_party or by specifying another header directory: https://github.com/NVIDIA/VideoProcessingFramework/blob/ec8caf75c341b9f4a125db59676c6742c8b666fd/src/TC/CMakeLists.txt#L102
Here is a similar issue: https://github.com/NVIDIA/VideoProcessingFramework/issues/424#issuecomment-1404885171

**Comment by SubMarineas** [comment]
> Your driver is the problem here. As we are using video codec SDK headers version 12 the minimum requirements are: ‣ Windows: Driver version 522.25 or higher ‣ Linux: Driver version 520.56.06 or higher It is not an issue to compile VPF with different video codec headers by either replacing the local files in: https://github.com/NVIDIA/VideoProcessingFramework/tree/master/src/TC/third_party or by specifying another header directory:
> 
> https://github.com/NVIDIA/VideoProcessingFramework/blob/ec8caf75c341b9f4a125db59676c6742c8b666fd/src/TC/CMakeLists.txt#L102
> 
> 
> Here is a similar issue: [#424 (comment)](https://github.com/NVIDIA/VideoProcessingFramework/issues/424#issuecomment-1404885171)

Oh, this is indeed the problem. After updating the driver of the host machine, I copied the `so` dynamic library into the docker images, and it can run without recompilation. Thank you very much
