### ISSUE TITLE
There is no PytorchNvCodec after pip installation.

### ISSUE THREAD

**Issue by quqixun** [NVIDIA/VideoProcessingFramework#434]
**Describe the bug**

In the sample code SampleTensorRTResnet.py , PytorchNvCodec is required.
However, there is no PytorchNvCodec in python environment after pip installation.

In previous code like 873a17b829f1bb2181b9e5a7bd24960dcf17d94a , PytorchNvCodec can be compiled from source, see https://github.com/NVIDIA/VideoProcessingFramework/issues/430 .
How to compile PytorchNvCodec with newest code using pip installation?

**Comment by theHamsta** [comment]
We should document that more clearly. At the moment it is only in the wiki and in the README for building the documentation
