### ISSUE TITLE
Hello, can you compile in python3.8?

### ISSUE THREAD

**Issue by sbbug** [NVIDIA/VideoProcessingFramework#44]
Hello,I'm so sorry to ask you one more question!

Can you compile in python3.8?

When I compiled in python3.8,i encountered an error:

-- Searching for FFmpeg libs in /usr/local/ffmpeg/lib
-- Searching for FFmpeg headers in /usr/local/ffmpeg/include
**CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS) (Required is at
  least version "3.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  PyNvCodec/CMakeLists.txt:46 (find_package)**

-- Configuring incomplete, errors occurred!
See also "/home/jt1/VideoProcessingFramework/build/CMakeFiles/CMakeOutput.log".

**Comment by rarzumanyan** [comment]
Hi @sbbug 

VPF doesn't have any settings specific to Python version. 
Probably you're just missing Python development package.

**Comment by ImpudentStrumpet** [comment]
which python development package?
the python development package?

**Comment by ImpudentStrumpet** [comment]
the ffmpeg python development package?
