### ISSUE TITLE
How do I build and install PytorchNvCodec? 

### ISSUE THREAD

**Issue by AntreasAntoniou** [NVIDIA/VideoProcessingFramework#449]
**Describe the bug**
I can't run any of the pytorch samples. I need to use this package in the context of deep learning, so any help is greatly appreciated.

**To Reproduce**
1. Follow installation instructions to install VPF
2. run python Samples/SamplePytorch.py
Get error about PytorchNvCodec not being available

**Expected behavior**
The program should run and sample pytorch tensors from a video

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.08
 - Nvidia driver version: 525.85.05
 - CUDA Version: 12.0
 - Video Codec SDK Version: Whatever shipped with 525 (How do I get this version info?)
 - Python Version: 3.10

**Additional context**

**Comment by theHamsta** [comment]
Does this work for you?
```
pip install src/PytorchNvCodec  # install Torch extension if needed (optional), requires "torch" to be installed before
```
