### ISSUE TITLE
Failed to create new PyNvDecoder instance

### ISSUE THREAD

**Issue by mchl0203** [NVIDIA/VideoProcessingFramework#45]
Hi @rarzumanyan :

After my decoder process runs for a few hours, `nv_dec.DecodeSingleSurface()` is empty. So I wrote a piece of code to recreate the `PyNvDecoder` instance:
```

while True:
    raw_surface = nv_dec.DecodeSingleSurface()
    if raw_surface.Empty():
        logging.info(f'failed to decode video frame')
        nv_dec = None
        while not isinstance(nv_dec, nvc.PyNvDecoder):
            try:
                time.sleep(30)
                nv_dec = nvc.PyNvDecoder(url, gpu_id, {'rtsp_transport': 'tcp', 'max_delay': '5000000'})
            except Exception as e:
                logging.info(f'failed to recreate the nv_dec: {e}')
                continue
        continue
    ...
```
But the PyNvDecoder instance cannot be created all the time, and print a error: `FFmpegDemuxer: no AVFormatContext provided`. Do you know why? How should I locate the error?
Looking forward to your recovery ~

**Comment by rarzumanyan** [comment]
Hi @mchl0203 

> But the PyNvDecoder instance cannot be created all the time, and print a error: FFmpegDemuxer: no AVFormatContext provided

It means FFmpeg demuxer can't open URL.
That's probably the reason `nv_dec.DecodeSingleSurface()` returns empty surface.

**Comment by mchl0203** [comment]
Hi @rarzumanyan :
Now, the process is normal again after running for half an hour...
> It means FFmpeg demuxer can't open URL.
What are the reasons for this: Is the network unstable, or is the tcp cache full ?

**Comment by rarzumanyan** [comment]
>Is the network unstable, or is the tcp cache full ?

**Comment by mchl0203** [comment]
OK, Sorry to cause you a lot of trouble, and thank you for your help during this time ~
