### ISSUE TITLE
SampleEncode.py RuntimeError: LoadNvEncApi : NVENC library file is not found. 

### ISSUE THREAD

**Issue by MrShenGaHui** [NVIDIA/VideoProcessingFramework#467]
Traceback (most recent call last):
  File "SampleEncode.py", line 120, in <module>
    encode(gpuID, decFilePath, encFilePath, width, heihgt)
  File "SampleEncode.py", line 79, in encode
    success = nvEnc.EncodeSingleFrame(rawFrame, encFrame, sync = False)
RuntimeError: LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at /home/vpf/VideoProcessingFramework-1.1.2/PyNvCodec/TC/src/NvEncoder.cpp:102

How can I solve it？

**Comment by theHamsta** [comment]
Can you check whether `libnvidia-encoder.so` is present on your system? Try
```
❯ ll /usr/lib/x86_64-linux-gnu/libnvidia-encode.so*
Permissions Size User Date Modified Name
lrwxrwxrwx    21 root 19 Apr 13:43  /usr/lib/x86_64-linux-gnu/libnvidia-encode.so -> libnvidia-encode.so.1
lrwxrwxrwx    26 root 19 Apr 13:43  /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1 -> libnvidia-encode.so.545.00
.rwxr-xr-x  248k root 19 Apr 13:43  /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.545.00
```
Please provide more information on your system. Are you running Docker? Which Linux distribution are you using?

**Comment by MrShenGaHui** [comment]
How do I install libnvidia encoder. so
Docker version 23.0.1, build a5ee5b1

**Comment by theHamsta** [comment]
Check whether this `*.so` is present at your host.

Can you try to launch your docker container like as `docker run -it --rm --gpus 'all,"capabilities=compute,utility,video"' <your docker image>` as it is documented in the README.md https://github.com/theHamsta/VideoProcessingFramework/blob/b69ac4ffc11e975e62610c26a7c2600b80cdfc61/README.md#L50-L53

**Comment by MrShenGaHui** [comment]
Thank you, my problem has been resolved。How can I turn the frame Save as Picture?I need pictures
 
![image](https://user-images.githubusercontent.com/74952780/233817747-6cc280c3-d2ac-4f58-8a81-d27e190e68c2.png)

**Comment by theHamsta** [comment]
> Thank you, my problem has been resolved。How can I turn the frame Save as Picture?I need pictures
> 
> ![image](https://user-images.githubusercontent.com/74952780/233817747-6cc280c3-d2ac-4f58-8a81-d27e190e68c2.png)

I don't understand. You can convert the bytes to a Numpy array and then use a image library like scikit-image to save the image. You probably want to convert from NV12 to RGB to save as an image.
