### ISSUE TITLE
High Bit Depth Encoding not supported while input video is 8-bit (incorrect error message?)

### ISSUE THREAD

**Issue by Renzzauw** [NVIDIA/VideoProcessingFramework#469]
**Describe the bug**
I try to encode a video in my pipeline that uses VPF. The input video has multiple video streams, but they all have 8 bits depth, so I would expect no issues while encoding. I'm not sure if the correct encoding error is being thrown, so perhaps this is a bug. I've managed to reproduce this issue simply by running the SamplePytorch script (since I'm also converting from and to PyTorch in my code).

Maybe another question I have is, what is the expected decoding behavior in case of multiple video streams in one single container?

**To Reproduce**
1. Run SamplePytorch.py on attached video
2. See error `High Bit Depth Encoding not supported` in console

**Expected behavior**
The video should be encoded with zero issues or raise the correct or a more clear error message what is wrong with the input video.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Nvidia driver version: 530.30.02
 - CUDA Version 12.1
 - Python Version 3.8.10

**Additional context**
[Video related to my issue](https://drive.google.com/file/d/1MSbQzr50w9nrYDMJklNX2i2IYT6oo-kn/view?usp=share_link)

**Comment by rnaskulwar** [comment]
taking a look

**Comment by Renzzauw** [comment]
Hi @rnaskulwar, appreciate the help! Do you have any updates on this issue by any chance?

**Comment by KrabbyPattie** [comment]
Hi @Renzzauw,

I stumbled across this thread as I also had this issue on Windows.
After delving into the docs a bit, I started changing the parameters available in the constructor.
Changing the codec to hevc instead of h264 solved my issue. 
Hopefully it works!

**Comment by Renzzauw** [comment]
This issue seems to be fixed after pulling the latest commit
