### ISSUE TITLE
What can i do for get the newest frame from stream media.

### ISSUE THREAD

**Issue by summm** [NVIDIA/VideoProcessingFramework#471]
Really strange, the decoding speed is ten times faster than the other, but with this code, the final video displayed in front of me is 50-100ms later than the other,  probably a 3-6 frame delay. How can I get the latest frame of the streaming media as quickly as possible?
```
video_path = "http://192.168.0.5/test.flv"

nvDec = nvc.PyNvDecoder(video_path, 0,)#{'max_delay': '1', 'bufsize': '1k'}
# nvCvt = nvc.PySurfaceResizer(1080, 720, nvDec.Format(), 0)
x_width, x_height = nvDec.Width(), nvDec.Height()
to_rgb = cconverter(x_width, x_height, 0)
to_rgb.add(nvc.PixelFormat.NV12, nvc.PixelFormat.YUV420)
to_rgb.add(nvc.PixelFormat.YUV420, nvc.PixelFormat.RGB)
#to_rgb.add(nvc.PixelFormat.RGB, nvc.PixelFormat.RGB_PLANAR)
nvDwn = nvc.PySurfaceDownloader(x_width, x_height, nvc.PixelFormat.RGB, 0)
while True:
    #t1 = time.time()
    src_surface = nvDec.DecodeSingleSurface()
    if src_surface.Empty():
        break
    #t2=time.time()
    #print(t2-t1)

    rgb_pln = to_rgb.run(src_surface)
    if rgb_pln.Empty():
        break

    frameRGB = np.ndarray(shape=(rgb_pln.HostSize()), dtype=np.uint8)
    success = nvDwn.DownloadSingleSurface(rgb_pln, frameRGB)

    #cv2.imwrite("{}.jpg".format(count), frameRGB.reshape((x_height, x_width, 3)))
    cv2.imshow("PyNvCodec",frameRGB.reshape((x_height, x_width, 3)))
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

```

**Comment by rnaskulwar** [comment]
you need flush the remaining frames from decoder, to get the latest frame or any frame for that matter, you could use Seek functionality from demuxer

**Comment by rnaskulwar** [comment]
yes, due to B frames (inter frame dependency) there is latency of 2-3 frames, Could you elaborate on the two applications being run, If my understanding is correct, you are running VPF for streaming media and a video from disk. VPF decode for streaming is slower in your case?

**Comment by RomanArzumanyan** [comment]
Hi @summm 

I recommend you to build VPF with NPP support and examine both timelines like it's described here: [VPF-Performance-analysis](https://github.com/NVIDIA/VideoProcessingFramework/wiki/VPF-Performance-analysis).
Probably you will only need to check the last couple seconds.

**Comment by summm** [comment]
@rnaskulwar The media source for the test is live streaming media on TikTok, such as links like https://pull-f5-sg01.fcdn.us.tiktokv.com/stage/stream-7226994747657751298_or4.flv. It is not reading files on the hard disk.
At any time when I take a screenshot, they will have different degrees of time difference, but using PyNvCodec to decode is the slower one.The way they are displayed has been converted to rgb numpy arrays and displayed through opencv, which should be the same, but I measured the time for getframe part, VPF is much faster than the other, so I really feel very strange.
![1](https://user-images.githubusercontent.com/8618253/235091021-63801501-3614-4a78-bfd3-7c11a3475254.png)
![2](https://user-images.githubusercontent.com/8618253/235091027-10795fdf-7c89-4d42-bb32-affe57e5fc79.png)
![3](https://user-images.githubusercontent.com/8618253/235091033-3eedce53-5351-403e-afd6-106a5f333cfd.png)

Thank you @RomanArzumanyan, I am reading it, which is a bit difficult for beginners like me to understand, but I am trying my best to understand it.

**Comment by RomanArzumanyan** [comment]
@theHamsta @gedoensmax 
Hello guys. Please take a closer look at this PR: #332 it may be the case here.

**Comment by summm** [comment]
Thank you @RomanArzumanyan , i`mtring to add this word to the two file.
NvDecoder.h
from
```
  bool setEndOfPicture = false;
```
to
```
bool setEndOfPicture = true;  
```
NvDecoder.cpp
from
```
---------------------------------------------------------------------------------------------
  const char *num_decode_surfaces_str = getenv("NV_NUM_DECODE_SURFACES");
  if (num_decode_surfaces_str) {
    return atoi(num_decode_surfaces_str);
  }

 int lowLatency = getenv("NV_LOW_LATENCY") ? atoi(getenv("NV_LOW_LATENCY")) : 0;
  if (lowLatency&1) setEndOfPicture = true;
  if (lowLatency&2) bLowLatency = true;
---------------------------------------------------------------------------------------------

if (setEndOfPicture) packet.flags |= CUVID_PKT_ENDOFPICTURE;
---------------------------------------------------------------------------------------------

```
```
---------------------------------------------------------------------------------------------
//const char *num_decode_surfaces_str = getenv("NV_NUM_DECODE_SURFACES");
//if (num_decode_surfaces_str) {
//  return atoi(num_decode_surfaces_str);
//}

//int lowLatency = getenv("NV_LOW_LATENCY") ? atoi(getenv("NV_LOW_LATENCY")) : 0; 
if (1) setEndOfPicture = true;
if (2) bLowLatency = true;
---------------------------------------------------------------------------------------------
packet.flags |= CUVID_PKT_ENDOFPICTURE;
---------------------------------------------------------------------------------------------
```

is it right? and uninstall old vpf then rebuilt it with base vpf2.0.0,The end seems to be the same as before, the latency still exists.
Perhaps some steps I did wrong?
