### ISSUE TITLE
RGB to YUV420 to NV12

### ISSUE THREAD

**Issue by sniklaus** [NVIDIA/VideoProcessingFramework#48]
Thank you for making this library! I have an array of RGB images, each image stored as a Numpy array, and would like to encode them using `PyNvEncoder`. However, I am currently stuck converting the RGB images to the NV12 format. I am under the impression that NPP does not support this conversion directly, but please correct me if I am wrong [1]. I will thus have to convert the RGB images to YUV420 first but `PySurfaceConverter(w, h, PixelFormat.RGB, PixelFormat.YUV420, 0)` is unfortunately not implemented. Any suggestions? Thanks!

[1] https://docs.nvidia.com/cuda/npp/group__image__color__model__conversion.html

**Comment by rarzumanyan** [comment]
@sniklaus 
>RGB images to the NV12 format

You're right. Unfortunately RGB->NV12 isn't supported in NPP.
I've merged you PR to master, thanks!
