### ISSUE TITLE
Frames and Timestamps(PTS) matching

### ISSUE THREAD

**Issue by DanCorvesor** [NVIDIA/VideoProcessingFramework#492]
**Describe the bug**
There seems no obvious way (or example of how to) match the decoded frames with their timestamps specifically when it's required to flush the decoding queue. 

Specifically, in the SampleDecode (with Standalone Demuxer) and SampleDemux, the packets are consumed sequentially and the example shows how to also get the timestamps (which is what I want). How can I match these timestamps with the frames, in particular if some of the frames are added to the queue and are not returned immediately so they have to be flushed at the end.

It would be great if I could have some advice/guidance about how to go about this or whether this is not possible. When I print the timestamps in the above examples, they are not in order. I'm not a GPU expert but it makes intuitive sense this is because of the parallelism under the hood but again the way in which you can relate this information to the processed frames would be very helpful. 

In addition, it would be great to know if this were possible for the Pytorch examples, as you're looping through the frames to be able to have a way to get the correct timestamps and hence only select those that match an input fps. 

Thanks in advance, 

Daniel

**Comment by RomanArzumanyan** [comment]
Hi @DanCorvesor 
Take a look here: https://github.com/NVIDIA/VideoProcessingFramework/blob/d8d5d1874c65ecfe6a82db2c282182e1b865452e/tests/test_PyNvDecoder.py#L201

**Comment by DanCorvesor** [comment]
Hi @RomanArzumanyan . Thanks so much for getting back, it's really appreciated. This helped a lot - I was able to successfully match the timestamps that I get reading an mp4 video on CPU with PyAV which is what I want. 

However, if I use your code in your Pytorch example to convert the color chain into the rgb format and then convert into a pytorch tensor (and then back to a numpy array) - the frames that I get are vastly different than those that I get back with PyAV on CPU. Am I missing something here - I presume I should be able to reproduce them? I can provide a code snippet and the video I am using if required?

**Comment by RomanArzumanyan** [comment]
Hi @DanCorvesor 

Attaching a screenshot and color conversion code would be helpful.

VPF has pretty accurate yuv 2 rgb color conversion, we just need to make sure that proper color space and range are used.

**Comment by RomanArzumanyan** [comment]
Hi @DanCorvesor 

You're converting YUV > RGB with hard-coded parameters:
```python
    def run(self, src_surface: nvc.Surface) -> nvc.Surface:
        surf = src_surface
        cc = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601, nvc.ColorRange.MPEG)
```

Actual colorspace and color range may be different hence the difference between VPF and PyAV results.
You can get color conversion params using `PyFfMpegDemuxer` class as it's shown here:
https://github.com/NVIDIA/VideoProcessingFramework/blob/d8d5d1874c65ecfe6a82db2c282182e1b865452e/tests/test_PyFfmpegDemuxer.py#L73-L77

**Comment by DanCorvesor** [comment]
Hi @RomanArzumanyan, update I actually messed up I was comparing integer values to float values so the difference is very very close - which is great. Sorry for the messing around on this. 

However, going back to your point that you made - given the colour spaces and ranges are unsupported, are the ones I specified originally good defaults (they are working in this case so seem to be). Is there a way I could check in code whether a colour space is supported when I initialise the colour converter class to check if the colour space/range inferred from the demuxer is supported and use these defaults if not?

**Comment by RomanArzumanyan** [comment]
Hi @DanCorvesor 

>Is there a way I could check in code whether a colour space is supported when I initialise the colour converter class to check if the colour space/range inferred from the demuxer is supported and use these defaults if not?

You can get the values with `nvDmx.ColorSpace()` and `nvDmx.ColorRange()`.
If they return `ColorSpace.UNSPEC` and / or `ColorRange.UDEF` then you can only guess or hard-code values.
Choosing different color conversion options won't crush you program, it will only affect the colors.
Basically that's what happening in your PyAV vs. VPF comparison test. PyAV just chooses different default options.
Since the are just 4 possible combinations (2 color space and 2 color range options) you can play around and see how simialr PyAV and VPF results are.

**Comment by DanCorvesor** [comment]
Thanks again @RomanArzumanyan last question (I hope) - you mentioned there are two default options for both. What are these, how can I see them?

**Comment by RomanArzumanyan** [comment]
Hi @DanCorvesor 

Honestly I don't know what the default values for PyAV are.
I assume the decision is made somewhere deep within FFMpeg guts.

For VPF there are no default values. That's done on purpose.
Inaccurate color space conversion can impose penalty on inference accuracy. 
There were couple issues of this nature, you can find them in list of closed issues if you like.

>you mentioned there are two default options for both. What are these, how can I see them?

If you want to see possible values for color space and color range, here they are:
https://github.com/NVIDIA/VideoProcessingFramework/blob/d8d5d1874c65ecfe6a82db2c282182e1b865452e/src/PyNvCodec/src/PyNvCodec.cpp#L240-L250

2 most common SDR color spaces are supported: BT.601 and BT.709.
Those define the coefficients of YUV > RGB color space conversion.

Also, 2 most common SDR color ranges are supported: narrow (MPEG) where pixel range is within [16;235] and wide (JPEG) which means [0;255] pixel range.

**Comment by RomanArzumanyan** [comment]
Hi @DanCorvesor 
Please LMK if your issue is resolved
