### ISSUE TITLE
enableMinQP / enableMaxQP

### ISSUE THREAD

**Issue by sniklaus** [NVIDIA/VideoProcessingFramework#50]
Shouldn't this be `enableMaxQP`?

https://github.com/NVIDIA/VideoProcessingFramework/blob/cd2ba87039930a45c6be81835e74021a63952d3d/PyNvCodec/TC/inc/NvEncoderCLIOptions.h#L218-L226

**Comment by rarzumanyan** [comment]
Hi @sniklaus ,

The code you're referencing sets the value at line 221 and enables the flag at line 223.

VPF uses some of Video Codec SDK Samples sources for decoder and encoder classes. So this CLI option name was kept as is. Do you have any particular issue with this feature behavior or its just the name that confuses you?
