### ISSUE TITLE
Is there CPP sample to how to use this lib?

### ISSUE THREAD

**Issue by BobDLA** [NVIDIA/VideoProcessingFramework#503]
Is there CPP sample to how to use this lib? 
Or is there  CPP lib with simple api to do the same hardware acceleration work?

Thank you

**Comment by BobDLA** [comment]
opencv video_reader should be a good start for gpu codec.

**Comment by avickars** [comment]
hey Im having the same issue as I would like to use this in c++ and am not able to figure out how to compile my program with it....did you figure it out?

**Comment by BobDLA** [comment]
> hey Im having the same issue as I would like to use this in c++ and am not able to figure out how to compile my program with it....did you figure it out?

I use opencv cudacodec instead of this.... the sample code is at https://github.com/opencv/opencv/blob/4.x/samples/gpu/video_reader.cpp  .

FYI
