### ISSUE TITLE
Guidance on modifying PyNvCode/CMakeLists.txt for c++ uses

### ISSUE THREAD

**Issue by avickars** [NVIDIA/VideoProcessingFramework#505]
**Describe the bug**

This continues on my previous issue here: https://github.com/NVIDIA/VideoProcessingFramework/issues/504 that I prematurely closed due to some misunderstandings I had (Im not very familiar with python bindings).

What I'm wondering is before a delve into into how to use the TC/TC_Core API,  if it is possible to get some guidance on modifying the PyNvCode/CMakeLists.txt file to create a shared library instead of a python binary?  I can see that it has been done before here: https://github.com/NVIDIA/VideoProcessingFramework/tree/cpp_samples, however it is very out dated.

I figured out ask since the API contained in PyNvCode is much simpler than the TC/TC_Core API.

I think it would be very beneficial to be able to use this package easily in c++ environments!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - Nvidia driver version
 - CUDA Version [e.g. 10.2]
 - Python Version [e.g. 3.7]
 - Video Codec SDK Version (only if using a custom header from the Video Codec SDK via the CMake variable `TC_VIDEO_CODEC_INTERFACE_DIR`)

**Additional context**

**Comment by rnaskulwar** [comment]
TC/TC_Core are set of C++ functions which are compiled into static library and VPF links to this library to create Python binding, you could change the CMakeLists.txt to create DLL instead

**Comment by avickars** [comment]
thanks @rnaskulwar .  Closing this ticket as I just extracted what I needed.  Ill post the code here in the future.
