### ISSUE TITLE
pip install vpf

### ISSUE THREAD

**Issue by sniklaus** [NVIDIA/VideoProcessingFramework#51]
Not having to go through the quite involved manual installation process and instead just being able to run `pip install vpf`, for example, would be greatly appreciated. :slightly_smiling_face:

**Comment by rarzumanyan** [comment]
VPF depends on Video Codec SDK which requires manual downloading and accepting the license agreement. This fact also prevents, for example, deploying the CI (which I’d really like to set up).

To my best knowledge, this feature can’t be implemented due to legal reasons.

**Comment by sniklaus** [comment]
That makes sense but it is unfortunate. In the past, one also had to login to download the CUDA toolkit. I hope Nvidia will eventually come to its senses rather sooner than later and stop doing this forced login hogwash on all of its libraries.

**Comment by rarzumanyan** [comment]
@sniklaus 
>Nvidia will eventually come to its senses rather sooner than later and stop doing this forced login hogwash 

Video Codec SDK allows users to facilitate H.264 and H.265 codecs which are not free. Situation around their licensing policies is not trivial and that's the reason for explicit login and license acceptance requirements. It's not hidden behind `git pull`.

Unlike that, VPF is distributed under Apache-2.0 so you understand the licensing straight from the project's main page.

**Comment by sniklaus** [comment]
I am not trying to argue about this, but I just wanted to let you know that NvPipe comes with the Video Codec SDK: https://github.com/NVIDIA/NvPipe/tree/master/src/Video_Codec_SDK_9.0.20

**Comment by rarzumanyan** [comment]
>I just wanted to let you know that NvPipe comes with the Video Codec SDK

I agree, it doesn't look too consistent.

Dont' get me wrong, I've asked this question to Video Codec SDK management, and it turned out that Video Codec SDK sources were distributed alongside NvPipe by mistake and they are now removed from repository. This is purely a legal matter so I'm following requirements here.

**Comment by TobiFisch** [comment]
I am necromancing this issue with the following question:
Nvidia DALI also decodes video, and is installable via pip:
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html

I am not sure whether this would apply to vpf as well, however I want to stress that having to build a library from source is a deployment nightmare. Having an easy way to install VPF (like DALI) would be great!

**Comment by rarzumanyan** [comment]
Hi @TobiFisch 

Unfortunately I don't have enough resources to take this task up and maintain proper PIP support in case of success. 
The next big thing for VPF is to implement better handshake with TensorRT and Triton server.

We accept 3rd party contributions so if you could contribute to the project by implementing this feature - that would be great and I'll help you with that as much as I can.

**Comment by TobiFisch** [comment]
I see, thank you for the information, perfectly understandable. The way DALI is deployed seems like an internal thing for nvidia, so I will not be able to contribute something similar as far as I can tell.
