### ISSUE TITLE
feat: cupy encoder , format for surface pointer

### ISSUE THREAD

**Issue by royinx** [NVIDIA/VideoProcessingFramework#510]
**Is your feature request related to a problem? Please describe.**

I'm writing a [cupy Encoder script](https://github.com/royinx/VideoProcessingFramework/blob/master/samples/SampleCupy.py) after reviewing the issue #383. my script copied the augmented frame from the cupy pointer to the surface pointer w/o error but cannot encode it into a video file.

Q1. surface input format
I'm thinking of the `array input format/ dimension` for the surface, please correct me if I made a mistake. 
|Encode surface (from) | dim | dtype |
|:---:|:---:|:---:|
|`nvc.PixelFormat.RGB` |CHW|uint8|
|`nvc.PixelFormat.RGB_PLANAR` |HWC|uint8|

Q2. memcpy2D
referencing to `PytorchNvCodec.cpp`,  memcpy2D(Async),  the pitch can transfer data faster.
The copy operation runs w/o an error, but shows 0 when validated while switching to `memcpyAsync` working well, any idea? 

```python
cp.cuda.runtime.memcpy2D(self.get_memptr(surface),
                         surface.Pitch(),
                         img_array.data.ptr,
                         surface.Width(),
                         surface.Width(),
                         surface.Height(),
                         cp.cuda.runtime.memcpyDeviceToDevice) 
``` 
to reproduce,  please uncomment [line 130](https://github.com/royinx/VideoProcessingFramework/blob/52e02c694150cc928e5d087ea3b2d104cf0a3218/samples/SampleCupy.py#L130)
```python
self._validate(surface, img_array)
```

**Additional context**
`cupy` is light and suitable for production, and the test script is easy to follow, may I contribute a PR after this issue?

**Comment by sayanmutd** [comment]
@royinx I think you are mistaken by the format of RGB and RGB Planar. RGB is in HWC format and it is also known as planar format. While the RGB planar is in CHW format.

**Comment by royinx** [comment]
thanks, @sayanmutd, 
After fixing the output format and debugging for mem copying, 
seems surface pixel is not stored by increment, 
means `memcpy2d` is necessary for surface pointer format instead of simple `memcpy`. 

Q1 and Q2 is fixed , this issue is closing.
The sample code is updated and posted for PR.
