### ISSUE TITLE
Set gpu devices

### ISSUE THREAD

**Issue by mchl0203** [NVIDIA/VideoProcessingFramework#52]
Hi,
```
nvc.PyNvDecoder(encFile, gpuID)
```
There are 2 GPUs, If I set `gpuID` to 1, the memory usage of gpu0 will also increase. What is the cause of this phenomenon? How to make the program use only gpu1 memory？Thank you ~
*PS: 2 threads running on different GPUs, can not handle this problem in multi-thread by setting CUDA_VISIBLE_DEVICES.*

**Comment by rarzumanyan** [comment]
Hi @mchl0203 
Does this happen only with GPU №1?
I mean if you use only GPU 0, does GPU 1 memory usage increase?

**Comment by mchl0203** [comment]
>I mean if you use only GPU 0, does GPU 1 memory usage increase?

No.

Decode in GPU 1:
![image](https://user-images.githubusercontent.com/8417221/82663116-a7406f00-9c61-11ea-9a30-1d7e33e1f7e4.png)
Decode in GPU 0:
![image](https://user-images.githubusercontent.com/8417221/82663531-6b59d980-9c62-11ea-8df8-eb36e60dcda2.png)
Decode in GPU 0 & CUDA_VISIBLE_DEVICES=1,2,3:
![image](https://user-images.githubusercontent.com/8417221/82663652-a9ef9400-9c62-11ea-9078-5603beff41b6.png)

**Comment by rarzumanyan** [comment]
Thanks for the update, I'll ask our CUDA people what may be the reason and will update you as I get word back from them.

BTW I see that if GPU 0 is used, it takes 365MiB, and if GPU 1 is used, 126 + 250 - 11 = 365MiB used as well. Wild guess: some information (115MiB) may be stored in GPU0 memory by default.

**Comment by rarzumanyan** [comment]
Hi @mchl0203 

Please check if GPU 0 memory utilization is higher then other GPUs when VPF isn't running.
If so, this is normal behavior as it's the scan-out GPU, and OS may allocate some resources on it by default. If you're using Quadro or Tesla GPUs, please let me know as they also support TCC mode.

**Comment by mchl0203** [comment]
Hi @rarzumanyan :
> Please check if GPU 0 memory utilization is higher then other GPUs when VPF isn't running.

When VPF is not running, does the memory utilization of all GPUs equal to 0?

I test on GeForce RTX 2080 Ti, GPU 1 decode 20 channels rtsp video stream, and GPU 0 memory utilization is 2.6G+. So, If I use GPUs to decode more video streams, the memory usage of GPU0 will be very high, then it is difficult to use GPU0. 
I mean, if I can allocate memory by setting and allocate GPU0's memory to other GPUs, then I can make more use of gpu0.
![image](https://user-images.githubusercontent.com/8417221/82820766-5c2e9200-9ed5-11ea-9d04-ec4d83463560.png)

**Comment by rarzumanyan** [comment]
Hi @mchl0203 

Thanks for the update. Can you upload a code snippet you're using?
I'll try to reproduce on my machine. Also, what's your OS?

**Comment by mchl0203** [comment]
Hi @rarzumanyan :

Thank you for your reply. My OS is CentOS7.7 .

```
import argparse
import logging
import multiprocessing as mp
import os
import time
from multiprocessing import Process

import numpy as np
import PyNvCodec as nvc

logging.basicConfig(
    format='[%(asctime)s] [p%(process)s] [%(levelname)s] %(message)s',
    level=logging.INFO)


def decode_stream(gpu_id, rtsp_url):
    video_id = rtsp_url.split('/')[-1]

    nv_dec = nvc.PyNvDecoder(rtsp_url, gpu_id, {'rtsp_transport': 'tcp',
                                                'max_delay': '5000000'})
    frame_rate = nv_dec.Framerate()
    logging.info(f"{video_id} Framerate: {nv_dec.Framerate()}")
    logging.info(f"{video_id} Framesize: {nv_dec.Framesize()}")
    w, h = nv_dec.Width(), nv_dec.Height()
    nv_cvt = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.NV12, nvc.PixelFormat.RGB,
                                    gpu_id)
    nv_dwl = nvc.PySurfaceDownloader(w, h, nvc.PixelFormat.RGB, gpu_id)

    cnt = 0
    s = time.time()
    while True:
        raw_surface = nv_dec.DecodeSingleSurface()
        if raw_surface.Empty():
            logging.info(f'{video_id}: failed to decode video frame')
            break

        cvt_surface = nv_cvt.Execute(raw_surface)
        if cvt_surface.Empty():
            break

        frame_size = cvt_surface.HostSize()
        raw_frame = np.ndarray(shape=frame_size, dtype=np.uint8)

        success = nv_dwl.DownloadSingleSurface(cvt_surface, raw_frame)
        if not success:
            logging.info(f'{video_id}: failed to download surface')
            break

        input_img = raw_frame.reshape(h, w, 3)

        cnt += 1
        if cnt % frame_rate == 0:
            logging.info(f"{video_id}: cost time: {time.time() - s}")
            logging.info(f"{video_id}: img shape: {input_img.shape}")
            cnt = 0
            s = time.time()


def create_procs(args):
    logging.info(f"Main process pid: {os.getpid()}")

    mp.set_start_method('spawn')

    if isinstance(args.decode_gpu_ids, list):
        gpu_ids = args.decode_gpu_ids
    else:
        gpu_ids = list(map(int, args.decode_gpu_ids.split(",")))

    proc_args = list(zip(gpu_ids, args.rtsp_urls))
    procs = [Process(target=decode_stream, args=(gpu_id, rtsp_url))
             for gpu_id, rtsp_url in proc_args]

    for proc in procs:
        proc.daemon = True
        proc.start()
    for proc in procs:
        proc.join()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="config")
    # modify rtsp url
    parser.add_argument("--rtsp_urls", help="rtsp_urls", type=str,
                        default=["rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream" for i in range(20)])
    parser.add_argument("--decode_gpu_ids", help="decode gpu ids", type=str,
                        default=[1] * 20)

    args = parser.parse_args()
    create_procs(args)

```

**Comment by rarzumanyan** [comment]
Any CLI arguments I need to pass to script?

**Comment by mchl0203** [comment]
It can be run directly. If you have 20 channels rtsp video streams, you can modify the default option of rtsp_urls.
![image](https://user-images.githubusercontent.com/8417221/83015304-d46e9200-a052-11ea-9fce-c051319b1392.png)

**Comment by rarzumanyan** [comment]
@mchl0203 
Doesn't reproduce on my machine with CentOS 8:

```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:02:00.0 Off |                    0 |
| N/A   20C    P0    24W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:82:00.0 Off |                  Off |
| N/A   17C    P8     9W / 250W |      0MiB / 24451MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

The `nvidia-smi dmon output`:
```bash
# gpu   pwr gtemp mtemp    sm   mem   enc   dec  mclk  pclk
# Idx     W     C     C     %     %     %     %   MHz   MHz
    0    30    20     -     0     0     0     0   715  1189
    1    60    15     -    39     6     0    87  4006  1442
    0    30    20     -     0     0     0     0   715  1189
    1    89    18     -    58    12     0   100  4006  1911
    0    30    20     -     0     0     0     0   715  1189
    1    91    20     -    57    12     0   100  4006  1911
    0    30    21     -     0     0     0     0   715  1189
    1    92    20     -    58    13     0   100  4006  1911
    0    30    21     -     0     0     0     0   715  1189
    1    91    21     -    58    13     0   100  4006  1911
    0    30    20     -     0     0     0     0   715  1189
    1    91    21     -    59    12     0   100  4006  1911
    0    30    21     -     0     0     0     0   715  1189
    1    92    21     -    53    11     0   100  4006  1911
    0    30    21     -     1     0     0     0   715  1189
```

**Comment by rarzumanyan** [comment]
@mchl0203 
Is there a chance you can test the same scenario in headless configuration? (no X server running, cards are not plugged to display).

**Comment by mchl0203** [comment]
@rarzumanyan 
Yes, The program run on the rack server without display device. What does this affect?

**Comment by mchl0203** [comment]
I tested this program on Tesla T4 and the result is the same. The OS of the machines I use are centos7.x, so this problem should not be related to TCC mode. I will try to find out the cause of this problem and update here, thank you for your reply.
![image](https://user-images.githubusercontent.com/8417221/84336188-56b99300-abc9-11ea-9863-1508c357d788.png)

**Comment by niaoyu** [comment]
@mchl0203 @rarzumanyan 
I also encountered the same problem. I tried 10 rtsp urls in gpuid 1. 
There will be a small gpu consuming which 99M per url, it looks like:

<img width="571" alt="截屏2020-09-29 下午7 19 35" src="https://user-images.githubusercontent.com/23436844/94551957-b75c0100-0288-11eb-8e53-7040f10a1f64.png">

@mchl0203 also using multiprocessing, each rtsp will consume 1144MiB  (desired gpu1)+ 11MiB(undesired gpu0), how could you do that with 20rtso urls with only 15079MB cuda?

**Comment by rarzumanyan** [comment]
@niaoyu 

Please check out latest `master` branch, many changes were introduced to memory allocation logic. CUDA runtime API was removed from GPU etc. It shall decrease the GPU #0 memory occupancy issue.
