### ISSUE TITLE
disable output delay

### ISSUE THREAD

**Issue by sniklaus** [NVIDIA/VideoProcessingFramework#53]
When encoding a frame, is there a way to make `bOutputDelay` in `GetEncodedPacket` set to `false`? Possible applications include streaming while wanting to keep the latency at a minimum. Thanks!

**Comment by rarzumanyan** [comment]
Hi @sniklaus 
Take a look at `sync_encode` branch. 
It adds the flag to `EncodeSingleSurface` and `EncodeSingleFrame` functions allowing to do synchronous encode:
```python
success = nvEnc.EncodeSingleFrame(frame=rawFrame, packet=encFrame, sync=True)
if not(success):
    print("Sync encode didn't return packet immediately")
```

Please update me if works fine for you, I will later merge to master.

**Comment by sniklaus** [comment]
Thank you for looking into this! And also thanks for the heads-up about the low latency preset!

The `sync_encode` branch works in the sense that it doesn't crash but the image quality when using a `cbr_ll_hq` rate control together with an average bitrate is significantly worse than what I got with my modified version of `f7a87fd41c49a9cf3b5504bad897afc71ae881a0`. Any ideas?

**Comment by rarzumanyan** [comment]
Hi @sniklaus,

Encoder initialization was re-implemented for better clarity and reconfigure flexibility, so the actual params encoder is initialized with may be different from that in [f7a87fd](https://github.com/NVIDIA/VideoProcessingFramework/commit/f7a87fd41c49a9cf3b5504bad897afc71ae881a0).

I've compared the settings before and after, the most significant difference I was able to see is the binary encoding selection mode: it was CABAC before and auto-selection after (which may also be VLC, it's better for performance and latency but worse for quality).

If you have any bitstream analyzer you can look at the encoded sequences and compare the actual encoding settings, then set needed options by hand.

**Comment by sniklaus** [comment]
I was setting `--lookahead 0` to explicitly disable lookahead which worked in the old version.

https://github.com/NVIDIA/VideoProcessingFramework/blob/f7a87fd41c49a9cf3b5504bad897afc71ae881a0/PyNvCodec/TC/inc/NvEncoderCLIOptions.h#L242-L249

In the new version `--lookahead 0` actually enables lookahead with a lookahead depth of 0.

https://github.com/NVIDIA/VideoProcessingFramework/blob/7189b72650513e36888ee5c455dd1b9261d6c0ed/PyNvCodec/TC/src/NvEncoderCliOptions.cpp#L622-L626

I changed my parameters but still no luck. I'll keep playing around with it.

**Comment by rarzumanyan** [comment]
@sniklaus 
That's a good point.
At line 623 it searches for a map entry and sets the flag disregarding the value.
It should be:
```cpp
auto look_ahead = FindAttribute(options, "lookahead"); 
if (!look_ahead.empty()) { 
  params.lookaheadDepth = FromString<uint16_t>(look_ahead);   
  params.enableLookahead = (0U != params.lookaheadDepth); 
} 
```

**Comment by sniklaus** [comment]
You got me good with this one: #58

The `sync_encode` branch looks good otherwise and it is similar to what I had with my modified version based off f7a87fd41c49a9cf3b5504bad897afc71ae881a0. I would be happy if this feature were merged in the main branch. :+1:

**Comment by rarzumanyan** [comment]
@sniklaus 
Merged to master, closing the issue.
