### ISSUE TITLE
Why don't support llhq/ll_hq preset?

### ISSUE THREAD

**Issue by allenling** [NVIDIA/VideoProcessingFramework#531]
in NvCodecCliOptions.cpp, i found this
```
  static const map<string, PresetProperties> preset_guids = {
      {"default", PresetProperties(NV_ENC_PRESET_DEFAULT_GUID, false, false)},
#if CHECK_API_VERSION(10, 0)
      {"P1", PresetProperties(NV_ENC_PRESET_P1_GUID, false, false)},
      {"P2", PresetProperties(NV_ENC_PRESET_P2_GUID, false, false)},
      {"P3", PresetProperties(NV_ENC_PRESET_P3_GUID, false, false)},
      {"P4", PresetProperties(NV_ENC_PRESET_P4_GUID, false, false)},
      {"P5", PresetProperties(NV_ENC_PRESET_P5_GUID, false, false)},
      {"P6", PresetProperties(NV_ENC_PRESET_P6_GUID, false, false)},
      {"P7", PresetProperties(NV_ENC_PRESET_P7_GUID, false, false)},
#else
      {"hp", PresetProperties(NV_ENC_PRESET_HP_GUID, false, false)},
      {"hq", PresetProperties(NV_ENC_PRESET_HQ_GUID, false, false)},
      {"bd", PresetProperties(NV_ENC_PRESET_BD_GUID, false, false)},
      {"ll",
       PresetProperties(NV_ENC_PRESET_LOW_LATENCY_DEFAULT_GUID, true, false)},
      {"ll_hp",
       PresetProperties(NV_ENC_PRESET_LOW_LATENCY_HP_GUID, true, false)},
      {"ll_hq",
       PresetProperties(NV_ENC_PRESET_LOW_LATENCY_HQ_GUID, true, false)},
      {"lossless",
       PresetProperties(NV_ENC_PRESET_LOSSLESS_DEFAULT_GUID, false, true)},
      {"lossless_hp",
       PresetProperties(NV_ENC_PRESET_LOSSLESS_HP_GUID, false, true)}
#endif
  };
```

options like hp, ll_hp are selectively included into preset_guids map.

and what the marco ` #if CHECK_API_VERSION(10, 0)` does is basically  to check the API version of nvEncodeAPI.

```
#define CHECK_API_VERSION(major, minor)                                        \
  ((major < NVENCAPI_MAJOR_VERSION) ||                                         \
   (major == NVENCAPI_MAJOR_VERSION) && (minor <= NVENCAPI_MINOR_VERSION))
```

so if we have a nvEncodeAPI of version greater than 10, in my case, my nvEncodeAPI has a version of 12, then we can not use ll_hp 

preset. 

so VPF doesn't support nvEncodeAPI whose version is greater than 10.0?

and actually if i just removed `#else`, then everything worked fine.

**Comment by allenling** [comment]
and any support for forced-idr option?

**Comment by RomanArzumanyan** [comment]
Hi @allenling 

These are legacy presets, they will be eventually deprecated. P1…P7 are simply better in terms of quality and speed.

**Comment by allenling** [comment]
@RomanArzumanyan 

i have a couple of questions about encoding, i hope they wouldn't bother you.

1. what about forced-idr opt? how could i set a frame to key frame?

2. apparently, VFP only supports limited types of frames to be encoded. and YUV420P is not on the list.

```
bool PyNvEncoder::EncodeSingleSurface(EncodeContext& ctx)
{
   // code omitted

    switch (eFormat) {
    case VPF::NV12:
      encoderFormat = NV_ENC_BUFFER_FORMAT_NV12;
      break;
    case VPF::YUV444:
      encoderFormat = NV_ENC_BUFFER_FORMAT_YUV444;
      break;
    case VPF::YUV420_10bit: //P12 already has memory representation similar to 10 bit yuv420, hence reusing the same class
    case VPF::P12:
      encoderFormat = NV_ENC_BUFFER_FORMAT_YUV420_10BIT;
      break;
    case VPF::YUV444_10bit:
      encoderFormat = NV_ENC_BUFFER_FORMAT_YUV444_10BIT;
      break;
    default:
      throw invalid_argument("Input buffer format not supported by VPF currently.");
        break;
    }
```

what if i got a yuv420P frame, and i wanted to encode it, what could i do?

1.  initalize PyNvEncoder with nvc.PixelFormat.NV12 format? but NV12 has a different memory order than YUV420P.
2.  convert YUV420P to YUV444P first? but VPF doesn't support conversions from YUV420P to YUV444P, or YUV444P to 
     YUV420P.

**Comment by RomanArzumanyan** [comment]
@allenling 

> what about forced-idr opt? how could i set a frame to key frame?

To force IDR frame you have to reconfigure encoder because it overrides it's GOP size.
Here's the method for that:
https://github.com/NVIDIA/VideoProcessingFramework/blob/82b51e7c29cb1c8259721170f39e95f3e95b4ad4/src/PyNvCodec/src/PyNvEncoder.cpp#L549-L560

> VFP only supports limited types of frames to be encoded

It only supports NV12 and YUV444 because that's what HW encoder can accept.
The only difference between YUV420 and NV12 is that for NV12 U and V values are interleaved.
You can simply convert from NV12 to YUV420, VPF supports that.

**Comment by allenling** [comment]
Thanks!
