### ISSUE TITLE
Feature Request: Support for Decoding Only I-Frames

### ISSUE THREAD

**Issue by XInitialize** [NVIDIA/VideoProcessingFramework#534]
Hello VPF maintainers and contributors,

I would like to propose a new feature for the Video Processing Framework - the ability to decode only I-frames from a video stream or file.

**Rationale:**
In the realm of video surveillance, I-frames (or intra-coded frames) often represent key frames that stand on their own without any reference to other frames. As such, they can provide a comprehensive view of the scene at a particular moment, even in the absence of the intervening P-frames and B-frames. This characteristic makes I-frames incredibly valuable for applications like:

1. **Quick Video Previews:** By only decoding and presenting I-frames, a system can offer a rapid overview of a long-duration video without processing every single frame, greatly increasing the speed and efficiency of previews.
2. **Reduced Computational Load:** As I-frames do not require references from other frames, systems can avoid the overhead associated with managing and referencing dependent frames. This can result in a faster and more streamlined decoding process, especially beneficial for systems with limited computational resources or those handling multiple video streams simultaneously.

Adding support for this feature can further enhance the versatility of VPF and cater to a broader range of applications, especially in industries like surveillance where rapid video summaries and efficient processing are of paramount importance.

I understand that there are challenges associated with implementing such a feature, given the interdependencies in encoded video streams. However, with the growing demand for efficient video processing tools in industries like surveillance, I believe this feature would be a valuable addition to the framework.

Thank you for considering this request. I look forward to any discussions or feedback related to this proposal.

Best regards,
[Initializer](https://github.com/XInitialize)

**Comment by RomanArzumanyan** [comment]
Hi @XInitialize 

Nothing stops you from doing that right now:
```python
# Code copy-pasted from SampleDemuxDecode.py withi minor changes.

nvDmx = nvc.PyFFmpegDemuxer("/path/to/the/file")
nvDec = nvc.PyNvDecoder(
    nvDmx.Width(),
    nvDmx.Height(),
    nvDmx.Format(),
    nvDmx.Codec(),
    cuda_ctx.handle,
    cuda_str.handle,
)

pdata = nvc.PacketData()
packet = np.ndarray(shape=(0), dtype=np.uint8)

while True:
    if not nvDmx.DemuxSinglePacket(packet):
        break

    nvDmx.LastPacketData(pdata)
    
    if pdata.key:
        surface_nv12 = nvDec.DecodeSurfaceFromPacket(packet)      
```

**Comment by RomanArzumanyan** [comment]
@XInitialize 

Please LMK if your issue is resolved.

**Comment by XInitialize** [comment]
Okay. Thanks for your reply.
