### ISSUE TITLE
build error！

### ISSUE THREAD

**Issue by Waxyoung** [NVIDIA/VideoProcessingFramework#54]
Hello， hello，i get a problem，please give me some advise，thank you！
when i make VideoProcessingFramework ，it occur：
![image](https://user-images.githubusercontent.com/26435611/83123334-5a4c1500-a107-11ea-81f3-c7481a7d32c9.png)
![image](https://user-images.githubusercontent.com/26435611/83123372-6506aa00-a107-11ea-9ae4-4040bc62ea64.png)

**Comment by rarzumanyan** [comment]
Hi @Waxyoung,

Your CUDA SDK probably is too old and doesn't have stream-managed NPP functions. Please update the CUDA SDK to latest version.

**Comment by daizzhisheng** [comment]
I got the same problem when i compiled the VPF on jeston TX2 by source ，my CUDA version is 10.0，and Video_Codec_SDK_9.1.23.

**Comment by rarzumanyan** [comment]
@daizzhisheng 
Video Codec SDK doesn't support ARM architecture.
![Untitled](https://user-images.githubusercontent.com/45193474/83140471-cd995b00-a0f6-11ea-8f77-436358b7d505.jpg)

**Comment by Waxyoung** [comment]
@rarzumanyan I try cuda10.0 it occur the same problem. so , must 10.1+ ?

**Comment by PVLTMK** [comment]
I had the same error while using cuda 10.0. Updating to 10.2 solved it

**Comment by rarzumanyan** [comment]
@Waxyoung 
Did the CUDA SDK update work for you?

**Comment by Waxyoung** [comment]
yes,issues are solved! thank you !

**Comment by rarzumanyan** [comment]
Great, I'm closing the issue.
