### ISSUE TITLE
if i want add some Codec format， what should i do？

### ISSUE THREAD

**Issue by ADongGu** [NVIDIA/VideoProcessingFramework#545]
such as hevc yuv420p10le，  and i want the documentation， who can post me？ thans a lot.

**Comment by ADongGu** [comment]
i want decoding HEVC 10bit ，  i just change switch (pImpl->demuxer.GetPixelFormat()) ， add case 64，params.videoContext.format = NV12;， but lase， it will be
![I6AMZ8FJS$ 6JK$)O~0NT_H](https://github.com/NVIDIA/VideoProcessingFramework/assets/76807600/76260902-1f51-43bb-93f2-d88f04a19dbf)

**Comment by RomanArzumanyan** [comment]
Ok, so basically you mean that HEVC 10 bit decoder is broken in VPF?

**Comment by ADongGu** [comment]
Look at AVPixelFormat, it seems that there is no yuv420p10le format, then what should I do now, can I support.

**Comment by RomanArzumanyan** [comment]
There's a HW decoding support for HEVC 8, 10 and 12 bit. Anything beyond basic 8 bit support was never implemented in VPF due to the lack of demand.

> Look at AVPixelFormat, it seems that there is no yuv420p10le format

There are 10 bit pixel formats supported by Nvdec:
```cpp
    AV_PIX_FMT_P010LE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian
    AV_PIX_FMT_P010BE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, big-endian
```

Adding 10 bit HEVC decoding support to VPF is doable, but it's not the easiest task. If you'd like to do that yourself you will need to:

1. Add `AV_PIX_FMT_P010LE` support to `Surface`.
2. Add 10 bit support to various places within `NvDecoder` guts.

**Comment by ADongGu** [comment]
thanks a lot,  i will try it.

**Comment by ADongGu** [comment]
> There's a HW decoding support for HEVC 8, 10 and 12 bit. Anything beyond basic 8 bit support was never implemented in VPF due to the lack of demand.
> 
> > Look at AVPixelFormat, it seems that there is no yuv420p10le format
> 
> There are 10 bit pixel formats supported by Nvdec:
> 
> ```c++
>     AV_PIX_FMT_P010LE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian
>     AV_PIX_FMT_P010BE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, big-endian
> ```
> 
> Adding 10 bit HEVC decoding support to VPF is doable, but it's not the easiest task. If you'd like to do that yourself you will need to:
> 
> 1. Add `AV_PIX_FMT_P010LE` support to `Surface`.
> 2. Add 10 bit support to various places within `NvDecoder` guts.

thanks a lot,  i will try it.

**Comment by ADongGu** [comment]
Hi, bro:
 1. The AV_PIX_FMT_P010LE is  mean  10 bit HEVC.
 2. I try to add  the  class surfaceYUV10bit, But I found that every surface class is handled the same way, what's the use.
 
When I look at the decoding process, all of them are to determine the format, initialize, decapsulate (demux) to get the stream, and then decode, and see that different surfaces are only in different formats, that is, to obtain the decoder->Execute()) after decoding, but how do I modify to determine the hevc 10bit? There is still no direction, the reason is that I did not find any difference between different surfaces, I hope the boss can clear up the confusion.

**Comment by ADongGu** [comment]
> > There's a HW decoding support for HEVC 8, 10 and 12 bit. Anything beyond basic 8 bit support was never implemented in VPF due to the lack of demand.
> > > Look at AVPixelFormat, it seems that there is no yuv420p10le format
> > 
> > 
> > There are 10 bit pixel formats supported by Nvdec:
> > ```c++
> >     AV_PIX_FMT_P010LE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian
> >     AV_PIX_FMT_P010BE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, big-endian
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Adding 10 bit HEVC decoding support to VPF is doable, but it's not the easiest task. If you'd like to do that yourself you will need to:
> > 
> > 1. Add `AV_PIX_FMT_P010LE` support to `Surface`.
> > 2. Add 10 bit support to various places within `NvDecoder` guts.
> 
> thanks a lot, i will try it.



> There's a HW decoding support for HEVC 8, 10 and 12 bit. Anything beyond basic 8 bit support was never implemented in VPF due to the lack of demand.
> 
> > Look at AVPixelFormat, it seems that there is no yuv420p10le format
> 
> There are 10 bit pixel formats supported by Nvdec:
> 
> ```c++
>     AV_PIX_FMT_P010LE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian
>     AV_PIX_FMT_P010BE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, big-endian
> ```
> 
> Adding 10 bit HEVC decoding support to VPF is doable, but it's not the easiest task. If you'd like to do that yourself you will need to:
> 
> 1. Add `AV_PIX_FMT_P010LE` support to `Surface`.
> 2. Add 10 bit support to various places within `NvDecoder` guts.

Hi, bro:

The AV_PIX_FMT_P010LE is mean 10 bit HEVC.
I try to add the class surfaceYUV10bit, But I found that every surface class is handled the same way, what's the use.
When I look at the decoding process, all of them are to determine the format, initialize, decapsulate (demux) to get the stream, and then decode, and see that different surfaces are only in different formats, that is, to obtain the decoder->Execute()) after decoding, but how do I modify to determine the hevc 10bit? There is still no direction, the reason is that I did not find any difference between different surfaces, I hope the boss can clear up the confusion.

**Comment by ADongGu** [comment]
> There's a HW decoding support for HEVC 8, 10 and 12 bit. Anything beyond basic 8 bit support was never implemented in VPF due to the lack of demand.
> 
> > Look at AVPixelFormat, it seems that there is no yuv420p10le format
> 
> There are 10 bit pixel formats supported by Nvdec:
> 
> ```c++
>     AV_PIX_FMT_P010LE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian
>     AV_PIX_FMT_P010BE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, big-endian
> ```
> 
> Adding 10 bit HEVC decoding support to VPF is doable, but it's not the easiest task. If you'd like to do that yourself you will need to:
> 
> 1. Add `AV_PIX_FMT_P010LE` support to `Surface`.
> 2. Add 10 bit support to various places within `NvDecoder` guts.

Hi, bro:

The AV_PIX_FMT_P010LE is mean 10 bit HEVC.
I try to add the class surfaceYUV10bit, But I found that every surface class is handled the same way, what's the use.
When I look at the decoding process, all of them are to determine the format, initialize, decapsulate (demux) to get the stream, and then decode, and see that different surfaces are only in different formats, that is, to obtain the decoder->Execute()) after decoding, but how do I modify to determine the hevc 10bit? There is still no direction, the reason is that I did not find any difference between different surfaces, I hope the boss can clear up the confusion.

**Comment by ADongGu** [comment]
> There's a HW decoding support for HEVC 8, 10 and 12 bit. Anything beyond basic 8 bit support was never implemented in VPF due to the lack of demand.
> 
> > Look at AVPixelFormat, it seems that there is no yuv420p10le format
> 
> There are 10 bit pixel formats supported by Nvdec:
> 
> ```c++
>     AV_PIX_FMT_P010LE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian
>     AV_PIX_FMT_P010BE, ///< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, big-endian
> ```
> 
> Adding 10 bit HEVC decoding support to VPF is doable, but it's not the easiest task. If you'd like to do that yourself you will need to:
> 
> 1. Add `AV_PIX_FMT_P010LE` support to `Surface`.
> 2. Add 10 bit support to various places within `NvDecoder` guts.

Hi, bro:
 1. The AV_PIX_FMT_P010LE is  mean  10 bit HEVC.
 2. I try to add  the  class surfaceYUV10bit, But I found that every surface class is handled the same way, what's the use. 2. I try to add  the  class surfaceYUV10bit, But I found that every surface class is handled the same way, what's the use.
  

When I look at the decoding process, all of them are to determine the format, initialize, decapsulate (demux) to get the stream, and then decode, and see that different surfaces are only in different formats, that is, to obtain the decoder->Execute()) after decoding, but how do I modify to determine the hevc 10bit? There is still no direction, the reason is that I did not find any difference between different surfaces, I hope the boss can clear up the confusion.
