### ISSUE TITLE
do we need a gpu compiled ffmpeg to use this library?

### ISSUE THREAD

**Issue by HaoLiuHust** [NVIDIA/VideoProcessingFramework#553]
as descriped in ReadME, we need install ffmpeg to use VPF, I wonder if we need install a ffmpeg compiled with cuda or just a normal one？

**Comment by theHamsta** [comment]
A "normal" one is sufficient. FFmpeg is used for demuxing and bitstream filtering only, no CUDA functionality from FFmpeg is needed.
