### ISSUE TITLE
CUDA error: CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by cytheria43** [NVIDIA/VideoProcessingFramework#57]
when I try : python3 ./SampleDecode.py  ,there is a cuda error without error code
`Traceback (most recent call last):
  File "./SampleDecode.py", line 50, in <module>
    decode(gpuID, encFilePath, decFilePath)
  File "./SampleDecode.py", line 23, in decode
    nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
RuntimeError: /home/user/github-repository/VideoProcessingFramework/PyNvCodec/src/PyNvCodec.cpp:61
CUDA error: CUDA_ERROR_UNKNOWN
unknown error`

my cuda lib path is :/usr/local/cuda-10.1/lib64   and libcuda.so is in /usr/local/cuda-10.1/lib64/stubs/    
I try to put libs of Video_Codec_SDK_9.1.23 into /usr/local/cuda-10.1/lib64/stubs/
but the error is still the same
My versions: nvidia driver==430.50  cuda==10.1  sdk==9.1.23

**Comment by cytheria43** [comment]
![2020-06-03 10-23-04 的屏幕截图](https://user-images.githubusercontent.com/41312465/83588566-4af41e00-a584-11ea-8e2b-523c6903d1ef.png)
this is my ldd result.

**Comment by cytheria43** [comment]
![ldd result](https://user-images.githubusercontent.com/41312465/83588650-6eb76400-a584-11ea-8603-dbb01c9ca04d.png)

**Comment by rarzumanyan** [comment]
Hi @cytheria43,

I recommend you to update to latest CUDA SDK first as Video Codec SDK 9.1.23 requires driver version 435.21 anyway.

**Comment by cytheria43** [comment]
> Hi @cytheria43,
> 
> I recommend you to update to latest CUDA SDK first as Video Codec SDK 9.1.23 requires driver version 435.21 anyway.

Thank you! But this problem was solved after reboot or source the profile. There is another error when I try to use the sample code:RuntimeError: can't get unknown filter by name.   I update my driver versions and try the new nv-codec-headers and  recompile ffmpeg ,it finally works.
