### ISSUE TITLE
Is it possible to change output pix_fmt?

### ISSUE THREAD

**Issue by sealedtx** [NVIDIA/VideoProcessingFramework#60]
Hi, thank you for providing great api to encode/decode! Is it possible to decode image with RGB or BGR format using DecodeSingleFrame?  By passing some ffmpeg options or by modifying code? Thank you

**Comment by rarzumanyan** [comment]
Hi @sealedtx 
H.264 and H.265 video coding standards support only YUV pixels format.

However you can convert your RGB frames to NV12 format (similar to YUV, just chroma pixels reordered) prior encoding and NV12 decoded frames to RGB after decoding.

**Comment by sealedtx** [comment]
@rarzumanyan Thank you for a fast response! I mean can I do this using hw acceleration ffmpeg/video codec sdk? Currenlty my code looks like:
```python
nvDec = nvc.PyNvDecoder(encFile, 0, {'rtsp_transport':'tcp'})

height = 1536
width = 2048
shape = (int(height*1.5), width) # yuv image shape

frameSize = nvDec.Framesize()
rawFrameNV12 = np.ndarray(shape=(frameSize), dtype=np.uint8)
while True:
    success = nvDec.DecodeSingleFrame(rawFrameNV12) # <- Decoding rtsp stream consumes mostly GPU and little CPU, this is great!
    if not success:
        break
    yuv = rawFrameNV12.reshape(shape)
    rbg = cv2.cvtColor(yuv, cv2.COLOR_YUV2RGB_NV21) # <- But converting consumes a lot CPU 
    cv2.imshow('window', rgb)
    k = cv2.waitKey(1)
    if k == 0xFF & ord("q"):
        break
```
I need to work with rgb/bgr format after decoding rtsp stream, and want to reduce CPU usage, that is why I tried to use your framework. Do you have any suggestions for me? Thank you

**Comment by rarzumanyan** [comment]
You can do color conversion on GPU.
Take a look at `SampleDecodeMultiThread.py`, it covers exactly this topic.
One thing you need to change is color conversion parameters:

```python
self.nvDec = nvc.PyNvDecoder(encFile, gpuID)
self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.RGB, gpuID)
self.nvRes = nvc.PySurfaceResizer(hwidth, hheight, self.nvCvt.Format(), gpuID)
self.nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, self.nvRes.Format(), gpuID)

rawSurface = self.nvDec.DecodeSingleSurface()
cvtSurface = self.nvCvt.Execute(rawSurface)
resSurface = self.nvRes.Execute(cvtSurface)
rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)
success = self.nvDwn.DownloadSingleSurface(resSurface, rawFrame)
```

**Comment by sealedtx** [comment]
@rarzumanyan Thanks a lot for a quick and clear answer, i will take a look at `SampleDecodeMultiThread.py`

**Comment by wan-h** [comment]
I can only get YUV420 resize successfully.
follow the code:
```
self.nvDec = nvc.PyNvDecoder(encFile, gpuID)
self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.RGB, gpuID)
self.nvRes = nvc.PySurfaceResizer(hwidth, hheight, self.nvCvt.Format(), gpuID)
self.nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, self.nvRes.Format(), gpuID)

rawSurface = self.nvDec.DecodeSingleSurface()
cvtSurface = self.nvCvt.Execute(rawSurface)
resSurface = self.nvRes.Execute(cvtSurface)
rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)
success = self.nvDwn.DownloadSingleSurface(resSurface, rawFrame)
```
if I use 
`self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.RGB, gpuID)`
`resSurface.Empty()` return True
if I use 
`self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.YUV420, gpuID)`
this work successfully
