### ISSUE TITLE
No error string available

### ISSUE THREAD

**Issue by Materx** [NVIDIA/VideoProcessingFramework#61]
![image](https://user-images.githubusercontent.com/48338930/84005060-1a0a5380-a99f-11ea-94d6-8d69b6508b3a.png)

I  see #23 , my driver version is 440.33.01,but can't run the example

![image](https://user-images.githubusercontent.com/48338930/84005456-baf90e80-a99f-11ea-8299-be582154914c.png)
![image](https://user-images.githubusercontent.com/48338930/84005632-00b5d700-a9a0-11ea-9f71-52c7cfb4f301.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04
 - Nvidia driver version: 440.33.01
 - CUDA Version : 10.2
 - Video Codec SDK Version 9.1.23
 - Python Version  3.7

pls,help me!

**Comment by rarzumanyan** [comment]
Hi @Materx,
You're using stub nvcuvid library. Please make sure your app loads library from driver distribution.
![84005456-baf90e80-a99f-11ea-8299-be582154914c](https://user-images.githubusercontent.com/45193474/84007192-ab1a0400-a978-11ea-92eb-9c3f5f53f687.png)

**Comment by Materx** [comment]
thx your answer,but i dont know , the libnvcuvid.so.1  not ==>   Video_Codoc_SDK_9.1.23/....../ libnvcuvid.so.1?
after using make && make install ,  i not see libnvcuvid.so.1, so  i run :
ln -s /workspace/Video_Codec_SDK_9.1.23/Lib/linux/stubs/x86_64/libnvcuvid.so /workspace/Video_Codec_SDK_9.1.23/Lib/linux/stubs/x86_64/libnvcuvid.so.1
ln -s /workspace/Video_Codec_SDK_9.1.23/Lib/linux/stubs/x86_64/libnvidia-encode.so /workspace/Video_Codec_SDK_9.1.23/Lib/linux/stubs/x86_64/libnvidia-encode.so.1
its wrong?

**Comment by rarzumanyan** [comment]
@Materx 
libnvcuvid.so is installed together with the GPU driver.
So if you have your `libcuda.so` at `/usr/lib/x86_64-linux-gnu/libcuda.so.1` the nvcuvid library should be located there as well.

You can search for the library with
```bash
find / -name libnvcuvid*
```

And then export `LD_LIBRARY_PATH` to load the nvcuvid library from needed folder.

**Comment by rarzumanyan** [comment]
Hi @Materx 

Were you able to make the module load proper nvcuvid library?

**Comment by Materx** [comment]
Hi @rarzumanyan 
Thank you very much for your help！  I can use it normally.
My mistake is that I install VPF in docker，Nvcuvid library cannot be detected by the model！

**Comment by rarzumanyan** [comment]
@Materx 
You need to use video driver capability, the nvcuvid library will be seen.

**Comment by rarzumanyan** [comment]
@Materx 

From the `nvidia-smi` output I see that you're using some serious industrial-grade server.
May I ask you to describe in couple of words how you use VPF in your company?
It's completely optional and just for my own education.
I'm trying to track how do people use this project for better priorities scheduling. You may also contact me via my email which is in the profile description.
