### ISSUE TITLE
SampleEncode.py crashed

### ISSUE THREAD

**Issue by lc2a** [NVIDIA/VideoProcessingFramework#66]
**Describe the bug**
SampleEncode.py crashed. Pls see below screenshots. Kindly advise.

**Expected behavior**
 https://devblogs.nvidia.com/vpf-hardware-accelerated-video-processing-framework-in-python/

**Screenshots**

![image](https://user-images.githubusercontent.com/1294945/85006239-7124db00-b18c-11ea-8c48-8b82e239379f.png)

![image](https://user-images.githubusercontent.com/1294945/85006344-9580b780-b18c-11ea-8945-d071eebc18ae.png)

**Desktop:**
 - OS: Windows Server 2016
 - Nvidia driver version 451.22
 - CUDA Version 11
 - Video Codec SDK Version [ 9.1.23
 - Python Version 3.7.7

**Comment by rarzumanyan** [comment]
Hi,

I see that you’re giving encoded h264 file as input while SampleEncode expects you to use raw NV12 file as it prints it to output.

**Comment by lc2a** [comment]
Thanks Roman.  

My transcoding took 1 minute versus yours 32 seconds



    import PyNvCodec as nvc
    import numpy as np

    gpuID = 0
    encFile = "big_buck_bunny_1080p_h264.mov"
    xcodeFile = open("big_buck_bunny_1080p.h264", "wb")

    nvDec = nvc.PyNvDecoder(encFile, gpuID)
    nvEnc = nvc.PyNvEncoder({'preset': 'hq', 'codec': 'h264', 's': '1920x1080'}, gpuID)

    while True:
        rawSurface = nvDec.DecodeSingleSurface()
        if (rawSurface.Empty()):
            # Empty surface means we have reached EOF
            break
        
        encFrame = np.ndarray(shape=(0), dtype=np.uint8)
        success = nvEnc.EncodeSingleSurface(rawSurface, encFrame)
        if(success):
            frameByteArray = bytearray(encFrame)
            xcodeFile.write(frameByteArray)

    #Encoder is asynchronous, so we need to flush it
    encFrame = np.ndarray(shape=(0), dtype=np.uint8)
    success = nvEnc.Flush(encFrame)
    if(success):
        encByteArray = bytearray(encFrame)
        xcodeFile.write(encByteArray) 




![image](https://user-images.githubusercontent.com/1294945/85033587-b6103800-b1b3-11ea-92f7-e221000e0e61.png)

![image](https://user-images.githubusercontent.com/1294945/85033408-7d705e80-b1b3-11ea-9a30-8287757b3972.png)

**Comment by rarzumanyan** [comment]
@lc2a 
Given the difference between the cards (P4 vs. Quadro RTX5000) this looks reasonable.
If you want to track performance bottleneck, `nvidia-smi.exe -dmon` is a good place to start, it will show Nvenc and Nvdec utilization.

**Comment by lc2a** [comment]
i see, thanks i will try to understand those reading for 'nvidia-smi.exe -dmon'

btw, i need simple showcase to demo on the impact of with & without GPU.
could you advise any tools, samples.

Thanks in advance.

**Comment by rarzumanyan** [comment]
Hi,

Take a look at this [article](https://devblogs.nvidia.com/turing-h264-video-encoding-speed-and-quality), it shows Turing vs. CPU encoder speed / quality and energy efficiency comparison. All the tools and settings used are freely available so you can basically reproduce the results on any compatible machine.

**Comment by rarzumanyan** [comment]
Closing the issue as fixed.
