### ISSUE TITLE
Get timing information from rtsp stream

### ISSUE THREAD

**Issue by maxclaey** [NVIDIA/VideoProcessingFramework#69]
Is there a possibility to get the timing information that is part of the RTSP protocol out of ffmpeg and expose it to the video processing framework? If this is possible, but not currently on your roadmap, some pointers on where it can be introduced would be very nice!

**Comment by rarzumanyan** [comment]
Hi @maxclaey 

It should be possible as VPF demuxer is relatively thin wrapper around ffmpeg. Though I don’t know exactly how to extract it using ffmpeg api. 

There’s a MuxingParams structure used to pass such data, you can find reference in PyNvCodec.cpp, feel free to extend it as you wouldn’t break the ABI anyway.

**Comment by maxclaey** [comment]
Thanks for the pointers! I tried to get the PacketData information to the PyNvDecoder. This was not as trivial because as opposed to the part of the MuxingParams that were already exposed, the PacketData changes for each frame. I made a pull request for it, if you want (see #70), but as I'm not really familiar with FFMpeg or VPF, I think it needs a critical review.

**Comment by rarzumanyan** [comment]
@maxclaey 
Thanks for the pull request, closing this issue as solved.
