### ISSUE TITLE
ubuntu VPF build link failed

### ISSUE THREAD

**Issue by heefe92** [NVIDIA/VideoProcessingFramework#7]
![image](https://user-images.githubusercontent.com/28752568/71814932-3d179b00-30c1-11ea-8803-413bbb059d1e.png)

![image](https://user-images.githubusercontent.com/28752568/71814946-4acd2080-30c1-11ea-9ac9-4daaa0a3e8a7.png)

**Comment by pycoco** [comment]
How to solve the problem？

**Comment by heefe92** [comment]
I solved the FFMPEG build by ```./configure --enable-pic --enable-shared --cc="gcc -m64 -fPIC" --prefix=$(pwd)/build_release ```.

**Comment by pycoco** [comment]
@heefe92  thank u
