### ISSUE TITLE
windows install VPF

### ISSUE THREAD

**Issue by Materx** [NVIDIA/VideoProcessingFramework#71]
Hi @rarzumanyan , I want install VPF in windows10.

 - OS: Windows
 - Nvidia driver version 445.75
 - CUDA Version 10.2
 - Video Codec SDK Version 9.1.23
 - Python Version  3.7
This is my cmake values list:
![image](https://user-images.githubusercontent.com/48338930/85968071-9e785100-b9f6-11ea-80af-cba0a7caaf05.png)
but build Error, its No CUDA toolset found.
![image](https://user-images.githubusercontent.com/48338930/85968185-fadb7080-b9f6-11ea-9023-ea8efdb46cd7.png)
CMakeError.log 👇
     Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \(R\) Cuda compiler driver":
     Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
my Nvidia driver is 445.75, its cuda version is 11.0,   but my Cuda compilation tools, release 10.2, V10.2.89 in nvcc .

**Comment by rarzumanyan** [comment]
Hi @Materx 

Do you have CUDA visual studio extension installed?

**Comment by Materx** [comment]
yes，my vs setting is wrong，sorry。now ， its successly install my windows。 thx
