### ISSUE TITLE
Does this framework provide memory release operations?

### ISSUE THREAD

**Issue by XZG-0457** [NVIDIA/VideoProcessingFramework#75]
The specific question is I asked in opencv：

https://github.com/opencv/opencv/issues/17774

**Comment by XZG-0457** [comment]
I want to ask, if I read a hundred rtmp addresses and then push the stream, I can do it for a long time, and the memory will not be backlogged...

**Comment by rarzumanyan** [comment]
Hi @XZG-0457 

VPF is designed in such a fashion that every main class (e. g. `PyNvDecoder`) has it's own pool of memory reserved for multiple frames.
Every time you call the method like `DecodeSingleSufrace` it will return you a reference to one of the frames from decoder's pool.
Unless you copy the frames and / or surfaces by hand, VPF classes will allocate some amount of memory on GPU and will keep it until they end their lifetime.

P. S.
I recommend you to run `nvidia-smi dmon` console utility in separate terminal while you use VPF. You will see the memory consumption trend.

**Comment by XZG-0457** [comment]
> Hi @XZG-0457
> 
> VPF is designed in such a fashion that every main class (e. g. `PyNvDecoder`) has it's own pool of memory reserved for multiple frames.
> Every time you call the method like `DecodeSingleSufrace` it will return you a reference to one of the frames from decoder's pool.
> Unless you copy the frames and / or surfaces by hand, VPF classes will allocate some amount of memory on GPU and will keep it until they end their lifetime.
> 
> P. S.
> I recommend you to run `nvidia-smi dmon` console utility in separate terminal while you use VPF. You will see the memory consumption trend.

Ok, I have installed cuda10.2 and compiled successfully. I will test it today. Thank you for your reply. I think it should be OK

**Comment by XZG-0457** [comment]
> Hi @XZG-0457
> 
> VPF is designed in such a fashion that every main class (e. g. `PyNvDecoder`) has it's own pool of memory reserved for multiple frames.
> Every time you call the method like `DecodeSingleSufrace` it will return you a reference to one of the frames from decoder's pool.
> Unless you copy the frames and / or surfaces by hand, VPF classes will allocate some amount of memory on GPU and will keep it until they end their lifetime.
> 
> P. S.
> I recommend you to run `nvidia-smi dmon` console utility in separate terminal while you use VPF. You will see the memory consumption trend.

At present, I have tested a single video stream, but I found that the resize error "resize not format", I reduced to 352,288 format, and I found that the GPU is particularly stuck after the program starts, or even no response.

![image](https://user-images.githubusercontent.com/43441239/86995497-c5dfd280-c1db-11ea-80a8-426356dea809.png)

![image](https://user-images.githubusercontent.com/43441239/86995515-d3955800-c1db-11ea-8574-01fea4a1b269.png)

**Comment by XZG-0457** [comment]
```python
nvDec = nvc.PyNvDecoder(vid_path, 0)

nvRes = nvc.PySurfaceResizer(352, 288, nvDec.Format(), 0)
nvDwn = nvc.PySurfaceDownloader(352, 288, nvRes.Format(), 0)

print(nvDec, "nvCvt....................")
self.fileLog.info("produce_frame:open finished")

true_fp = -1
fp = -1
count = 0
arr = []
image_container = []
fp_skip = 1
true_fp_skip = 1
set_num_skip = 1
streamFlag = store_status.get('streamFlag', 0)

createTime = time.time()
fps = 25
set_num = 0

while (store_status['status'] != 2):
    try:
        lasttime = time.time()
        # image = vidcap.read()
        # success = vidcap.grab()
        rawSurface = nvDec.DecodeSingleSurface()
        self.read_time += time.time() - lasttime
        if (rawSurface.Empty()):
            print("frame read end or read error")
            self.fileLog.warning("frame read end or read error:path ={}  cid ={}".format(vid_path, cid))
            break
        fp += 1
        if (fp % fp_skip != 0):
            continue
        true_fp += 1

        # print("retrieve time:",time.time() - createTime)
        createTime = time.time()

        ta = time.time()
        try:

            # if (resize == True):
            if len(image_container) < 2:
                resSurface = nvRes.Execute(rawSurface)
                if (resSurface.Empty()):
                    print("failed to resize surface")
                    break
                rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)
                success = nvDwn.DownloadSingleSurface(resSurface, rawFrame)
                if not (success):
                    print("failed to download surface")
                    break
                img = rawFrame
                # print(type(img),"img.............")
                screenFlag = 1
                image_container.append(img)
```

**Comment by XZG-0457** [comment]
> Hi @XZG-0457
> 
> VPF is designed in such a fashion that every main class (e. g. `PyNvDecoder`) has it's own pool of memory reserved for multiple frames.
> Every time you call the method like `DecodeSingleSufrace` it will return you a reference to one of the frames from decoder's pool.
> Unless you copy the frames and / or surfaces by hand, VPF classes will allocate some amount of memory on GPU and will keep it until they end their lifetime.
> 
> P. S.
> I recommend you to run `nvidia-smi dmon` console utility in separate terminal while you use VPF. You will see the memory consumption trend.

Traceback (most recent call last):
  File "/home/runone/anaconda3/envs/py36_zcz/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/runone/anaconda3/envs/py36_zcz/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "FrameManager.py", line 179, in produce_frame
    nvRes = nvc.PySurfaceResizer(352, 288, nvDec.Format(), 0)
RuntimeError: ResizeSurface: pixel format not supported

**Comment by rarzumanyan** [comment]
Hi @XZG-0457 

>RuntimeError: ResizeSurface: pixel format not supported

VPF tells you that it can't resize NV12 video surface.
GPU-accelerated resizing is done with help of Nvidia NPP library which unfortunately doesn't support NV12 yet.
You may convert video surface to another format (YUV420 and RGB are supported for now) and then resize it on GPU.

**Comment by XZG-0457** [comment]
> Hi @XZG-0457
> 
> > RuntimeError: ResizeSurface: pixel format not supported
> 
> VPF tells you that it can't resize NV12 video surface.
> GPU-accelerated resizing is done with help of Nvidia NPP library which unfortunately doesn't support NV12 yet.
> You may convert video surface to another format (YUV420 and RGB are supported for now) and then resize it on GPU.


Do you mean to add PySurfaceConverter? But I still get an error when I use it
![image](https://user-images.githubusercontent.com/43441239/87020339-45829700-c206-11ea-88a5-bd00f7be5412.png)

The error message is as follows:

Decoding on GPU 0
<PyNvCodec.PyNvDecoder object at 0x7f184115f180> nvCvt....................
failed to resize surface

**Comment by rarzumanyan** [comment]
@XZG-0457 

Can you launch `SampleDecodeMultiThread.py` and check if it works?

**Comment by XZG-0457** [comment]
> @XZG-0457
> 
> Can you launch `SampleDecodeMultiThread.py` and check if it works?

yes，The rtmp path I entered is the same

![image](https://user-images.githubusercontent.com/43441239/87021900-559b7600-c208-11ea-8b5c-4ed9f3847491.png)

**Comment by rarzumanyan** [comment]
So this sample takes a frame from decoder, converts it to different format, resize, etc.
You can also check individual components of this sample (e. g. resize to 352x288) to see if it works & isolate the root cause of you resize issue.

**Comment by XZG-0457** [comment]
> So this sample takes a frame from decoder, converts it to different format, resize, etc.
> You can also check individual components of this sample (e. g. resize to 352x288) to see if it works & isolate the root cause of you resize issue.

Okay, I feel like there may be a problem with my code, I will go to debug, thank you for your reply

**Comment by XZG-0457** [comment]
> So this sample takes a frame from decoder, converts it to different format, resize, etc.
> You can also check individual components of this sample (e. g. resize to 352x288) to see if it works & isolate the root cause of you resize issue.

I seem to find a bug，When I use the yuv420 converter, it does not meet my needs, but I should use rgb to resize, I found that my program is blocked：
![image](https://user-images.githubusercontent.com/43441239/87108729-8970ad00-c295-11ea-8040-5f78aa91f7ee.png)


Then I used the SampleDecodeMul.py program you gave to replace YUV420 with RGB, and found that an error will be reported：
![image](https://user-images.githubusercontent.com/43441239/87108829-c177f000-c295-11ea-98f0-ab65677c9775.png)

**Comment by rarzumanyan** [comment]
Hi @XZG-0457 

>but I should use rgb to resize, I found that my program is blocked

Unfortunately, this is known issue which sometimes happens with RGB resize (the resize function returns `NPP_STEP_ERROR` despite image step is non-negative value).

The easiest workaround is to add one more `PySurfaceConverter` class which converts resized YUV420 video surface to RGB.

If you export your video frames to Pytorch tensors, you can also resize the exported frame using Pytorch API.

**Comment by XZG-0457** [comment]
> Hi @XZG-0457
> 
> > but I should use rgb to resize, I found that my program is blocked
> 
> Unfortunately, this is known issue which sometimes happens with RGB resize (the resize function returns `NPP_STEP_ERROR` despite image step is non-negative value).
> 
> The easiest workaround is to add one more `PySurfaceConverter` class which converts resized YUV420 video surface to RGB.
> 
> If you export your video frames to Pytorch tensors, you can also resize the exported frame using Pytorch API.

Oh, I know, I will test it, now I use opencv to convert the image to RGB after downloading, but I found that there is still a memory leak, about 5 seconds or 10M increase, currently has been running for half an hour, The memory consumption has reached 18G, although this is better than the GPU version of opencv, but if I stress test 100 rtmp addresses, I find that as long as the GPU is used, there will be memory leaks. Is there any way?

![image](https://user-images.githubusercontent.com/43441239/87130932-3cf19580-c2c6-11ea-8233-24b9afb20e0b.png)

**Comment by rarzumanyan** [comment]
@XZG-0457 

>I find that as long as the GPU is used, there will be memory leaks. Is there any way?

Do you mean VPF mas memory leaks (2Mb/s)?

**Comment by XZG-0457** [comment]
> @XZG-0457
> 
> > I find that as long as the GPU is used, there will be memory leaks. Is there any way?
> 
> Do you mean VPF has memory leaks (2Mb/s)?

After testing, I found that the efficiency of the RGB I used in the converter will be higher than the COLOR_YUV2BGR_I420 of cv2, but the multi-process reading the stream address will still generate a memory backlog. Through valgrind I can see a memory leak, and I am still locating the problem , But I calculated the time after GPU decoding, I found this time is extremely short, I think the garbage generated can also be recycled by python, that should be different from opencv CPU decoding, not leaked here, the previous answer is a bit arbitrary Thank you for your reply
