### ISSUE TITLE
The question of PytorchNvCodec make install

### ISSUE THREAD

**Issue by Materx** [NVIDIA/VideoProcessingFramework#76]
Hi @rarzumanyan , i'm studying VPF now, and successfully build the PyNvCodec.cpython-37m-x86_64-linux-gnu.so

next , i want to make exporting video frame to Pytorch tensor, but i can't find the Pytorch binding course。

I refer to the wiki,after the build method is compiled successfully, there is only one PyNvCodec.cpython-37m-x86_64-linux-gnu.so .  so can't import PytorchNvCodec.

**Comment by Materx** [comment]
![2020-07-14 14-10-55屏幕截图](https://user-images.githubusercontent.com/48338930/87391124-bfd36280-c5dc-11ea-9b99-d2b1326e6bb0.png)
![2020-07-14 14-09-59屏幕截图](https://user-images.githubusercontent.com/48338930/87391129-c2ce5300-c5dc-11ea-968c-b7929e1f7022.png)

**Comment by rarzumanyan** [comment]
Hi @Materx 

Please make sure you've set up `GENERATE_PYTORCH_EXTENSION` CMake variable:
```cmake
-GENERATE_PYTORCH_EXTENSION:BOOL="1"
```

This line is indeed missing in wiki page, I'll add it.

**Comment by Materx** [comment]
thx, I have tried to add this parameter in cmake, but the command cannot be executed。

cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DPYTHON_LIBRARY=/opt/anaconda3/envs/yolo/bin/lib/libpython3.7m.so \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" \
  -GENERATE_PYTORCH_EXTENSION:BOOL="1"

**Comment by Materx** [comment]
![2020-07-14 15-56-19屏幕截图](https://user-images.githubusercontent.com/48338930/87400062-e5ffff00-c5ea-11ea-8730-a6d2d8af3149.png)

**Comment by Materx** [comment]
thx, I have tried to add this parameter in cmake, but the command cannot be executed.

cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DPYTHON_LIBRARY=/opt/anaconda3/envs/yolo/bin/lib/libpython3.7m.so \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" \
  -DGENERATE_PYTORCH_EXTENSION:BOOL="1" \
  -DPYTHON_INCLUDE_DIRS=/opt/anaconda3/envs/yolo/include/python3.7m

**Comment by Materx** [comment]
![2020-07-14 16-10-22屏幕截图](https://user-images.githubusercontent.com/48338930/87401440-b520c980-c5ec-11ea-9027-9d83cab6c4a2.png)

**Comment by rarzumanyan** [comment]
Hi @Materx 
Log messages show that you don’t have Python development files (namely headers) and that VPF failed to find ffmpeg headers.

Please install python development package and check that ffmpeg dir contains needed files.

**Comment by Materx** [comment]
I'm very sorry. The error I just made was caused by my own carelessness. 
Now it has been compiled successfully, but I still can't import the pytochnvcodec library. 
![2020-07-14 17-25-35屏幕截图](https://user-images.githubusercontent.com/48338930/87410179-8872af00-c5f8-11ea-9d0f-6cd140f480bb.png)
![2020-07-14 17-25-07屏幕截图](https://user-images.githubusercontent.com/48338930/87410186-8a3c7280-c5f8-11ea-97c3-8e5ca18f9e59.png)

**Comment by rarzumanyan** [comment]
@Materx 
Please take a look at this message: https://github.com/NVIDIA/VideoProcessingFramework/issues/36#issuecomment-629873431.
The following thread shows how to fix similar issue.

**Comment by Materx** [comment]
Thank you very much. I have solved this problem with reference to [ClementPinard / Pytorch-Correlation-extension＃15（评论）](https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/15).
Before importing pytochnvcodec, you should import pytorch first.
```python
import torch
import PyNvCodec as nvc
import PytorchNvCodec as pnvc
```
