### ISSUE TITLE
Video's Size After Decoding is too huge

### ISSUE THREAD

**Issue by leviethung2103** [NVIDIA/VideoProcessingFramework#79]
**Describe the bug**
I've tried to run the samle decode a video. The original input size is approximately 550 MB. However, after decoding processing, the output size of the video is extremely large. 25 GB. Furthermore, I can view the properties of video by right click to file as well as open the video normally. 

**To Reproduce**
Input video: 4k Video
Format: .mp4
Size: 550 MB

Output video after decoding: 
Size: 25 GB 

```
python SampleDecode.py 0 ../test_videos/input/4K.MP4 ../test_videos/output/4K_test.mp4
```
The process is working properly without any problems.

```
Usage: SampleDecode.py $gpu_id $input_file $output_file.
Decoding on GPU 0
No more video frames
```

**Screenshots**
Check the property of the video file. It's almost empty.
![Screenshot from 2020-07-16 11-32-57](https://user-images.githubusercontent.com/16741872/87627079-2466fc80-c758-11ea-9e87-b9a84d5e34a2.png)

**Desktop (please complete the following information):**
 - OS: Linux 18.04
 - Nvidia driver version: 440
 - CUDA Version : 10.1
 - Video Codec SDK Version: 9.1.23
 - Python Version: 3.7
 - FFmpeg version: 4.x

**Additional context**
Is there any problem with the FFmpeg when decode and encode the video? Thank you in advance.

**Comment by rarzumanyan** [comment]
Hi @leviethung2103 

SampleDecode.py saves decoded raw NV12 frames. Every raw 4K frame is ~12 Mb, so 25 Gb output file size is perfectly fine.
