### ISSUE TITLE
Have you create a Docker file ?

### ISSUE THREAD

**Issue by leviethung2103** [NVIDIA/VideoProcessingFramework#81]
Thank you for your great work !!!

I have built a Docker file for Video Processing Framework. Everything looks fine. However, when I am trying to use the `SampleEncode.py` file. The output video cannot be played. 

I have two questions for you: 

- Have you build a Docker image for this framework? 
- How can I debug the problem with my case. 

Thank you in advance.

**Comment by rarzumanyan** [comment]
Hi @leviethung2103 

>However, when I am trying to use the SampleEncode.py file. The output video cannot be played.

Please provide more information like what's the input file, it's pixel format, resolution and what encoding options did you use?

**Comment by zdhernandez** [comment]
> Thank you for your great work !!!
> 
> I have built a Docker file for Video Processing Framework. Everything looks fine. However, when I am trying to use the `SampleEncode.py` file. The output video cannot be played.
> 
> I have two questions for you:
> 
> * Have you build a Docker image for this framework?
> * How can I debug the problem with my case.
> 
> Thank you in advance.

Can you share the Docker file?

**Comment by zachary-dh** [comment]
@leviethung2103 would you mind sharing the docker file? I am trying to do the same and I am currently stuck with a missing .so issue.
