### ISSUE TITLE
About the parameters of image quality

### ISSUE THREAD

**Issue by zjx94** [NVIDIA/VideoProcessingFramework#82]
Hi,I have a question for you.
I use ffmpeg for transcoding, 1920*1080 to 352*288  and bit rate: 1M to 32K
##cmd##
`ffmpeg_cuda.exe -y -hwaccel cuvid -hwaccel_device 0 -c:v h264_cuvid -i "rtmp://aaa" -vcodec h264_nvenc -an -vf scale_npp=352:288 -r 25 -g 50 -sc_threshold 0 -b:v 32k -maxrate 32k -minrate 32k -bufsize 64K -f flv "rtmp://bbb"`

I transcode according to this parameter, when I frame comes, the picture will suddenly blur.[Picture 1], and then gradually clear
If I remove the parameter **-gop 50** and add  **-rc constqp**, the picture quality will be very good [Picture 2], but the bit rate will reach about 100kb/s

_How to ensure that the picture quality will not become blurred when I frame is turned under the condition of **-gop 50** and bit rate of **32kb/s**?_

My friend can get a very high image quality with VPF[Picture 2],he uses VPF to get YUV and ffmpeg to push YUV to RTMP stream。
so I'd like to ask about the solution about  the image quality. 
Thank you in advance.

**Screenshots**
 [Picture 1]
![image](https://user-images.githubusercontent.com/26242895/87868690-2a184880-c9cb-11ea-9667-929253aa0e2a.png)

 [Picture 2]
![image](https://user-images.githubusercontent.com/26242895/87868628-8a5aba80-c9ca-11ea-9f4a-f5edc6d9cb45.png)

**Comment by zjx94** [comment]
sorry，the -gop 50 should be -g 50.
I think it should be the quality difference (the quantization parameter QP?)  between I frame and P framethat caused the picture to suddenly blur.
After my friend reduced the GOP value, the picture quality really became very poor as picture 1

**Comment by rarzumanyan** [comment]
>How to ensure that the picture quality will not become blurred when I frame is turned under the condition of -gop 50 and bit rate of 32kb/s?

I frame contains much more bits then P and B frames, so under condition of low bitrate (32K for 355x288) encoder isn't allowed to spend too much on I frames. As a result they are blurred. Possible solutions are:

- Increase bitrate.
- Increase GOP size (I frames will occur less frequently).
- Use infinite GOP with intra refresh (bitstream will consist of 1st I frame and then P frames only, each will have some intra-coded blocks).
- Change bitrate mode to say QP and tune QP values for I, P and B individually.
- Use B frames, it will increase compression efficiency if your solution has tolerance to higher latencies.
- Increase `maxrate` to allow encoder spend more bits on I frames.

**Comment by zjx94** [comment]
I think small GOP value and good image quality can't be achieved at low bit rate, After many tests.  
I hope there will be a solution in the future.
I will close this issue,thanks for your reply.
