### ISSUE TITLE
PyNvCodec/TC/src/MemoryInterfaces.cpp:253:35: error

### ISSUE THREAD

**Issue by qAlistairs** [NVIDIA/VideoProcessingFramework#84]
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:253:35: Error: ‘runtime_error’ has not been declared in this scope
       throw runtime_error(ss.str());
                                   ^
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In the member function ‘virtual uint32_t VPF::SurfaceY::Width(uint32_t) const’:
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:344:48: Error:'invalid_argument' has not been declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In the member function ‘virtual uint32_t VPF::SurfaceY::WidthInBytes(uint32_t) const’:
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:352:48: Error:'invalid_argument' has not been declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In the member function ‘virtual uint32_t VPF::SurfaceY::Height(uint32_t) const’:
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:360:48: Error:'invalid_argument' has not been declared in this scope
   throw invalid_argument("Invalid plane number");
                                                ^
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp: In the member function ‘virtual uint32_t VPF::SurfaceY::Pitch(uint32_t) const’:
/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp:368:48: Error:'invalid_argument' has not been declared in this scope
   throw invalid_argument("Invalid plane number");

I want to ask what is the problem? Is it because of a certain environment?I am using centos 7 and CMake has been upgraded to the latest version. Other environments are the same as what you recommend

**Comment by rarzumanyan** [comment]
Hi @qAlistairs 

>I want to ask what is the problem?

It's just me not including the <stdexcept> header file in `/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp`.
I'm testing build on Windows & Ubuntu machines and some headers are included by default on them. 
Please check out the latest `master` branch, I've pushed a patch there that should solve the issue.

**Comment by qAlistairs** [comment]
> Hi @qAlistairs
> 
> > I want to ask what is the problem?
> 
> It's just me not including the header file in `/VideoProcessingFramework/PyNvCodec/TC/src/MemoryInterfaces.cpp`.
> I'm testing build on Windows & Ubuntu machines and some headers are included by default on them.
> Please check out the latest `master` branch, I've pushed a patch there that should solve the issue.

Ok, thanks for your reply
