### ISSUE TITLE
some encode problem

### ISSUE THREAD

**Issue by Shengxiaolin** [NVIDIA/VideoProcessingFramework#85]
**Describe the bug**
hi！i use VPF in my c++ project，when i encode a rtsp stream to h264 file and the output file(vlc displayed) looks like this：
![image](https://user-images.githubusercontent.com/32874811/88515715-b9061000-d01e-11ea-9215-f3a9d27de65b.png)
here is my code：

    int main(int argc, char* argv[]){

        string stream = "rtsp://admin:admin123456@192.168.0.69";
        int gpu = 0;

        std::map<string, string> params;
        params.insert(
            std::make_pair("rtsp_transport", "tcp")
        );
        params.insert(
            std::make_pair("max_delay", "5000000")
        );
        params.insert(
            std::make_pair("bufsize", "30000k")
        );

        std::map<string, string> encode_params;
        encode_params.insert(
            std::make_pair("codec", "h264")
        );
        encode_params.insert(
            std::make_pair("bitrate", "10M")
        );
        encode_params.insert(
            std::make_pair("s", "1920x1080")
        );

        PyNvDecoder decoder(stream, gpu, params);
        auto height = decoder.Height();
        auto width = decoder.Width();
        auto format = decoder.GetPixelFormat();
        // PySurfaceConverter convertor(width, height, format, Pixel_Format::YUV420, gpu);  // nv12 -> yuv420
        // PySurfaceDownloader downloader(width, height, Pixel_Format::YUV420, gpu);

        PyNvEncoder encoder(encode_params, 0);
        // PyFrameUploader uploader(1920, 1080, Pixel_Format::NV12, 0);

        ofstream enc_out("out.h264", ios::out|ios::binary);

        vector<unsigned char> frame;
        vector<unsigned char> enc_frame;
        string enc_string;

        int frame_num = 250;
        while (frame_num--){
            decoder.DecodeSingleFrame(frame);
            auto success = encoder.EncodeSingleFrame(frame, enc_frame, 0);
            enc_string.assign(enc_frame.begin(), enc_frame.end());
            if(success) enc_out << enc_string;
            cout << frame_num << " " << enc_frame.size() << " decoding ...\n";
        }

        auto success = encoder.Flush(enc_frame);
        if(success) enc_out << enc_string;
        return 0;
    }
is there anything wrong ?

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Nvidia driver version：450.51
 - CUDA Version [10.2]
 - Video Codec SDK Version [10.0.26]
 - Python Version [3.7]

**Additional context**

**Comment by rarzumanyan** [comment]
HI @Shengxiaolin 

>is there anything wrong ?

I don't know what's exactly wrong as expected vs. actual behavior is missing the issue description ;)
It looks like RTSP stream is encoded in interlaced mode and decoder doesn't combine two decoded fields together properly.
Can you please dump the decoded frames to NV12 raw file and upload one of the raw decoded frames?

To do that you just need to `fwrite` the `frame` and use any kind of raw file viewer to see it.

**Comment by Shengxiaolin** [comment]
thanks for your prompt response,i have tested the decoded frames using opencv:

     while (frame_num--){

            decoder.DecodeSingleFrame(frame);
            cv::Mat dst(height, width, CV_8UC3);
            cv::Mat src(height + height / 2, width, CV_8UC1, frame.data());
            // cv::cvtColor(src, dst, CV_YUV2BGR_I420);
            cv::cvtColor(src, dst, CV_YUV2BGR_NV12);

            cv::imwrite("test.jpg", dst);
            break;
        }
and the test.jpg looks correct .

**Comment by rarzumanyan** [comment]
@Shengxiaolin 

May I ask you how do you pass the `std::vector<unsigned char> &` to the VPF API functions while they require `py::array_t<uint8_t> &`?

**Comment by Shengxiaolin** [comment]
i just use std::vector<unsigned char> instead py::array_t<uint8_t> in PyNvCodec.cpp(rename to  PyNvCodec.h), remove some code about pybind11, and my project linked libTC.so and libTC_CORE.so its passed compile.

**Comment by rarzumanyan** [comment]
Closing this issue, codebase had changed significantly since the last response in this thread. No longer relevant.
