### ISSUE TITLE
Question: set reading frame of decoder 

### ISSUE THREAD

**Issue by ychnh** [NVIDIA/VideoProcessingFramework#86]
Hi, is it possible to set the starting point if the decoder? I have looked through some documentation but could not find any clues...

**Comment by rarzumanyan** [comment]
Hi @ychnh 

>is it possible to set the starting point if the decoder?

Do you mean the seek functionality?

**Comment by ychnh** [comment]
Yes! Could you give me some pointers on where to start? I would be more than happy to add this functionality.

**Comment by rarzumanyan** [comment]
It's at https://github.com/NVIDIA/VideoProcessingFramework/blob/369bb88a43893c5ed08a5ea7041267677f93589c/PyNvCodec/TC/src/FFmpegDemuxer.cpp#L108-L123

You need to add `av_seek_frame` there and somehow pass the frame number.

**Comment by ychnh** [comment]
Thank you. I did experiment bit with this with hardcoding some code. I will now work on making the python binds to feed in a number. Also, am I doing the timestamp correctly? I am quite new to video decoding and this is quite confusing...

```
  int64_t seek_target = 106* AV_TIME_BASE;
  av_seek_frame(fmtc, -1, seek_target, AVSEEK_FLAG_BACKWARD);
```

**Comment by rarzumanyan** [comment]
@ychnh 

To my best knowledge, you can use this function like below:
```cpp
// Seek for frame #106
int64_t seek_target = 106;

// AVSEEK_FLAG_FRAME flag allows to search for frame by number
av_seek_frame(fmtc, -1, seek_target, AVSEEK_FLAG_FRAME | AVSEEK_FLAG_BACKWARD);
```

**Comment by rarzumanyan** [comment]
`Seek` functionality was added some time ago, hence closing this issue as resolved.
