### ISSUE TITLE
Are there demo programs in C++

### ISSUE THREAD

**Issue by taosean** [NVIDIA/VideoProcessingFramework#88]
Hi @rarzumanyan , thank you for your great work.

Now in my task, I need to hard decode a RTSP stream using NVIDIA GPU in C++, I see all your demo scripts are in python, so I'm wondering, are there any demo programs for C++?

**Comment by rarzumanyan** [comment]
Hi @taosean 

VPF doesn't have a C++ sample yet but there's an open issue in which you can see the example of C++ program which uses VPF: https://github.com/NVIDIA/VideoProcessingFramework/issues/85#issue-666069474
The only thing to account is that VPF uses pybind11 for STL containers wrappers so your C++ application shall also be using that.
Other possible approach is to overload VPF C++ API methods to accept 'normal' STL containers.

**Comment by rarzumanyan** [comment]
@taosean 

I've added C++ decoding sample, check the `cpp_samples` branch.
Please test if it works for you. Later on I'll merge to master after better testing.

**Comment by taosean** [comment]
Thank you so much @rarzumanyan , It will be a great help.
I will test it.

**Comment by taosean** [comment]
Hi @rarzumanyan , I encounterd a problem when trying to compile the `SampleDecode.cpp`.

>SampleDecode.obj : error LNK2019: unresolved external symbol "public: bool __cdecl PyNvDecoder::DecodeSingleFrame(class std::vector<unsigned char,class std::allocator<unsigned char> > &)" (?DecodeSingleFrame@PyNvDecoder@@QEAA_NAEAV?$vector@EV?$allocator@E@std@@@std@@@Z) referenced in function main

I know it's a linking error that the linker cannot find the `PyNvDecoder::DecodeSingleFrame` definition. However, I already configured the `PyNvCodec.lib` in **Linker->Input->Additional Dependencies**.

Besides, I also configured the header files and `TC.lib` and `TC_CORE.lib` in the project created by my own.
The entry point is `SampleDecode.cpp` provoided by this repo.

Could you kindly check what is the cause of this error?

**Comment by rarzumanyan** [comment]
@taosean 

I've tested this branch under Windows with VS 2017.
What Visual Studio version do you use?

**Comment by taosean** [comment]
@rarzumanyan 
I'm using VS 2015.

**Comment by rarzumanyan** [comment]
>However, I already configured the PyNvCodec.lib in Linker->Input->Additional Dependencies.

**Comment by taosean** [comment]
Hi @rarzumanyan , thank you for your suggestions, it is indeed that I set `GENERATE_PYTHON_BINDINGS=1` when configuring caused this issue. I modified it and recompiled, no errors any more.

---
After that, I tested several local video files:
|id|codec|duration|status|Description|
|--|--|--|--|--|
|1|h264|00:05:27|Failed in the middle|see **error msg 1** below|
|2|h264|00:04:17|Success||
|3|MPEG-1/2|00:00:15|Failed at begining|No error msg|
|4|MPEG-1/2|00:10:00|Failed at begining|No error msg|

## error msg 1
>D:\Projects\VPF\VideoProcessingFramework-cpp_samples\BUILD\Release>SampleDecodeCpp.exe 0 D:/Data/demo_1.mpeg D:/Data/demo_1.nv12
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] non-existing PPS 0 referenced
[h264 @ 000001dd091a62c0] decode_slice_header error
[h264 @ 000001dd091a62c0] no frame!
[mpegts @ 000001dd091a0440] Packet corrupt (stream = 0, dts = 3624587772).
**Decode Error occurred for picture 2573
Exception thrown during decoding process: HW decoder faced error. Re-create instance.
HW decoder will be reset.
HW decoder reset time: 10 milliseconds**

The decode error always occur at **2573**, then the whole process is terminated.

So, I want to ask 2 questions:
1. What is the reason for the first issue that `Decode Error occurred for picture 2573`?
2. Does VPF only support h264 codec?

Thank you very much!

**Comment by rarzumanyan** [comment]
Hi @taosean 

As you see the sources of `SampleDecode.cpp` file, no decoder options were added:
https://github.com/NVIDIA/VideoProcessingFramework/blob/11c59b5b2491acc3c85d07d1520f67b5872b1d01/SampleDecode.cpp#L44

You can add needed options as it's shown in this code snippet I've referenced before:
https://github.com/NVIDIA/VideoProcessingFramework/issues/85#issue-666069474
```cpp
    string stream = "rtsp://admin:admin123456@192.168.0.69";
    int gpu = 0;

    std::map<string, string> params;
    params.insert(
        std::make_pair("rtsp_transport", "tcp")
    );
    params.insert(
        std::make_pair("max_delay", "5000000")
    );
    params.insert(
        std::make_pair("bufsize", "30000k")
    );

    std::map<string, string> encode_params;
    encode_params.insert(
        std::make_pair("codec", "h264")
    );
    encode_params.insert(
        std::make_pair("bitrate", "10M")
    );
    encode_params.insert(
        std::make_pair("s", "1920x1080")
    );
```

>Does VPF only support h264 codec?

VPF supports H.264 and H.265
Nvdec supports more codecs, they are not added to VPF (H.264 and H.265 are the most popular).
There are no constraints on that, it's just a feature that is not implemented yet.

**Comment by taosean** [comment]
Hi, @rarzumanyan , thank you so much for your response.

>Usual approach to root-cause the issue is to feed the bitstream under question to reference JM H.264 decoder.

Sorry, I don't know too much about video decoding and etc. But I played the video with VLC player, it played well.
Actually, I do observe a **frame skipping** around pic 2573 on VLC and I think it is the reason which caused the error in VPF. However, VLC continued playing while VPF threw an error and exited.

---
Besides, I debugged the VPF program and the error comes from here. https://github.com/NVIDIA/VideoProcessingFramework/blob/11c59b5b2491acc3c85d07d1520f67b5872b1d01/PyNvCodec/src/PyNvCodec.cpp#L574-L593

this line https://github.com/NVIDIA/VideoProcessingFramework/blob/11c59b5b2491acc3c85d07d1520f67b5872b1d01/PyNvCodec/src/PyNvCodec.cpp#L574-L575 set `hw_decoder_failure` to `True`, and then `throw HwResetException();` was executed.

---
By the way, I added `std::map<string, string> params;` to `	PyNvDecoder nvDec(input, gpu_id, params);
`, but it remained the same error.

---
I know this might be a issue comes from the stream and not VPF, but I'd like to know if there is a way to ignore this error and continue decoding? Because in real application environment, there is a probability of stream issue, and I don't want the application to currupt.

Thank you for your attention.

**Comment by rarzumanyan** [comment]
Hi @taosean 

>I'd like to know if there is a way to ignore this error and continue decoding?
 
As you see from https://github.com/NVIDIA/VideoProcessingFramework/blob/11c59b5b2491acc3c85d07d1520f67b5872b1d01/PyNvCodec/src/PyNvCodec.cpp#L577-L593

The decoder class instance is reset so that it can keep on working.
It's up to your application to handle this exception, this can be ignored as well (as it's done in Python samples).

BTW there's a feature enhancement that's stored in separate branch: https://github.com/NVIDIA/VideoProcessingFramework/issues/67#issuecomment-654822506
It was required by users but never tested by them after I've implemented the patch.
This improves `PyNvDecoder` class design to increase it's robustness against HW exceptions.
If you can test this and create a PR for `cpp_samples` branch that would be great.

**Comment by taosean** [comment]
@rarzumanyan , thank you so much for your response.
I'll give it a try and feedback.

**Comment by rarzumanyan** [comment]
No updates from issue originator for a long time, closing as resolved.
Please reopen in case it still needs attention.
