### ISSUE TITLE
make report error

### ISSUE THREAD

**Issue by kaiven11** [NVIDIA/VideoProcessingFramework#89]
I follow the wiki step to build vpf,but report error. I find a same issue,I try but failed.

step:
1.  cmake ..   -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK"   -DGENERATE_PYTHON_BINDINGS:BOOL="1"   -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG"
2. make && make install

![image](https://user-images.githubusercontent.com/25794106/89422930-88ce1800-d768-11ea-88cd-d0aebac1ce46.png)

In file included from /root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:32:0:
/root/VideoProcessingFramework/PyNvCodec/TC/inc/FFmpegDemuxer.h:39:3: error: ‘AVBSFContext’ does not name a type
   AVBSFContext *bsfc = nullptr;
   ^
In file included from /usr/include/ffmpeg/libavutil/avutil.h:295:0,
                 from /usr/include/ffmpeg/libavutil/frame.h:31,
                 from /root/VideoProcessingFramework/PyNvCodec/TC/inc/Tasks.hpp:22,
                 from /root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:26:
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp: In member function ‘virtual VPF::TaskExecStatus VPF::NvencEncodeFrame::Execute()’:
/usr/include/ffmpeg/libavutil/pixfmt.h:424:21: error: ‘class VPF::Surface’ has no member named ‘AVPixelFormat’
 #define PixelFormat AVPixelFormat
                     ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:146:33: note: in expansion of macro ‘PixelFormat’
     if (input && NV12 == input->PixelFormat()) {
                                 ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp: In member function ‘void VPF::MuxFrame_Impl::SetupVideoStream(MuxingParams&)’:
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:618:5: error: ‘AVCodecParameters’ was not declared in this scope
     AVCodecParameters *videoCodecParams = videoStream->codecpar;
     ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:618:24: error: ‘videoCodecParams’ was not declared in this scope
     AVCodecParameters *videoCodecParams = videoStream->codecpar;
                        ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:618:56: error: ‘AVStream’ has no member named ‘codecpar’
     AVCodecParameters *videoCodecParams = videoStream->codecpar;
                                                        ^
In file included from /usr/include/ffmpeg/libavutil/avutil.h:295:0,
                 from /usr/include/ffmpeg/libavutil/frame.h:31,
                 from /root/VideoProcessingFramework/PyNvCodec/TC/inc/Tasks.hpp:22,
                 from /root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:26:
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp: In member function ‘virtual VPF::TaskExecStatus VPF::NppResizeSurfaceRGB_Impl::Execute(VPF::Surface&)’:
/usr/include/ffmpeg/libavutil/pixfmt.h:424:21: error: ‘class VPF::Surface’ has no member named ‘AVPixelFormat’
 #define PixelFormat AVPixelFormat
                     ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:797:19: note: in expansion of macro ‘PixelFormat’
     if (pSurface->PixelFormat() != source.PixelFormat()) {
                   ^
/usr/include/ffmpeg/libavutil/pixfmt.h:424:21: error: ‘class VPF::Surface’ has no member named ‘AVPixelFormat’
 #define PixelFormat AVPixelFormat
                     ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:797:43: note: in expansion of macro ‘PixelFormat’
     if (pSurface->PixelFormat() != source.PixelFormat()) {
                                           ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp: In member function ‘virtual VPF::TaskExecStatus VPF::NppResizeSurfaceYUV420_Impl::Execute(VPF::Surface&)’:
/usr/include/ffmpeg/libavutil/pixfmt.h:424:21: error: ‘class VPF::Surface’ has no member named ‘AVPixelFormat’
 #define PixelFormat AVPixelFormat
                     ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:850:19: note: in expansion of macro ‘PixelFormat’
     if (pSurface->PixelFormat() != source.PixelFormat()) {
                   ^
/usr/include/ffmpeg/libavutil/pixfmt.h:424:21: error: ‘class VPF::Surface’ has no member named ‘AVPixelFormat’
 #define PixelFormat AVPixelFormat
                     ^
/root/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:850:43: note: in expansion of macro ‘PixelFormat’
     if (pSurface->PixelFormat() != source.PixelFormat()) {
                                           ^
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o] Error 1
make[1]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
make: *** [all] Error 2

**Desktop (please complete the following information):**
 - OS: [centos7.8]
 - Driver Version: 440.95.01
 - CUDA Version: 10.2 
 - Video Codec SDK Version:10.0.26/9.1.23
 - Python Version :3.6

**Comment by rarzumanyan** [comment]
Hi @kaiven11 

Make sure you've set up FFmpeg include path.
Compiler complains only on FFmpeg symbols.

**Comment by kaiven11** [comment]
When I excute  python3 ./SampleDecode.py , The output was like  this:
[root@localhost bin]# python3 ./SampleDecode.py 
Traceback (most recent call last):
  File "./SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ImportError: /root/VideoProcessingFramework/build/PyNvCodec/TC/libTC.so: undefined symbol: avcodec_parameters_copy

what should i do?

**Comment by rarzumanyan** [comment]
@kaiven11 

What ffmpeg version do use?

**Comment by kaiven11** [comment]
I removed ffmpeg2.8.5 with yum ,Then recompile,Now all good. Thank you! 

Another question，I view your blog,And paste the test code, The output is below:
Traceback (most recent call last):
  File "testvpf.py", line 13, in <module>
    if not (rawSurface.GetCudaDevicePtr()):
AttributeError: 'PyNvCodec.Surface' object has no attribute 'GetCudaDevicePtr'

**Comment by rarzumanyan** [comment]
Hi @kaiven11 
Information in the article is partially outdated.
Please use sample python scripts instead.

**Comment by kaiven11** [comment]
Thank you! Sample python scripts run good, issue all resolved.I'll close the issue.

**Comment by yuluhan** [comment]
> I removed ffmpeg2.8.5 with yum ,Then recompile,Now all good. Thank you!
> 
> Another question，I view your blog,And paste the test code, The output is below:
> Traceback (most recent call last):
> File "testvpf.py", line 13, in
> if not (rawSurface.GetCudaDevicePtr()):
> AttributeError: 'PyNvCodec.Surface' object has no attribute 'GetCudaDevicePtr'

How did you solve this problem?
I uninstall the original ffmpeg and reinstall as the wiki shows, but still get the same error

![ffmpeg](https://user-images.githubusercontent.com/59047015/90612145-3a297f00-e23a-11ea-961c-b9a676a11529.png)

and I type the below to the .bashrc file
` export LD_LIBARRY_PATH=/home/ai/git_install/FFmpeg/build_x64_release_shared/lib:$LD_LIBRARY_PATH`
`export PATH=/home/ai/git_install/FFmpeg/build_x64_release_shared/bin:$PATH`

Could you please give me more instruction? @kaiven11 @rarzumanyan

**Comment by rarzumanyan** [comment]
@yuluhan 

>I uninstall the original ffmpeg and reinstall as the wiki shows, but still get the same error

What kind of error do you have?
On your screenshot I can only see ffmpeg libraries versions.

**Comment by yuluhan** [comment]
> @yuluhan
> 
> > I uninstall the original ffmpeg and reinstall as the wiki shows, but still get the same error
> 
> What kind of error do you have?
> On your screenshot I can only see ffmpeg libraries versions.

![image](https://user-images.githubusercontent.com/59047015/90613967-a4dbba00-e23c-11ea-9290-93d61611b395.png)

same error

**Comment by rarzumanyan** [comment]
@yuluhan 

Please delete the CMake cache and follow the build procedure described in wiki.
In case you still have issues, please upload the CMake configure output where it shows the path to FFmpeg library.

**Comment by yuluhan** [comment]
@rarzumanyan 
I still get the same error after I remove the build folder and cmake again
![echo](https://user-images.githubusercontent.com/59047015/90615638-f9803480-e23e-11ea-8e55-89aa74c644ef.png)
My cmake commond:
`cmake .. -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" -DGENERATE_PYTHON_BINDINGS:BOOL="1" -DPYTHON_LIBRARY=/home/ai/anaconda3/envs/python36/lib/libpython3.6m.so -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"`

You may see the bellow reference:
[build/CMakeFiles/CMakeOutput.log](https://github.com/NVIDIA/VideoProcessingFramework/files/5095320/CMakeOutput.log)

[build/CMakeCache.txt](https://github.com/NVIDIA/VideoProcessingFramework/files/5095296/CMakeCache.txt)

**Comment by yuluhan** [comment]
@rarzumanyan 
cmake log info
![cmakeout](https://user-images.githubusercontent.com/59047015/90617108-e0788300-e240-11ea-9005-44e3bb6b2351.png)

**Comment by rarzumanyan** [comment]
@yuluhan 

Within your `build/CMakeCache.txt` file I see that it still looks for FFmpeg files in system folders:
```
# This is the CMakeCache file.
# For build in directory: /home/ai/git_install/VideoProcessingFramework/build
# It was generated by CMake: /usr/local/bin/cmake
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
# KEY:TYPE=VALUE
# KEY is the name of a variable in the cache.
# TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
# VALUE is the current value for the KEY.

########################
# EXTERNAL cache entries
########################

//Path to a file.
AVCODEC_INCLUDE_DIR:PATH=/usr/include/x86_64-linux-gnu

//Path to a library.
AVCODEC_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libavcodec.so

//Path to a file.
AVFORMAT_INCLUDE_DIR:PATH=/usr/include/x86_64-linux-gnu

//Path to a library.
AVFORMAT_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libavformat.so

//Path to a file.
AVUTIL_INCLUDE_DIR:PATH=/usr/include/x86_64-linux-gnu

//Path to a library.
AVUTIL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libavutil.so

```

It looks like you've not removed ffmpeg installed with package manager or didn't delete the CMake cache.

**Comment by yuluhan** [comment]
> @yuluhan
> 
> Within your `build/CMakeCache.txt` file I see that it still looks for FFmpeg files in system folders:
> 
> ```
> # This is the CMakeCache file.
> # For build in directory: /home/ai/git_install/VideoProcessingFramework/build
> # It was generated by CMake: /usr/local/bin/cmake
> # You can edit this file to change values found and used by cmake.
> # If you do not want to change any of the values, simply exit the editor.
> # If you do want to change a value, simply edit, save, and exit the editor.
> # The syntax for the file is as follows:
> # KEY:TYPE=VALUE
> # KEY is the name of a variable in the cache.
> # TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
> # VALUE is the current value for the KEY.
> 
> ########################
> # EXTERNAL cache entries
> ########################
> 
> //Path to a file.
> AVCODEC_INCLUDE_DIR:PATH=/usr/include/x86_64-linux-gnu
> 
> //Path to a library.
> AVCODEC_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libavcodec.so
> 
> //Path to a file.
> AVFORMAT_INCLUDE_DIR:PATH=/usr/include/x86_64-linux-gnu
> 
> //Path to a library.
> AVFORMAT_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libavformat.so
> 
> //Path to a file.
> AVUTIL_INCLUDE_DIR:PATH=/usr/include/x86_64-linux-gnu
> 
> //Path to a library.
> AVUTIL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libavutil.so
> ```
> 
> It looks like you've not removed ffmpeg installed with package manager or didn't delete the CMake cache.

I finally make install successfully!
By running the cmake command as below, so that I can link to the ffmpeg path I compiled.
```
cmake .. -DFFMPEG_DIR:PATH=/home/ai/git_install/FFmpeg/build_x64_release_shared \
-DVIDEO_CODEC_SDK_DIR:PATH=/home/ai/software/Video_Codec_SDK_10.0.26 \
-DGENERATE_PYTHON_BINDINGS:BOOL="1" \
-DPYTHON_LIBRARY=/home/ai/anaconda3/envs/python36/lib/libpython3.6m.so \
-DCMAKE_INSTALL_PREFIX:PATH=/home/ai/git_install/VideoProcessingFramework/install \
-DAVCODEC_INCLUDE_DIR=/home/ai/git_install/FFmpeg/build_x64_release_shared/include \
-DAVCODEC_LIBRARY=/home/ai/git_install/FFmpeg/build_x64_release_shared/lib/libavcodec.so \
-DAVFORMAT_INCLUDE_DIR=/home/ai/git_install/FFmpeg/build_x64_release_shared/include \
-DAVFORMAT_LIBRARY=/home/ai/git_install/FFmpeg/build_x64_release_shared/lib/libavformat.so \
-DAVUTIL_INCLUDE_DIR=/home/ai/git_install/FFmpeg/build_x64_release_shared/include \
-DAVUTIL_LIBRARY=/home/ai/git_install/FFmpeg/build_x64_release_shared/lib/libavutil.so
```

**Comment by rarzumanyan** [comment]
@yuluhan 
Great news!
