### ISSUE TITLE
RuntimeError: can't get unknown filter by name

### ISSUE THREAD

**Issue by heefe92** [NVIDIA/VideoProcessingFramework#9]
ipython

```
import PyNvCodec as nvc 
nvDec = nvc.PyNvDecoder('rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov', 0)
Decoding on GPU 0
[-----] Media format: RTSP input (rtsp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: can't get unknown filter by name
```

**Comment by rarzumanyan** [comment]
Hi,

This is caused by ffmpeg input format context name having value unknown to VPF so that it doesn’t know what filter to use to extract elementary h264 or h265 bitstream:
```
is_mp4H264 = eVideoCodec == AV_CODEC_ID_H264 &&
               (!strcmp(fmtc->iformat->long_name, "QuickTime / MOV") ||
                !strcmp(fmtc->iformat->long_name, "FLV (Flash Video)") ||
                !strcmp(fmtc->iformat->long_name, "Matroska / WebM"));
is_mp4HEVC = eVideoCodec == AV_CODEC_ID_HEVC &&
               (!strcmp(fmtc->iformat->long_name, "QuickTime / MOV") ||
                !strcmp(fmtc->iformat->long_name, "FLV (Flash Video)") ||
                !strcmp(fmtc->iformat->long_name, "Matroska / WebM")); 
```

Is your stream publicly available or can you check format name yourself if not?

**Comment by pycoco** [comment]
@heefe92  about "ubuntu VPF build link failed",how to solve the problem?

**Comment by Wenlong0913** [comment]
@rarzumanyan 
> Hi,
> 
> This is caused by ffmpeg input format context name having value unknown to VPF so that it doesn’t know what filter to use to extract elementary h264 or h265 bitstream:
> 
> ```
> is_mp4H264 = eVideoCodec == AV_CODEC_ID_H264 &&
>                (!strcmp(fmtc->iformat->long_name, "QuickTime / MOV") ||
>                 !strcmp(fmtc->iformat->long_name, "FLV (Flash Video)") ||
>                 !strcmp(fmtc->iformat->long_name, "Matroska / WebM"));
> is_mp4HEVC = eVideoCodec == AV_CODEC_ID_HEVC &&
>                (!strcmp(fmtc->iformat->long_name, "QuickTime / MOV") ||
>                 !strcmp(fmtc->iformat->long_name, "FLV (Flash Video)") ||
>                 !strcmp(fmtc->iformat->long_name, "Matroska / WebM")); 
> ```
> 
> Is your stream publicly available or can you check format name yourself if not?

Hi rarzumanyan,

I'm facing the same problem. I'm sure the input rtsp format is h265 and can you please let me know how to change the url in order to make it work?

Here is my code:

```
import PyNvCodec as nvc 

enc = 'rtsp://admin:password@172.21.71.10:554/streaming/channels/1'
nvDec = nvc.PyNvDecoder(enc 0)
```

Many thanks.

**Comment by rarzumanyan** [comment]
Hi,
I guess the easiest way to check what's the format name is to add a debug output line of code like below
`cout << "fmtc->iformat->long_name: " << fmtc->iformat->long_name << endl;`
to see what format name is stored in the RTSP stream.

> I'm sure the input rtsp format is h265


H.265 is video codec, not format.
VPF Demuxer is extracting encoded H.264 or H.265 coded packets from RTSP stream, and structure of that stream is determined by format (mov, webm etc.).

**Comment by Wenlong0913** [comment]
> Hi,
> I guess the easiest way to check what's the format name is to add a debug output line of code like below
> `cout << "fmtc->iformat->long_name: " << fmtc->iformat->long_name << endl;`
> to see what format name is stored in the RTSP stream.
> 
> > I'm sure the input rtsp format is h265
> 
> H.265 is video codec, not format.
> VPF Demuxer is extracting encoded H.264 or H.265 coded packets from RTSP stream, and structure of that stream is determined by format (mov, webm etc.).

Hi @rarzumanyan ,

I tried it a moment ago, it returns as follows:
```
>>> nvDec = nvc.PyNvDecoder(input, 0)
Decoding on GPU 0
[-----] Media format: RTSP input (rtsp)
[rtsp @ 0x5610cefb6740] max delay reached. need to consume packet
[rtsp @ 0x5610cefb6740] RTP: missed 1 packets
fmtc->iformat->long_name: RTSP input
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: can't get unknown filter by name
```

Since we have already known that the codec is h.265, can we just modify the code like this to solve it for this specific case?
```
is_mp4HEVC = eVideoCodec == AV_CODEC_ID_HEVC &&
               (!strcmp(fmtc->iformat->long_name, "QuickTime / MOV") ||
                !strcmp(fmtc->iformat->long_name, "FLV (Flash Video)") ||
                !strcmp(fmtc->iformat->long_name, "RTSP input") ||
                !strcmp(fmtc->iformat->long_name, "Matroska / WebM")); 
```

Btw, the format name is "RTSP input" is strange, do you think this is due to the IP camera's issue?

Again, many thanks for your help.

**Comment by Wenlong0913** [comment]
It works, great.

**Comment by rarzumanyan** [comment]
Hi,
Glad that you’ve fixed that.

**Comment by dexception** [comment]
@Wenlong0913 

> > Hi,
> > I guess the easiest way to check what's the format name is to add a debug output line of code like below
> > `cout << "fmtc->iformat->long_name: " << fmtc->iformat->long_name << endl;`
> > to see what format name is stored in the RTSP stream.
> > > I'm sure the input rtsp format is h265
> > 
> > 
> > H.265 is video codec, not format.
> > VPF Demuxer is extracting encoded H.264 or H.265 coded packets from RTSP stream, and structure of that stream is determined by format (mov, webm etc.).
> 
> Hi @rarzumanyan ,
> 
> I tried it a moment ago, it returns as follows:
> 
> ```
> >>> nvDec = nvc.PyNvDecoder(input, 0)
> Decoding on GPU 0
> [-----] Media format: RTSP input (rtsp)
> [rtsp @ 0x5610cefb6740] max delay reached. need to consume packet
> [rtsp @ 0x5610cefb6740] RTP: missed 1 packets
> fmtc->iformat->long_name: RTSP input
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: can't get unknown filter by name
> ```
> 
> Since we have already known that the codec is h.265, can we just modify the code like this to solve it for this specific case?
> 
> ```
> is_mp4HEVC = eVideoCodec == AV_CODEC_ID_HEVC &&
>                (!strcmp(fmtc->iformat->long_name, "QuickTime / MOV") ||
>                 !strcmp(fmtc->iformat->long_name, "FLV (Flash Video)") ||
>                 !strcmp(fmtc->iformat->long_name, "RTSP input") ||
>                 !strcmp(fmtc->iformat->long_name, "Matroska / WebM")); 
> ```
> 
> Btw, the format name is "RTSP input" is strange, do you think this is due to the IP camera's issue?
> 
> Again, many thanks for your help.

Can you please specify the file where your changes have to be done ?

**Comment by rarzumanyan** [comment]
Hi,
It's FFmpegDemuxer.cpp:233.

This piece of code was taken from Video Codec SDK Samples on which VPF relies. I think the logic can be changed here, it would be better to select the bitstream filter depending on codec instead of format name. 

If you have some time to prepare the change as pull request I'll be glad to merge it as there are numerous issues with very this part of code.

**Comment by dexception** [comment]
@rarzumanyan 
I am getting this error:


```
Decoding on GPU 0
Can't open rtsp://ashutosh:ashu1234@192.168.1.250:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif: Protocol not found
Traceback (most recent call last):
  File "SampleDecode_rtsp.py", line 23, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
ValueError: No AVFormatContext provided.
```

There seems to be an empty instance passed to this method:

```
FFmpegDemuxer::FFmpegDemuxer(AVFormatContext *fmtcx) : fmtc(fmtcx) {
  pkt = {};
  pktFiltered = {};

  if (!fmtc) {
    throw invalid_argument("No AVFormatContext provided.");
  }
```

**Comment by rarzumanyan** [comment]
@dexception 

This is FFmpeg error, not the VPF one. Looks like library doesn't support ONVIF protocol.
I can't tell the exact reason without debugging. Can you open the URL with ffmpeg application?

**Comment by dexception** [comment]
@rarzumanyan 
Yes it working with ffmpeg and vlc and every other player. Only VPF is unable to play.

**Comment by sniklaus** [comment]
Try adding `avformat_open_input()` before the call(s) to `avformat_open_input(...)`.

**Comment by mel-2445** [comment]
Hi @rarzumanyan, thanks for the project.
I get the original error of this thread, `RuntimeError: can't get unknown filter by name` when running the example decode script with an `mjpeg` video, but it works fine with `h264` videos. Is this behavior expected?

**Comment by rarzumanyan** [comment]
Hi @mel-2445 
Yes, this is expected behaviour.
VPF supports h264 and h265 hw acceleration.

**Comment by ADongGu** [comment]
> Hi @mel-2445 Yes, this is expected behaviour. VPF supports h264 and h265 hw acceleration.

That means other formats, such as mpeg2, are not supported
What do I need to do? Can you give me some ideas, thank you, boss.

**Comment by RomanArzumanyan** [comment]
Hi @ADongGu 

NV HW does support mpeg2 decoding, I just think mpeg2 was never properly tested in VPF. Can you create a dedicated issue for that?

If you could attach problematic file input there, that would be helpful. Thank you!
