### ISSUE TITLE
The channels reduced when convert RTSP

### ISSUE THREAD

**Issue by kaiven11** [NVIDIA/VideoProcessingFramework#90]
I want to convert the RTSP to BGR,and then use Opencv to tackle it ,But the program report error :
    `cv2.error: OpenCV(4.4.0) /root/opencv/modules/dnn/src/layers/convolution_layer.cpp:347: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 1 in function 'getMemoryShapes'`

I made the programe #60 :
https://github.com/NVIDIA/VideoProcessingFramework/issues/60#issuecomment-638818818

           `width, height = nvDec.Width(), nvDec.Height()
            hwidth, hheight = int(width / 2), int(height / 2)
            rawSurface = nvDec.DecodeSingleSurface()
            to_rgb = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(),nvDec.Format() ,nvc.PixelFormat.RGB, 0)
            rgb = to_rgb.Execute(rawSurface)
            nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, nvDec.Format(), 0)
            frame = np.ndarray(shape=(rgb.HostSize()), dtype=np.uint8)
            nvDwn.DownloadSingleSurface(rgb, frame)
            cvtFrame = cv2.cvtColor(frame, cv.COLOR_RGB2BGR)
            # Create a 4D blob from a frame.
            blob = cv.dnn.blobFromImage(cvtFrame, 1/255, (inpWidth, inpHeight), [0,0,0], 1, crop=False) 

Why the channels reduced ? Is there problem in my program?

Please give me some advice.

**Desktop (please complete the following information):**
 - OS: [centos 7 ]
 - Nvidia driver version:440.95.01
 - CUDA Version:10.2
 - Video Codec SDK Version :10.0.26
 - Python Version:3.6

**Comment by rarzumanyan** [comment]
Hi @kaiven11 

From your code snippet I see that you're creating numpy array for RGB picture which has 1 channel:
```python
frame = np.ndarray(shape=(rgb.HostSize()), dtype=np.uint8)
```

`PySurfaceDownloader` class doesn't change the type of numpy array, it only does memory copy:
https://github.com/NVIDIA/VideoProcessingFramework/blob/ae4608337b80444b50db4a3863498bcf4553d683/PyNvCodec/src/PyNvCodec.cpp#L224-L243

So you end up having single-channel RGB frame.
E. g. for 1920x1080 RGB image the frame size will be 5760x1080 where 5760=1920x3.

VPF is a C++ project by it's nature so many things are done at low level.
E. g. RGB image is simple one-dimensional array big enough to store all the pixels. This is mostly done for performance sake.

I guess you can reshape the numpy array after you download image from GPU.

**Comment by kaiven11** [comment]
Thank you for your response, When I download the image from GPU,Then convert it  from YUV420 to BRG,The output is below:
       `cv2.error: OpenCV(4.4.0) /root/opencv/modules/imgproc/src/color.simd_helpers.hpp:108: error: (-215:Assertion failed) sz.width % 2 == 0 && sz.height % 3 == 0 in function 'CvtHelper'`

My code:
   `nvCvt = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(),nvDec.Format() ,nvc.PixelFormat.YUV420, 0)

            nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, nvDec.Format(), 0)
            nvRes = nvc.PySurfaceResizer(hwidth, hheight, nvCvt.Format(),0)

            rawSurface = nvDec.DecodeSingleSurface()
            cvtSurface = nvCvt.Execute(rawSurface)
            resSurface = nvRes.Execute(cvtSurface)
            rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)
            success = nvDwn.DownloadSingleSurface(resSurface, rawFrame)
            if success:
               print("success!")
            frame = cv.cvtColor(rawFrame, cv.COLOR_YUV2BGR_I420)
            # Create a 4D blob from a frame.
            blob = cv.dnn.blobFromImage(frame, 1/255, (inpWidth, inpHeight), [0,0,0], 1, crop=False)`


and reshape the numpy array after download image or before download image ,  does it affect  the result?

**Comment by rarzumanyan** [comment]
@kaiven11 
I think it's better to reshape after the download, when all the VPF C++ stuff has done it's job.

**Comment by kaiven11** [comment]
I know VPF now support YUV420、NV12、RGB, can you give me some advice to convert YUV420 to BGR for using opencv .
I try use  cv.cvtColor(rawFrame, cv.COLOR_YUV2BGR_I420)  ,but report error，and  then change the arg COLOR_YUV2BGR_I420 to other args ,but i does't  work, please give me some advice.This is import to me ,Thank you .

**Comment by kaiven11** [comment]
I viewed some other issues,I had resolved my problem,Thank you .

**Comment by niaoyu** [comment]
> I viewed some other issues,I had resolved my problem,Thank you .

Hi，could you share the code which just reshape after the download using opencv?

**Comment by scai2013** [comment]
> I viewed some other issues,I had resolved my problem,Thank you .

could you share the code reshape using opencv after downloader
