### ISSUE TITLE
How  can i get the latest frame in real time?

### ISSUE THREAD

**Issue by kaiven11** [NVIDIA/VideoProcessingFramework#91]
Now I try decode  rtsp with VPF, and then test the FPS is 400FPS around,Decoding  use 0.002 seconds,That's very good,but algorithm part a little slow,  the latency is a little high. Is there a solution that can get the latest frame in real time?  

the test result is below:

![image](https://user-images.githubusercontent.com/25794106/89749579-e660bc80-dafa-11ea-877b-4a826d76a397.png)

**Desktop (please complete the following information):**
 - OS: [centos7]
 - Nvidia driver version:440.95.01
 - CUDA Version:10.2
 - Video Codec SDK Version:10.0.20
 - Python Version:3.6

**Comment by rarzumanyan** [comment]
Hi @kaiven11 

>Is there a solution that can get the latest frame in real time?

I'm not sure I fully understand your question. Could you elaborate on that?

VPF reads encoded video frames from RTSP protocol and decodes them one by one taking into account inter-frame dependencies. As soon as next available frame is decoded it's returned it to user. So it's not possible to decode "latest" video frame (say it has number `N`) until all the frames used as reference (if any, say they have numbers `N-1`, `N-2`,...) are decoded as well.

**Comment by rarzumanyan** [comment]
No response from issue originator for a long time, hence closing. Please reopen if it's not resolved.
