### ISSUE TITLE
In Windows system, how to operate the sixth step "Open Visual Studio project & build the INSTALL target".

### ISSUE THREAD

**Issue by wuwenhao8866** [NVIDIA/VideoProcessingFramework#93]
Hello. According to the "Building from source" in WiKi, how to operate the sixth step "Open Visual Studio project & build the INSTALL target" in Windows system. Thank you.

**Comment by rarzumanyan** [comment]
Hi @wuwenhao8866 

You just right-click the target in Visual Studio and build it:
![image](https://user-images.githubusercontent.com/45193474/90362740-00098300-e06a-11ea-980a-e1dbb968b2df.png)
