### ISSUE TITLE
Doesn't compile on Video Codec SDK 9.0 because "nvEncGetLastErrorString" is missing

### ISSUE THREAD

**Issue by adroit91** [NVIDIA/VideoProcessingFramework#95]
**Describe the bug**
When I compile against Video Codec SDK 9.0, I get multiple errors on compiling "PyNvCodec/TC/inc/NvEncoder.h" regarding missing "nvEncGetLastErrorString", which is clearly a new addition in SDK 10.

**To Reproduce**
Compile latest master against SDK 9.0.

**Expected behavior**
Just like other places in code where SDK versions are checked and accordingly handled, SDK 9.0 should continue to work.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Nvidia driver version -- 418.87.01
 - CUDA Version 10.1
 - Video Codec SDK Version 9.0.20
 - Python Version 3.7.6

**Comment by rarzumanyan** [comment]
Hi @adroit91 

Is there a chance you can update to Video Codec SDK 9.1?

**Comment by adroit91** [comment]
On GCP right now, using a prebuilt VM for DL, so very difficult to try that out. Since you're not using releases, is there a last known good checkout SHA that I could use for SDK 9.0?

**Comment by rarzumanyan** [comment]
@adroit91 

Ok, I've prepared a quick patch in `issue_95` branch which puts the `nvEncGetLastErrorString` calls under conditional compilation.
Please check if it works for you.

**Comment by adroit91** [comment]
@rarzumanyan Hey, thanks a lot. It works now! Had to add an include statement and all was good.

`--- a/PyNvCodec/TC/src/NvEncoder.cpp
+++ b/PyNvCodec/TC/src/NvEncoder.cpp
@@ -12,6 +12,7 @@
  */
 
 #include "NvEncoder.h"
+#include "NvCodecCLIOptions.h"
 using namespace std;
`
