### ISSUE TITLE
The video generated by VPF encoder has no bitrate and duration information.

### ISSUE THREAD

**Issue by TracelessLe** [NVIDIA/VideoProcessingFramework#96]
**Describe the bug**
I run the SampleDecode.py and SampleEncode.py, but the output video by the encode process is weird. The video generated by VPF encoder has no bitrate and duration information, it can't be played by video player or chrome browser. 
I input it to ffmpeg and it shows the video information:
```
Input #0, h264, from 'test-gpu.mp4':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 720x1280 [SAR 1:1 DAR 9:16], 25 fps, 25 tbr, 1200k tbn, 50 tbc
```

**To Reproduce**
1. Run SampleDecode.py on a normal h264 video and generate a raw NV12 file.
2. Run SampleEncode.py using the a raw NV12 file to generate a h264(or mp4) file.
3. Try to open the h264(or mp4) video using player but failed.
4. Using 'ffmpeg -i output.mp4' command and find the generated video has no bitrate and duration.

**Expected behavior**
To generate a normal h264 video that QuickTimePlayer or Chrome browser can play.

**Screenshots**
![image](https://user-images.githubusercontent.com/22371026/91002676-e7691200-e601-11ea-9616-72b9fd9d7eb7.png)

**Desktop:**
 - OS: ubuntu 18.04
 - Nvidia driver version: 440.82
 - CUDA Version : 10.1 
 - Video Codec SDK Version: 9.1.23
 - Python Version: 3.6.10
 - FFmpeg Version: 4.2.2

**Additional context**
By the way , I find a player name sPlayer on mac can play the generated video, it shows that the video palyed vert fast and no time control bar.
![image](https://user-images.githubusercontent.com/22371026/91003215-4d09ce00-e603-11ea-96e0-5df6033f2fe3.png)

The output video is attached (be zipped) as below:
[output.mp4.zip](https://github.com/NVIDIA/VideoProcessingFramework/files/5115720/output.mp4.zip)
 
I integrate the SampleDecode.py and  SampleEncode.py and finally code I used is attached as below:

[SampleDecodeEncode.py.zip](https://github.com/NVIDIA/VideoProcessingFramework/files/5115736/SampleDecodeEncode.py.zip)

**Comment by rarzumanyan** [comment]
Hi @TracelessLe 

VPF generates Annex.B elementary bitstream video which isn't put into any container.
So by giving output file *.mp4 extension, it won't change the output file structure.
This is done intentionally and users have to mux video output themselves.

P. S.
VLC can play Annex.B videos without issues.

**Comment by TracelessLe** [comment]
> Hi @TracelessLe
> 
> VPF generates Annex.B elementary bitstream video which isn't put into any container.
> So by giving output file *.mp4 extension, it won't change the output file structure.
> This is done intentionally and users have to mux video output themselves.
> 
> P. S.
> VLC can play Annex.B videos without issues.

Thank you for your great help and support! I solve the problem.
VPF is an excellent framework! Thans for your efforts!

**Comment by wykvictor** [comment]
> > Hi @TracelessLe
> > VPF generates Annex.B elementary bitstream video which isn't put into any container.
> > So by giving output file *.mp4 extension, it won't change the output file structure.
> > This is done intentionally and users have to mux video output themselves.
> > P. S.
> > VLC can play Annex.B videos without issues.
> 
> Thank you for your great help and support! I solve the problem. VPF is an excellent framework! Thans for your efforts!

Hi, @TracelessLe , I encountered the same problem. Could you pls share the way to mux the output video?  As far as I know, ffmpeg command can do this( ffmpeg -i output.h264 -c copy output.mp4). But this will cost time to read the bytes(output.h264) from disk and additional time to launch the ffmpeg process. My use of the VPF is to save time encoding the video, so is there any 3-party interface of doing video-mux efficiently? cc @rarzumanyan  Thanks!

**Comment by rarzumanyan** [comment]
Hi @wykvictor 

PyAV can be used for that, take a look [here](https://github.com/NVIDIA/VideoProcessingFramework/issues/99#issuecomment-820962437).

**Comment by wykvictor** [comment]
> Hi @wykvictor
> 
> PyAV can be used for that, take a look [here](https://github.com/NVIDIA/VideoProcessingFramework/issues/99#issuecomment-820962437).

Thanks! I tried PyAV and it worded fine. Here is the code snippet,  so everyone else could refer to it.
```
# 1. init
dstFile = av.open(dstFilePath, 'w')
out_stream = dstFile.add_stream('h264', rate = 25)
out_stream.width = w
out_stream.height = h

# 2. mux
encByteArray = bytearray(encFrame)  # encFrame from EncodeSingleSurface
pkt = av.packet.Packet(encByteArray)
pkt.pts = pts_time
pkt.dts = pts_time
pkt.stream = out_stream  # attach pkt to the stream
dstFile.mux(pkt)
```

**Comment by rarzumanyan** [comment]
Thank for the code snippet, @wykvictor that's super useful.
I'll add this to wiki if you don't mind.

**Comment by wykvictor** [comment]
> Thank for the code snippet, @wykvictor that's super useful.
> I'll add this to wiki if you don't mind.

It's fine, very happy if this can help others
