### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Waxyoung** [NVIDIA/VideoProcessingFramework#98]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26435611/91026494-632c8400-e62d-11ea-9ff0-5bc40a765819.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Nvidia driver version 440.33.01
 - CUDA Version 10.2
 - Video Codec SDK Version [ 9.1.23]
 - Python Version 3.5

**Additional context**

**Comment by rarzumanyan** [comment]
Hi @Waxyoung 

`PytorchNvCodec` extension is built with the Python script which launches Pytorch built-in extension builder:
https://github.com/NVIDIA/VideoProcessingFramework/blob/ae4608337b80444b50db4a3863498bcf4553d683/PytorchNvCodec/src/setup.py#L1-L8

Looks like your issue is caused by system C++ compiler, it trues to build C++ code as plain C code and fails when it meets Cpp template.
What C++ compiler do you use?

**Comment by Waxyoung** [comment]
i use dpkg to get gcc version
![image](https://user-images.githubusercontent.com/26435611/91028154-a12aa780-e62f-11ea-8fc3-62641e8af351.png)

**Comment by Waxyoung** [comment]
![image](https://user-images.githubusercontent.com/26435611/91028693-69702f80-e630-11ea-8850-ed23ef462bde.png)

**Comment by rarzumanyan** [comment]
Please update to latest gcc and g++ versions.
I see that gcc-5 and g++-5 are installed on your machine, but they are very outdated.

**Comment by Waxyoung** [comment]
ok，thank you！

**Comment by Waxyoung** [comment]
i update gcc and g++ version 7.0 , but error is still occur....
![image](https://user-images.githubusercontent.com/26435611/91039870-e9ea5c80-e63f-11ea-86bf-680beb09f184.png)
![image](https://user-images.githubusercontent.com/26435611/91039916-fbcbff80-e63f-11ea-8fd8-a340b9359122.png)

**Comment by Waxyoung** [comment]
If i use gcc-9  cuda version is not allow....
![image](https://user-images.githubusercontent.com/26435611/91043670-96c7d800-e646-11ea-9fe8-de537513df35.png)

**Comment by Waxyoung** [comment]
@rarzumanyan

**Comment by rarzumanyan** [comment]
@Waxyoung 

There's a similar issue #105 
Please update the Pytorch to latest version (1.6) and try again.

**Comment by StianHanssen** [comment]
@rarzumanyan Do you have to have PyTorch installed? I have the exact same issue with GCC 7.5.0 with:
`-DGENERATE_PYTORCH_EXTENSION:BOOL="0"`

For what I plan to use VPF for, I don't think I need PyTorch

**Comment by rarzumanyan** [comment]
Hi Stian,

You don’t need to have PyTorch if you’re not building the PyTorch VPF Extension.

--
BR, Roman Arzumanyan

**Comment by rarzumanyan** [comment]
No response from issue originator for a long time, hence closing. Please reopen in case it's not resolved.
